leanux: leanux::tools::lmon::RealtimeSampler Class Reference
leanux::tools::lmon::RealtimeSampler Class Reference
Provides data by real time sampling.
#include <realtime.hpp>
Public Member Functions
RealtimeSampler ()
Constructor.
const XIOView & getXIOView () const
const XNetView & getXNetView () const
const XProcView & getXProcView () const
const XSysView & getXSysView () const
Return snapshot XSysView data.
void resetCPUTrail ()
void sample (int cpubarheight)
Sample a snapshot.
Protected Member Functions
void sampleXIOView ()
void sampleXNetView ()
void sampleXProcView ()
void sampleXSysView (int cpubarheight)
Protected Attributes
cpu::CPUInfo cpuinfo_
cpu model info
cpu::CPUStatsMap cpustat1_
Earlier CPUStatsMap snapshot.
cpu::CPUStatsMap cpustat2_
Later CPUStatsMap snapshot.
leanux::cpu::CPUStatsMap delta_
Delta of stat1_ and stat2_.
unsigned long disabled_procs_
number of procs on the system when sampling disabled.
block::DeviceStatsMap diskstats1_
Earlier DeviceStatsMap snapshot.
block::DeviceStatsMap diskstats2_
Later DeviceStatsMap snapshot.
unsigned long mounted_bytes_1_
unsigned long mounted_bytes_2_
net::NetStatDeviceMap netsnap1_
earlier snap.
net::NetStatDeviceMap netsnap2_
later snap.
process::ProcPidStatMap procsnap1_
earlier snap.
process::ProcPidStatMap procsnap2_
later snap.
cpu::SchedInfo sched1_
Earlier SchedInfo snapshot.
cpu::SchedInfo sched2_
Later SchedInfo snapshot.
std::list< vmem::SwapInfo > swaps_
List of SwapInfo.
vmem::VMStat vmstat1_
Earlier VMStat snapshot.
vmem::VMStat vmstat2_
Later VMStat snapshot.
XIOView xioview_
XNetView xnetview_
XProcView xprocview_
XSysView xsysview_
Static Protected Attributes
static std::map< std::string, block::MajorMinor > devicefilecache_
cache of device special files to MajorMinor
static const double max_proc_sample_time
maximum sample duration in seconds before being disabled.
Detailed Description
Provides data by real time sampling.
Definition at line 51 of file realtime.hpp.
Constructor & Destructor Documentation
RealtimeSampler()
leanux::tools::lmon::RealtimeSampler::RealtimeSampler ()
Constructor.
Definition at line 53 of file realtime.cpp.
References cpuinfo_, leanux::tools::lmon::XProcView::disabled, leanux::cpu::getCPUInfo(), leanux::system::getPageSize(), mounted_bytes_1_, mounted_bytes_2_, leanux::tools::lmon::XSysView::pagesize_, sample(), xprocview_, and xsysview_.
Member Function Documentation
getXIOView()
const XIOView& leanux::tools::lmon::RealtimeSampler::getXIOView () const inline
Definition at line 67 of file realtime.hpp.
References xioview_.
Referenced by leanux::tools::lmon::Screen::runRealtime().
getXNetView()
const XNetView& leanux::tools::lmon::RealtimeSampler::getXNetView () const inline
Definition at line 68 of file realtime.hpp.
References xnetview_.
Referenced by leanux::tools::lmon::Screen::runRealtime().
getXProcView()
const XProcView& leanux::tools::lmon::RealtimeSampler::getXProcView () const inline
Definition at line 69 of file realtime.hpp.
References xprocview_.
Referenced by leanux::tools::lmon::Screen::runRealtime().
getXSysView()
const XSysView& leanux::tools::lmon::RealtimeSampler::getXSysView () const inline
Return snapshot XSysView data.
Definition at line 66 of file realtime.hpp.
References xsysview_.
Referenced by leanux::tools::lmon::Screen::runRealtime().
resetCPUTrail()
void leanux::tools::lmon::RealtimeSampler::resetCPUTrail () inline
Definition at line 71 of file realtime.hpp.
References leanux::tools::lmon::XSysView::cpurtpast, and xsysview_.
Referenced by leanux::tools::lmon::Screen::runRealtime().
sample()
void leanux::tools::lmon::RealtimeSampler::sample (int cpubarheight)
Sample a snapshot.
Definition at line 63 of file realtime.cpp.
References sampleXIOView(), sampleXNetView(), sampleXProcView(), and sampleXSysView().
Referenced by RealtimeSampler(), and leanux::tools::lmon::Screen::runRealtime().
sampleXIOView()
void leanux::tools::lmon::RealtimeSampler::sampleXIOView () protected
Definition at line 136 of file realtime.cpp.
References leanux::tools::lmon::XIORec::artm, leanux::block::MountInfo::attrs, leanux::tools::lmon::XIORec::awtm, leanux::block::deltaDeviceStats(), leanux::util::deltaTime(), leanux::block::MountInfo::device, leanux::tools::lmon::XIORec::device, devicefilecache_, diskstats1_, diskstats2_, leanux::block::enumMounts(), leanux::tools::lmon::XIOView::fsbytes1, leanux::tools::lmon::XIOView::fsbytes2, leanux::block::MountInfo::fstype, leanux::block::getFileMajorMinor(), leanux::block::getMountUsedBytes(), leanux::block::getStats(), leanux::vmem::getSwapInfo(), leanux::tools::lmon::XIORec::iodone_cnt, leanux::tools::lmon::XIORec::ioerr_cnt, leanux::tools::lmon::XIORec::iorequest_cnt, leanux::tools::lmon::XIOView::iosorted, leanux::tools::lmon::XIOView::iostats, leanux::block::MountInfo::mountpoint, leanux::tools::lmon::XIOView::mountsorted, leanux::tools::lmon::XIOView::mountstats, leanux::tools::lmon::XIORec::qsz, leanux::tools::lmon::XIORec::rbs, leanux::tools::lmon::XIORec::rs, leanux::tools::lmon::XIOView::sample_count, leanux::tools::lmon::XIORec::svctm, swaps_, leanux::tools::lmon::XIOView::t1, leanux::tools::lmon::XIOView::t2, leanux::tools::lmon::XIORec::util, leanux::tools::lmon::XIORec::wbs, leanux::tools::lmon::XIORec::ws, and xioview_.
Referenced by sample().
sampleXNetView()
void leanux::tools::lmon::RealtimeSampler::sampleXNetView () protected
Definition at line 117 of file realtime.cpp.
References leanux::tools::lmon::XNetView::delta, leanux::util::deltaTime(), leanux::net::getNetStat(), leanux::net::getNetStatDelta(), leanux::net::getTCPConnectionCounters(), netsnap1_, netsnap2_, leanux::tools::lmon::XNetView::sample_count, leanux::tools::lmon::XNetView::t1, leanux::tools::lmon::XNetView::t2, leanux::tools::lmon::XNetView::tcpclient, leanux::tools::lmon::XNetView::tcpserver, and xnetview_.
Referenced by sample().
sampleXProcView()
void leanux::tools::lmon::RealtimeSampler::sampleXProcView () protected
Definition at line 70 of file realtime.cpp.
References leanux::tools::lmon::XProcView::delta, leanux::process::deltaProcPidStats(), leanux::util::deltaTime(), leanux::tools::lmon::XProcView::disabled, disabled_procs_, leanux::process::getAllProcPidStat(), leanux::system::getNumProcesses(), leanux::process::getProcCmdLine(), leanux::process::getProcUid(), leanux::tools::lmon::XProcView::pidargs, leanux::tools::lmon::XProcView::piduids, procsnap1_, procsnap2_, leanux::tools::lmon::XProcView::sample_count, leanux::util::Stopwatch::stop(), leanux::tools::lmon::XProcView::t1, leanux::tools::lmon::XProcView::t2, leanux::process::StatsSorter::top, and xprocview_.
Referenced by sample().
sampleXSysView()
void leanux::tools::lmon::RealtimeSampler::sampleXSysView (int cpubarheight) protected
Definition at line 240 of file realtime.cpp.
References leanux::cpu::SchedInfo::blocked, leanux::tools::lmon::XSysView::blockq, leanux::vmem::VMStat::committed_as, leanux::tools::lmon::XSysView::cpu_delta, leanux::tools::lmon::XSysView::cpu_seconds, leanux::tools::lmon::XSysView::cpu_topo, leanux::tools::lmon::XSysView::cpu_total, leanux::tools::lmon::XSysView::cpurtpast, cpustat1_, cpustat2_, leanux::tools::lmon::XSysView::ctxsws, leanux::cpu::SchedInfo::ctxt, leanux::cpu::deltaStats(), leanux::util::deltaTime(), leanux::tools::lmon::XSysView::forks, leanux::tools::lmon::XSysView::fs_growths, leanux::cpu::getCPUStats(), leanux::cpu::getCPUTopology(), leanux::cpu::getCPUTotal(), leanux::cpu::getLoadAvg(), leanux::block::getMountUsedBytes(), leanux::system::getNumLogins(), leanux::system::getNumLoginUsers(), leanux::system::getNumProcesses(), leanux::system::getOpenFiles(), leanux::system::getOpenInodes(), leanux::cpu::getSchedInfo(), leanux::vmem::getSwapInfo(), leanux::vmem::getVMStat(), leanux::vmem::VMStat::hugepages_free, leanux::vmem::VMStat::hugepages_reserved, leanux::vmem::VMStat::hugepages_total, leanux::vmem::VMStat::hugepagesize, leanux::cpu::CPUStat::iowait, leanux::cpu::CPUStat::irq, leanux::tools::lmon::XSysView::loadavg, leanux::cpu::CPUTopology::logical, leanux::tools::lmon::makeCPUBar(), leanux::tools::lmon::MAX_CPU_TRAIL, leanux::tools::lmon::XSysView::mem_allocs, leanux::tools::lmon::XSysView::mem_anon, leanux::tools::lmon::XSysView::mem_commitas, leanux::tools::lmon::XSysView::mem_dirty, leanux::tools::lmon::XSysView::mem_file, leanux::tools::lmon::XSysView::mem_frees, leanux::tools::lmon::XSysView::mem_hpfree, leanux::tools::lmon::XSysView::mem_hprsvd, leanux::tools::lmon::XSysView::mem_hptotal, leanux::tools::lmon::XSysView::mem_majflts, leanux::tools::lmon::XSysView::mem_mapped, leanux::tools::lmon::XSysView::mem_minflts, leanux::tools::lmon::XSysView::mem_mlock, leanux::tools::lmon::XSysView::mem_pageins, leanux::tools::lmon::XSysView::mem_pageouts, leanux::tools::lmon::XSysView::mem_pagetbls, leanux::tools::lmon::XSysView::mem_shmem, leanux::tools::lmon::XSysView::mem_slab, leanux::tools::lmon::XSysView::mem_swapins, leanux::tools::lmon::XSysView::mem_swapouts, leanux::tools::lmon::XSysView::mem_swpsize, leanux::tools::lmon::XSysView::mem_swpused, leanux::tools::lmon::XSysView::mem_thpanon, leanux::vmem::VMStat::mem_total, leanux::tools::lmon::XSysView::mem_total, leanux::tools::lmon::XSysView::mem_unused, mounted_bytes_1_, mounted_bytes_2_, leanux::cpu::CPUStat::nice, leanux::cpu::normalizeCPUstats(), leanux::vmem::VMStat::nr_anon_pages, leanux::vmem::VMStat::nr_anon_transparent_hugepages, leanux::vmem::VMStat::nr_dirty, leanux::vmem::VMStat::nr_file_pages, leanux::vmem::VMStat::nr_free_pages, leanux::vmem::VMStat::nr_mapped, leanux::vmem::VMStat::nr_mlock, leanux::vmem::VMStat::nr_page_table_pages, leanux::vmem::VMStat::nr_shmem, leanux::vmem::VMStat::nr_slab_reclaimable, leanux::vmem::VMStat::nr_slab_unreclaimable, leanux::tools::lmon::XSysView::pagesize_, leanux::vmem::VMStat::pgalloc_dma, leanux::vmem::VMStat::pgalloc_dma32, leanux::vmem::VMStat::pgalloc_movable, leanux::vmem::VMStat::pgalloc_normal, leanux::vmem::VMStat::pgfault, leanux::vmem::VMStat::pgfree, leanux::vmem::VMStat::pgmajfault, leanux::vmem::VMStat::pgpgin, leanux::vmem::VMStat::pgpgout, leanux::cpu::SchedInfo::processes, leanux::vmem::VMStat::pswpin, leanux::vmem::VMStat::pswpout, leanux::tools::lmon::XSysView::res_filesmax, leanux::tools::lmon::XSysView::res_filesopen, leanux::tools::lmon::XSysView::res_inodesfree, leanux::tools::lmon::XSysView::res_inodesopen, leanux::tools::lmon::XSysView::res_logins, leanux::tools::lmon::XSysView::res_processes, leanux::tools::lmon::XSysView::res_users, leanux::cpu::SchedInfo::running, leanux::tools::lmon::XSysView::runq, leanux::tools::lmon::XSysView::sample_count, sched1_, sched2_, leanux::cpu::CPUStat::softirq, leanux::cpu::CPUStat::steal, swaps_, leanux::cpu::CPUStat::system, leanux::tools::lmon::XSysView::t1, leanux::tools::lmon::XSysView::t2, leanux::tools::lmon::XSysView::time_slice, leanux::cpu::CPUStat::user, vmstat1_, vmstat2_, and xsysview_.
Referenced by sample().
Field Documentation
cpuinfo_
cpu::CPUInfo leanux::tools::lmon::RealtimeSampler::cpuinfo_ protected
cpu model info
Definition at line 119 of file realtime.hpp.
Referenced by RealtimeSampler().
cpustat1_
cpu::CPUStatsMap leanux::tools::lmon::RealtimeSampler::cpustat1_ protected
Earlier CPUStatsMap snapshot.
Definition at line 84 of file realtime.hpp.
Referenced by sampleXSysView().
cpustat2_
cpu::CPUStatsMap leanux::tools::lmon::RealtimeSampler::cpustat2_ protected
Later CPUStatsMap snapshot.
Definition at line 87 of file realtime.hpp.
Referenced by sampleXSysView().
delta_
leanux::cpu::CPUStatsMap leanux::tools::lmon::RealtimeSampler::delta_ protected
Delta of stat1_ and stat2_.
Definition at line 116 of file realtime.hpp.
devicefilecache_
std::map< std::string, block::MajorMinor > leanux::tools::lmon::RealtimeSampler::devicefilecache_ static protected
cache of device special files to MajorMinor
Definition at line 122 of file realtime.hpp.
Referenced by sampleXIOView().
disabled_procs_
unsigned long leanux::tools::lmon::RealtimeSampler::disabled_procs_ protected
number of procs on the system when sampling disabled.
Definition at line 137 of file realtime.hpp.
Referenced by sampleXProcView().
diskstats1_
block::DeviceStatsMap leanux::tools::lmon::RealtimeSampler::diskstats1_ protected
Earlier DeviceStatsMap snapshot.
Definition at line 105 of file realtime.hpp.
Referenced by sampleXIOView().
diskstats2_
block::DeviceStatsMap leanux::tools::lmon::RealtimeSampler::diskstats2_ protected
Later DeviceStatsMap snapshot.
Definition at line 108 of file realtime.hpp.
Referenced by sampleXIOView().
max_proc_sample_time
const double leanux::tools::lmon::RealtimeSampler::max_proc_sample_time static protected
maximum sample duration in seconds before being disabled.
Definition at line 140 of file realtime.hpp.
mounted_bytes_1_
unsigned long leanux::tools::lmon::RealtimeSampler::mounted_bytes_1_ protected
Definition at line 111 of file realtime.hpp.
Referenced by RealtimeSampler(), and sampleXSysView().
mounted_bytes_2_
unsigned long leanux::tools::lmon::RealtimeSampler::mounted_bytes_2_ protected
Definition at line 113 of file realtime.hpp.
Referenced by RealtimeSampler(), and sampleXSysView().
netsnap1_
net::NetStatDeviceMap leanux::tools::lmon::RealtimeSampler::netsnap1_ protected
earlier snap.
Definition at line 125 of file realtime.hpp.
Referenced by sampleXNetView().
netsnap2_
net::NetStatDeviceMap leanux::tools::lmon::RealtimeSampler::netsnap2_ protected
later snap.
Definition at line 128 of file realtime.hpp.
Referenced by sampleXNetView().
procsnap1_
process::ProcPidStatMap leanux::tools::lmon::RealtimeSampler::procsnap1_ protected
earlier snap.
Definition at line 131 of file realtime.hpp.
Referenced by sampleXProcView().
procsnap2_
process::ProcPidStatMap leanux::tools::lmon::RealtimeSampler::procsnap2_ protected
later snap.
Definition at line 134 of file realtime.hpp.
Referenced by sampleXProcView().
sched1_
cpu::SchedInfo leanux::tools::lmon::RealtimeSampler::sched1_ protected
Earlier SchedInfo snapshot.
Definition at line 90 of file realtime.hpp.
Referenced by sampleXSysView().
sched2_
cpu::SchedInfo leanux::tools::lmon::RealtimeSampler::sched2_ protected
Later SchedInfo snapshot.
Definition at line 93 of file realtime.hpp.
Referenced by sampleXSysView().
swaps_
std::list<vmem::SwapInfo> leanux::tools::lmon::RealtimeSampler::swaps_ protected
List of SwapInfo.
Definition at line 102 of file realtime.hpp.
Referenced by sampleXIOView(), and sampleXSysView().
vmstat1_
vmem::VMStat leanux::tools::lmon::RealtimeSampler::vmstat1_ protected
Earlier VMStat snapshot.
Definition at line 96 of file realtime.hpp.
Referenced by sampleXSysView().
vmstat2_
vmem::VMStat leanux::tools::lmon::RealtimeSampler::vmstat2_ protected
Later VMStat snapshot.
Definition at line 99 of file realtime.hpp.
Referenced by sampleXSysView().
xioview_
XIOView leanux::tools::lmon::RealtimeSampler::xioview_ protected
Definition at line 78 of file realtime.hpp.
Referenced by getXIOView(), and sampleXIOView().
xnetview_
XNetView leanux::tools::lmon::RealtimeSampler::xnetview_ protected
Definition at line 80 of file realtime.hpp.
Referenced by getXNetView(), and sampleXNetView().
xprocview_
XProcView leanux::tools::lmon::RealtimeSampler::xprocview_ protected
Definition at line 81 of file realtime.hpp.
Referenced by getXProcView(), RealtimeSampler(), and sampleXProcView().
xsysview_
XSysView leanux::tools::lmon::RealtimeSampler::xsysview_ protected
Definition at line 79 of file realtime.hpp.
Referenced by getXSysView(), RealtimeSampler(), resetCPUTrail(), and sampleXSysView().
The documentation for this class was generated from the following files:
tools/lmon/realtime.hpp
tools/lmon/realtime.cpp