leanux: leanux::tools::labbix Namespace Reference
leanux::tools::labbix Namespace Reference
Functions
void discovery (std::ostream &json)
generate the JSON zabbix expects.
block::MajorMinor findByZabbix (const std::string &zabid)
void getIOms (const std::string &zabid, std::ostream &output)
void getIOs (const std::string &zabid, std::ostream &output)
void getReadms (const std::string &zabid, std::ostream &output)
void getReads (const std::string &zabid, std::ostream &output)
void getReadSectors (const std::string &zabid, std::ostream &output)
void getWritems (const std::string &zabid, std::ostream &output)
void getWrites (const std::string &zabid, std::ostream &output)
void getWriteSectors (const std::string &zabid, std::ostream &output)
int main (int argc, char *argv[])
int printHelp (int r)
std::string zabbifyId (const std::string &id)
Detailed Description
GNU/Linux Zabbix UserParameter disk monitoring extension
Function Documentation
discovery()
void leanux::tools::labbix::discovery (std::ostream & json)
generate the JSON zabbix expects.
Definition at line 63 of file labbix.cpp.
References leanux::block::enumWholeDisks(), and zabbifyId().
Referenced by main().
findByZabbix()
block::MajorMinor leanux::tools::labbix::findByZabbix (const std::string & zabid)
Definition at line 49 of file labbix.cpp.
References leanux::block::enumWholeDisks(), leanux::block::MajorMinor::invalid, and zabbifyId().
Referenced by getIOms(), getIOs(), getReadms(), getReads(), getReadSectors(), getWritems(), getWrites(), and getWriteSectors().
getIOms()
void leanux::tools::labbix::getIOms (const std::string & zabid, std::ostream & output)
Definition at line 137 of file labbix.cpp.
References findByZabbix(), leanux::block::MajorMinor::getStats(), leanux::block::MajorMinor::invalid, and leanux::block::DeviceStats::io_ms.
Referenced by main().
getIOs()
void leanux::tools::labbix::getIOs (const std::string & zabid, std::ostream & output)
Definition at line 127 of file labbix.cpp.
References findByZabbix(), leanux::block::MajorMinor::getStats(), leanux::block::MajorMinor::invalid, leanux::block::DeviceStats::reads, and leanux::block::DeviceStats::writes.
Referenced by main().
getReadms()
void leanux::tools::labbix::getReadms (const std::string & zabid, std::ostream & output)
Definition at line 147 of file labbix.cpp.
References findByZabbix(), leanux::block::MajorMinor::getStats(), leanux::block::MajorMinor::invalid, and leanux::block::DeviceStats::read_ms.
Referenced by main().
getReads()
void leanux::tools::labbix::getReads (const std::string & zabid, std::ostream & output)
Definition at line 87 of file labbix.cpp.
References findByZabbix(), leanux::block::MajorMinor::getStats(), leanux::block::MajorMinor::invalid, and leanux::block::DeviceStats::reads.
Referenced by main().
getReadSectors()
void leanux::tools::labbix::getReadSectors (const std::string & zabid, std::ostream & output)
Definition at line 97 of file labbix.cpp.
References findByZabbix(), leanux::block::MajorMinor::getStats(), leanux::block::MajorMinor::invalid, and leanux::block::DeviceStats::read_sectors.
Referenced by main().
getWritems()
void leanux::tools::labbix::getWritems (const std::string & zabid, std::ostream & output)
Definition at line 157 of file labbix.cpp.
References findByZabbix(), leanux::block::MajorMinor::getStats(), leanux::block::MajorMinor::invalid, and leanux::block::DeviceStats::write_ms.
Referenced by main().
getWrites()
void leanux::tools::labbix::getWrites (const std::string & zabid, std::ostream & output)
Definition at line 107 of file labbix.cpp.
References findByZabbix(), leanux::block::MajorMinor::getStats(), leanux::block::MajorMinor::invalid, and leanux::block::DeviceStats::writes.
Referenced by main().
getWriteSectors()
void leanux::tools::labbix::getWriteSectors (const std::string & zabid, std::ostream & output)
Definition at line 117 of file labbix.cpp.
References findByZabbix(), leanux::block::MajorMinor::getStats(), leanux::block::MajorMinor::invalid, and leanux::block::DeviceStats::write_sectors.
Referenced by main().
main()
int leanux::tools::labbix::main (int argc, char * argv[])
Definition at line 195 of file labbix.cpp.
References discovery(), getIOms(), getIOs(), getReadms(), getReads(), getReadSectors(), getWritems(), getWrites(), getWriteSectors(), leanux::init(), and printHelp().
Referenced by main().
printHelp()
int leanux::tools::labbix::printHelp (int r)
Definition at line 167 of file labbix.cpp.
Referenced by main().
zabbifyId()
std::string leanux::tools::labbix::zabbifyId (const std::string & id)
Definition at line 19 of file labbix.cpp.
Referenced by discovery(), and findByZabbix().