leanux: leanux::persist::Database Class Reference
leanux::persist::Database Class Reference
A STL friendly wrapper around a sqlite3 database.
#include <persist.hpp>
Public Member Functions
Database (const std::string &filename, WaitHandler handler=0)
Constructor with explicit wait handler.
~Database ()
Destructor.
void begin ()
Begin a transaction.
void beginExclusive ()
Begin an exclusive transaction.
void beginImmediate ()
Begin an immediate transaction.
void checkPointPassive ()
Issue a passive checpoint.
void checkPointTruncate ()
Issue a (WAL) truncate checpoint.
void commit ()
Commit a transaction.
void disableForeignKeys ()
void enableForeignKeys ()
Enable foreign key constraints.
void enableTriggers ()
Enable triggers.
std::string fileName () const
sqlite3 * getDB () const
Return database handle.
int getUserVersion ()
get the current user_version pragma
long lastInsertRowid () const
Get the rowid of the last inserted row.
void release (const std::string &sp)
Release a savepoint.
void releaseMemory ()
void rollback ()
Rollback a transaction.
void rollback (const std::string &sp)
Rollback to a savepoint.
void savepoint (const std::string &sp)
Create a named savepoint.
void setUserVersion (int version)
set the user_version pragma
Static Public Member Functions
static unsigned long memHighWater ()
static unsigned long memUsed ()
static long softHeapLimit (long limit)
Protected Attributes
sqlite3 * database_
Database handle.
Detailed Description
A STL friendly wrapper around a sqlite3 database.
Additionally, a few extension functions are added for use in SQL
power(double x,double y) gives base x to the power y (x^y)
floor(double x) gives the nearest integer downwards
ceil(double x) gives the nearest integer upwards
Definition at line 62 of file persist.hpp.
Constructor & Destructor Documentation
Database()
leanux::persist::Database::Database (const std::string & filename, WaitHandler handler = 0)
Constructor with explicit wait handler.
Parameters
filename the database filename
handler the wait handler
Definition at line 134 of file persist.cpp.
References database_, leanux::persist::sqlite_ext_ceil(), leanux::persist::sqlite_ext_floor(), leanux::persist::sqlite_ext_log2(), and leanux::persist::sqlite_ext_pow().
~Database()
leanux::persist::Database::~Database ()
Destructor.
Definition at line 197 of file persist.cpp.
References database_.
Member Function Documentation
begin()
void leanux::persist::Database::begin ()
Begin a transaction.
Definition at line 226 of file persist.cpp.
References leanux::persist::Statement::close(), leanux::persist::DDL::execute(), and leanux::persist::Statement::prepare().
Referenced by leanux::tools::lard::mainLoop(), and leanux::tools::lard::shrinkDB().
beginExclusive()
void leanux::persist::Database::beginExclusive ()
Begin an exclusive transaction.
Definition at line 244 of file persist.cpp.
References leanux::persist::Statement::close(), leanux::persist::DDL::execute(), and leanux::persist::Statement::prepare().
beginImmediate()
void leanux::persist::Database::beginImmediate ()
Begin an immediate transaction.
Definition at line 235 of file persist.cpp.
References leanux::persist::Statement::close(), leanux::persist::DDL::execute(), and leanux::persist::Statement::prepare().
checkPointPassive()
void leanux::persist::Database::checkPointPassive ()
Issue a passive checpoint.
Definition at line 306 of file persist.cpp.
References database_.
Referenced by leanux::tools::lard::mainLoop().
checkPointTruncate()
void leanux::persist::Database::checkPointTruncate ()
Issue a (WAL) truncate checpoint.
Definition at line 315 of file persist.cpp.
References database_.
Referenced by leanux::tools::lard::mainLoop().
commit()
void leanux::persist::Database::commit ()
Commit a transaction.
Definition at line 253 of file persist.cpp.
References leanux::persist::Statement::close(), leanux::persist::DDL::execute(), and leanux::persist::Statement::prepare().
Referenced by leanux::tools::lard::mainLoop(), and leanux::tools::lard::shrinkDB().
disableForeignKeys()
void leanux::persist::Database::disableForeignKeys ()
Definition at line 210 of file persist.cpp.
References database_.
enableForeignKeys()
void leanux::persist::Database::enableForeignKeys ()
Enable foreign key constraints.
Definition at line 202 of file persist.cpp.
References database_.
Referenced by leanux::tools::lard::mainLoop().
enableTriggers()
void leanux::persist::Database::enableTriggers ()
Enable triggers.
Definition at line 218 of file persist.cpp.
References database_.
fileName()
std::string leanux::persist::Database::fileName () const inline
Definition at line 168 of file persist.hpp.
References database_.
Referenced by leanux::tools::lmon::Screen::runHistory().
getDB()
sqlite3* leanux::persist::Database::getDB () const inline
Return database handle.
Returns
the sqlite3 database handle.
Definition at line 93 of file persist.hpp.
References database_.
Referenced by leanux::persist::Statement::Statement().
getUserVersion()
int leanux::persist::Database::getUserVersion ()
get the current user_version pragma
Definition at line 337 of file persist.cpp.
References leanux::persist::Statement::close(), database_, leanux::persist::Query::getInt(), leanux::persist::Statement::prepare(), and leanux::persist::Query::step().
Referenced by leanux::tools::lard::mainLoop(), and leanux::tools::lard::updateSchema().
lastInsertRowid()
long leanux::persist::Database::lastInsertRowid () const
Get the rowid of the last inserted row.
Definition at line 298 of file persist.cpp.
References database_.
Referenced by leanux::tools::lard::TimeSnap::storeSnap(), leanux::tools::lard::IOSnap::storeSnap(), leanux::tools::lard::NetSnap::storeSnap(), leanux::tools::lard::ProcSnap::storeSnap(), leanux::tools::lard::MountSnap::storeSnap(), and leanux::tools::lard::TCPEstaSnap::storeSnap().
memHighWater()
static unsigned long leanux::persist::Database::memHighWater () inline static
Definition at line 160 of file persist.hpp.
Referenced by leanux::tools::lard::mainLoop().
memUsed()
static unsigned long leanux::persist::Database::memUsed () inline static
Definition at line 156 of file persist.hpp.
Referenced by leanux::tools::lard::mainLoop().
release()
void leanux::persist::Database::release (const std::string & sp)
Release a savepoint.
Parameters
sp the savepoint name
Definition at line 280 of file persist.cpp.
References leanux::persist::Statement::close(), leanux::persist::DDL::execute(), and leanux::persist::Statement::prepare().
releaseMemory()
void leanux::persist::Database::releaseMemory ()
Definition at line 348 of file persist.cpp.
References database_.
rollback() [1/2]
void leanux::persist::Database::rollback ()
Rollback a transaction.
Definition at line 262 of file persist.cpp.
References leanux::persist::Statement::close(), leanux::persist::DDL::execute(), and leanux::persist::Statement::prepare().
rollback() [2/2]
void leanux::persist::Database::rollback (const std::string & sp)
Rollback to a savepoint.
Parameters
sp the savepoint name
Definition at line 289 of file persist.cpp.
References leanux::persist::Statement::close(), leanux::persist::DDL::execute(), and leanux::persist::Statement::prepare().
savepoint()
void leanux::persist::Database::savepoint (const std::string & sp)
Create a named savepoint.
Parameters
sp the savepoint name
See also
release, rollback
Definition at line 271 of file persist.cpp.
References leanux::persist::Statement::close(), leanux::persist::DDL::execute(), and leanux::persist::Statement::prepare().
setUserVersion()
void leanux::persist::Database::setUserVersion (int version)
set the user_version pragma
Definition at line 328 of file persist.cpp.
References leanux::persist::Statement::close(), leanux::persist::DDL::execute(), and leanux::persist::Statement::prepare().
Referenced by leanux::tools::lard::updateSchema().
softHeapLimit()
static long leanux::persist::Database::softHeapLimit (long limit) inline static
Definition at line 164 of file persist.hpp.
Referenced by leanux::tools::lard::mainLoop().
Field Documentation
database_
sqlite3* leanux::persist::Database::database_ protected
Database handle.
Definition at line 168 of file persist.hpp.
Referenced by checkPointPassive(), checkPointTruncate(), Database(), disableForeignKeys(), enableForeignKeys(), enableTriggers(), fileName(), getDB(), getUserVersion(), lastInsertRowid(), releaseMemory(), and ~Database().
The documentation for this class was generated from the following files:
lib/persist.hpp
lib/persist.cpp