leanux: leanux::persist Namespace Reference
leanux::persist Namespace Reference
Persistent SQL storage, uses the great sqlite3.
Data Structures
class Database
A STL friendly wrapper around a sqlite3 database.
class DDL
Data Definition Language, SQL that takes no parameters, returns no data such as CREATE TABLE.
class DML
Data Modification Language statements can take bind values.
class Query
Queries can take bind values and return select lists.
class Statement
Generic SQL Statement.
Typedefs
typedef int(* WaitHandler) (void *, int)
Functions
static void sqlite_ext_ceil (sqlite3_context *context, int argc, sqlite3_value **argv)
static void sqlite_ext_floor (sqlite3_context *context, int argc, sqlite3_value **argv)
static void sqlite_ext_log2 (sqlite3_context *context, int argc, sqlite3_value **argv)
static void sqlite_ext_pow (sqlite3_context *context, int argc, sqlite3_value **argv)
Detailed Description
Persistent SQL storage, uses the great sqlite3.
Typedef Documentation
WaitHandler
typedef int(* leanux::persist::WaitHandler) (void *, int)
Definition at line 52 of file persist.hpp.
Function Documentation
sqlite_ext_ceil()
static void leanux::persist::sqlite_ext_ceil (sqlite3_context * context, int argc, sqlite3_value ** argv) static
Definition at line 94 of file persist.cpp.
Referenced by leanux::persist::Database::Database().
sqlite_ext_floor()
static void leanux::persist::sqlite_ext_floor (sqlite3_context * context, int argc, sqlite3_value ** argv) static
Definition at line 114 of file persist.cpp.
Referenced by leanux::persist::Database::Database().
sqlite_ext_log2()
static void leanux::persist::sqlite_ext_log2 (sqlite3_context * context, int argc, sqlite3_value ** argv) static
Definition at line 74 of file persist.cpp.
Referenced by leanux::persist::Database::Database().
sqlite_ext_pow()
static void leanux::persist::sqlite_ext_pow (sqlite3_context * context, int argc, sqlite3_value ** argv) static
Definition at line 52 of file persist.cpp.
Referenced by leanux::persist::Database::Database().