leanux: leanux::util::Stopwatch Class Reference
leanux::util::Stopwatch Class Reference
Stopwatch to time durations with microsecond precision.
#include <util.hpp>
Public Member Functions
Stopwatch ()
~Stopwatch ()
double getElapsedSeconds () const
void start ()
Start the Stopwatch.
double stop ()
stop the Stopwatch.
Private Attributes
struct timeval t1_
start time
struct timeval t2_
stop time
Detailed Description
Stopwatch to time durations with microsecond precision.
Definition at line 281 of file util.hpp.
Constructor & Destructor Documentation
Stopwatch()
leanux::util::Stopwatch::Stopwatch () inline
Definition at line 284 of file util.hpp.
References t1_, and t2_.
~Stopwatch()
leanux::util::Stopwatch::~Stopwatch () inline
Definition at line 286 of file util.hpp.
Member Function Documentation
getElapsedSeconds()
double leanux::util::Stopwatch::getElapsedSeconds () const
Definition at line 435 of file util.cpp.
References t1_.
Referenced by leanux::tools::lrep::main(), and leanux::tools::lard::mainLoop().
start()
void leanux::util::Stopwatch::start () inline
Start the Stopwatch.
Definition at line 291 of file util.hpp.
References t1_.
Referenced by leanux::tools::lrep::main(), and leanux::tools::lard::mainLoop().
stop()
double leanux::util::Stopwatch::stop () inline
stop the Stopwatch.
Returns
number of seconds since last call to start.
Definition at line 297 of file util.hpp.
References t1_, and t2_.
Referenced by leanux::tools::lrep::main(), and leanux::tools::lmon::RealtimeSampler::sampleXProcView().
Field Documentation
t1_
struct timeval leanux::util::Stopwatch::t1_ private
start time
Definition at line 303 of file util.hpp.
Referenced by getElapsedSeconds(), start(), stop(), and Stopwatch().
t2_
struct timeval leanux::util::Stopwatch::t2_ private
stop time
Definition at line 306 of file util.hpp.
Referenced by stop(), and Stopwatch().
The documentation for this class was generated from the following files:
lib/util.hpp
lib/util.cpp