leanux: leanux::tools::lmon::Screen Class Reference
leanux::tools::lmon::Screen Class Reference
The curses screen.
#include <lmon_curses.hpp>
Public Member Functions
Screen ()
Constructor.
~Screen ()
Destructor.
void clearMessage (unsigned int key)
Clear a message.
void reportMessage (unsigned int key, unsigned int prio, const std::string &message)
Report a message.
void runHistory (persist::Database *db)
Run the Screen in history mode.
void runRealtime ()
Run the Screen in realtime mode.
void Stop ()
Stop the Screen.
Data Fields
Palette palette_
The Screen palette.
Private Member Functions
void initTerminal ()
Initialize and start the ncurses Screen.
void resetTerminal ()
Deinitialize and stop the ncurses Screen.
void screenResize ()
Recalculate the window sizes.
bool sizeChanged ()
Determine if terminal size has changed.
Private Attributes
unsigned int footer_scroll_interval_s_
Footer scrolling interval.
unsigned int sample_interval_s_
The sample interval.
unsigned int sleep_duration_ms_
The amount of time to sleep between wakeups.
bool stopped_
If true, the Screen is requested to stop.
View * vfooter_
Footer View.
View * vheader_
Header View.
View * vio_
Disk/Filesystem View.
View * vnetwork_
Network View.
View * vprocess_
Process View.
View * vsys_
SysView.
struct winsize winsz_
Structure to hold the terminal size (columns,lines).
WINDOW * wmain_
ncurses main window.
Detailed Description
The curses screen.
Definition at line 748 of file lmon_curses.hpp.
Constructor & Destructor Documentation
Screen()
leanux::tools::lmon::Screen::Screen ()
Constructor.
Definition at line 189 of file lmon_curses.cpp.
References footer_scroll_interval_s_, leanux::util::ConfigFile::getConfig(), leanux::util::ConfigFile::getIntValue(), initTerminal(), sample_interval_s_, screenResize(), sleep_duration_ms_, stopped_, vfooter_, vheader_, vio_, vnetwork_, vprocess_, vsys_, and winsz_.
~Screen()
leanux::tools::lmon::Screen::~Screen ()
Destructor.
Definition at line 206 of file lmon_curses.cpp.
References leanux::util::ConfigFile::getConfig(), leanux::util::ConfigFile::read(), resetTerminal(), sample_interval_s_, leanux::util::ConfigFile::setValue(), vfooter_, vheader_, vio_, vnetwork_, vprocess_, vsys_, and leanux::util::ConfigFile::write().
Member Function Documentation
clearMessage()
void leanux::tools::lmon::Screen::clearMessage (unsigned int key)
Clear a message.
Parameters
key key of the message.
Definition at line 575 of file lmon_curses.cpp.
References vfooter_.
initTerminal()
void leanux::tools::lmon::Screen::initTerminal () private
Initialize and start the ncurses Screen.
Definition at line 224 of file lmon_curses.cpp.
References palette_, leanux::tools::lmon::Palette::setup(), TRACE, winsz_, and wmain_.
Referenced by Screen().
reportMessage()
void leanux::tools::lmon::Screen::reportMessage (unsigned int key, unsigned int prio, const std::string & message)
Report a message.
Parameters
key key of the message.
prio priority of the message.
message the message text.
Definition at line 571 of file lmon_curses.cpp.
References vfooter_.
Referenced by runHistory(), and runRealtime().
resetTerminal()
void leanux::tools::lmon::Screen::resetTerminal () private
Deinitialize and stop the ncurses Screen.
Definition at line 346 of file lmon_curses.cpp.
Referenced by ~Screen().
runHistory()
void leanux::tools::lmon::Screen::runHistory (persist::Database * db)
Run the Screen in history mode.
Definition at line 353 of file lmon_curses.cpp.
References leanux::tools::lmon::LardHistory::dayDown(), leanux::tools::lmon::LardHistory::dayUp(), leanux::util::deltaTime(), leanux::tools::lmon::LardHistory::fetchXIOView(), leanux::tools::lmon::LardHistory::fetchXNetView(), leanux::tools::lmon::LardHistory::fetchXProcView(), leanux::tools::lmon::LardHistory::fetchXSysView(), leanux::persist::Database::fileName(), footer_scroll_interval_s_, leanux::tools::lmon::LardHistory::getEndTime(), leanux::tools::lmon::LardHistory::getStartTime(), leanux::tools::lmon::HLP_BROWSE_ARROW, leanux::tools::lmon::HLP_BROWSE_DAY, leanux::tools::lmon::HLP_BROWSE_HOMEND, leanux::tools::lmon::HLP_BROWSE_HOUR, leanux::tools::lmon::HLP_BROWSE_WEEK, leanux::tools::lmon::HLP_QUIT, leanux::tools::lmon::LardHistory::hourDown(), leanux::tools::lmon::LardHistory::hourUp(), leanux::util::localStrISODateTime(), leanux::util::localStrISOTime(), leanux::tools::lmon::LardHistory::rangeDown(), leanux::tools::lmon::LardHistory::rangeEnd(), leanux::tools::lmon::LardHistory::rangeStart(), leanux::tools::lmon::LardHistory::rangeUp(), reportMessage(), screenResize(), sizeChanged(), leanux::util::Sleep(), sleep_duration_ms_, stopped_, leanux::tools::lmon::XSysView::t1, leanux::tools::lmon::XSysView::t2, leanux::util::TimeStrSec(), TRACE, vfooter_, vheader_, vio_, vnetwork_, vprocess_, vsys_, leanux::tools::lmon::LardHistory::weekDown(), leanux::tools::lmon::LardHistory::weekUp(), winsz_, wmain_, leanux::tools::lmon::LardHistory::zoomIn(), and leanux::tools::lmon::LardHistory::zoomOut().
Referenced by leanux::tools::lmon::main().
runRealtime()
void leanux::tools::lmon::Screen::runRealtime ()
Run the Screen in realtime mode.
Definition at line 475 of file lmon_curses.cpp.
References leanux::util::deltaTime(), footer_scroll_interval_s_, leanux::tools::lmon::View::getHeight(), leanux::tools::lmon::RealtimeSampler::getXIOView(), leanux::tools::lmon::RealtimeSampler::getXNetView(), leanux::tools::lmon::RealtimeSampler::getXProcView(), leanux::tools::lmon::RealtimeSampler::getXSysView(), leanux::tools::lmon::HLP_BROWSE_ARROW, leanux::tools::lmon::HLP_QUIT, leanux::util::localStrISODateTime(), reportMessage(), leanux::tools::lmon::RealtimeSampler::resetCPUTrail(), leanux::tools::lmon::RealtimeSampler::sample(), sample_interval_s_, screenResize(), sizeChanged(), leanux::util::Sleep(), sleep_duration_ms_, stopped_, TRACE, vfooter_, vheader_, vio_, vnetwork_, vprocess_, vsys_, winsz_, and wmain_.
Referenced by leanux::tools::lmon::main().
screenResize()
void leanux::tools::lmon::Screen::screenResize () private
Recalculate the window sizes.
Definition at line 245 of file lmon_curses.cpp.
References leanux::tools::lmon::Header::getMinHeight(), leanux::tools::lmon::Footer::getMinHeight(), leanux::tools::lmon::SysView::getMinHeight(), leanux::tools::lmon::IOView::getMinHeight(), leanux::tools::lmon::ProcessView::getMinHeight(), leanux::tools::lmon::NetView::getMinHeight(), leanux::tools::lmon::Header::getOptimalHeight(), leanux::tools::lmon::Footer::getOptimalHeight(), leanux::tools::lmon::SysView::getOptimalHeight(), leanux::tools::lmon::IOView::getOptimalHeight(), leanux::tools::lmon::ProcessView::getOptimalHeight(), leanux::tools::lmon::NetView::getOptimalHeight(), leanux::tools::lmon::View::resize(), TRACE, vfooter_, vheader_, vio_, vnetwork_, vprocess_, vsys_, and winsz_.
Referenced by runHistory(), runRealtime(), and Screen().
sizeChanged()
bool leanux::tools::lmon::Screen::sizeChanged () private
Determine if terminal size has changed.
Returns
true when the terminal size has changed.
Definition at line 563 of file lmon_curses.cpp.
References winsz_.
Referenced by runHistory(), and runRealtime().
Stop()
void leanux::tools::lmon::Screen::Stop () inline
Stop the Screen.
Definition at line 760 of file lmon_curses.hpp.
References stopped_.
Referenced by leanux::tools::lmon::main(), and leanux::tools::lmon::sig_handler().
Field Documentation
footer_scroll_interval_s_
unsigned int leanux::tools::lmon::Screen::footer_scroll_interval_s_ private
Footer scrolling interval.
Definition at line 860 of file lmon_curses.hpp.
Referenced by runHistory(), runRealtime(), and Screen().
palette_
Palette leanux::tools::lmon::Screen::palette_
The Screen palette.
Definition at line 789 of file lmon_curses.hpp.
Referenced by leanux::tools::lmon::SysView::attrFromCPUChar(), leanux::tools::lmon::Footer::Footer(), initTerminal(), leanux::tools::lmon::View::View(), leanux::tools::lmon::IOView::xrefresh(), and leanux::tools::lmon::ProcessView::xrefresh().
sample_interval_s_
unsigned int leanux::tools::lmon::Screen::sample_interval_s_ private
The sample interval.
Definition at line 855 of file lmon_curses.hpp.
Referenced by runRealtime(), Screen(), and ~Screen().
sleep_duration_ms_
unsigned int leanux::tools::lmon::Screen::sleep_duration_ms_ private
The amount of time to sleep between wakeups.
Definition at line 850 of file lmon_curses.hpp.
Referenced by runHistory(), runRealtime(), and Screen().
stopped_
bool leanux::tools::lmon::Screen::stopped_ private
If true, the Screen is requested to stop.
Definition at line 845 of file lmon_curses.hpp.
Referenced by runHistory(), runRealtime(), Screen(), and Stop().
vfooter_
View* leanux::tools::lmon::Screen::vfooter_ private
Footer View.
Definition at line 823 of file lmon_curses.hpp.
Referenced by clearMessage(), reportMessage(), runHistory(), runRealtime(), Screen(), screenResize(), and ~Screen().
vheader_
View* leanux::tools::lmon::Screen::vheader_ private
Header View.
Definition at line 820 of file lmon_curses.hpp.
Referenced by runHistory(), runRealtime(), Screen(), screenResize(), and ~Screen().
vio_
View* leanux::tools::lmon::Screen::vio_ private
Disk/Filesystem View.
Definition at line 829 of file lmon_curses.hpp.
Referenced by runHistory(), runRealtime(), Screen(), screenResize(), and ~Screen().
vnetwork_
View* leanux::tools::lmon::Screen::vnetwork_ private
Network View.
Definition at line 835 of file lmon_curses.hpp.
Referenced by runHistory(), runRealtime(), Screen(), screenResize(), and ~Screen().
vprocess_
View* leanux::tools::lmon::Screen::vprocess_ private
Process View.
Definition at line 832 of file lmon_curses.hpp.
Referenced by runHistory(), runRealtime(), Screen(), screenResize(), and ~Screen().
vsys_
View* leanux::tools::lmon::Screen::vsys_ private
SysView.
Definition at line 826 of file lmon_curses.hpp.
Referenced by runHistory(), runRealtime(), Screen(), screenResize(), and ~Screen().
winsz_
struct winsize leanux::tools::lmon::Screen::winsz_ private
Structure to hold the terminal size (columns,lines).
Definition at line 840 of file lmon_curses.hpp.
Referenced by initTerminal(), runHistory(), runRealtime(), Screen(), screenResize(), and sizeChanged().
wmain_
WINDOW* leanux::tools::lmon::Screen::wmain_ private
ncurses main window.
Definition at line 817 of file lmon_curses.hpp.
Referenced by initTerminal(), runHistory(), and runRealtime().
The documentation for this class was generated from the following files:
tools/lmon/lmon_curses.hpp
tools/lmon/lmon_curses.cpp