leanux: leanux::usb Namespace Reference
leanux::usb Namespace Reference
Data Structures
struct USBHardwareId
Indentifies hardware (documented in usb.ids).
struct USBHardwareInfo
human readable USBHardwareId translated through usb.ids.
Typedefs
typedef std::string USBDevicePath
Typedef for usb device absolute paths.
Enumerations
enum USBHardwareClass {
usbInterfaceDescriptor = 0x00, usbAudio = 0x01, usbCommAndCDC = 0x02, usbHID = 0x03,
usbPhysical = 0x05, usbImage = 0x06, usbPrinter = 0x07, usbMassStorage = 0x08,
usbHub = 0x09, usbCDCData = 0x0a, usbSmartCard = 0x0b, usbContentSecurity = 0x0d,
usbVideo = 0x0e, usbPersonalHealthcare = 0x0f, usbAudioVideo = 0x10, usbBillboard = 0x11,
usbDiagnostic = 0xdc, usbWireless = 0xe0, usbMisc = 0xef, usbVendorSpecific = 0xff
}
Identifies an USB device or interface hardware class.
Functions
void enumUSBDevices (std::list< USBDevicePath > &paths)
Enumerate the USB devices attached to the system.
USBDevicePath getParent (const USBDevicePath &path)
Get the parent device for the USBDevice.
USBHardwareClass getUSBDeviceHardwareClass (const USBDevicePath &path)
std::string getUSBHardwareClassStr (USBHardwareClass c)
bool getUSBHardwareId (const USBDevicePath &path, USBHardwareId &id)
Get the USBHardwareId from an USBDevicePath.
bool getUSBHardwareInfo (const USBHardwareId &id, USBHardwareInfo &inf)
Translate an USBHardwareId into an USBHardwareInfo by using the system (/usr/share) usb.ids database.
USBHardwareClass getUSBInterfaceHardwareClass (const USBDevicePath &path)
void init ()
initialize usb namespace.
Variables
std::string USBDeviceDatabase = "/usr/share/misc/pci.ids"
The location of the system's PCI device database.
Detailed Description
USB device API.
Data Structure Documentation
leanux::usb::USBHardwareId
struct leanux::usb::USBHardwareId
Indentifies hardware (documented in usb.ids).
Examples
example_usb.cpp.
Definition at line 74 of file usb.hpp.
Data Fields
unsigned int idProduct
unsigned int idVendor
leanux::usb::USBHardwareInfo
struct leanux::usb::USBHardwareInfo
human readable USBHardwareId translated through usb.ids.
Examples
example_usb.cpp.
Definition at line 82 of file usb.hpp.
Data Fields
string idProduct
string idVendor
Typedef Documentation
USBDevicePath
typedef std::string leanux::usb::USBDevicePath
Typedef for usb device absolute paths.
When connected to a PCI bus, such a path may be '/sys/devices/pci0000:00/0000:00:1a.0/usb5/5-1'.
See also
enumUSBDevices to obtain valid device paths for all connected USB devices.
Definition at line 120 of file usb.hpp.
Enumeration Type Documentation
USBHardwareClass
enum leanux::usb::USBHardwareClass
Identifies an USB device or interface hardware class.
http://www.usb.org/developers/defined_class
Enumerator
usbInterfaceDescriptor
usbAudio
usbCommAndCDC
usbHID
usbPhysical
usbImage
usbPrinter
usbMassStorage
usbHub
usbCDCData
usbSmartCard
usbContentSecurity
usbVideo
usbPersonalHealthcare
usbAudioVideo
usbBillboard
usbDiagnostic
usbWireless
usbMisc
usbVendorSpecific
Definition at line 91 of file usb.hpp.
Function Documentation
enumUSBDevices()
void leanux::usb::enumUSBDevices (std::list< USBDevicePath > & paths)
Enumerate the USB devices attached to the system.
See also
USBDevicePath.
Examples
example_usb.cpp.
Definition at line 76 of file usb.cpp.
References leanux::util::realPath(), and leanux::sysdevice::sysbus_root.
getParent()
USBDevicePath leanux::usb::getParent (const USBDevicePath & path)
Get the parent device for the USBDevice.
Examples
example_usb.cpp.
Definition at line 192 of file usb.cpp.
getUSBDeviceHardwareClass()
USBHardwareClass leanux::usb::getUSBDeviceHardwareClass (const USBDevicePath & path)
Definition at line 94 of file usb.cpp.
References leanux::util::fileReadAccess(), leanux::util::fileReadHexString(), and usbVendorSpecific.
Referenced by leanux::sysdevice::USBDevice::getClass(), leanux::sysdevice::USBBus::getClass(), and leanux::tools::lsys::getLeafColStr().
getUSBHardwareClassStr()
std::string leanux::usb::getUSBHardwareClassStr (USBHardwareClass c)
Definition at line 109 of file usb.cpp.
References usbAudio, usbAudioVideo, usbBillboard, usbCDCData, usbCommAndCDC, usbContentSecurity, usbDiagnostic, usbHID, usbHub, usbImage, usbInterfaceDescriptor, usbMassStorage, usbMisc, usbPersonalHealthcare, usbPhysical, usbPrinter, usbSmartCard, usbVendorSpecific, usbVideo, and usbWireless.
Referenced by leanux::sysdevice::USBDevice::getClass(), leanux::sysdevice::USBInterface::getClass(), leanux::sysdevice::USBBus::getClass(), and leanux::tools::lsys::getLeafColStr().
getUSBHardwareId()
bool leanux::usb::getUSBHardwareId (const USBDevicePath & path, USBHardwareId & id)
Get the USBHardwareId from an USBDevicePath.
Examples
example_usb.cpp.
Definition at line 135 of file usb.cpp.
References leanux::util::fileReadAccess(), and leanux::util::fileReadHexString().
Referenced by leanux::sysdevice::USBDevice::getClass(), leanux::sysdevice::USBBus::getClass(), leanux::sysdevice::USBDevice::getDescription(), leanux::sysdevice::USBBus::getDescription(), leanux::sysdevice::USBDevice::getDisplayName(), leanux::sysdevice::USBBus::getDisplayName(), leanux::tools::lsys::getLeafColStr(), leanux::sysdevice::USBDevice::getPropertyValueList(), and leanux::sysdevice::USBBus::getPropertyValueList().
getUSBHardwareInfo()
bool leanux::usb::getUSBHardwareInfo (const USBHardwareId & id, USBHardwareInfo & inf)
Translate an USBHardwareId into an USBHardwareInfo by using the system (/usr/share) usb.ids database.
Examples
example_usb.cpp.
Definition at line 144 of file usb.cpp.
References leanux::usb::USBHardwareInfo::idProduct, leanux::usb::USBHardwareInfo::idVendor, and USBDeviceDatabase.
Referenced by leanux::sysdevice::USBDevice::getClass(), leanux::sysdevice::USBBus::getClass(), leanux::sysdevice::USBDevice::getDescription(), leanux::sysdevice::USBBus::getDescription(), leanux::sysdevice::USBDevice::getDisplayName(), leanux::sysdevice::USBBus::getDisplayName(), leanux::tools::lsys::getLeafColStr(), leanux::sysdevice::USBDevice::getPropertyValueList(), and leanux::sysdevice::USBBus::getPropertyValueList().
getUSBInterfaceHardwareClass()
USBHardwareClass leanux::usb::getUSBInterfaceHardwareClass (const USBDevicePath & path)
Definition at line 100 of file usb.cpp.
References leanux::util::fileReadAccess(), and leanux::util::fileReadHexString().
Referenced by leanux::sysdevice::USBInterface::getClass(), and leanux::tools::lsys::getLeafColStr().
init()
void leanux::usb::init ()
initialize usb namespace.
Definition at line 64 of file usb.cpp.
References leanux::util::fileReadAccess(), and USBDeviceDatabase.
Referenced by leanux::init().
Variable Documentation
USBDeviceDatabase
std::string leanux::usb::USBDeviceDatabase = "/usr/share/misc/pci.ids"
The location of the system's PCI device database.
This varies among GNU/Linux distributions, set by and see pci::init().
Definition at line 62 of file usb.cpp.
Referenced by getUSBHardwareInfo(), and init().