leanux: leanux::pci Namespace Reference
leanux::pci Namespace Reference
Data Structures
struct PCIAddress
PCI address identifying a PCI device function.
struct PCIHardwareId
Identifies PCI hardware.
struct PCIHardwareInfo
Human readable variant of PCIHardwareId.
Typedefs
typedef std::string PCIDevicePath
String path relative to /sys/devices identifying the PCI device on the system, typedeffed for API clarity.
Enumerations
enum PCIHardwareClass {
pciOld = 0x0, pciMassStorage = 0x01, pciNetwork = 0x02, pciDisplay = 0x03,
pciMultimedia = 0x04, pciMemory = 0x05, pciBridge = 0x06, pciSimpleCommunication = 0x07,
pciBaseSystemPeripheral = 0x08, pciInput = 0x09, pciDockingStation = 0x0a, pciProcessor = 0x0b,
pciSerialBus = 0x0c, pciWireless = 0x0d, pciIntelligentIO = 0x0e, pciSatelliteCommunication = 0x0f,
pciEncryption = 0x10, pciDataAquisistion = 0x11, pciUnclassified = 0xff
}
enumerate main PCI hardware classes
Functions
PCIAddress decodeEBDF (const std::string &s)
Decode an EBDF std::string into a PCIAddress.
void enumPCIATAPorts (const PCIDevicePath &device, std::list< std::string > &ports)
Enumerate ata ports for a given PCI device.
void enumPCIDevicePaths (std::list< PCIDevicePath > &paths)
get PCI device paths relative to /sys/devices/
PCIDevicePath findPCIDeviceByATAPort (const std::string &port)
return a device path relative to /sys/devices to the PCI device providing the ATA port.
PCIDevicePath findPCIDeviceByIRQ (unsigned int irq)
return a device path relative to /sys/devices to the PCI device assigned the irq
std::string getBDF (const PCIAddress &id)
Get the BDF format std::string for a PCIId 03:04.0 03 = bus number 04 = device number 0 = function number.
std::string getEBDF (const PCIAddress &id)
Get the EBDF format std::string for a PCIId.
std::string getEtherNetworkInterfaceName (const PCIDevicePath &device)
Get the name of an ethernet network communication device, such as 'eth0'.
unsigned int getPCIDeviceIRQ (const PCIDevicePath &device)
Get the IRQ assigned to a PCI device.
PCIHardwareClass getPCIHardwareClass (unsigned int classcode)
Transform a PCI class code to a PCIHardwareClass.
std::string getPCIHardwareClassString (unsigned int classcode)
Transform a PCI class code to class name.
PCIHardwareId getPCIHardwareId (const PCIDevicePath &devicepath)
get PCIHardwareId for a PCI device path relative to /sys/devives/
bool getPCIHardwareInfo (const PCIHardwareId &id, PCIHardwareInfo &inf)
Get PCI device info based on (vendor,device) function retrieves data from /usr/share/misc/pci.ids.
std::string getPCISubClassString (unsigned int classcode)
Get the PCI subclass name for a PCI class code http://wiki.osdev.org/PCI#Class_Codes.
void init ()
Initialize pci namespace.
bool isPCIDevice (const PCIDevicePath &path)
std::ostream & operator<< (std::ostream &os, PCIAddress a)
handy for debugging.
std::ostream & operator<< (std::ostream &os, PCIHardwareInfo i)
handy for debugging.
Variables
const PCIAddress NullPCIAddress = {0xffff, 0xffff, 0xffff, 0xffff}
Invalid PCIAddress.
std::string PCIDeviceDatabase = "/usr/share/misc/pci.ids"
The location of the system's PCI device database.
Detailed Description
PCI device API.
Data Structure Documentation
leanux::pci::PCIHardwareId
struct leanux::pci::PCIHardwareId
Identifies PCI hardware.
See also
getPCIHardwareId
Examples
example_pci.cpp.
Definition at line 199 of file pci.hpp.
Data Fields
unsigned int device
unsigned int pciclass
unsigned int subdevice
unsigned int subvendor
unsigned int vendor
leanux::pci::PCIHardwareInfo
struct leanux::pci::PCIHardwareInfo
Human readable variant of PCIHardwareId.
See also
getPCIHardwareInfo.
Examples
example_pci.cpp.
Definition at line 211 of file pci.hpp.
Data Fields
string device
string pciclass
string pcisubclass
string subdevice
string vendor
Typedef Documentation
PCIDevicePath
typedef std::string leanux::pci::PCIDevicePath
String path relative to /sys/devices identifying the PCI device on the system, typedeffed for API clarity.
Definition at line 75 of file pci.hpp.
Enumeration Type Documentation
PCIHardwareClass
enum leanux::pci::PCIHardwareClass
enumerate main PCI hardware classes
Enumerator
pciOld
pciMassStorage
pciNetwork
pciDisplay
pciMultimedia
pciMemory
pciBridge
pciSimpleCommunication
pciBaseSystemPeripheral
pciInput
pciDockingStation
pciProcessor
pciSerialBus
pciWireless
pciIntelligentIO
pciSatelliteCommunication
pciEncryption
pciDataAquisistion
pciUnclassified
Definition at line 155 of file pci.hpp.
Function Documentation
decodeEBDF()
PCIAddress leanux::pci::decodeEBDF (const std::string & s)
Decode an EBDF std::string into a PCIAddress.
Parameters
s the EBDF std::string to decode.
Returns
the PCIAddress that s specifies in EBDF.
Definition at line 99 of file pci.cpp.
References leanux::pci::PCIAddress::bus, leanux::pci::PCIAddress::device, leanux::pci::PCIAddress::domain, leanux::pci::PCIAddress::function, and NullPCIAddress.
enumPCIATAPorts()
void leanux::pci::enumPCIATAPorts (const PCIDevicePath & device, std::list< std::string > & ports)
Enumerate ata ports for a given PCI device.
Only valid to call on pciMassStorage devcies.
Parameters
device the PCIDevicePath.
ports a std::list of ata ports.
Examples
example_pci.cpp.
Definition at line 637 of file pci.cpp.
References getPCIHardwareClass(), getPCIHardwareId(), leanux::pci::PCIHardwareId::pciclass, and pciMassStorage.
Referenced by findPCIDeviceByATAPort().
enumPCIDevicePaths()
void leanux::pci::enumPCIDevicePaths (std::list< PCIDevicePath > & paths)
get PCI device paths relative to /sys/devices/
get a complete std::list of PCIDevicePaths pointing to PCI devices under /sys/devices.
Parameters
paths the std::list of device paths to fill.
See also
getPCIHardwareId to convert a device path std::string to a PCIHardwareId.
Examples
example_pci.cpp.
Definition at line 584 of file pci.cpp.
References leanux::util::realPath(), and leanux::sysdevice::sysbus_root.
Referenced by findPCIDeviceByATAPort(), findPCIDeviceByIRQ(), and isPCIDevice().
findPCIDeviceByATAPort()
PCIDevicePath leanux::pci::findPCIDeviceByATAPort (const std::string & port)
return a device path relative to /sys/devices to the PCI device providing the ATA port.
Parameters
port the sought ATA port
Returns
the device path realtive to /sys/devices/ if found, empty std::string otherwise
Definition at line 614 of file pci.cpp.
References enumPCIATAPorts(), enumPCIDevicePaths(), getPCIHardwareClass(), getPCIHardwareId(), leanux::pci::PCIHardwareId::pciclass, and pciMassStorage.
findPCIDeviceByIRQ()
PCIDevicePath leanux::pci::findPCIDeviceByIRQ (unsigned int irq)
return a device path relative to /sys/devices to the PCI device assigned the irq
Parameters
irq the sought irq
Returns
the device path realtive to /sys/devices/ if found, empty std::string otherwise
Definition at line 601 of file pci.cpp.
References enumPCIDevicePaths(), leanux::util::fileReadAccess(), and leanux::util::fileReadInt().
getBDF()
std::string leanux::pci::getBDF (const PCIAddress & id)
Get the BDF format std::string for a PCIId 03:04.0 03 = bus number 04 = device number 0 = function number.
See also
getEBDF
Parameters
id the PCIAddress to be translated to BDF
Returns
the BDF notation for PCIAddress
Definition at line 88 of file pci.cpp.
getEBDF()
std::string leanux::pci::getEBDF (const PCIAddress & id)
Get the EBDF format std::string for a PCIId.
0000:03:04.0 (BDF with domain extension): 0000 = domain 03 = bus number 04 = device number 0 = function number
See also
getBDF
Parameters
id the PCIAddress to be translated to EBDF
Returns
the EBDF notation for PCIAddress
Definition at line 75 of file pci.cpp.
getEtherNetworkInterfaceName()
std::string leanux::pci::getEtherNetworkInterfaceName (const PCIDevicePath & device)
Get the name of an ethernet network communication device, such as 'eth0'.
Parameters
device the network device to get the name for.
Returns
the network device name or empty if not found.
Examples
example_pci.cpp.
Definition at line 655 of file pci.cpp.
getPCIDeviceIRQ()
unsigned int leanux::pci::getPCIDeviceIRQ (const PCIDevicePath & device)
Get the IRQ assigned to a PCI device.
Examples
example_pci.cpp.
Definition at line 630 of file pci.cpp.
References leanux::util::fileReadAccess(), and leanux::util::fileReadInt().
Referenced by leanux::tools::lsys::getLeafColStr(), leanux::sysdevice::PCIDevice::getPropertyValueList(), and leanux::sysdevice::PCIBus::getPropertyValueList().
getPCIHardwareClass()
PCIHardwareClass leanux::pci::getPCIHardwareClass (unsigned int classcode)
Transform a PCI class code to a PCIHardwareClass.
http://wiki.osdev.org/PCI#Class_Codes
Examples
example_pci.cpp.
Definition at line 127 of file pci.cpp.
References pciBaseSystemPeripheral, pciBridge, pciDataAquisistion, pciDisplay, pciDockingStation, pciEncryption, pciInput, pciIntelligentIO, pciMassStorage, pciMemory, pciMultimedia, pciNetwork, pciProcessor, pciSatelliteCommunication, pciSerialBus, pciUnclassified, and pciWireless.
Referenced by enumPCIATAPorts(), and findPCIDeviceByATAPort().
getPCIHardwareClassString()
std::string leanux::pci::getPCIHardwareClassString (unsigned int classcode)
Transform a PCI class code to class name.
http://wiki.osdev.org/PCI#Class_Codes
Definition at line 153 of file pci.cpp.
Referenced by getPCIHardwareInfo().
getPCIHardwareId()
PCIHardwareId leanux::pci::getPCIHardwareId (const PCIDevicePath & devicepath)
get PCIHardwareId for a PCI device path relative to /sys/devives/
Examples
example_pci.cpp.
Definition at line 673 of file pci.cpp.
References leanux::pci::PCIHardwareId::device, leanux::util::fileReadHexString(), leanux::pci::PCIHardwareId::pciclass, leanux::pci::PCIHardwareId::subdevice, leanux::pci::PCIHardwareId::subvendor, and leanux::pci::PCIHardwareId::vendor.
Referenced by enumPCIATAPorts(), findPCIDeviceByATAPort(), leanux::sysdevice::PCIDevice::getClass(), leanux::sysdevice::PCIDevice::getDescription(), leanux::sysdevice::PCIBus::getDescription(), leanux::sysdevice::PCIDevice::getDisplayName(), leanux::sysdevice::PCIBus::getDisplayName(), leanux::tools::lsys::getLeafColStr(), leanux::sysdevice::PCIDevice::getPropertyValueList(), and leanux::sysdevice::PCIBus::getPropertyValueList().
getPCIHardwareInfo()
bool leanux::pci::getPCIHardwareInfo (const PCIHardwareId & id, PCIHardwareInfo & inf)
Get PCI device info based on (vendor,device) function retrieves data from /usr/share/misc/pci.ids.
Parameters
id the PCIHardwareId of the PCI device.
inf the PCIHardwareInfo to fill.
Returns
true when the device is found, in which case subdevicestring may be empty.
0 = initial (aka EVENDOR_NOT_FOUND) 1 = vendor found (aka EDEVICE_NOT_FOUND) 2 = device found 3 = subdevice found
Examples
example_pci.cpp.
Definition at line 510 of file pci.cpp.
References leanux::pci::PCIHardwareInfo::device, getPCIHardwareClassString(), getPCISubClassString(), leanux::pci::PCIHardwareInfo::pciclass, PCIDeviceDatabase, leanux::pci::PCIHardwareInfo::pcisubclass, leanux::pci::PCIHardwareInfo::subdevice, and leanux::pci::PCIHardwareInfo::vendor.
Referenced by leanux::sysdevice::PCIDevice::getClass(), leanux::sysdevice::PCIDevice::getDescription(), leanux::sysdevice::PCIBus::getDescription(), leanux::sysdevice::PCIDevice::getDisplayName(), leanux::sysdevice::PCIBus::getDisplayName(), leanux::tools::lsys::getLeafColStr(), leanux::sysdevice::PCIDevice::getPropertyValueList(), and leanux::sysdevice::PCIBus::getPropertyValueList().
getPCISubClassString()
std::string leanux::pci::getPCISubClassString (unsigned int classcode)
Get the PCI subclass name for a PCI class code http://wiki.osdev.org/PCI#Class_Codes.
Definition at line 180 of file pci.cpp.
References pciBaseSystemPeripheral, pciBridge, pciDataAquisistion, pciDisplay, pciDockingStation, pciEncryption, pciInput, pciIntelligentIO, pciMassStorage, pciMemory, pciMultimedia, pciNetwork, pciProcessor, pciSatelliteCommunication, pciSerialBus, pciSimpleCommunication, and pciWireless.
Referenced by getPCIHardwareInfo().
init()
void leanux::pci::init ()
Initialize pci namespace.
Definition at line 63 of file pci.cpp.
References leanux::util::fileReadAccess(), and PCIDeviceDatabase.
Referenced by leanux::init().
isPCIDevice()
bool leanux::pci::isPCIDevice (const PCIDevicePath & path)
Definition at line 118 of file pci.cpp.
References enumPCIDevicePaths().
operator<<() [1/2]
std::ostream& leanux::pci::operator<< (std::ostream & os, PCIAddress a) inline
handy for debugging.
Definition at line 273 of file pci.hpp.
References leanux::pci::PCIAddress::bus, leanux::pci::PCIAddress::device, leanux::pci::PCIAddress::domain, and leanux::pci::PCIAddress::function.
operator<<() [2/2]
std::ostream& leanux::pci::operator<< (std::ostream & os, PCIHardwareInfo i) inline
handy for debugging.
Definition at line 295 of file pci.hpp.
References leanux::pci::PCIHardwareInfo::device, leanux::pci::PCIHardwareInfo::pciclass, leanux::pci::PCIHardwareInfo::pcisubclass, leanux::pci::PCIHardwareInfo::subdevice, and leanux::pci::PCIHardwareInfo::vendor.
Variable Documentation
NullPCIAddress
const PCIAddress leanux::pci::NullPCIAddress = {0xffff, 0xffff, 0xffff, 0xffff}
Invalid PCIAddress.
Definition at line 61 of file pci.cpp.
Referenced by decodeEBDF().
PCIDeviceDatabase
std::string leanux::pci::PCIDeviceDatabase = "/usr/share/misc/pci.ids"
The location of the system's PCI device database.
This varies among GNU/Linux distributions, set by and see pci::init().
Definition at line 59 of file pci.cpp.
Referenced by getPCIHardwareInfo(), and init().