leanux: leanux::util Namespace Reference
leanux::util Namespace Reference
Utility classes and functions.
Data Structures
class ConfigFile
A configuration file of name=value pairs.
class RegExp
POSIX regular expression wrapper.
class Stopwatch
Stopwatch to time durations with microsecond precision.
class Tracer
Simple singleton tracing class.
Functions
std::string ByteStr (double bytes, int prec)
convert a byte value to pretty print string.
double deltaTime (const struct timeval &t1, const struct timeval &t2)
Return the deltaof two timevals in seconds.
bool directoryExists (const std::string &path)
Test if the path is an existing directory.
bool fileReadAccess (const std::string &path)
Test if a file exists and can be read.
long fileReadHexString (const std::string &filename)
read the first data in the file as a hexadecimal string representation of a signed long.
int fileReadInt (const std::string &filename)
read the first data in the file as a string representation of a signed int.
std::string fileReadString (const std::string &filename)
read the file as a single string.
unsigned long fileReadUL (const std::string &filename)
read the first data in the file as a string representation of a unsigned long.
std::string findDir (const std::string &path, const std::string &match)
Find subdirectories, first match is returned, if any.
std::string getUserConfigDir ()
Return the config dir for the current user.
bool hexnatstrlt (const char *s1, const char *s2)
STL natural less-than string compare.
std::string leafDir (const std::string &dir)
returns the leaf of the tree - that string after the last '/'
std::string leanuxVersion ()
return the build leanux version
void listDir (const std::string &path, const std::string &match, std::list< std::string > &result)
std::list subdirectories that match into result, if any.
std::string localStrISODateTime ()
Return current local time in ISO format; YYYY-MM-DD HH24:MI:SS.
std::string localStrISODateTime (time_t t)
std::string localStrISOTime ()
std::string localStrISOTime (time_t t)
int natstrcmp (const char *s1, const char *s2)
standard C natural c-string compare
bool natstrlt (const char *s1, const char *s2)
STL natural less-than string compare.
std::string NumStr (double num, int prec=2)
Convert a double (real number) to a pretty print string.
std::string realPath (const std::string path)
Convert a path on a filesystem to the realpath if the path is a link.
std::string shortenString (const std::string &src, size_t maxsz, char filler='.')
Shorten a string by replacing characters from the middle with three filler charachters.
void Sleep (time_t seconds, long nanoseconds)
Sleep seconds+nanoseconds.
bool stlhexnatstrlt (const std::string &s1, const std::string &s2)
STL natural less-than std::string compare, treating hex numbers as numbers.
bool stlnatstrlt (const std::string &s1, const std::string &s2)
STL natural less-than std::string compare.
bool t_digit (char c)
bool t_xdigit (char c)
std::string TimeStrMicro (double time)
convert a time duration in microseconds to a pretty print string.
std::string TimeStrSec (double time)
convert a time duration in seconds to a pretty print string.
void tokenize (const std::string &str, std::list< std::string > &tokens, char sep, const std::set< std::string > &omit, bool reverse)
Variables
const double base_1024 = 10.0793683991589837489755
pow(1024.0,1.0/3.0)
const double base_1024_log = 2.31049060186648436143741
log (pow(1024.0,1.0/3.0)
const size_t bytestr_max_width = 64
maximum width a std::string returned by ByteStr.
Detailed Description
Utility classes and functions.
Function Documentation
ByteStr()
std::string leanux::util::ByteStr (double bytes, int prec)
convert a byte value to pretty print string.
Examples
example_pci.cpp, example_process.cpp, and example_process2.cpp.
Definition at line 174 of file util.cpp.
References base_1024, base_1024_log, and bytestr_max_width.
Referenced by leanux::tools::lblk::detailDisk(), leanux::tools::lblk::detailLVM(), leanux::tools::lblk::detailMetaDisk(), leanux::tools::lmon::Footer::Footer(), leanux::tools::lsys::getLeafColStr(), leanux::sysdevice::BlockDevice::getPropertyValueList(), leanux::sysdevice::BlockPartition::getPropertyValueList(), leanux::sysdevice::NVMeDevice::getPropertyValueList(), leanux::sysdevice::NVMePartition::getPropertyValueList(), leanux::sysdevice::MapperDevice::getPropertyValueList(), leanux::sysdevice::LoopbackDevice::getPropertyValueList(), leanux::sysdevice::RamDiskDevice::getPropertyValueList(), leanux::sysdevice::MDDevice::getPropertyValueList(), leanux::tools::lrep::htmlDiskDetails(), leanux::tools::lrep::htmlDiskHolderTreeLine(), leanux::tools::lrep::htmlSnapDetails(), leanux::tools::lrep::htmlSystemDetails(), leanux::tools::lblk::listAllDevices(), leanux::tools::lblk::listAllDisks(), leanux::tools::lblk::listAllMetaDisks(), leanux::tools::lard::mainLoop(), leanux::tools::lblk::printHolderTree(), leanux::tools::lblk::printSlaveTree(), leanux::tools::lmon::SysView::xrefresh(), leanux::tools::lmon::IOView::xrefresh(), leanux::tools::lmon::ProcessView::xrefresh(), and leanux::tools::lmon::NetView::xrefresh().
deltaTime()
double leanux::util::deltaTime (const struct timeval & t1, const struct timeval & t2)
Return the deltaof two timevals in seconds.
Examples
example_process2.cpp.
Definition at line 304 of file util.cpp.
Referenced by leanux::tools::lmon::Screen::runHistory(), leanux::tools::lmon::Screen::runRealtime(), leanux::tools::lmon::RealtimeSampler::sampleXIOView(), leanux::tools::lmon::RealtimeSampler::sampleXNetView(), leanux::tools::lmon::RealtimeSampler::sampleXProcView(), leanux::tools::lmon::RealtimeSampler::sampleXSysView(), and leanux::tools::lmon::SysView::xrefresh().
directoryExists()
bool leanux::util::directoryExists (const std::string & path)
Test if the path is an existing directory.
Parameters
path the directory to test for existence.
Returns
true when the directory exists.
Definition at line 144 of file util.cpp.
Referenced by leanux::sysdevice::PCIBus::accept(), leanux::tools::lsys::fullSysDevice(), leanux::sysdevice::SysDevice::getDriver(), leanux::sysdevice::BlockDevice::getDriver(), leanux::net::getSysPath(), leanux::init(), leanux::block::init(), and leanux::sysdevice::SysDevice::validatePath().
fileReadAccess()
bool leanux::util::fileReadAccess (const std::string & path)
Test if a file exists and can be read.
Parameters
path the file to test for read access.
Returns
true when the path is a file and can be read.
Definition at line 153 of file util.cpp.
Referenced by leanux::pci::findPCIDeviceByIRQ(), leanux::tools::lsys::fullSysDevice(), leanux::system::getChassisType(), leanux::system::getDistribution(), leanux::block::MajorMinor::getIOScheduler(), leanux::sysdevice::BlockDevice::getMajorMinor(), leanux::block::MajorMinor::getModel(), leanux::pci::getPCIDeviceIRQ(), leanux::block::MajorMinor::getSerial(), leanux::sysdevice::iSCSIDevice::getTargetAddress(), leanux::sysdevice::iSCSIDevice::getTargetIQN(), leanux::sysdevice::iSCSIDevice::getTargetPort(), leanux::usb::getUSBDeviceHardwareClass(), leanux::usb::getUSBHardwareId(), leanux::usb::getUSBInterfaceHardwareClass(), leanux::net::init(), leanux::pci::init(), leanux::usb::init(), leanux::tools::lmon::main(), leanux::block::modeFromMajorMinor(), and leanux::sysdevice::SysDevice::validatePath().
fileReadHexString()
long leanux::util::fileReadHexString (const std::string & filename)
read the first data in the file as a hexadecimal string representation of a signed long.
Exceptions
Oops when the file cannot be read.
Parameters
filename the file to read from.
Returns
the file contents as a long.
Definition at line 109 of file util.cpp.
Referenced by leanux::pci::getPCIHardwareId(), leanux::block::MajorMinor::getSCSIIODone(), leanux::block::MajorMinor::getSCSIIOError(), leanux::block::MajorMinor::getSCSIIORequest(), leanux::usb::getUSBDeviceHardwareClass(), leanux::usb::getUSBHardwareId(), and leanux::usb::getUSBInterfaceHardwareClass().
fileReadInt()
int leanux::util::fileReadInt (const std::string & filename)
read the first data in the file as a string representation of a signed int.
Exceptions
Oops when the file cannot be read.
Parameters
filename the file to read from.
Returns
the file contents as an int.
Definition at line 119 of file util.cpp.
Referenced by leanux::pci::findPCIDeviceByIRQ(), leanux::system::getChassisType(), and leanux::pci::getPCIDeviceIRQ().
fileReadString()
std::string leanux::util::fileReadString (const std::string & filename)
read the file as a single string.
Exceptions
Oops when the file cannot be read.
Parameters
filename the file to read from.
Returns
the file contents as a string.
Definition at line 100 of file util.cpp.
Referenced by leanux::block::getATALinkSpeed(), leanux::system::getBoardName(), leanux::system::getBoardVendor(), leanux::system::getBoardVersion(), leanux::block::MajorMinor::getCacheMode(), leanux::system::getDistribution(), leanux::block::MajorMinor::getDMName(), leanux::block::MajorMinor::getDMUUID(), leanux::block::MajorMinor::getIOScheduler(), leanux::block::MajorMinor::getKernelModule(), leanux::sysdevice::BlockDevice::getMajorMinor(), leanux::block::MajorMinor::getMDArrayState(), leanux::block::MajorMinor::getMDLevel(), leanux::block::MajorMinor::getMDMetaDataVersion(), leanux::block::MajorMinor::getMDRaidDisks(), leanux::block::MajorMinor::getMDRaidDiskStates(), leanux::block::MajorMinor::getModel(), leanux::block::MajorMinor::getRevision(), leanux::block::MajorMinor::getRotational(), leanux::block::MajorMinor::getSerial(), leanux::sysdevice::iSCSIDevice::getTargetAddress(), leanux::sysdevice::iSCSIDevice::getTargetIQN(), leanux::sysdevice::iSCSIDevice::getTargetPort(), leanux::process::getWChan(), and leanux::block::MajorMinor::getWWN().
fileReadUL()
unsigned long leanux::util::fileReadUL (const std::string & filename)
read the first data in the file as a string representation of a unsigned long.
Exceptions
Oops when the file cannot be read.
Parameters
filename the file to read from.
Returns
the file contents as an unsigned long.
Definition at line 128 of file util.cpp.
Referenced by leanux::cpu::getCPUCoreId(), leanux::cpu::getCPUPhysicalId(), leanux::cpu::getCPUTopology(), leanux::vmem::getDirtyBackgroundBytes(), leanux::vmem::getDirtyBackgroundRatio(), leanux::vmem::getDirtyBytes(), leanux::vmem::getDirtyRatio(), leanux::block::MajorMinor::getMaxHWIOSize(), leanux::block::MajorMinor::getMaxIOSize(), leanux::block::MajorMinor::getMDChunkSize(), leanux::block::MajorMinor::getMDDevices(), leanux::block::MajorMinor::getMinIOSize(), leanux::block::MajorMinor::getReadAhead(), leanux::block::MajorMinor::getSectorSize(), and leanux::block::MajorMinor::getSize().
findDir()
std::string leanux::util::findDir (const std::string & path, const std::string & match)
Find subdirectories, first match is returned, if any.
Any directory that starts with a '.' is not considered.
Parameters
path base path / parent directory.
match the search pattern.
Returns
subdirectory or empty std::string if no match.
Definition at line 335 of file util.cpp.
Referenced by leanux::block::getATAPortLink(), leanux::block::MajorMinor::getSCSIHCTL(), leanux::sysdevice::iSCSIDevice::getTargetAddress(), and leanux::sysdevice::iSCSIDevice::getTargetPort().
getUserConfigDir()
std::string leanux::util::getUserConfigDir ()
Return the config dir for the current user.
It checks $XDG_CONFIG_HOME, HOME and getpwuid->pw_dir in that order, first match returned.
Returns
the user's configuration directory.
Definition at line 309 of file util.cpp.
Referenced by leanux::tools::lmon::main().
hexnatstrlt()
bool leanux::util::hexnatstrlt (const char * s1, const char * s2)
STL natural less-than string compare.
Returns
true when natural s1 < s2
Definition at line 215 of file natsort.cpp.
References t_digit(), and t_xdigit().
Referenced by stlhexnatstrlt().
leafDir()
std::string leanux::util::leafDir (const std::string & dir)
returns the leaf of the tree - that string after the last '/'
Definition at line 64 of file util.cpp.
Referenced by leanux::tools::lsys::getLeafColStr(), and leanux::sysdevice::NetDevice::getPropertyValueList().
leanuxVersion()
std::string leanux::util::leanuxVersion () inline
return the build leanux version
Definition at line 59 of file util.hpp.
listDir()
void leanux::util::listDir (const std::string & path, const std::string & match, std::list< std::string > & result)
std::list subdirectories that match into result, if any.
Parameters
path base directory to search.
match pattern to match.
result std::list of subdirectories matching.
Definition at line 320 of file util.cpp.
localStrISODateTime() [1/2]
std::string leanux::util::localStrISODateTime ()
Return current local time in ISO format; YYYY-MM-DD HH24:MI:SS.
Returns
a string with the local time
Definition at line 354 of file util.cpp.
Referenced by leanux::tools::lmon::Screen::runHistory(), leanux::tools::lmon::Screen::runRealtime(), and leanux::tools::lmon::SysView::xrefresh().
localStrISODateTime() [2/2]
std::string leanux::util::localStrISODateTime (time_t t)
Definition at line 366 of file util.cpp.
localStrISOTime() [1/2]
std::string leanux::util::localStrISOTime ()
Definition at line 376 of file util.cpp.
Referenced by leanux::tools::lrep::htmlSnapDetails(), leanux::tools::lmon::Screen::runHistory(), and leanux::tools::lmon::SysView::xrefresh().
localStrISOTime() [2/2]
std::string leanux::util::localStrISOTime (time_t t)
Definition at line 388 of file util.cpp.
natstrcmp()
int leanux::util::natstrcmp (const char * s1, const char * s2)
standard C natural c-string compare
Parameters
s1 left string
s2 right string
Returns
-1 when s1 < s2, 0 when s1 == s2, 1 when s1 > s2
Definition at line 55 of file natsort.cpp.
References t_digit().
natstrlt()
bool leanux::util::natstrlt (const char * s1, const char * s2)
STL natural less-than string compare.
STL natural less-than c-string compare.
Returns
true when natural s1 < s2
Parameters
s1 left string
s2 right string
Returns
true when natural s1 < s2
Definition at line 138 of file natsort.cpp.
References t_digit().
Referenced by stlnatstrlt().
NumStr()
std::string leanux::util::NumStr (double num, int prec = 2)
Convert a double (real number) to a pretty print string.
Parameters
num the number to pretty print.
prec the number of digits after decimal to display.
Returns
the pretty print string.
Definition at line 265 of file util.cpp.
Referenced by leanux::tools::lblk::detailDisk(), leanux::tools::lrep::htmlCmdUidDetail(), leanux::tools::lrep::htmlDiskDetails(), leanux::tools::lrep::htmlHeatMap(), leanux::tools::lblk::listAllDisks(), leanux::tools::lblk::printHolderTree(), leanux::tools::lblk::printSlaveTree(), leanux::tools::lmon::SysView::xrefresh(), leanux::tools::lmon::IOView::xrefresh(), leanux::tools::lmon::ProcessView::xrefresh(), and leanux::tools::lmon::NetView::xrefresh().
realPath()
std::string leanux::util::realPath (const std::string path)
Convert a path on a filesystem to the realpath if the path is a link.
Parameters
path the path to find the realpath for.
Returns
the realpath corresponding to path. If path is not a link, the original path is returned.
Definition at line 85 of file util.cpp.
Referenced by leanux::block::MajorMinor::buildCache(), leanux::sysdevice::enumATADevices(), leanux::sysdevice::enumBlockDevices(), leanux::sysdevice::enumNetDevices(), leanux::sysdevice::enumPCIBusses(), leanux::pci::enumPCIDevicePaths(), leanux::sysdevice::enumPCIDevices(), leanux::sysdevice::enumSCSIHostDevices(), leanux::usb::enumUSBDevices(), leanux::sysdevice::enumUSBDevices(), leanux::tools::lsys::fullSysDevice(), leanux::sysdevice::SysDevice::getDriver(), leanux::sysdevice::BlockDevice::getDriver(), leanux::block::getFileMajorMinor(), leanux::block::MajorMinor::getSysPath(), leanux::net::getSysPath(), and leanux::tools::lblk::parseDeviceArg().
shortenString()
std::string leanux::util::shortenString (const std::string & src, size_t maxsz, char filler = '.')
Shorten a string by replacing characters from the middle with three filler charachters.
If maxsz >= src.lenght(), src is returned as is.
Parameters
src the (constant) source string.
maxsz the maximum size of the returned string.
filler the maximum size of the returned string.
Returns
the shortened string.
Definition at line 93 of file util.cpp.
Referenced by leanux::tools::lrep::htmlDiskDetails(), leanux::tools::lsys::sysfsTree(), and leanux::tools::lmon::IOView::xrefresh().
Sleep()
void leanux::util::Sleep (time_t seconds, long nanoseconds)
Sleep seconds+nanoseconds.
Examples
example_cpu.cpp, and example_process2.cpp.
Definition at line 137 of file util.cpp.
Referenced by leanux::tools::lard::mainLoop(), leanux::tools::lmon::Screen::runHistory(), leanux::tools::lmon::Screen::runRealtime(), and leanux::tools::lard::wait_log_handler().
stlhexnatstrlt()
bool leanux::util::stlhexnatstrlt (const std::string & s1, const std::string & s2) inline
STL natural less-than std::string compare, treating hex numbers as numbers.
stable, good enough, but not flawless.
Parameters
s1 left string
s2 right string std::string variant of natstrlt.
Returns
true when natural s1 < s2
Definition at line 83 of file natsort.hpp.
References hexnatstrlt().
Referenced by leanux::tools::lsys::runOptions().
stlnatstrlt()
bool leanux::util::stlnatstrlt (const std::string & s1, const std::string & s2) inline
STL natural less-than std::string compare.
Parameters
s1 left string
s2 right string std::string variant of natstrlt.
Returns
true when natural s1 < s2
Definition at line 70 of file natsort.hpp.
References natstrlt().
t_digit()
bool leanux::util::t_digit (char c) inline
Definition at line 47 of file natsort.cpp.
Referenced by hexnatstrlt(), natstrcmp(), natstrlt(), and t_xdigit().
t_xdigit()
bool leanux::util::t_xdigit (char c) inline
Definition at line 51 of file natsort.cpp.
References t_digit().
Referenced by hexnatstrlt().
TimeStrMicro()
std::string leanux::util::TimeStrMicro (double time)
convert a time duration in microseconds to a pretty print string.
Definition at line 225 of file util.cpp.
Referenced by TimeStrSec().
TimeStrSec()
std::string leanux::util::TimeStrSec (double time)
convert a time duration in seconds to a pretty print string.
Examples
example_process.cpp.
Definition at line 221 of file util.cpp.
References TimeStrMicro().
Referenced by leanux::tools::lblk::detailDisk(), leanux::tools::lsys::getLeafColStr(), leanux::tools::lrep::htmlSnapDetails(), leanux::tools::lrep::htmlTimeLines(), leanux::tools::lblk::listAllDisks(), leanux::tools::lrep::main(), leanux::tools::lblk::printHolderTree(), leanux::tools::lblk::printSlaveTree(), leanux::tools::lmon::Screen::runHistory(), leanux::tools::lmon::SysView::xrefresh(), and leanux::tools::lmon::IOView::xrefresh().
tokenize()
void leanux::util::tokenize (const std::string & str, std::list< std::string > & tokens, char sep, const std::set< std::string > & omit, bool reverse)
Definition at line 72 of file util.cpp.
Referenced by leanux::tools::lsys::getOptions(), leanux::sysdevice::SysDevice::tokenize(), and leanux::util::ConfigFile::write().
Variable Documentation
base_1024
const double leanux::util::base_1024 = 10.0793683991589837489755
pow(1024.0,1.0/3.0)
Definition at line 169 of file util.cpp.
Referenced by ByteStr().
base_1024_log
const double leanux::util::base_1024_log = 2.31049060186648436143741
log (pow(1024.0,1.0/3.0)
Definition at line 172 of file util.cpp.
Referenced by ByteStr().
bytestr_max_width
const size_t leanux::util::bytestr_max_width = 64
maximum width a std::string returned by ByteStr.
Definition at line 166 of file util.cpp.
Referenced by ByteStr().