leanux: leanux::tools::lard Namespace Reference
leanux::tools::lard Namespace Reference
Data Structures
class CPUSnap
class IOSnap
class MountSnap
class NetSnap
struct Options
class ProcSnap
class ResSnap
class SchedSnap
class Snapshot
class TCPEstaSnap
class TimeSnap
class VMSnap
Typedefs
typedef long snapid
Functions
void applyRetention (persist::Database &db)
void createSchema (persist::Database &db)
void createTableCmd (persist::Database &db)
void createTableCpustat (persist::Database &db)
void createTableDisk (persist::Database &db)
void createTableIostat (persist::Database &db)
void createTableMountpoint (persist::Database &db)
void createTableMountstat (persist::Database &db)
void createTableNetstat (persist::Database &db)
void createTableNic (persist::Database &db)
void createTableProcstat (persist::Database &db)
void createTableResstat (persist::Database &db)
void createTableSchedstat (persist::Database &db)
void createTableSnapshot (persist::Database &db)
void createTableStatus (persist::Database &db)
void createTableTcpclientstat (persist::Database &db)
void createTableTcpkey (persist::Database &db)
void createTableTcpserverstat (persist::Database &db)
void createTableVmstat (persist::Database &db)
void createTableWchan (persist::Database &db)
void deleteSnapshots (persist::Database &db, long snapid)
long ensureSinglePid (persist::Database &db)
void initDB ()
set page_size and enable WAL mode.
void interrupt_handler (int sig)
int main (int argc, char *argv[])
Entry point.
void mainLoop ()
bool parseArgs (int argc, char *argv[])
void shrinkDB (persist::Database &db, const std::string filename)
void sysLog (unsigned short level, unsigned short limit, const std::string &msg)
void updateSchema (persist::Database &db)
void vacuumAnalyze (persist::Database &db)
int wait_log_handler (void *p, int count)
Variables
const unsigned short LOG_DEBUG = 4
const unsigned short LOG_ERR = 0
const unsigned short LOG_INFO = 3
const unsigned short LOG_STAT = 2
const unsigned short LOG_WARN = 1
Options options
const std::string pid_name = "lard_pid"
int schema_version = 1977
bool stopped = false
when this becomes true, lard stops.
const size_t task_comm_len = 16
maximum size of a command name as tracked by the kernel.
bool was_busy = false
Detailed Description
daemon that logs performance data to a sqlite database
Data Structure Documentation
leanux::tools::lard::Options
struct leanux::tools::lard::Options
Definition at line 80 of file lar.cpp.
Data Fields
string config configuration file
bool daemonize daemonize
string database sqlite database file
Typedef Documentation
snapid
typedef long leanux::tools::lard::snapid
Definition at line 60 of file lar_snap.hpp.
Function Documentation
applyRetention()
void leanux::tools::lard::applyRetention (persist::Database & db)
Definition at line 604 of file lar_schema.cpp.
References leanux::persist::DML::bind(), leanux::persist::Statement::close(), deleteSnapshots(), leanux::util::ConfigFile::getConfig(), leanux::persist::Query::getLong(), leanux::util::ConfigFile::getValue(), leanux::persist::Statement::prepare(), and leanux::persist::Query::step().
Referenced by mainLoop().
createSchema()
void leanux::tools::lard::createSchema (persist::Database & db)
Definition at line 472 of file lar_schema.cpp.
References createTableCmd(), createTableCpustat(), createTableDisk(), createTableIostat(), createTableMountpoint(), createTableMountstat(), createTableNetstat(), createTableNic(), createTableProcstat(), createTableResstat(), createTableSchedstat(), createTableSnapshot(), createTableStatus(), createTableTcpclientstat(), createTableTcpkey(), createTableTcpserverstat(), createTableVmstat(), and createTableWchan().
Referenced by mainLoop().
createTableCmd()
void leanux::tools::lard::createTableCmd (persist::Database & db)
Definition at line 307 of file lar_schema.cpp.
References leanux::persist::DDL::execute(), and leanux::persist::Statement::prepare().
Referenced by createSchema().
createTableCpustat()
void leanux::tools::lard::createTableCpustat (persist::Database & db)
Definition at line 76 of file lar_schema.cpp.
References leanux::persist::DDL::execute(), leanux::persist::Statement::prepare(), and leanux::persist::Statement::reset().
Referenced by createSchema().
createTableDisk()
void leanux::tools::lard::createTableDisk (persist::Database & db)
Definition at line 176 of file lar_schema.cpp.
References leanux::persist::DDL::execute(), and leanux::persist::Statement::prepare().
Referenced by createSchema().
createTableIostat()
void leanux::tools::lard::createTableIostat (persist::Database & db)
Definition at line 188 of file lar_schema.cpp.
References leanux::persist::DDL::execute(), leanux::persist::Statement::prepare(), and leanux::persist::Statement::reset().
Referenced by createSchema().
createTableMountpoint()
void leanux::tools::lard::createTableMountpoint (persist::Database & db)
Definition at line 398 of file lar_schema.cpp.
References leanux::persist::DDL::execute(), and leanux::persist::Statement::prepare().
Referenced by createSchema().
createTableMountstat()
void leanux::tools::lard::createTableMountstat (persist::Database & db)
Definition at line 408 of file lar_schema.cpp.
References leanux::persist::DDL::execute(), leanux::persist::Statement::prepare(), and leanux::persist::Statement::reset().
Referenced by createSchema().
createTableNetstat()
void leanux::tools::lard::createTableNetstat (persist::Database & db)
Definition at line 251 of file lar_schema.cpp.
References leanux::persist::DDL::execute(), leanux::persist::Statement::prepare(), and leanux::persist::Statement::reset().
Referenced by createSchema().
createTableNic()
void leanux::tools::lard::createTableNic (persist::Database & db)
Definition at line 239 of file lar_schema.cpp.
References leanux::persist::DDL::execute(), and leanux::persist::Statement::prepare().
Referenced by createSchema().
createTableProcstat()
void leanux::tools::lard::createTableProcstat (persist::Database & db)
Definition at line 331 of file lar_schema.cpp.
References leanux::persist::DDL::execute(), leanux::persist::Statement::prepare(), and leanux::persist::Statement::reset().
Referenced by createSchema().
createTableResstat()
void leanux::tools::lard::createTableResstat (persist::Database & db)
Definition at line 364 of file lar_schema.cpp.
References leanux::persist::DDL::execute(), leanux::persist::Statement::prepare(), and leanux::persist::Statement::reset().
Referenced by createSchema().
createTableSchedstat()
void leanux::tools::lard::createTableSchedstat (persist::Database & db)
Definition at line 141 of file lar_schema.cpp.
References leanux::persist::DDL::execute(), leanux::persist::Statement::prepare(), and leanux::persist::Statement::reset().
Referenced by createSchema().
createTableSnapshot()
void leanux::tools::lard::createTableSnapshot (persist::Database & db)
Definition at line 60 of file lar_schema.cpp.
References leanux::persist::DDL::execute(), leanux::persist::Statement::prepare(), and leanux::persist::Statement::reset().
Referenced by createSchema().
createTableStatus()
void leanux::tools::lard::createTableStatus (persist::Database & db)
Definition at line 54 of file lar_schema.cpp.
References leanux::persist::DDL::execute(), and leanux::persist::Statement::prepare().
Referenced by createSchema(), and ensureSinglePid().
createTableTcpclientstat()
void leanux::tools::lard::createTableTcpclientstat (persist::Database & db)
Definition at line 459 of file lar_schema.cpp.
References leanux::persist::DDL::execute(), and leanux::persist::Statement::prepare().
Referenced by createSchema().
createTableTcpkey()
void leanux::tools::lard::createTableTcpkey (persist::Database & db)
Definition at line 433 of file lar_schema.cpp.
References leanux::persist::DDL::execute(), and leanux::persist::Statement::prepare().
Referenced by createSchema().
createTableTcpserverstat()
void leanux::tools::lard::createTableTcpserverstat (persist::Database & db)
Definition at line 446 of file lar_schema.cpp.
References leanux::persist::DDL::execute(), and leanux::persist::Statement::prepare().
Referenced by createSchema().
createTableVmstat()
void leanux::tools::lard::createTableVmstat (persist::Database & db)
Definition at line 273 of file lar_schema.cpp.
References leanux::persist::DDL::execute(), and leanux::persist::Statement::prepare().
Referenced by createSchema().
createTableWchan()
void leanux::tools::lard::createTableWchan (persist::Database & db)
Definition at line 318 of file lar_schema.cpp.
References leanux::persist::DDL::execute(), leanux::persist::Statement::prepare(), and leanux::persist::Statement::reset().
Referenced by createSchema().
deleteSnapshots()
void leanux::tools::lard::deleteSnapshots (persist::Database & db, long snapid)
Definition at line 493 of file lar_schema.cpp.
References leanux::persist::DML::bind(), leanux::persist::Statement::close(), leanux::persist::DML::execute(), leanux::persist::Statement::prepare(), and leanux::persist::Statement::reset().
Referenced by applyRetention(), and shrinkDB().
ensureSinglePid()
long leanux::tools::lard::ensureSinglePid (persist::Database & db)
Definition at line 134 of file lar.cpp.
References leanux::persist::DML::bind(), leanux::persist::Statement::close(), leanux::process::ProcPidStat::comm, createTableStatus(), leanux::persist::DML::execute(), leanux::util::ConfigFile::getConfig(), leanux::persist::Query::getInt(), leanux::Oops::getMessage(), leanux::process::getProcPidStat(), LOG_ERR, pid_name, leanux::persist::Statement::prepare(), leanux::persist::Statement::reset(), leanux::persist::Query::step(), and sysLog().
Referenced by mainLoop().
initDB()
void leanux::tools::lard::initDB ()
set page_size and enable WAL mode.
Definition at line 118 of file lar.cpp.
References leanux::persist::Statement::close(), leanux::tools::lard::Options::database, leanux::persist::DDL::execute(), leanux::util::ConfigFile::getConfig(), leanux::util::ConfigFile::getValue(), options, leanux::persist::Statement::prepare(), and leanux::persist::Query::step().
Referenced by mainLoop().
interrupt_handler()
void leanux::tools::lard::interrupt_handler (int sig)
Definition at line 102 of file lar.cpp.
References leanux::util::ConfigFile::getConfig(), LOG_STAT, stopped, and sysLog().
Referenced by main().
main()
int leanux::tools::lard::main (int argc, char * argv[])
Entry point.
Parameters
argc number of command line arguments.
argv command line arguments.
Returns
0 on succes, 1 on Oops, 2 on other errors.
Definition at line 360 of file lar.cpp.
References leanux::tools::lard::Options::config, leanux::tools::lard::Options::daemonize, leanux::util::ConfigFile::declareParameter(), leanux::util::ConfigFile::getConfig(), leanux::Oops::getMessage(), leanux::init(), interrupt_handler(), LOG_ERR, mainLoop(), options, parseArgs(), leanux::util::ConfigFile::releaseConfig(), leanux::util::ConfigFile::setConfig(), sysLog(), and leanux::util::ConfigFile::write().
Referenced by main().
mainLoop()
void leanux::tools::lard::mainLoop ()
Definition at line 176 of file lar.cpp.
References applyRetention(), leanux::persist::Database::begin(), leanux::persist::DML::bind(), leanux::util::ByteStr(), leanux::persist::Database::checkPointPassive(), leanux::persist::Database::checkPointTruncate(), leanux::persist::Statement::close(), leanux::persist::Database::commit(), createSchema(), leanux::tools::lard::Options::database, leanux::persist::Database::enableForeignKeys(), ensureSinglePid(), leanux::persist::DML::execute(), leanux::util::ConfigFile::getConfig(), leanux::util::Stopwatch::getElapsedSeconds(), leanux::util::ConfigFile::getIntValue(), leanux::tools::lard::TimeSnap::getSeconds(), leanux::persist::Database::getUserVersion(), initDB(), LOG_DEBUG, LOG_ERR, LOG_STAT, leanux::persist::Database::memHighWater(), leanux::persist::Database::memUsed(), options, pid_name, leanux::persist::Statement::prepare(), shrinkDB(), leanux::util::Sleep(), leanux::persist::Database::softHeapLimit(), leanux::util::Stopwatch::start(), leanux::tools::lard::TimeSnap::startSnap(), leanux::tools::lard::IOSnap::startSnap(), leanux::tools::lard::CPUSnap::startSnap(), leanux::tools::lard::SchedSnap::startSnap(), leanux::tools::lard::NetSnap::startSnap(), leanux::tools::lard::VMSnap::startSnap(), leanux::tools::lard::ProcSnap::startSnap(), leanux::tools::lard::ResSnap::startSnap(), leanux::tools::lard::MountSnap::startSnap(), leanux::tools::lard::TCPEstaSnap::startSnap(), leanux::persist::Query::step(), stopped, leanux::tools::lard::TimeSnap::stopSnap(), leanux::tools::lard::IOSnap::stopSnap(), leanux::tools::lard::CPUSnap::stopSnap(), leanux::tools::lard::SchedSnap::stopSnap(), leanux::tools::lard::NetSnap::stopSnap(), leanux::tools::lard::VMSnap::stopSnap(), leanux::tools::lard::ProcSnap::stopSnap(), leanux::tools::lard::ResSnap::stopSnap(), leanux::tools::lard::MountSnap::stopSnap(), leanux::tools::lard::TCPEstaSnap::stopSnap(), leanux::tools::lard::TimeSnap::storeSnap(), leanux::tools::lard::IOSnap::storeSnap(), leanux::tools::lard::CPUSnap::storeSnap(), leanux::tools::lard::SchedSnap::storeSnap(), leanux::tools::lard::NetSnap::storeSnap(), leanux::tools::lard::VMSnap::storeSnap(), leanux::tools::lard::ProcSnap::storeSnap(), leanux::tools::lard::ResSnap::storeSnap(), leanux::tools::lard::MountSnap::storeSnap(), leanux::tools::lard::TCPEstaSnap::storeSnap(), sysLog(), updateSchema(), vacuumAnalyze(), wait_log_handler(), and was_busy.
Referenced by main().
parseArgs()
bool leanux::tools::lard::parseArgs (int argc, char * argv[])
Definition at line 328 of file lar.cpp.
References leanux::tools::lard::Options::config, leanux::tools::lard::Options::daemonize, leanux::tools::lard::Options::database, and options.
Referenced by main().
shrinkDB()
void leanux::tools::lard::shrinkDB (persist::Database & db, const std::string filename)
Definition at line 575 of file lar_schema.cpp.
References leanux::persist::Database::begin(), leanux::persist::Statement::close(), leanux::persist::Database::commit(), deleteSnapshots(), leanux::util::ConfigFile::getConfig(), leanux::util::ConfigFile::getIntValue(), leanux::persist::Query::getLong(), LOG_DEBUG, leanux::persist::Statement::prepare(), leanux::persist::Query::step(), sysLog(), and vacuumAnalyze().
Referenced by mainLoop().
sysLog()
void leanux::tools::lard::sysLog (unsigned short level, unsigned short limit, const std::string & msg)
Definition at line 56 of file lar_snap.cpp.
References LOG_DEBUG, LOG_ERR, and LOG_INFO.
Referenced by ensureSinglePid(), interrupt_handler(), main(), mainLoop(), shrinkDB(), updateSchema(), and wait_log_handler().
updateSchema()
void leanux::tools::lard::updateSchema (persist::Database & db)
Definition at line 626 of file lar_schema.cpp.
References leanux::util::ConfigFile::getConfig(), leanux::persist::Database::getUserVersion(), LOG_STAT, schema_version, leanux::persist::Database::setUserVersion(), and sysLog().
Referenced by mainLoop().
vacuumAnalyze()
void leanux::tools::lard::vacuumAnalyze (persist::Database & db)
Definition at line 616 of file lar_schema.cpp.
References leanux::persist::Statement::close(), leanux::persist::DDL::execute(), leanux::persist::Statement::prepare(), and leanux::persist::Statement::reset().
Referenced by mainLoop(), and shrinkDB().
wait_log_handler()
int leanux::tools::lard::wait_log_handler (void * p, int count)
Definition at line 91 of file lar.cpp.
References leanux::util::ConfigFile::getConfig(), LOG_WARN, leanux::util::Sleep(), sysLog(), and was_busy.
Referenced by mainLoop().
Variable Documentation
LOG_DEBUG
const unsigned short leanux::tools::lard::LOG_DEBUG = 4
Definition at line 58 of file lar_snap.hpp.
Referenced by mainLoop(), shrinkDB(), and sysLog().
LOG_ERR
const unsigned short leanux::tools::lard::LOG_ERR = 0
Definition at line 54 of file lar_snap.hpp.
Referenced by ensureSinglePid(), main(), mainLoop(), and sysLog().
LOG_INFO
const unsigned short leanux::tools::lard::LOG_INFO = 3
Definition at line 57 of file lar_snap.hpp.
Referenced by sysLog().
LOG_STAT
const unsigned short leanux::tools::lard::LOG_STAT = 2
Definition at line 56 of file lar_snap.hpp.
Referenced by interrupt_handler(), mainLoop(), and updateSchema().
LOG_WARN
const unsigned short leanux::tools::lard::LOG_WARN = 1
Definition at line 55 of file lar_snap.hpp.
Referenced by wait_log_handler().
options
Options leanux::tools::lard::options
Definition at line 89 of file lar.cpp.
Referenced by initDB(), main(), mainLoop(), and parseArgs().
pid_name
const std::string leanux::tools::lard::pid_name = "lard_pid"
Definition at line 78 of file lar.cpp.
Referenced by ensureSinglePid(), and mainLoop().
schema_version
int leanux::tools::lard::schema_version = 1977
Definition at line 52 of file lar_schema.cpp.
Referenced by updateSchema().
stopped
bool leanux::tools::lard::stopped = false
when this becomes true, lard stops.
See also
interrupt_handler(int sig) and mainLoop()
Definition at line 74 of file lar.cpp.
Referenced by interrupt_handler(), and mainLoop().
task_comm_len
const size_t leanux::tools::lard::task_comm_len = 16
maximum size of a command name as tracked by the kernel.
should be set to TASK_COMM_LEN which seems to be unavailable outside kernel sources (/usr/src/linux/include/linux/sched.h)
Definition at line 54 of file lar_snap.cpp.
Referenced by leanux::tools::lard::ProcSnap::storeSnap().
was_busy
bool leanux::tools::lard::was_busy = false
Definition at line 76 of file lar.cpp.
Referenced by mainLoop(), and wait_log_handler().