leanux: leanux::tools::lard::ProcSnap Class Reference
leanux::tools::lard::ProcSnap Class Reference
#include <lar_snap.hpp>
Public Member Functions
ProcSnap ()
virtual ~ProcSnap ()
virtual void startSnap ()
virtual void stopSnap ()
virtual long storeSnap (const persist::Database &db, long snapid, double seconds)
Protected Attributes
process::ProcPidStatMap snap1_
process::ProcPidStatMap snap2_
Detailed Description
Definition at line 156 of file lar_snap.hpp.
Constructor & Destructor Documentation
ProcSnap()
leanux::tools::lard::ProcSnap::ProcSnap () inline
Definition at line 158 of file lar_snap.hpp.
~ProcSnap()
virtual leanux::tools::lard::ProcSnap::~ProcSnap () inline virtual
Definition at line 159 of file lar_snap.hpp.
Member Function Documentation
startSnap()
void leanux::tools::lard::ProcSnap::startSnap () virtual
Implements leanux::tools::lard::Snapshot.
Definition at line 408 of file lar_snap.cpp.
References leanux::process::getAllProcPidStat(), and snap1_.
Referenced by leanux::tools::lard::mainLoop().
stopSnap()
void leanux::tools::lard::ProcSnap::stopSnap () virtual
Implements leanux::tools::lard::Snapshot.
Definition at line 412 of file lar_snap.cpp.
References leanux::process::getAllProcPidStat(), and snap2_.
Referenced by leanux::tools::lard::mainLoop().
storeSnap()
long leanux::tools::lard::ProcSnap::storeSnap (const persist::Database & db, long snapid, double seconds) virtual
Implements leanux::tools::lard::Snapshot.
Definition at line 416 of file lar_snap.cpp.
References leanux::persist::DML::bind(), leanux::process::deltaProcPidStats(), leanux::persist::DML::execute(), leanux::util::ConfigFile::getConfig(), leanux::util::ConfigFile::getIntValue(), leanux::persist::Query::getLong(), leanux::process::getProcCmdLine(), leanux::process::getProcUid(), leanux::util::ConfigFile::getStringListValue(), leanux::persist::Database::lastInsertRowid(), leanux::persist::Statement::prepare(), leanux::persist::Statement::reset(), snap1_, snap2_, leanux::persist::Query::step(), leanux::tools::lard::task_comm_len, and leanux::process::StatsSorter::top.
Referenced by leanux::tools::lard::mainLoop().
Field Documentation
snap1_
process::ProcPidStatMap leanux::tools::lard::ProcSnap::snap1_ protected
Definition at line 165 of file lar_snap.hpp.
Referenced by startSnap(), and storeSnap().
snap2_
process::ProcPidStatMap leanux::tools::lard::ProcSnap::snap2_ protected
Definition at line 166 of file lar_snap.hpp.
Referenced by stopSnap(), and storeSnap().
The documentation for this class was generated from the following files:
tools/lard/lar_snap.hpp
tools/lard/lar_snap.cpp