leanux: leanux::tools::lsys Namespace Reference
leanux::tools::lsys Namespace Reference
Data Structures
struct Filter
struct Options
Invocation options.
Typedefs
typedef std::list< std::string > DisplayFields
type for fields to display.
typedef std::map< std::string, Filter > FilterMap
type for map of field names to field filters.
typedef std::map< sysdevice::SysDevice::SysDeviceType, std::set< std::string > > RTypeFields
typedef std::map< sysdevice::SysDevice::SysDeviceType, std::string > RTypeMap
typedef std::map< std::string, std::set< sysdevice::SysDevice::SysDeviceType > > TypeFields
type for mapping of field name to a set of supported SysDeviceTypes
typedef std::map< std::string, sysdevice::SysDevice::SysDeviceType > TypeMap
type for mapping of user friendly names to SysDeviceType
Functions
std::string fullSysDevice (const std::string &device)
attempt to make sense of user provided device string.
std::string getLeafColStr (const sysdevice::SysDevice *leaf, const std::string &field)
get named field attributes for the SysDevice.
bool getOptions (int argc, char *argv[])
Transform command line arguments into options.
void listDevices (const std::list< sysdevice::SysDevicePath > &devices, sysdevice::SysDevice::SysDeviceType t)
list devices, filtered if opt_t is set.
int main (int argc, char *argv[])
Entry point.
void printHelp ()
Print command help.
void printVersion ()
void registerField (const std::string &field, sysdevice::SysDevice::SysDeviceType type)
void registerType (const std::string &st, sysdevice::SysDevice::SysDeviceType et)
register devices types and maintain mappings between type and string representation.
void runOptions ()
Run based on options.
void sysfsTree (const std::string &sysfs)
Variables
DisplayFields display_fields
The global default or user specified display fields.
FilterMap filter_map
global map of field names to field filters.
Options options
the default or user specified options.
RTypeFields rtype_fields
RTypeMap rtype_map
TypeFields type_fields
The global TypeFields.
TypeMap type_map
The global TypeMap.
Detailed Description
show system device configuration
Data Structure Documentation
leanux::tools::lsys::Filter
struct leanux::tools::lsys::Filter
Definition at line 108 of file lsys.cpp.
Data Fields
string filter regexp
bool negate negate the result
leanux::tools::lsys::Options
struct leanux::tools::lsys::Options
Invocation options.
Definition at line 60 of file lsys.cpp.
Data Fields
string device the specified sysdevice (empty if not specified)
string opt_f -f field[=filter],..: select display fields
bool opt_h -h : show help
bool opt_l -l : list all
string opt_t -t type : limit to specified type
bool opt_v -v : show version
Typedef Documentation
DisplayFields
typedef std::list<std::string> leanux::tools::lsys::DisplayFields
type for fields to display.
Definition at line 101 of file lsys.cpp.
FilterMap
typedef std::map<std::string, Filter> leanux::tools::lsys::FilterMap
type for map of field names to field filters.
Definition at line 116 of file lsys.cpp.
RTypeFields
typedef std::map<sysdevice::SysDevice::SysDeviceType, std::set<std::string> > leanux::tools::lsys::RTypeFields
Definition at line 84 of file lsys.cpp.
RTypeMap
typedef std::map<sysdevice::SysDevice::SysDeviceType,std::string> leanux::tools::lsys::RTypeMap
Definition at line 78 of file lsys.cpp.
TypeFields
typedef std::map<std::string, std::set<sysdevice::SysDevice::SysDeviceType> > leanux::tools::lsys::TypeFields
type for mapping of field name to a set of supported SysDeviceTypes
Definition at line 83 of file lsys.cpp.
TypeMap
typedef std::map<std::string, sysdevice::SysDevice::SysDeviceType> leanux::tools::lsys::TypeMap
type for mapping of user friendly names to SysDeviceType
Definition at line 77 of file lsys.cpp.
Function Documentation
fullSysDevice()
std::string leanux::tools::lsys::fullSysDevice (const std::string & device)
attempt to make sense of user provided device string.
Definition at line 264 of file lsys.cpp.
References leanux::util::directoryExists(), leanux::util::fileReadAccess(), and leanux::util::realPath().
Referenced by runOptions().
getLeafColStr()
std::string leanux::tools::lsys::getLeafColStr (const sysdevice::SysDevice * leaf, const std::string & field)
get named field attributes for the SysDevice.
Definition at line 310 of file lsys.cpp.
References leanux::util::ByteStr(), leanux::pci::PCIHardwareInfo::device, leanux::block::getATALinkSpeed(), leanux::block::getATAPortLink(), leanux::net::getDeviceIP4Addresses(), leanux::net::getDeviceIP6Addresses(), leanux::net::getDeviceSpeed(), leanux::block::MajorMinor::getDMUUID(), leanux::sysdevice::SysDevice::getDriver(), leanux::block::MajorMinor::getIOScheduler(), leanux::sysdevice::BlockDevice::getMajorMinor(), leanux::block::MajorMinor::getModel(), leanux::net::getNetStat(), leanux::sysdevice::SysDevice::getPath(), leanux::pci::getPCIDeviceIRQ(), leanux::pci::getPCIHardwareId(), leanux::pci::getPCIHardwareInfo(), leanux::sysdevice::ATAPort::getPort(), leanux::block::MajorMinor::getSectorSize(), leanux::block::MajorMinor::getSize(), leanux::block::MajorMinor::getStats(), leanux::sysdevice::iSCSIDevice::getTargetAddress(), leanux::sysdevice::iSCSIDevice::getTargetIQN(), leanux::sysdevice::iSCSIDevice::getTargetPort(), leanux::usb::getUSBDeviceHardwareClass(), leanux::usb::getUSBHardwareClassStr(), leanux::usb::getUSBHardwareId(), leanux::usb::getUSBHardwareInfo(), leanux::usb::getUSBInterfaceHardwareClass(), leanux::block::MajorMinor::getWWN(), leanux::usb::USBHardwareInfo::idProduct, leanux::usb::USBHardwareInfo::idVendor, leanux::block::DeviceStats::io_ms, leanux::util::leafDir(), leanux::pci::PCIHardwareInfo::pciclass, leanux::block::DeviceStats::read_sectors, leanux::block::DeviceStats::reads, leanux::util::TimeStrSec(), leanux::pci::PCIHardwareInfo::vendor, leanux::block::DeviceStats::write_sectors, and leanux::block::DeviceStats::writes.
Referenced by listDevices().
getOptions()
bool leanux::tools::lsys::getOptions (int argc, char * argv[])
Transform command line arguments into options.
Parameters
argc as from main.
argv as from main.
Returns
false when the command line arguments could not be parsed.
Definition at line 129 of file lsys.cpp.
References leanux::tools::lsys::Options::device, display_fields, leanux::tools::lsys::Filter::filter, filter_map, leanux::tools::lsys::Filter::negate, leanux::tools::lsys::Options::opt_f, leanux::tools::lsys::Options::opt_h, leanux::tools::lsys::Options::opt_l, leanux::tools::lsys::Options::opt_t, leanux::tools::lsys::Options::opt_v, options, leanux::util::tokenize(), type_fields, and type_map.
Referenced by main().
listDevices()
void leanux::tools::lsys::listDevices (const std::list< sysdevice::SysDevicePath > & devices, sysdevice::SysDevice::SysDeviceType t)
list devices, filtered if opt_t is set.
Definition at line 550 of file lsys.cpp.
References display_fields, filter_map, getLeafColStr(), leanux::sysdevice::SysDevice::getPath(), leanux::sysdevice::SysDevice::getType(), leanux::sysdevice::SysDevice::getTypeStr(), leanux::sysdevice::leafDetect(), leanux::util::RegExp::match(), leanux::sysdevice::SysDevice::matchSysDeviceType(), leanux::tools::lsys::Options::opt_t, options, and leanux::util::RegExp::set().
Referenced by runOptions().
main()
int leanux::tools::lsys::main (int argc, char * argv[])
Entry point.
Parameters
argc number of command line arguments.
argv command line arguments.
Returns
0 on succes, 1 on Oops, 2 on other errors.
Definition at line 632 of file lsys.cpp.
References leanux::Oops::getMessage(), getOptions(), leanux::init(), printHelp(), registerField(), registerType(), runOptions(), leanux::sysdevice::SysDevice::sdtATAPort, leanux::sysdevice::SysDevice::sdtBCacheDevice, leanux::sysdevice::SysDevice::sdtBlock, leanux::sysdevice::SysDevice::sdtBlockPartition, leanux::sysdevice::SysDevice::sdtiSCSIDevice, leanux::sysdevice::SysDevice::sdtMapperDevice, leanux::sysdevice::SysDevice::sdtMetaDisk, leanux::sysdevice::SysDevice::sdtMMCDevice, leanux::sysdevice::SysDevice::sdtNetDevice, leanux::sysdevice::SysDevice::sdtNVMeDevice, leanux::sysdevice::SysDevice::sdtPCIBus, leanux::sysdevice::SysDevice::sdtPCIDevice, leanux::sysdevice::SysDevice::sdtSCSIDevice, leanux::sysdevice::SysDevice::sdtSCSIRPort, leanux::sysdevice::SysDevice::sdtSCSIVPort, leanux::sysdevice::SysDevice::sdtUSBBus, leanux::sysdevice::SysDevice::sdtUSBDevice, leanux::sysdevice::SysDevice::sdtUSBInterface, leanux::sysdevice::SysDevice::sdtVirtioBlockDevice, and leanux::sysdevice::SysDevice::sdtVirtioNetDevice.
Referenced by main().
printHelp()
void leanux::tools::lsys::printHelp ()
Print command help.
Definition at line 225 of file lsys.cpp.
References rtype_fields, rtype_map, type_fields, and type_map.
Referenced by main(), and runOptions().
printVersion()
void leanux::tools::lsys::printVersion ()
Definition at line 218 of file lsys.cpp.
Referenced by runOptions().
registerField()
void leanux::tools::lsys::registerField (const std::string & field, sysdevice::SysDevice::SysDeviceType type)
Definition at line 621 of file lsys.cpp.
References rtype_fields, and type_fields.
Referenced by main().
registerType()
void leanux::tools::lsys::registerType (const std::string & st, sysdevice::SysDevice::SysDeviceType et)
register devices types and maintain mappings between type and string representation.
Definition at line 616 of file lsys.cpp.
References rtype_map, and type_map.
Referenced by main().
runOptions()
void leanux::tools::lsys::runOptions ()
Run based on options.
Definition at line 594 of file lsys.cpp.
References leanux::tools::lsys::Options::device, leanux::sysdevice::enumDevices(), fullSysDevice(), listDevices(), leanux::tools::lsys::Options::opt_h, leanux::tools::lsys::Options::opt_t, leanux::tools::lsys::Options::opt_v, options, printHelp(), printVersion(), leanux::util::stlhexnatstrlt(), sysfsTree(), and type_map.
Referenced by main().
sysfsTree()
void leanux::tools::lsys::sysfsTree (const std::string & sysfs)
Definition at line 282 of file lsys.cpp.
References leanux::sysdevice::destroy(), leanux::sysdevice::SysDevice::getTypeStr(), leanux::util::shortenString(), and leanux::sysdevice::treeDetect().
Referenced by runOptions().
Variable Documentation
display_fields
DisplayFields leanux::tools::lsys::display_fields
The global default or user specified display fields.
Definition at line 106 of file lsys.cpp.
Referenced by getOptions(), and listDevices().
filter_map
FilterMap leanux::tools::lsys::filter_map
global map of field names to field filters.
Definition at line 121 of file lsys.cpp.
Referenced by getOptions(), and listDevices().
options
Options leanux::tools::lsys::options
the default or user specified options.
Definition at line 72 of file lsys.cpp.
Referenced by getOptions(), listDevices(), and runOptions().
rtype_fields
RTypeFields leanux::tools::lsys::rtype_fields
Definition at line 96 of file lsys.cpp.
Referenced by printHelp(), and registerField().
rtype_map
RTypeMap leanux::tools::lsys::rtype_map
Definition at line 90 of file lsys.cpp.
Referenced by printHelp(), and registerType().
type_fields
TypeFields leanux::tools::lsys::type_fields
The global TypeFields.
Definition at line 95 of file lsys.cpp.
Referenced by getOptions(), printHelp(), and registerField().
type_map
TypeMap leanux::tools::lsys::type_map
The global TypeMap.
Definition at line 89 of file lsys.cpp.
Referenced by getOptions(), printHelp(), registerType(), and runOptions().