leanux: leanux::tools::lmon::LardHistory Class Reference
leanux::tools::lmon::LardHistory Class Reference
#include <history.hpp>
Public Member Functions
LardHistory (persist::Database *db, time_t zoom)
void dayDown ()
void dayUp ()
void fetchXIOView (XIOView &ioview)
void fetchXNetView (XNetView &netview)
void fetchXProcView (XProcView &procview)
void fetchXSysView (XSysView &sysview)
long getEndSnap () const
time_t getEndTime () const
time_t getRangeDuration () const
long getStartSnap () const
time_t getStartTime () const
void hourDown ()
void hourUp ()
void rangeDown ()
void rangeEnd ()
void rangeStart ()
void rangeUp ()
time_t setZoom (time_t zoom)
Sets the current time selection into the lard data.
void weekDown ()
void weekUp ()
time_t zoomIn ()
time_t zoomOut ()
Protected Types
typedef std::map< SnapRange, cpu::CPUStat > RangeMap
Protected Member Functions
bool getCPUStatRange (SnapRange range)
void updateMinMax ()
void updateRangeTime ()
Protected Attributes
std::map< SnapRange, cpu::CPUStat > cpumap_
persist::Database * db_
time_t snap_avg_time_
long snap_end_
long snap_end_time_
long snap_max_
time_t snap_max_stop_time_
long snap_min_
time_t snap_min_start_time_
long snap_range_
long snap_start_
long snap_start_time_
time_t zoom_
Detailed Description
Definition at line 49 of file history.hpp.
Member Typedef Documentation
RangeMap
typedef std::map<SnapRange,cpu::CPUStat> leanux::tools::lmon::LardHistory::RangeMap protected
Definition at line 116 of file history.hpp.
Constructor & Destructor Documentation
LardHistory()
leanux::tools::lmon::LardHistory::LardHistory (persist::Database * db, time_t zoom)
Definition at line 47 of file history.cpp.
References db_, setZoom(), snap_end_, snap_max_, snap_range_, snap_start_, updateMinMax(), and updateRangeTime().
Member Function Documentation
dayDown()
void leanux::tools::lmon::LardHistory::dayDown ()
Definition at line 170 of file history.cpp.
References cpumap_, snap_end_, snap_end_time_, snap_min_, snap_range_, snap_start_, snap_start_time_, updateMinMax(), and updateRangeTime().
Referenced by leanux::tools::lmon::Screen::runHistory().
dayUp()
void leanux::tools::lmon::LardHistory::dayUp ()
Definition at line 154 of file history.cpp.
References cpumap_, snap_end_, snap_end_time_, snap_max_, snap_range_, snap_start_, snap_start_time_, updateMinMax(), and updateRangeTime().
Referenced by leanux::tools::lmon::Screen::runHistory().
fetchXIOView()
void leanux::tools::lmon::LardHistory::fetchXIOView (XIOView & ioview)
Definition at line 444 of file history.cpp.
References leanux::tools::lmon::XIORec::artm, leanux::tools::lmon::XIORec::awtm, leanux::persist::DML::bind(), db_, leanux::persist::Query::getDouble(), leanux::persist::Query::getText(), leanux::tools::lmon::XIORec::growths, leanux::tools::lmon::XIORec::iodone_cnt, leanux::tools::lmon::XIORec::ioerr_cnt, leanux::tools::lmon::XIORec::iorequest_cnt, leanux::tools::lmon::XIOView::iosorted, leanux::tools::lmon::XIOView::iostats, leanux::tools::lmon::XIOView::mountsorted, leanux::tools::lmon::XIOView::mountstats, leanux::persist::Statement::prepare(), leanux::tools::lmon::XIORec::qsz, leanux::tools::lmon::XIORec::rbs, leanux::tools::lmon::XIORec::rs, snap_end_, snap_start_, leanux::persist::Query::step(), leanux::tools::lmon::XIORec::svctm, leanux::tools::lmon::XIORec::util, leanux::tools::lmon::XIORec::wbs, and leanux::tools::lmon::XIORec::ws.
Referenced by leanux::tools::lmon::Screen::runHistory().
fetchXNetView()
void leanux::tools::lmon::LardHistory::fetchXNetView (XNetView & netview)
Definition at line 353 of file history.cpp.
References leanux::persist::DML::bind(), db_, leanux::tools::lmon::XNetView::delta, leanux::net::NetStat::device, leanux::persist::Query::getDouble(), leanux::persist::Query::getLong(), leanux::persist::Query::getText(), leanux::persist::Statement::prepare(), leanux::net::NetStat::rx_bytes, leanux::net::NetStat::rx_errors, leanux::net::NetStat::rx_packets, leanux::tools::lmon::XNetView::sample_count, snap_end_, snap_start_, leanux::persist::Query::step(), leanux::tools::lmon::XNetView::tcpclient, leanux::tools::lmon::XNetView::tcpserver, leanux::net::NetStat::tx_bytes, leanux::net::NetStat::tx_errors, and leanux::net::NetStat::tx_packets.
Referenced by leanux::tools::lmon::Screen::runHistory().
fetchXProcView()
void leanux::tools::lmon::LardHistory::fetchXProcView (XProcView & procview)
Definition at line 263 of file history.cpp.
References leanux::persist::DML::bind(), leanux::process::ProcPidStatDelta::comm, db_, leanux::process::ProcPidStatDelta::delayacct_blkio_ticks, leanux::tools::lmon::XProcView::delta, leanux::tools::lmon::XProcView::disabled, leanux::persist::Query::getDouble(), leanux::persist::Query::getLong(), leanux::persist::Query::getText(), leanux::persist::Query::isNull(), leanux::process::ProcPidStatDelta::majflt, leanux::process::ProcPidStatDelta::minflt, leanux::process::ProcPidStatDelta::pgrp, leanux::process::ProcPidStatDelta::pid, leanux::tools::lmon::XProcView::pidargs, leanux::tools::lmon::XProcView::piduids, leanux::persist::Statement::prepare(), leanux::persist::Statement::reset(), leanux::process::ProcPidStatDelta::rss, leanux::tools::lmon::XProcView::sample_count, snap_end_, snap_max_, snap_min_, snap_start_, leanux::process::ProcPidStatDelta::state, leanux::persist::Query::step(), leanux::process::ProcPidStatDelta::stime, leanux::process::ProcPidStatDelta::utime, leanux::process::ProcPidStatDelta::vsize, and leanux::process::ProcPidStatDelta::wchan.
Referenced by leanux::tools::lmon::Screen::runHistory().
fetchXSysView()
void leanux::tools::lmon::LardHistory::fetchXSysView (XSysView & sysview)
Definition at line 540 of file history.cpp.
References leanux::cpu::LoadAvg::avg10_, leanux::cpu::LoadAvg::avg15_, leanux::cpu::LoadAvg::avg5_, leanux::persist::DML::bind(), leanux::tools::lmon::XSysView::blockq, leanux::cpu::CPUTopology::cores, leanux::tools::lmon::XSysView::cpu_delta, leanux::tools::lmon::XSysView::cpu_seconds, leanux::tools::lmon::XSysView::cpu_topo, leanux::tools::lmon::XSysView::cpu_total, leanux::tools::lmon::XSysView::cpufuture, cpumap_, leanux::tools::lmon::XSysView::cpupast, leanux::tools::lmon::XSysView::ctxsws, db_, leanux::tools::lmon::XSysView::forks, leanux::tools::lmon::XSysView::fs_growths, getCPUStatRange(), leanux::cpu::getCPUTotal(), leanux::cpu::getCPUUsageTotal(), leanux::persist::Query::getDouble(), leanux::persist::Query::getLong(), leanux::tools::lmon::XSysView::loadavg, leanux::cpu::CPUTopology::logical, leanux::tools::lmon::XSysView::mem_allocs, leanux::tools::lmon::XSysView::mem_anon, leanux::tools::lmon::XSysView::mem_commitas, leanux::tools::lmon::XSysView::mem_dirty, leanux::tools::lmon::XSysView::mem_file, leanux::tools::lmon::XSysView::mem_frees, leanux::tools::lmon::XSysView::mem_hpfree, leanux::tools::lmon::XSysView::mem_hprsvd, leanux::tools::lmon::XSysView::mem_hptotal, leanux::tools::lmon::XSysView::mem_majflts, leanux::tools::lmon::XSysView::mem_mapped, leanux::tools::lmon::XSysView::mem_minflts, leanux::tools::lmon::XSysView::mem_mlock, leanux::tools::lmon::XSysView::mem_pageins, leanux::tools::lmon::XSysView::mem_pageouts, leanux::tools::lmon::XSysView::mem_pagetbls, leanux::tools::lmon::XSysView::mem_shmem, leanux::tools::lmon::XSysView::mem_slab, leanux::tools::lmon::XSysView::mem_swapins, leanux::tools::lmon::XSysView::mem_swapouts, leanux::tools::lmon::XSysView::mem_swpsize, leanux::tools::lmon::XSysView::mem_swpused, leanux::tools::lmon::XSysView::mem_thpanon, leanux::tools::lmon::XSysView::mem_total, leanux::tools::lmon::XSysView::mem_unused, leanux::cpu::CPUTopology::physical, leanux::persist::Statement::prepare(), leanux::tools::lmon::XSysView::res_filesmax, leanux::tools::lmon::XSysView::res_filesopen, leanux::tools::lmon::XSysView::res_inodesfree, leanux::tools::lmon::XSysView::res_inodesopen, leanux::tools::lmon::XSysView::res_logins, leanux::tools::lmon::XSysView::res_processes, leanux::tools::lmon::XSysView::res_users, leanux::tools::lmon::XSysView::runq, leanux::tools::lmon::XSysView::sample_count, snap_end_, snap_end_time_, leanux::tools::lmon::SnapRange::snap_max, leanux::tools::lmon::SnapRange::snap_min, snap_range_, snap_start_, snap_start_time_, leanux::persist::Query::step(), leanux::tools::lmon::XSysView::t1, leanux::tools::lmon::XSysView::t2, and leanux::tools::lmon::XSysView::time_slice.
Referenced by leanux::tools::lmon::Screen::runHistory().
getCPUStatRange()
bool leanux::tools::lmon::LardHistory::getCPUStatRange (SnapRange range) protected
Definition at line 768 of file history.cpp.
References leanux::persist::DML::bind(), cpumap_, db_, leanux::persist::Query::getDouble(), leanux::cpu::CPUStat::guest, leanux::cpu::CPUStat::guest_nice, leanux::cpu::CPUStat::iowait, leanux::cpu::CPUStat::irq, leanux::persist::Query::isNull(), leanux::cpu::CPUStat::nice, leanux::persist::Statement::prepare(), leanux::tools::lmon::SnapRange::snap_max, leanux::tools::lmon::SnapRange::snap_min, leanux::cpu::CPUStat::softirq, leanux::cpu::CPUStat::steal, leanux::persist::Query::step(), leanux::cpu::CPUStat::system, and leanux::cpu::CPUStat::user.
Referenced by fetchXSysView().
getEndSnap()
long leanux::tools::lmon::LardHistory::getEndSnap () const inline
Definition at line 87 of file history.hpp.
References snap_end_.
getEndTime()
time_t leanux::tools::lmon::LardHistory::getEndTime () const inline
Definition at line 91 of file history.hpp.
References snap_end_time_.
Referenced by leanux::tools::lmon::Screen::runHistory().
getRangeDuration()
time_t leanux::tools::lmon::LardHistory::getRangeDuration () const inline
Definition at line 93 of file history.hpp.
References snap_end_time_, and snap_start_time_.
getStartSnap()
long leanux::tools::lmon::LardHistory::getStartSnap () const inline
Definition at line 85 of file history.hpp.
References snap_start_.
getStartTime()
time_t leanux::tools::lmon::LardHistory::getStartTime () const inline
Definition at line 89 of file history.hpp.
References snap_start_time_.
Referenced by leanux::tools::lmon::Screen::runHistory().
hourDown()
void leanux::tools::lmon::LardHistory::hourDown ()
Definition at line 138 of file history.cpp.
References cpumap_, snap_end_, snap_end_time_, snap_min_, snap_range_, snap_start_, snap_start_time_, updateMinMax(), and updateRangeTime().
Referenced by leanux::tools::lmon::Screen::runHistory().
hourUp()
void leanux::tools::lmon::LardHistory::hourUp ()
Definition at line 122 of file history.cpp.
References cpumap_, snap_end_, snap_end_time_, snap_max_, snap_range_, snap_start_, snap_start_time_, updateMinMax(), and updateRangeTime().
Referenced by leanux::tools::lmon::Screen::runHistory().
rangeDown()
void leanux::tools::lmon::LardHistory::rangeDown ()
Definition at line 113 of file history.cpp.
References snap_end_, snap_min_, snap_range_, snap_start_, updateMinMax(), and updateRangeTime().
Referenced by leanux::tools::lmon::Screen::runHistory().
rangeEnd()
void leanux::tools::lmon::LardHistory::rangeEnd ()
Definition at line 226 of file history.cpp.
References cpumap_, snap_end_, snap_max_, snap_range_, snap_start_, updateMinMax(), and updateRangeTime().
Referenced by leanux::tools::lmon::Screen::runHistory().
rangeStart()
void leanux::tools::lmon::LardHistory::rangeStart ()
Definition at line 218 of file history.cpp.
References cpumap_, snap_end_, snap_min_, snap_range_, snap_start_, updateMinMax(), and updateRangeTime().
Referenced by leanux::tools::lmon::Screen::runHistory().
rangeUp()
void leanux::tools::lmon::LardHistory::rangeUp ()
Definition at line 104 of file history.cpp.
References snap_end_, snap_max_, snap_range_, snap_start_, updateMinMax(), and updateRangeTime().
Referenced by leanux::tools::lmon::Screen::runHistory().
setZoom()
time_t leanux::tools::lmon::LardHistory::setZoom (time_t zoom)
Sets the current time selection into the lard data.
If requested data is not available, setSel will do it's best to provide a sane alternative.
Parameters
zoom the snapshot time range in seconds
Definition at line 56 of file history.cpp.
References cpumap_, snap_end_, snap_max_, snap_min_, snap_range_, snap_start_, updateMinMax(), updateRangeTime(), and zoom_.
Referenced by LardHistory(), zoomIn(), and zoomOut().
updateMinMax()
void leanux::tools::lmon::LardHistory::updateMinMax () protected
Definition at line 248 of file history.cpp.
References db_, leanux::persist::Query::getDouble(), leanux::persist::Query::getLong(), leanux::persist::Statement::prepare(), snap_avg_time_, snap_max_, snap_max_stop_time_, snap_min_, snap_min_start_time_, snap_range_, leanux::persist::Query::step(), and zoom_.
Referenced by dayDown(), dayUp(), hourDown(), hourUp(), LardHistory(), rangeDown(), rangeEnd(), rangeStart(), rangeUp(), setZoom(), weekDown(), and weekUp().
updateRangeTime()
void leanux::tools::lmon::LardHistory::updateRangeTime () protected
Definition at line 234 of file history.cpp.
References leanux::persist::DML::bind(), db_, leanux::persist::Query::getLong(), leanux::persist::Statement::prepare(), snap_end_, snap_end_time_, snap_start_, snap_start_time_, and leanux::persist::Query::step().
Referenced by dayDown(), dayUp(), hourDown(), hourUp(), LardHistory(), rangeDown(), rangeEnd(), rangeStart(), rangeUp(), setZoom(), weekDown(), and weekUp().
weekDown()
void leanux::tools::lmon::LardHistory::weekDown ()
Definition at line 202 of file history.cpp.
References cpumap_, snap_end_, snap_end_time_, snap_min_, snap_range_, snap_start_, snap_start_time_, updateMinMax(), and updateRangeTime().
Referenced by leanux::tools::lmon::Screen::runHistory().
weekUp()
void leanux::tools::lmon::LardHistory::weekUp ()
Definition at line 186 of file history.cpp.
References cpumap_, snap_end_, snap_end_time_, snap_max_, snap_range_, snap_start_, snap_start_time_, updateMinMax(), and updateRangeTime().
Referenced by leanux::tools::lmon::Screen::runHistory().
zoomIn()
time_t leanux::tools::lmon::LardHistory::zoomIn ()
Definition at line 88 of file history.cpp.
References setZoom(), and zoom_.
Referenced by leanux::tools::lmon::Screen::runHistory().
zoomOut()
time_t leanux::tools::lmon::LardHistory::zoomOut ()
Definition at line 72 of file history.cpp.
References setZoom(), and zoom_.
Referenced by leanux::tools::lmon::Screen::runHistory().
Field Documentation
cpumap_
std::map<SnapRange,cpu::CPUStat> leanux::tools::lmon::LardHistory::cpumap_ protected
Definition at line 117 of file history.hpp.
Referenced by dayDown(), dayUp(), fetchXSysView(), getCPUStatRange(), hourDown(), hourUp(), rangeEnd(), rangeStart(), setZoom(), weekDown(), and weekUp().
db_
persist::Database* leanux::tools::lmon::LardHistory::db_ protected
Definition at line 101 of file history.hpp.
Referenced by fetchXIOView(), fetchXNetView(), fetchXProcView(), fetchXSysView(), getCPUStatRange(), LardHistory(), updateMinMax(), and updateRangeTime().
snap_avg_time_
time_t leanux::tools::lmon::LardHistory::snap_avg_time_ protected
Definition at line 111 of file history.hpp.
Referenced by updateMinMax().
snap_end_
long leanux::tools::lmon::LardHistory::snap_end_ protected
Definition at line 105 of file history.hpp.
Referenced by dayDown(), dayUp(), fetchXIOView(), fetchXNetView(), fetchXProcView(), fetchXSysView(), getEndSnap(), hourDown(), hourUp(), LardHistory(), rangeDown(), rangeEnd(), rangeStart(), rangeUp(), setZoom(), updateRangeTime(), weekDown(), and weekUp().
snap_end_time_
long leanux::tools::lmon::LardHistory::snap_end_time_ protected
Definition at line 106 of file history.hpp.
Referenced by dayDown(), dayUp(), fetchXSysView(), getEndTime(), getRangeDuration(), hourDown(), hourUp(), updateRangeTime(), weekDown(), and weekUp().
snap_max_
long leanux::tools::lmon::LardHistory::snap_max_ protected
Definition at line 108 of file history.hpp.
Referenced by dayUp(), fetchXProcView(), hourUp(), LardHistory(), rangeEnd(), rangeUp(), setZoom(), updateMinMax(), and weekUp().
snap_max_stop_time_
time_t leanux::tools::lmon::LardHistory::snap_max_stop_time_ protected
Definition at line 110 of file history.hpp.
Referenced by updateMinMax().
snap_min_
long leanux::tools::lmon::LardHistory::snap_min_ protected
Definition at line 107 of file history.hpp.
Referenced by dayDown(), fetchXProcView(), hourDown(), rangeDown(), rangeStart(), setZoom(), updateMinMax(), and weekDown().
snap_min_start_time_
time_t leanux::tools::lmon::LardHistory::snap_min_start_time_ protected
Definition at line 109 of file history.hpp.
Referenced by updateMinMax().
snap_range_
long leanux::tools::lmon::LardHistory::snap_range_ protected
Definition at line 114 of file history.hpp.
Referenced by dayDown(), dayUp(), fetchXSysView(), hourDown(), hourUp(), LardHistory(), rangeDown(), rangeEnd(), rangeStart(), rangeUp(), setZoom(), updateMinMax(), weekDown(), and weekUp().
snap_start_
long leanux::tools::lmon::LardHistory::snap_start_ protected
Definition at line 103 of file history.hpp.
Referenced by dayDown(), dayUp(), fetchXIOView(), fetchXNetView(), fetchXProcView(), fetchXSysView(), getStartSnap(), hourDown(), hourUp(), LardHistory(), rangeDown(), rangeEnd(), rangeStart(), rangeUp(), setZoom(), updateRangeTime(), weekDown(), and weekUp().
snap_start_time_
long leanux::tools::lmon::LardHistory::snap_start_time_ protected
Definition at line 104 of file history.hpp.
Referenced by dayDown(), dayUp(), fetchXSysView(), getRangeDuration(), getStartTime(), hourDown(), hourUp(), updateRangeTime(), weekDown(), and weekUp().
zoom_
time_t leanux::tools::lmon::LardHistory::zoom_ protected
Definition at line 113 of file history.hpp.
Referenced by setZoom(), updateMinMax(), zoomIn(), and zoomOut().
The documentation for this class was generated from the following files:
tools/lmon/history.hpp
tools/lmon/history.cpp