leanux: leanux::net Namespace Reference
leanux::net Namespace Reference
network configuration and performance API.
Data Structures
struct NetStat
Network device statistics as in /proc/net/dev.
struct OUI
struct TCP4SocketInfo
IPv4 socket.
struct TCP6SocketInfo
IPv4 socket.
class TCPKey
Utility structure to key TCP connections.
class TCPKeyCounter
TCP TCPKeyCounter status.
struct UDP4SocketInfo
UDP4 socket.
struct UnixDomainSocketInfo
Unix domain socket.
Typedefs
typedef std::map< std::string, NetStat > NetStatDeviceMap
A map of network device name to NetStat statistics.
typedef std::vector< NetStat > NetStatDeviceVector
A vector of NetStat objects.
Enumerations
enum TCPState {
TCP_ESTABLISHED = 1, TCP_SYN_SENT, TCP_SYN_RECV, TCP_FIN_WAIT1,
TCP_FIN_WAIT2, TCP_TIME_WAIT, TCP_CLOSE, TCP_CLOSE_WAIT,
TCP_LAST_ACK, TCP_LISTEN, TCP_CLOSING
}
TCP connection states.
Functions
std::string convertAF_INET (unsigned long addr)
convert IPv4 network IP representation to human readable format.
std::string convertAF_INET6 (const struct in6_addr *addr)
convert IPv6 network IP representation to human readable format.
void enumDevices (std::list< std::string > &devices)
Enumerate network devices.
void enumTCP4Sockets (std::list< TCP4SocketInfo > &sockets)
Enumerate TCP4 sockets from /proc/net/tcp.
void enumTCP6Sockets (std::list< TCP6SocketInfo > &sockets)
Enumerate TCP6 sockets from /proc/net/tcp6.
bool findTCP4SocketByINode (ino_t inode, TCP4SocketInfo &info)
Search for a TCP4 socket by inode number.
bool findUDP4SocketByINode (ino_t inode, UDP4SocketInfo &info)
Search for a UDP4 socket by inode number.
bool findUnixDomainSocketByINode (ino_t inode, UnixDomainSocketInfo &info)
Search for a Unix domain socket by inode number.
std::string getDeviceByIP (const std::string &ip)
Return the device name configured with the given ip address.
int getDeviceCarrier (const std::string &device)
Get the device speed in Mb/s.
std::string getDeviceDuplex (const std::string &device)
Get the duplex mode of the device.
void getDeviceIP4Addresses (const std::string &device, std::list< std::string > &addrlist)
Get a list of IP4 adresses assigned to the device.
void getDeviceIP6Addresses (const std::string &device, std::list< std::string > &addrlist)
Get a list of IP6 adresses assigned to the device.
std::string getDeviceMACAddress (const std::string &device)
Get the device's MAC address.
std::string getDeviceOperState (const std::string &device)
Get a network device's operating state.
unsigned long getDeviceSpeed (const std::string &device)
Get the device speed in Mb/s.
void getMACOUI (const std::string &mac, OUI &oui)
void getNetStat (NetStatDeviceMap &stats)
Get network device statistics from /proc/net/dev.
void getNetStatDelta (const NetStatDeviceMap &snap1, const NetStatDeviceMap &snap2, NetStatDeviceVector &delta)
Get the delta of two NetStatDeviceMap objects, sorted by using int operator<(const NetStat& n1, const NetStat &n2).
std::string getServiceName (int port)
Get the service name, eg 'ssh' for port 22.
std::string getSysPath (const std::string &device)
Get the device sysfs path.
void getTCPConnectionCounters (std::list< TCPKeyCounter > &servers, std::list< TCPKeyCounter > &clients)
Return the number of established TCP connections grouped by (ip,port,uid).
std::string getTCPStateString (int tcp_state)
Get human readable name for a tcp state.
void init ()
initialize net library
int operator< (const NetStat &n1, const NetStat &n2)
Compare two NetStat structs.
std::ostream & operator<< (std::ostream &os, const TCP4SocketInfo &inf)
Dump a TCP4Socket to stream.
std::ostream & operator<< (std::ostream &os, const UDP4SocketInfo &inf)
Dump a UDP4SocketInfo to stream.
std::ostream & operator<< (std::ostream &os, const UnixDomainSocketInfo &inf)
Dump a UnixDomainSocketInfo to stream.
bool parseTCP4Line (const std::string &s, TCP4SocketInfo &info)
parse a TCP4 std::string from /proc/net/tcp.
bool parseTCP6Line (const std::string &s, TCP6SocketInfo &info)
parse a TCP6 std::string from /proc/net/tcp.
bool parseUDP4Line (const std::string &s, UDP4SocketInfo &info)
parse a line from /proc/net/udp.
std::string resolveIP (const std::string &addr)
Try to resolve an IPv4 or IPv6 address.
int whatAF_INET (const std::string &addr)
Determine the type of IP address.
Variables
std::string MACOUIDatabase = "/usr/share/misc/oui.txt"
Detailed Description
network configuration and performance API.
Data Structure Documentation
leanux::net::NetStat
struct leanux::net::NetStat
Network device statistics as in /proc/net/dev.
Definition at line 327 of file net.hpp.
Data Fields
string device the name of the device.
unsigned long rx_bytes the number of bytes received.
unsigned long rx_compressed the number of compressed packets received.
unsigned long rx_dropped the number of packets recived but dropped.
unsigned long rx_errors the number of packets received in error.
unsigned long rx_fifo the number of fifo buffer errors.
unsigned long rx_frame the number of packet framing errors.
unsigned long rx_multicast the number of multicast packets received.
unsigned long rx_packets the number of packets received.
unsigned long tx_bytes the number of bytes transmitted.
unsigned long tx_carrier the number of carrier losses during transmit.
unsigned long tx_collisions the number of transmit collisions.
unsigned long tx_compressed the number of compressed packets transmitted.
unsigned long tx_dropped the number of packets dropped instead of transmitted.
unsigned long tx_errors the number of transmit errors.
unsigned long tx_fifo the number of transmit fifo buffer errors.
unsigned long tx_packets the number of packets transmitted.
leanux::net::OUI
struct leanux::net::OUI
Definition at line 103 of file net.hpp.
Data Fields
list< string > address
string countrycode
string vendor
leanux::net::TCP4SocketInfo
struct leanux::net::TCP4SocketInfo
IPv4 socket.
Examples
example_process.cpp.
Definition at line 142 of file net.hpp.
Data Fields
ino_t inode the inode of the socket.
unsigned long local_addr local address in network format.
See also
convertAF_INET.
unsigned int local_port the local port.
unsigned long remote_addr remote address in network format.
See also
convertAF_INET.
unsigned int remote_port the remote port.
unsigned long rx_queue entries in receive queue.
unsigned int tcp_state state of the socket, one of the Linux TCP_ defines.
See also
getTCPStateString.
unsigned long tx_queue entries in transmit queue.
unsigned int uid uid owning the socket.
See also
leanux::system::getUserName().
leanux::net::TCP6SocketInfo
struct leanux::net::TCP6SocketInfo
IPv4 socket.
Definition at line 166 of file net.hpp.
Data Fields
ino_t inode the inode of the socket.
struct in6_addr local_addr local address in network format.
See also
convertAF_INET.
unsigned int local_port the local port.
in6_addr remote_addr remote address in network format.
See also
convertAF_INET.
unsigned int remote_port the remote port.
unsigned long rx_queue entries in receive queue.
unsigned int tcp_state state of the socket, one of the Linux TCP_ defines.
See also
getTCPStateString.
unsigned long tx_queue entries in transmit queue.
unsigned int uid uid owning the socket.
See also
leanux::system::getUserName().
leanux::net::UDP4SocketInfo
struct leanux::net::UDP4SocketInfo
UDP4 socket.
Examples
example_process.cpp.
Definition at line 296 of file net.hpp.
Data Fields
unsigned int inode
unsigned long local_addr
unsigned int local_port
unsigned long remote_addr
unsigned int remote_port
unsigned long rx_queue
unsigned int tcp_state
unsigned long tx_queue
unsigned int uid
leanux::net::UnixDomainSocketInfo
struct leanux::net::UnixDomainSocketInfo
Unix domain socket.
Examples
example_process.cpp.
Definition at line 272 of file net.hpp.
Data Fields
unsigned long flags
ino_t inode
string path
unsigned long refcount
unsigned int state
Typedef Documentation
NetStatDeviceMap
typedef std::map<std::string,NetStat> leanux::net::NetStatDeviceMap
A map of network device name to NetStat statistics.
Definition at line 363 of file net.hpp.
NetStatDeviceVector
typedef std::vector<NetStat> leanux::net::NetStatDeviceVector
A vector of NetStat objects.
Definition at line 368 of file net.hpp.
Enumeration Type Documentation
TCPState
enum leanux::net::TCPState
TCP connection states.
Enumerator
TCP_ESTABLISHED
TCP_SYN_SENT
TCP_SYN_RECV
TCP_FIN_WAIT1
TCP_FIN_WAIT2
TCP_TIME_WAIT
TCP_CLOSE
TCP_CLOSE_WAIT
TCP_LAST_ACK
TCP_LISTEN
TCP_CLOSING
Definition at line 64 of file net.hpp.
Function Documentation
convertAF_INET()
std::string leanux::net::convertAF_INET (unsigned long addr)
convert IPv4 network IP representation to human readable format.
Parameters
addr the IPv4 address (in network format) to convert.
Returns
a std::string with the IPv4 address.
Definition at line 219 of file net.cpp.
Referenced by getTCPConnectionCounters(), and operator<<().
convertAF_INET6()
std::string leanux::net::convertAF_INET6 (const struct in6_addr * addr)
convert IPv6 network IP representation to human readable format.
Parameters
addr the IPv6 address (in network format) to convert.
Returns
a std::string with the IPv6 address.
Definition at line 225 of file net.cpp.
Referenced by getDeviceIP6Addresses(), and getTCPConnectionCounters().
enumDevices()
void leanux::net::enumDevices (std::list< std::string > & devices)
Enumerate network devices.
Parameters
devices the list of device names to fill.
Definition at line 281 of file net.cpp.
Referenced by getDeviceByIP().
enumTCP4Sockets()
void leanux::net::enumTCP4Sockets (std::list< TCP4SocketInfo > & sockets)
Enumerate TCP4 sockets from /proc/net/tcp.
Parameters
sockets the list of TCP4SocketInfo to fill.
Definition at line 296 of file net.cpp.
References parseTCP4Line().
Referenced by getTCPConnectionCounters().
enumTCP6Sockets()
void leanux::net::enumTCP6Sockets (std::list< TCP6SocketInfo > & sockets)
Enumerate TCP6 sockets from /proc/net/tcp6.
Parameters
sockets the list of TCP6SocketInfo to fill.
Definition at line 309 of file net.cpp.
References parseTCP6Line().
Referenced by getTCPConnectionCounters().
findTCP4SocketByINode()
bool leanux::net::findTCP4SocketByINode (ino_t inode, TCP4SocketInfo & info)
Search for a TCP4 socket by inode number.
Parameters
inode the indoe to match.
info the TCP4SocketInfo to fill if an entry is found.
Returns
true when the inode is found.
Examples
example_process.cpp.
Definition at line 429 of file net.cpp.
References leanux::net::TCP4SocketInfo::inode, and parseTCP4Line().
findUDP4SocketByINode()
bool leanux::net::findUDP4SocketByINode (ino_t inode, UDP4SocketInfo & info)
Search for a UDP4 socket by inode number.
Parameters
inode the indoe to match.
info the UDP4SocketInfo to fill if an entry is found.
Returns
true when the inode is found.
Examples
example_process.cpp.
Definition at line 490 of file net.cpp.
References leanux::net::UDP4SocketInfo::inode, and parseUDP4Line().
findUnixDomainSocketByINode()
bool leanux::net::findUnixDomainSocketByINode (ino_t inode, UnixDomainSocketInfo & info)
Search for a Unix domain socket by inode number.
Parameters
inode the indoe to match.
info the UnixDomainSocketInfo to fill if an entry is found.
Returns
true when the inode is found.
Examples
example_process.cpp.
Definition at line 445 of file net.cpp.
References leanux::net::UnixDomainSocketInfo::flags, leanux::net::UnixDomainSocketInfo::inode, leanux::net::UnixDomainSocketInfo::path, leanux::net::UnixDomainSocketInfo::refcount, and leanux::net::UnixDomainSocketInfo::state.
getDeviceByIP()
std::string leanux::net::getDeviceByIP (const std::string & ip)
Return the device name configured with the given ip address.
Parameters
ip the ip address, either IPV4 or IPV6.
Returns
device name or empty if not found.
Definition at line 201 of file net.cpp.
References enumDevices(), getDeviceIP4Addresses(), and getDeviceIP6Addresses().
getDeviceCarrier()
int leanux::net::getDeviceCarrier (const std::string & device)
Get the device speed in Mb/s.
Parameters
device the device name.
Returns
the device carrier.
Definition at line 94 of file net.cpp.
Referenced by leanux::sysdevice::NetDevice::getPropertyValueList().
getDeviceDuplex()
std::string leanux::net::getDeviceDuplex (const std::string & device)
Get the duplex mode of the device.
Parameters
device the device name.
Returns
the duplex mode.
Definition at line 105 of file net.cpp.
Referenced by leanux::sysdevice::NetDevice::getPropertyValueList().
getDeviceIP4Addresses()
void leanux::net::getDeviceIP4Addresses (const std::string & device, std::list< std::string > & addrlist)
Get a list of IP4 adresses assigned to the device.
Parameters
device the device name.
addrlist the list of IP4 addresses to fill.
Examples
example_pci.cpp.
Definition at line 161 of file net.cpp.
Referenced by getDeviceByIP(), leanux::tools::lsys::getLeafColStr(), leanux::sysdevice::NetDevice::getPropertyValueList(), and leanux::tools::lrep::htmlSystemDetails().
getDeviceIP6Addresses()
void leanux::net::getDeviceIP6Addresses (const std::string & device, std::list< std::string > & addrlist)
Get a list of IP6 adresses assigned to the device.
Parameters
device the device name.
addrlist the list of IP6 addresses to fill.
Examples
example_pci.cpp.
Definition at line 181 of file net.cpp.
References convertAF_INET6().
Referenced by getDeviceByIP(), leanux::tools::lsys::getLeafColStr(), and leanux::sysdevice::NetDevice::getPropertyValueList().
getDeviceMACAddress()
std::string leanux::net::getDeviceMACAddress (const std::string & device)
Get the device's MAC address.
Examples
example_pci.cpp.
Definition at line 116 of file net.cpp.
Referenced by leanux::sysdevice::NetDevice::getPropertyValueList(), and leanux::tools::lard::NetSnap::storeSnap().
getDeviceOperState()
std::string leanux::net::getDeviceOperState (const std::string & device)
Get a network device's operating state.
Parameters
device the device name (as in 'eth0').
Returns
either 'up' or 'down'.
Examples
example_pci.cpp.
Definition at line 76 of file net.cpp.
Referenced by leanux::sysdevice::NetDevice::getPropertyValueList().
getDeviceSpeed()
unsigned long leanux::net::getDeviceSpeed (const std::string & device)
Get the device speed in Mb/s.
Parameters
device the device name.
Returns
the device speed in Mb/s.
Examples
example_pci.cpp.
Definition at line 83 of file net.cpp.
Referenced by leanux::tools::lsys::getLeafColStr(), and leanux::sysdevice::NetDevice::getPropertyValueList().
getMACOUI()
void leanux::net::getMACOUI (const std::string & mac, OUI & oui)
Definition at line 123 of file net.cpp.
References leanux::net::OUI::address, leanux::net::OUI::countrycode, MACOUIDatabase, and leanux::net::OUI::vendor.
Referenced by leanux::sysdevice::NetDevice::getPropertyValueList().
getNetStat()
void leanux::net::getNetStat (NetStatDeviceMap & stats)
Get network device statistics from /proc/net/dev.
Parameters
stats the NetStatDeviceMap to fill with /proc/net/dev contents.
Definition at line 526 of file net.cpp.
References leanux::net::NetStat::rx_bytes, leanux::net::NetStat::rx_compressed, leanux::net::NetStat::rx_dropped, leanux::net::NetStat::rx_errors, leanux::net::NetStat::rx_fifo, leanux::net::NetStat::rx_frame, leanux::net::NetStat::rx_multicast, leanux::net::NetStat::rx_packets, leanux::net::NetStat::tx_bytes, leanux::net::NetStat::tx_carrier, leanux::net::NetStat::tx_collisions, leanux::net::NetStat::tx_compressed, leanux::net::NetStat::tx_dropped, leanux::net::NetStat::tx_errors, leanux::net::NetStat::tx_fifo, and leanux::net::NetStat::tx_packets.
Referenced by leanux::tools::lsys::getLeafColStr(), leanux::tools::lmon::NetView::getOptimalHeight(), leanux::tools::lmon::RealtimeSampler::sampleXNetView(), leanux::tools::lard::NetSnap::startSnap(), and leanux::tools::lard::NetSnap::stopSnap().
getNetStatDelta()
void leanux::net::getNetStatDelta (const NetStatDeviceMap & snap1, const NetStatDeviceMap & snap2, NetStatDeviceVector & delta)
Get the delta of two NetStatDeviceMap objects, sorted by using int operator<(const NetStat& n1, const NetStat &n2).
Parameters
snap1 first NetStatDeviceMap.
snap2 second NetStatDeviceMap.
delta the NetStatDeviceVector to fill.
Definition at line 558 of file net.cpp.
References leanux::net::NetStat::device, leanux::net::NetStat::rx_bytes, leanux::net::NetStat::rx_compressed, leanux::net::NetStat::rx_dropped, leanux::net::NetStat::rx_errors, leanux::net::NetStat::rx_fifo, leanux::net::NetStat::rx_frame, leanux::net::NetStat::rx_multicast, leanux::net::NetStat::rx_packets, leanux::net::NetStat::tx_bytes, leanux::net::NetStat::tx_carrier, leanux::net::NetStat::tx_collisions, leanux::net::NetStat::tx_compressed, leanux::net::NetStat::tx_dropped, leanux::net::NetStat::tx_errors, leanux::net::NetStat::tx_fifo, and leanux::net::NetStat::tx_packets.
Referenced by leanux::tools::lmon::RealtimeSampler::sampleXNetView().
getServiceName()
std::string leanux::net::getServiceName (int port)
Get the service name, eg 'ssh' for port 22.
Parameters
port the port number of the service
Returns
the service name associated with the port number
Definition at line 412 of file net.cpp.
Referenced by leanux::tools::lrep::chartTCPClientAverage(), leanux::tools::lrep::chartTCPClientTimeLine(), leanux::tools::lrep::chartTCPServerAverage(), and leanux::tools::lrep::chartTCPServerTimeLine().
getSysPath()
std::string leanux::net::getSysPath (const std::string & device)
Get the device sysfs path.
Parameters
device the network device
Returns
the sysfs path
Definition at line 421 of file net.cpp.
References leanux::util::directoryExists(), and leanux::util::realPath().
Referenced by leanux::tools::lard::NetSnap::storeSnap().
getTCPConnectionCounters()
void leanux::net::getTCPConnectionCounters (std::list< TCPKeyCounter > & servers, std::list< TCPKeyCounter > & clients)
Return the number of established TCP connections grouped by (ip,port,uid).
Parameters
servers receives the server (local ip) TCPKeyCounter list.
clients receives the client (remote ip) TCPKeyCounter list.
Definition at line 606 of file net.cpp.
References convertAF_INET(), convertAF_INET6(), enumTCP4Sockets(), enumTCP6Sockets(), TCP_ESTABLISHED, and TCP_LISTEN.
Referenced by leanux::tools::lmon::RealtimeSampler::sampleXNetView(), and leanux::tools::lard::TCPEstaSnap::storeSnap().
getTCPStateString()
std::string leanux::net::getTCPStateString (int tcp_state)
Get human readable name for a tcp state.
Parameters
tcp_state the tcp state.
Returns
a human readable std::string.
Definition at line 322 of file net.cpp.
References TCP_CLOSE, TCP_CLOSE_WAIT, TCP_CLOSING, TCP_ESTABLISHED, TCP_FIN_WAIT1, TCP_FIN_WAIT2, TCP_LAST_ACK, TCP_LISTEN, TCP_SYN_RECV, TCP_SYN_SENT, and TCP_TIME_WAIT.
Referenced by operator<<().
init()
void leanux::net::init ()
initialize net library
Definition at line 60 of file net.cpp.
References leanux::util::fileReadAccess(), and MACOUIDatabase.
Referenced by leanux::init().
operator<()
int leanux::net::operator< (const NetStat & n1, const NetStat & n2) inline
Compare two NetStat structs.
Criterium is bytes send+received, devicename.
Parameters
n1 the first NetStat.
n2 the second NetStat.
Returns
1 if n1 < n2.
Definition at line 355 of file net.hpp.
References leanux::net::NetStat::device, leanux::net::NetStat::rx_bytes, and leanux::net::NetStat::tx_bytes.
operator<<() [1/3]
std::ostream & leanux::net::operator<< (std::ostream & os, const TCP4SocketInfo & inf)
Dump a TCP4Socket to stream.
Definition at line 353 of file net.cpp.
References convertAF_INET(), getTCPStateString(), leanux::system::getUserName(), leanux::net::TCP4SocketInfo::inode, leanux::net::TCP4SocketInfo::local_addr, leanux::net::TCP4SocketInfo::local_port, leanux::net::TCP4SocketInfo::remote_addr, leanux::net::TCP4SocketInfo::remote_port, leanux::net::TCP4SocketInfo::rx_queue, TCP_LISTEN, leanux::net::TCP4SocketInfo::tcp_state, leanux::net::TCP4SocketInfo::tx_queue, and leanux::net::TCP4SocketInfo::uid.
operator<<() [2/3]
std::ostream & leanux::net::operator<< (std::ostream & os, const UDP4SocketInfo & inf)
Dump a UDP4SocketInfo to stream.
Parameters
os the stream to dump to.
inf the UDP4SocketInfo to dump.
Returns
reference to the stream.
Definition at line 506 of file net.cpp.
References convertAF_INET(), getTCPStateString(), leanux::system::getUserName(), leanux::net::UDP4SocketInfo::inode, leanux::net::UDP4SocketInfo::local_addr, leanux::net::UDP4SocketInfo::local_port, leanux::net::UDP4SocketInfo::remote_addr, leanux::net::UDP4SocketInfo::remote_port, leanux::net::UDP4SocketInfo::rx_queue, TCP_LISTEN, leanux::net::UDP4SocketInfo::tcp_state, leanux::net::UDP4SocketInfo::tx_queue, and leanux::net::UDP4SocketInfo::uid.
operator<<() [3/3]
std::ostream & leanux::net::operator<< (std::ostream & os, const UnixDomainSocketInfo & inf)
Dump a UnixDomainSocketInfo to stream.
Definition at line 466 of file net.cpp.
References leanux::net::UnixDomainSocketInfo::inode, leanux::net::UnixDomainSocketInfo::path, leanux::net::UnixDomainSocketInfo::refcount, and leanux::net::UnixDomainSocketInfo::state.
parseTCP4Line()
bool leanux::net::parseTCP4Line (const std::string & s, TCP4SocketInfo & info)
parse a TCP4 std::string from /proc/net/tcp.
Parameters
s the std::string to parse.
info the TCP4SocketInfo to fill.
Returns
false if s cannot be parsed.
Definition at line 237 of file net.cpp.
References leanux::net::TCP4SocketInfo::inode, leanux::net::TCP4SocketInfo::local_addr, leanux::net::TCP4SocketInfo::local_port, leanux::net::TCP4SocketInfo::remote_addr, leanux::net::TCP4SocketInfo::remote_port, leanux::net::TCP4SocketInfo::rx_queue, leanux::net::TCP4SocketInfo::tcp_state, leanux::net::TCP4SocketInfo::tx_queue, and leanux::net::TCP4SocketInfo::uid.
Referenced by enumTCP4Sockets(), and findTCP4SocketByINode().
parseTCP6Line()
bool leanux::net::parseTCP6Line (const std::string & s, TCP6SocketInfo & info)
parse a TCP6 std::string from /proc/net/tcp.
Parameters
s the std::string to parse.
info the TCP6SocketInfo to fill.
Returns
false if s cannot be parsed.
Definition at line 254 of file net.cpp.
References leanux::net::TCP6SocketInfo::inode, leanux::net::TCP6SocketInfo::local_addr, leanux::net::TCP6SocketInfo::local_port, leanux::net::TCP6SocketInfo::remote_addr, leanux::net::TCP6SocketInfo::remote_port, leanux::net::TCP6SocketInfo::rx_queue, leanux::net::TCP6SocketInfo::tcp_state, leanux::net::TCP6SocketInfo::tx_queue, and leanux::net::TCP6SocketInfo::uid.
Referenced by enumTCP6Sockets().
parseUDP4Line()
bool leanux::net::parseUDP4Line (const std::string & s, UDP4SocketInfo & info)
parse a line from /proc/net/udp.
Definition at line 479 of file net.cpp.
References leanux::net::UDP4SocketInfo::inode, leanux::net::UDP4SocketInfo::local_addr, leanux::net::UDP4SocketInfo::local_port, leanux::net::UDP4SocketInfo::remote_addr, leanux::net::UDP4SocketInfo::remote_port, leanux::net::UDP4SocketInfo::rx_queue, leanux::net::UDP4SocketInfo::tcp_state, leanux::net::UDP4SocketInfo::tx_queue, and leanux::net::UDP4SocketInfo::uid.
Referenced by findUDP4SocketByINode().
resolveIP()
std::string leanux::net::resolveIP (const std::string & addr)
Try to resolve an IPv4 or IPv6 address.
If resolving fails, it resturns the input.
Parameters
addr the address to resolve.
Returns
the resolved name for the adddress, or if the resolve failed, addr itself.
Definition at line 384 of file net.cpp.
References whatAF_INET().
Referenced by leanux::tools::lrep::resolveCacheIP().
whatAF_INET()
int leanux::net::whatAF_INET (const std::string & addr)
Determine the type of IP address.
If addr is not a valid address, an Oops is thrown.
Parameters
addr the IP address to inspect.
Returns
AF_INET or AF_INET6.
Definition at line 373 of file net.cpp.
Referenced by resolveIP().
Variable Documentation
MACOUIDatabase
std::string leanux::net::MACOUIDatabase = "/usr/share/misc/oui.txt"
Definition at line 58 of file net.cpp.
Referenced by getMACOUI(), and init().