leanux: leanux::util::Tracer Class Reference
leanux::util::Tracer Class Reference
Simple singleton tracing class.
#include <util.hpp>
Public Member Functions
~Tracer ()
Destructor.
Static Public Member Functions
static Tracer * getTracer ()
Return the singleton.
static Tracer * setTracer (const std::string &filename)
Initialize the singleton.
static void Trace (const std::string &s)
Dump the contents of the stringstream.
static void Trace (const std::stringstream &s)
Dump the contents of the stringstream.
Private Member Functions
Tracer (const std::string &filename)
Setup the Tracer.
Private Attributes
std::ofstream * of_
The tracing file stream.
Static Private Attributes
static Tracer * tracer_ = 0
The singleton Tracer object.
Detailed Description
Simple singleton tracing class.
Definition at line 206 of file util.hpp.
Constructor & Destructor Documentation
~Tracer()
leanux::util::Tracer::~Tracer () inline
Destructor.
Definition at line 212 of file util.hpp.
References of_.
Tracer()
leanux::util::Tracer::Tracer (const std::string & filename) private
Setup the Tracer.
Constructor is private as the singleton should be realized with Tracer::setTracer and accessed with Tracer::getTracer.
Parameters
filename file to trace to.
See also
Tracer::setTracer, Tracer::getTracer
Definition at line 400 of file util.cpp.
References of_.
Referenced by setTracer().
Member Function Documentation
getTracer()
static Tracer* leanux::util::Tracer::getTracer () inline static
Return the singleton.
Definition at line 229 of file util.hpp.
References tracer_.
setTracer()
Tracer * leanux::util::Tracer::setTracer (const std::string & filename) static
Initialize the singleton.
Parameters
filename the file to trace to.
Returns
the Tracer singleton.
See also
Tracer::Tracer
Definition at line 419 of file util.cpp.
References Tracer(), and tracer_.
Referenced by leanux::tools::lmon::main().
Trace() [1/2]
void leanux::util::Tracer::Trace (const std::string & s) static
Dump the contents of the stringstream.
Parameters
s the string to dump.
Definition at line 408 of file util.cpp.
References of_, and tracer_.
Trace() [2/2]
void leanux::util::Tracer::Trace (const std::stringstream & s) static
Dump the contents of the stringstream.
Parameters
s the stringstream to dump.
Definition at line 404 of file util.cpp.
Field Documentation
of_
std::ofstream* leanux::util::Tracer::of_ private
The tracing file stream.
Definition at line 253 of file util.hpp.
Referenced by Trace(), Tracer(), and ~Tracer().
tracer_
Tracer * leanux::util::Tracer::tracer_ = 0 static private
The singleton Tracer object.
Definition at line 258 of file util.hpp.
Referenced by getTracer(), setTracer(), and Trace().
The documentation for this class was generated from the following files:
lib/util.hpp
lib/util.cpp