leanux: leanux::cpu Namespace Reference
leanux::cpu Namespace Reference
CPU configuration and performance API.
Data Structures
struct CoreId
Utility struct to aid in identifying unique cores.
struct CPUInfo
CPU information.
struct CPUStat
CPU usage statistics from /proc/stat.
struct CPUTopology
CPU topology.
struct LoadAvg
System load average - the average number of processes on the run queue.
struct SchedInfo
CPU scheduler info.
Typedefs
typedef std::map< unsigned int, CPUStat > CPUStatsMap
Map of processor id to CPUStat.
Functions
bool deltaStats (const CPUStatsMap &earlier, const CPUStatsMap &later, CPUStatsMap &delta)
Compute the deltas for two CPUStatMap std::maps into delta.
unsigned long getCPUCoreId (unsigned long logicalcpu)
get the core id of the logical CPU from /sys/devices/system/cpu/cpuX/core_id.
bool getCPUInfo (CPUInfo &info)
Get CPU info.
unsigned long getCPUPhysicalId (unsigned long logicalcpu)
get the physical id of the logical CPU from /sys/devices/system/cpu/cpuX/physical_package_id.
void getCPUStats (CPUStatsMap &stats)
Get CPU usage statistics from /proc/stat.
void getCPUTopology (CPUTopology &topology)
get the CPU topology.
void getCPUTotal (const CPUStatsMap &all, CPUStat &total)
Sum the entries in all to derive the total.
double getCPUUsageTotal (const CPUStat &stat)
Compute the total amount of CPU time in stat.
void getLoadAvg (LoadAvg &avg)
Get the system load averages.
SchedInfo getSchedInfo ()
Get the number of running and blocked processes.
void normalizeCPUstats (CPUStat &stat, double dt, unsigned int processors)
Scales the numbers in stat to the time interval dt times the number of processors, which is equivalent to the maximum amount of CPU time that can be consumed in interval dt.
std::ostream & operator<< (std::ostream &os, CPUInfo &info)
Dump info to a stream.
Detailed Description
CPU configuration and performance API.
Data Structure Documentation
leanux::cpu::CPUInfo
struct leanux::cpu::CPUInfo
CPU information.
As the information in /proc/cpuinfo varies wildy between architectures, the CPUInfo is limited to these common attributes.
Examples
example_cpu.cpp.
Definition at line 97 of file cpu.hpp.
Data Fields
double bogomips the bogomips value for the CPU (bogomips is a bogus value, not usable to compare processor speeds)
double cpu_mhz the (current) clock speed of the CPU
string model a descriptive std::string for the CPU model.
leanux::cpu::CPUStat
struct leanux::cpu::CPUStat
CPU usage statistics from /proc/stat.
value are in seconds, leanux::system::getUserHz is silently applied.
Examples
example_process2.cpp.
Definition at line 122 of file cpu.hpp.
Data Fields
double guest guest mode CPU
double guest_nice guest nice mode CPU
double idle idle mode CPU
double iowait iowait mode CPU
double irq irq mode CPU
double nice nice mode CPU
double softirq softirq mode CPU
double steal steal mode CPU
double system system mode CPU
double user user mode CPU
leanux::cpu::CPUTopology
struct leanux::cpu::CPUTopology
CPU topology.
Examples
example_cpu.cpp, and example_process2.cpp.
Definition at line 58 of file cpu.hpp.
Data Fields
unsigned int cores number of CPU cores
unsigned int logical number of logical CPUs
unsigned int physical number of physical CPU's aka CPU sockets aka CPU packages.
leanux::cpu::LoadAvg
struct leanux::cpu::LoadAvg
System load average - the average number of processes on the run queue.
Examples
example_cpu.cpp.
Definition at line 172 of file cpu.hpp.
Data Fields
double avg10_ 10 minute load average
double avg15_ 15 minute load average
double avg5_ 5 minute load average
leanux::cpu::SchedInfo
struct leanux::cpu::SchedInfo
CPU scheduler info.
See also
getRunQueue
Examples
example_cpu.cpp.
Definition at line 190 of file cpu.hpp.
Data Fields
unsigned int blocked the number of blocked processes (processes in state D).
unsigned long ctxt the total number of context switches since boot.
unsigned long processes the total number of processes created since boot.
unsigned int running the number of running processes (processes in state R).
Typedef Documentation
CPUStatsMap
typedef std::map<unsigned int,CPUStat> leanux::cpu::CPUStatsMap
Map of processor id to CPUStat.
Definition at line 148 of file cpu.hpp.
Function Documentation
deltaStats()
bool leanux::cpu::deltaStats (const CPUStatsMap & earlier, const CPUStatsMap & later, CPUStatsMap & delta)
Compute the deltas for two CPUStatMap std::maps into delta.
There are conditions that could lead to an invalid delta
(at least) one of the numbers overflows.
the number of CPUs is changed between the stats asked to delta. In both cases, the function returns false indicating the results are invalid.
Parameters
earlier the earlier set of stats.
later the later set of stats.
delta the std::map that will hold the resulting delta.
Returns
false when a delta would show incorrect data
Examples
example_cpu.cpp, and example_process2.cpp.
Definition at line 229 of file cpu.cpp.
Referenced by leanux::tools::lmon::RealtimeSampler::sampleXSysView().
getCPUCoreId()
unsigned long leanux::cpu::getCPUCoreId (unsigned long logicalcpu)
get the core id of the logical CPU from /sys/devices/system/cpu/cpuX/core_id.
Parameters
logicalcpu the logical CPU number (starting from zero).
Returns
the core id (starting from zero).
Definition at line 114 of file cpu.cpp.
References leanux::util::fileReadUL(), and leanux::sysdevice::sysdevice_root.
Referenced by leanux::tools::lard::CPUSnap::storeSnap().
getCPUInfo()
bool leanux::cpu::getCPUInfo (CPUInfo & info)
Get CPU info.
Parameters
info the CPUInfo to fill.
Returns
false when the cpu is not found.
Examples
example_cpu.cpp.
Definition at line 120 of file cpu.cpp.
References leanux::cpu::CPUInfo::bogomips, leanux::cpu::CPUInfo::cpu_mhz, and leanux::cpu::CPUInfo::model.
Referenced by leanux::tools::lmon::Footer::Footer(), leanux::tools::lrep::htmlSystemDetails(), and leanux::tools::lmon::RealtimeSampler::RealtimeSampler().
getCPUPhysicalId()
unsigned long leanux::cpu::getCPUPhysicalId (unsigned long logicalcpu)
get the physical id of the logical CPU from /sys/devices/system/cpu/cpuX/physical_package_id.
Parameters
logicalcpu the logical CPU number (starting from zero).
Returns
the physical id (starting from zero).
Definition at line 108 of file cpu.cpp.
References leanux::util::fileReadUL(), and leanux::sysdevice::sysdevice_root.
Referenced by leanux::tools::lard::CPUSnap::storeSnap().
getCPUStats()
void leanux::cpu::getCPUStats (CPUStatsMap & stats)
Get CPU usage statistics from /proc/stat.
Parameters
stats std::map filled, keyed by CPU number, starts with 0.
Examples
example_cpu.cpp, and example_process2.cpp.
Definition at line 157 of file cpu.cpp.
References leanux::system::getUserHz(), leanux::cpu::CPUStat::guest, leanux::cpu::CPUStat::guest_nice, leanux::cpu::CPUStat::idle, leanux::cpu::CPUStat::iowait, leanux::cpu::CPUStat::irq, leanux::cpu::CPUStat::nice, leanux::cpu::CPUStat::softirq, leanux::cpu::CPUStat::steal, leanux::cpu::CPUStat::system, and leanux::cpu::CPUStat::user.
Referenced by leanux::tools::lmon::RealtimeSampler::sampleXSysView(), leanux::tools::lard::CPUSnap::startSnap(), and leanux::tools::lard::CPUSnap::stopSnap().
getCPUTopology()
void leanux::cpu::getCPUTopology (CPUTopology & topology)
get the CPU topology.
Should work on diffrent architectures as it does not rely on architecture dependent /proc/cpuinfo but inspects /sys/devices/cpu/cpu?/topology instead.
Exceptions
Oops when directory tree /sys/devices/system/cpu cannot be interpreted as expected.
Parameters
topology the CPUTopology to fill.
Examples
example_cpu.cpp, and example_process2.cpp.
Definition at line 75 of file cpu.cpp.
References leanux::cpu::CoreId::core_id, leanux::cpu::CPUTopology::cores, leanux::util::fileReadUL(), leanux::cpu::CPUTopology::logical, leanux::cpu::CoreId::phy_id, leanux::cpu::CPUTopology::physical, and leanux::sysdevice::sysdevice_root.
Referenced by leanux::tools::lrep::htmlSystemDetails(), and leanux::tools::lmon::RealtimeSampler::sampleXSysView().
getCPUTotal()
void leanux::cpu::getCPUTotal (const CPUStatsMap & all, CPUStat & total)
Sum the entries in all to derive the total.
Examples
example_process2.cpp.
Definition at line 293 of file cpu.cpp.
References leanux::cpu::CPUStat::guest, leanux::cpu::CPUStat::guest_nice, leanux::cpu::CPUStat::idle, leanux::cpu::CPUStat::iowait, leanux::cpu::CPUStat::irq, leanux::cpu::CPUStat::nice, leanux::cpu::CPUStat::softirq, leanux::cpu::CPUStat::steal, leanux::cpu::CPUStat::system, and leanux::cpu::CPUStat::user.
Referenced by leanux::tools::lmon::LardHistory::fetchXSysView(), and leanux::tools::lmon::RealtimeSampler::sampleXSysView().
getCPUUsageTotal()
double leanux::cpu::getCPUUsageTotal (const CPUStat & stat) inline
Compute the total amount of CPU time in stat.
Parameters
stat the CPUStat to compute over.
Returns
the total amount of cputime in stat.
Definition at line 226 of file cpu.hpp.
References leanux::cpu::CPUStat::iowait, leanux::cpu::CPUStat::irq, leanux::cpu::CPUStat::nice, leanux::cpu::CPUStat::softirq, leanux::cpu::CPUStat::system, and leanux::cpu::CPUStat::user.
Referenced by leanux::tools::lmon::LardHistory::fetchXSysView(), and leanux::tools::lmon::makeCPUBar().
getLoadAvg()
void leanux::cpu::getLoadAvg (LoadAvg & avg)
Get the system load averages.
Examples
example_cpu.cpp.
Definition at line 265 of file cpu.cpp.
References leanux::cpu::LoadAvg::avg10_, leanux::cpu::LoadAvg::avg15_, and leanux::cpu::LoadAvg::avg5_.
Referenced by leanux::tools::lmon::RealtimeSampler::sampleXSysView(), leanux::tools::lard::SchedSnap::startSnap(), and leanux::tools::lard::SchedSnap::stopSnap().
getSchedInfo()
SchedInfo leanux::cpu::getSchedInfo ()
Get the number of running and blocked processes.
Examples
example_cpu.cpp.
Definition at line 275 of file cpu.cpp.
References leanux::cpu::SchedInfo::blocked, leanux::cpu::SchedInfo::ctxt, leanux::cpu::SchedInfo::processes, and leanux::cpu::SchedInfo::running.
Referenced by leanux::tools::lmon::RealtimeSampler::sampleXSysView(), leanux::tools::lard::SchedSnap::startSnap(), and leanux::tools::lard::SchedSnap::stopSnap().
normalizeCPUstats()
void leanux::cpu::normalizeCPUstats (CPUStat & stat, double dt, unsigned int processors)
Scales the numbers in stat to the time interval dt times the number of processors, which is equivalent to the maximum amount of CPU time that can be consumed in interval dt.
Parameters
stat the CPUStat to scale.
dt the time interval to scale to.
processors the number of processors to scale to.
Definition at line 318 of file cpu.cpp.
References leanux::cpu::CPUStat::guest, leanux::cpu::CPUStat::guest_nice, leanux::cpu::CPUStat::idle, leanux::cpu::CPUStat::iowait, leanux::cpu::CPUStat::irq, leanux::cpu::CPUStat::nice, leanux::cpu::CPUStat::softirq, leanux::cpu::CPUStat::steal, leanux::cpu::CPUStat::system, and leanux::cpu::CPUStat::user.
Referenced by leanux::tools::lmon::RealtimeSampler::sampleXSysView().
operator<<()
std::ostream & leanux::cpu::operator<< (std::ostream & os, CPUInfo & info)
Dump info to a stream.
Definition at line 257 of file cpu.cpp.
References leanux::cpu::CPUInfo::bogomips, leanux::cpu::CPUInfo::cpu_mhz, and leanux::cpu::CPUInfo::model.