leanux: leanux::sysdevice Namespace Reference
leanux::sysdevice Namespace Reference
system device API.
Data Structures
class ATAPort
Say yes to (S)ATA ports.
class BCacheDevice
Say yes to bcache devices.
class BlockDevice
Generic block device.
class BlockPartition
Generic block device partition.
class BusDevice
Generic bus device.
class iSCSIDevice
Say yes to iSCSI devices.
class LoopbackDevice
Say yes to loopback devices.
class MapperDevice
Say yes to devicemapper devices.
class MDDevice
Say yes to metadisk devices.
class MMCDevice
Say yes to MMC devices.
class NetDevice
Generic networking device.
class NVMeDevice
Say yes to NVMe devices.
class NVMePartition
Say yes to partitions on NVMe devices.
class PCIBus
Say yes to PCI busses.
class PCIDevice
Say yes to PCI devices.
class PropertyValue
class RamDiskDevice
Say yes to ramdisk devices.
class SASEndDevice
Say yes to SAS end devices.
class SASPort
Say yes to SAS ports.
class SCSIDevice
Say yes to SCSI devices.
class SCSIHost
Say yes to SCSI hosts.
class SCSIRPort
Say yes to SCSI rport.
class SCSIVPort
Say yes to SCSI vport.
class SysDevice
Generic SysDevice, utility class for device detection from a SysDevicePath.
class UnknownSysDevice
Always says yes, so last resort, eats entire path.
class USBBus
Say yes to USB busses.
class USBDevice
Say yes to USB devices.
class USBInterface
Say yes to USB configurations (operation mode an USB device).
class VirtioBlockDevice
Say yes to virtio block devices.
class VirtioNetDevice
Say yes to virtio net devices.
class VirtualBlockRoot
Virtual block root.
class VirtualNetDevice
Virtual networking device.
class VirtualNetRoot
Virtual net root.
class VirtualRoot
Virtual root.
Typedefs
typedef std::list< PropertyValue > PropertyValueList
typedef std::string SysDevicePath
A string representing an absolute path on the sysfs filesystem.
Functions
void destroy (std::list< SysDevice * > &devices)
Destroy list of SysDevice* as returned by treeDetect.
void enumATADevices (std::list< SysDevicePath > &paths)
Enumerate all (S)ATA devices.
void enumBlockDevices (std::list< SysDevicePath > &paths)
Enumerate all block devices.
void enumDevices (std::list< SysDevicePath > &paths)
Enumerate all devices.
void enumNetDevices (std::list< SysDevicePath > &paths)
Enumerate all network devices.
void enumPCIBusses (std::list< SysDevicePath > &paths)
Enumerate all PCI bus devices.
void enumPCIDevices (std::list< SysDevicePath > &paths)
Enumerate all PCI devices.
void enumSCSIHostDevices (std::list< SysDevicePath > &paths)
Enumerate all SCSI host devices.
void enumUSBDevices (std::list< SysDevicePath > &paths)
Enumerate all USB devices.
SysDevice * leafDetect (const SysDevicePath &path, SysDevicePath &parent)
Return the leaf SysDevice detected in path.
bool treeDetect (const SysDevicePath &path, std::list< SysDevice * > &devices)
populates devices with the devices detected in path.
Variables
const SysDevicePath sysbus_root = "/sys/bus"
const for '/sys/bus'
const SysDevicePath sysdevice_root = "/sys/devices"
const for '/sys/devices'
Detailed Description
system device API.
Use the enum* functions to enumerate SysDevicePath device files on sysfs.
The leafDetect(const SysDevicePath& path, SysDevicePath &parent) function detects devices, returned as a concrete descendant of SysDevice, with the parent device returned as well.
The treeDetect(const SysDevicePath& path, std::list<SysDevice*> &devices) function detects entire system device trees, from the device in path and upwards.
Note that the caller is responsiable to delete objects returned by leafDetect and treeDetect.
See also
SysDevice::SysDeviceType for supported types.
Typedef Documentation
PropertyValueList
typedef std::list<PropertyValue> leanux::sysdevice::PropertyValueList
Definition at line 95 of file device.hpp.
SysDevicePath
typedef std::string leanux::sysdevice::SysDevicePath
A string representing an absolute path on the sysfs filesystem.
Definition at line 70 of file device.hpp.
Function Documentation
destroy()
void leanux::sysdevice::destroy (std::list< SysDevice * > & devices) inline
Destroy list of SysDevice* as returned by treeDetect.
Definition at line 730 of file device.hpp.
Referenced by leanux::tools::lblk::detailDisk(), leanux::tools::lrep::htmlDiskDetails(), and leanux::tools::lsys::sysfsTree().
enumATADevices()
void leanux::sysdevice::enumATADevices (std::list< SysDevicePath > & paths)
Enumerate all (S)ATA devices.
Parameters
paths recevies a list of SysDevicePath paths.
Definition at line 1857 of file device.cpp.
References leanux::util::realPath().
Referenced by enumDevices().
enumBlockDevices()
void leanux::sysdevice::enumBlockDevices (std::list< SysDevicePath > & paths)
Enumerate all block devices.
Parameters
paths recevies a list of SysDevicePath paths.
Definition at line 1782 of file device.cpp.
References leanux::util::realPath().
Referenced by enumDevices().
enumDevices()
void leanux::sysdevice::enumDevices (std::list< SysDevicePath > & paths)
Enumerate all devices.
Parameters
paths recevies a list of SysDevicePath paths.
Definition at line 1755 of file device.cpp.
References enumATADevices(), enumBlockDevices(), enumNetDevices(), enumPCIBusses(), enumPCIDevices(), enumSCSIHostDevices(), and enumUSBDevices().
Referenced by leanux::tools::lsys::runOptions().
enumNetDevices()
void leanux::sysdevice::enumNetDevices (std::list< SysDevicePath > & paths)
Enumerate all network devices.
Parameters
paths recevies a list of SysDevicePath paths.
Definition at line 1797 of file device.cpp.
References leanux::util::realPath().
Referenced by enumDevices().
enumPCIBusses()
void leanux::sysdevice::enumPCIBusses (std::list< SysDevicePath > & paths)
Enumerate all PCI bus devices.
Parameters
paths recevies a list of SysDevicePath paths.
Definition at line 1812 of file device.cpp.
References leanux::util::realPath().
Referenced by enumDevices().
enumPCIDevices()
void leanux::sysdevice::enumPCIDevices (std::list< SysDevicePath > & paths)
Enumerate all PCI devices.
Parameters
paths recevies a list of SysDevicePath paths.
Definition at line 1827 of file device.cpp.
References leanux::util::realPath().
Referenced by enumDevices().
enumSCSIHostDevices()
void leanux::sysdevice::enumSCSIHostDevices (std::list< SysDevicePath > & paths)
Enumerate all SCSI host devices.
Parameters
paths recevies a list of SysDevicePath paths.
Definition at line 1872 of file device.cpp.
References leanux::util::realPath().
Referenced by enumDevices().
enumUSBDevices()
void leanux::sysdevice::enumUSBDevices (std::list< SysDevicePath > & paths)
Enumerate all USB devices.
Parameters
paths recevies a list of SysDevicePath paths.
Definition at line 1842 of file device.cpp.
References leanux::util::realPath().
Referenced by enumDevices().
leafDetect()
SysDevice * leanux::sysdevice::leafDetect (const SysDevicePath & path, SysDevicePath & parent)
Return the leaf SysDevice detected in path.
Parameters
path the path to detect.
parent set to the parent path of the returned device, or empty when detection fails.
Returns
the detected SysDevice or NULL.
Definition at line 1887 of file device.cpp.
References leanux::sysdevice::BlockPartition::accept(), leanux::sysdevice::NetDevice::accept(), leanux::sysdevice::VirtualRoot::accept(), leanux::sysdevice::VirtualBlockRoot::accept(), leanux::sysdevice::VirtualNetRoot::accept(), leanux::sysdevice::VirtualNetDevice::accept(), leanux::sysdevice::UnknownSysDevice::accept(), leanux::sysdevice::SASPort::accept(), leanux::sysdevice::SASEndDevice::accept(), leanux::sysdevice::SCSIDevice::accept(), leanux::sysdevice::SCSIHost::accept(), leanux::sysdevice::SCSIRPort::accept(), leanux::sysdevice::SCSIVPort::accept(), leanux::sysdevice::iSCSIDevice::accept(), leanux::sysdevice::MMCDevice::accept(), leanux::sysdevice::NVMeDevice::accept(), leanux::sysdevice::NVMePartition::accept(), leanux::sysdevice::BCacheDevice::accept(), leanux::sysdevice::ATAPort::accept(), leanux::sysdevice::VirtioBlockDevice::accept(), leanux::sysdevice::VirtioNetDevice::accept(), leanux::sysdevice::MapperDevice::accept(), leanux::sysdevice::LoopbackDevice::accept(), leanux::sysdevice::RamDiskDevice::accept(), leanux::sysdevice::MDDevice::accept(), leanux::sysdevice::PCIDevice::accept(), leanux::sysdevice::PCIBus::accept(), leanux::sysdevice::USBDevice::accept(), leanux::sysdevice::USBInterface::accept(), leanux::sysdevice::USBBus::accept(), and leanux::sysdevice::SysDevice::validatePath().
Referenced by leanux::tools::lsys::listDevices(), and treeDetect().
treeDetect()
bool leanux::sysdevice::treeDetect (const SysDevicePath & path, std::list< SysDevice * > & devices)
populates devices with the devices detected in path.
The first device in the list is the top level device, the last device represents path. The previous device is the current device parent. Note that the caller should delete the objects returned in devices.
Parameters
path the path to detect. this must be a valid sysfs path to a device on the system.
devices list of devices detected in the path.
Returns
false if detection fails.
Definition at line 1963 of file device.cpp.
References leanux::sysdevice::SysDevice::getType(), leafDetect(), leanux::sysdevice::SysDevice::sdtUnknown, sysdevice_root, and leanux::sysdevice::SysDevice::validatePath().
Referenced by leanux::tools::lblk::detailDisk(), leanux::tools::lrep::htmlDiskDetails(), and leanux::tools::lsys::sysfsTree().
Variable Documentation
sysbus_root
const SysDevicePath leanux::sysdevice::sysbus_root = "/sys/bus"
const for '/sys/bus'
Definition at line 58 of file device.cpp.
Referenced by leanux::pci::enumPCIDevicePaths(), and leanux::usb::enumUSBDevices().
sysdevice_root
const SysDevicePath leanux::sysdevice::sysdevice_root = "/sys/devices"
const for '/sys/devices'
Definition at line 57 of file device.cpp.
Referenced by leanux::cpu::getCPUCoreId(), leanux::cpu::getCPUPhysicalId(), leanux::cpu::getCPUTopology(), treeDetect(), and leanux::sysdevice::SysDevice::validatePath().