leanux: leanux::process Namespace Reference
leanux::process Namespace Reference
Process configuration and performance API.
Data Structures
struct ProcPidIO
Process IO details from /proc/pid/io.
struct ProcPidStat
Process details and statistics as in /proc/[pid]/stat.
struct ProcPidStatDelta
Delta of a pid's stats.
class StatsSorter
Functor class for parametrized sorting with std::sort.
Typedefs
typedef std::map< unsigned long, std::string > OpenFileMap
A std::map of open files (file names) keyed by pid_t.
typedef std::vector< ProcPidStatDelta > ProcPidStatDeltaVector
A std::vector of ProcPidStatDelta elements.
typedef std::map< pid_t, ProcPidStat > ProcPidStatMap
Convienence typedef for a std::map keyed by pid_t to ProcPidStat.
Functions
void deltaProcPidStats (const ProcPidStatMap &snap1, const ProcPidStatMap &snap2, ProcPidStatDeltaVector &delta)
Get a delta of two ProcPidStatMap std::maps into the delta std::map.
bool findProcByComm (const std::string &comm, ProcPidStatMap &stats)
return all pids with specified comm (executable image) into stats
bool findProcByUid (uid_t uid, ProcPidStatMap &stats)
return all pids with specified uid.
void getAllDirectChildren (pid_t parent, const ProcPidStatMap &snap, std::list< pid_t > &children)
Get all direct children of a parent pid from a ProcPidStatMap snapshot.
void getAllProcPidStat (ProcPidStatMap &stats)
Get a snapshot of all pids (seen as /proc/PID) into a std::map keyed by pid_t.
void getOpenFiles (pid_t pid, OpenFileMap &files)
Get a process's open files - if the caller has the privilege to see them.
std::string getProcCmdLine (pid_t pid)
Get the pid's command line.
bool getProcPidIO (pid_t pid, ProcPidIO &io)
Get process IO details, root access required.
bool getProcPidStat (pid_t pid, ProcPidStat &stat)
Get the ProcPidStat for the pid.
bool getProcUid (pid_t pid, uid_t &uid)
get the effective uid of a running process.
std::string getWChan (pid_t pid)
get the current kernel channel waited on by the process.
int valueState (char state)
order process states from 'good' to 'bad'.
Detailed Description
Process configuration and performance API.
Data Structure Documentation
leanux::process::ProcPidIO
struct leanux::process::ProcPidIO
Process IO details from /proc/pid/io.
Note that the IO counters encompass all IO, not only to disk, but also pipes and sockets. Root access is required to read /prod/pid/io (one may detect the size of a password of another process by examining this file),
Examples
example_process.cpp.
Definition at line 140 of file process.hpp.
Data Fields
unsigned long cancelled_write_bytes The big inaccuracy here is truncate.
If a process writes 1MB to a file and then deletes the file, it will in fact perform no writeout. But it will have been accounted as having caused 1MB of write. In other words: this field represents the number of bytes which this process caused to not happen, by truncating pagecache. A task can cause "negative" I/O too. If this task truncates some dirty pagecache, some I/O which another task has been accounted for (in its write_bytes) will not be happening.
unsigned long rchar characters read - The number of bytes which this task has caused to be read from storage.
This is simply the sum of bytes which this process passed to read(2) and similar system calls. It includes things such as terminal I/O and is unaffected by whether or not actual physical disk I/O was required (the read might have been satisfied from pagecache).
unsigned long read_bytes bytes read - Attempt to count the number of bytes which this process really did cause to be fetched from the storage layer.
This is accurate for block-backed filesystems.
unsigned long syscr read syscalls - Attempt to count the number of read I/O operations—that is, system calls such as read(2) and pread(2).
unsigned long syscw write syscalls - Attempt to count the number of write I/O operations—that is, system calls such as write(2) and pwrite(2).
unsigned long wchar characters written - The number of bytes which this task has caused, or shall cause to be written to disk.
Similar caveats apply here as with rchar.
unsigned long write_bytes bytes written - Attempt to count the number of bytes which this process caused to be sent to the storage layer.
leanux::process::ProcPidStat
struct leanux::process::ProcPidStat
Process details and statistics as in /proc/[pid]/stat.
Examples
example_process.cpp.
Definition at line 66 of file process.hpp.
Data Fields
unsigned long cmajflt the number of major faults that the process's waited-for children have made.
unsigned long cminflt the number of minor faults that the process's waited-for children have made.
string comm the executable name.
double cstime amount of time that this process's waited-for children have been scheduled in kernel mode, measured in seconds.
double cutime amount of time that this process's waited-for children have been scheduled in user mode, measured in seconds.
double delayacct_blkio_ticks Aggregated block I/O delays, measured in seconds.
unsigned long majflt the number of major faults.
unsigned long minflt the number of minor faults the process has made which have not required loading a memory page from disk.
long nice the nice value
unsigned long num_threads number of threads in this process.
pid_t pgrp the process group id of the process.
pid_t pid the process id.
pid_t ppid the parent process id.
unsigned long priority the negated scheduling priority, minus one; that is, a number in the range -2 to -100.
unsigned int processor processsor the process is on
unsigned long rss resident set size: number of pages the process has in real memory.
multiply by leanux::system::getPageSize to get the number of bytes.
unsigned long rsslim current soft limit in bytes on the rss of the process; see the description of RLIMIT_RSS in getrlimit(2)
pid_t session the session id of the process.
unsigned long long starttime the time the process started after system boot.
char state the current process state.
double stime amount of time that this process has been scheduled in kernel mode, measured in seconds.
pid_t tpgid the id of the foreground process group of the controlling terminal of the process.
int tty_nr the controlling terminal of the process.
double utime amount of time that this process has been scheduled in user mode, measured in seconds.
unsigned long vsize virtual memory size in bytes.
string wchan kernel wait channel (or empty string)
leanux::process::ProcPidStatDelta
struct leanux::process::ProcPidStatDelta
Delta of a pid's stats.
Definition at line 228 of file process.hpp.
Data Fields
string comm
double delayacct_blkio_ticks
unsigned long majflt
unsigned long minflt
pid_t pgrp
pid_t pid
unsigned long rss
char state
double stime
double utime user time delta
unsigned long vsize
string wchan
Typedef Documentation
OpenFileMap
typedef std::map<unsigned long,std::string> leanux::process::OpenFileMap
A std::map of open files (file names) keyed by pid_t.
Definition at line 215 of file process.hpp.
ProcPidStatDeltaVector
typedef std::vector<ProcPidStatDelta> leanux::process::ProcPidStatDeltaVector
A std::vector of ProcPidStatDelta elements.
Definition at line 247 of file process.hpp.
ProcPidStatMap
typedef std::map<pid_t, ProcPidStat> leanux::process::ProcPidStatMap
Convienence typedef for a std::map keyed by pid_t to ProcPidStat.
Definition at line 195 of file process.hpp.
Function Documentation
deltaProcPidStats()
void leanux::process::deltaProcPidStats (const ProcPidStatMap & snap1, const ProcPidStatMap & snap2, ProcPidStatDeltaVector & delta)
Get a delta of two ProcPidStatMap std::maps into the delta std::map.
Parameters
snap1 first snapshot.
snap2 second snapshot.
delta resulting delta.
Examples
example_process2.cpp.
Definition at line 244 of file process.cpp.
References leanux::process::ProcPidStatDelta::comm, leanux::process::ProcPidStatDelta::delayacct_blkio_ticks, leanux::process::ProcPidStatDelta::majflt, leanux::process::ProcPidStatDelta::minflt, leanux::process::ProcPidStatDelta::pgrp, leanux::process::ProcPidStatDelta::pid, leanux::process::ProcPidStatDelta::rss, leanux::process::ProcPidStatDelta::state, leanux::process::ProcPidStatDelta::stime, leanux::process::ProcPidStatDelta::utime, leanux::process::ProcPidStatDelta::vsize, and leanux::process::ProcPidStatDelta::wchan.
Referenced by leanux::tools::lmon::RealtimeSampler::sampleXProcView(), and leanux::tools::lard::ProcSnap::storeSnap().
findProcByComm()
bool leanux::process::findProcByComm (const std::string & comm, ProcPidStatMap & stats)
return all pids with specified comm (executable image) into stats
Parameters
comm the command (executable image) to filter on.
stats the ProcPidStatMap to fill.
Returns
true when at least one pid is returned (aka stats.size()>0).
Definition at line 322 of file process.cpp.
References getAllProcPidStat().
findProcByUid()
bool leanux::process::findProcByUid (uid_t uid, ProcPidStatMap & stats)
return all pids with specified uid.
Parameters
uid the uid to filter on.
stats the ProcPidStatMap to fill.
Returns
true when at least one pid is returned (aka stats.size()>0).
Definition at line 354 of file process.cpp.
References getAllProcPidStat(), and getProcUid().
getAllDirectChildren()
void leanux::process::getAllDirectChildren (pid_t parent, const ProcPidStatMap & snap, std::list< pid_t > & children)
Get all direct children of a parent pid from a ProcPidStatMap snapshot.
Examples
example_process.cpp.
Definition at line 212 of file process.cpp.
getAllProcPidStat()
void leanux::process::getAllProcPidStat (ProcPidStatMap & stats)
Get a snapshot of all pids (seen as /proc/PID) into a std::map keyed by pid_t.
Note that the snapshot is not 'consistent', the ProcPidStat info is filled sequentially over a lttle amount of time - an amount that depends on the number of processes. Also note that this call scales O(n), n being the number of processes on the system.
Parameters
stats the ProcPidStatMap to fill.
Examples
example_process.cpp, and example_process2.cpp.
Definition at line 173 of file process.cpp.
References getProcPidStat().
Referenced by findProcByComm(), findProcByUid(), leanux::tools::lmon::RealtimeSampler::sampleXProcView(), leanux::tools::lard::ProcSnap::startSnap(), and leanux::tools::lard::ProcSnap::stopSnap().
getOpenFiles()
void leanux::process::getOpenFiles (pid_t pid, OpenFileMap & files)
Get a process's open files - if the caller has the privilege to see them.
Parameters
pid the process id for which to get the open files.
files the OpenFileMap of the pid's open files.
root access required:
only root can see the open files of any process, other users can only see open files of their own processes.
Examples
example_process.cpp.
Definition at line 219 of file process.cpp.
getProcCmdLine()
std::string leanux::process::getProcCmdLine (pid_t pid)
Get the pid's command line.
Examples
example_process.cpp.
Definition at line 157 of file process.cpp.
Referenced by leanux::tools::lmon::RealtimeSampler::sampleXProcView(), and leanux::tools::lard::ProcSnap::storeSnap().
getProcPidIO()
bool leanux::process::getProcPidIO (pid_t pid, ProcPidIO & io)
Get process IO details, root access required.
Parameters
pid the process id.
io the ProcPidIO struct to fill.
Returns
false if the operation failed (no permission, pid does not exist).
root access required:
root access is required even for processes the caller owns (as the information in this file might be used to deduce the size of an entered password).
Examples
example_process.cpp.
Definition at line 136 of file process.cpp.
References leanux::process::ProcPidIO::cancelled_write_bytes, leanux::process::ProcPidIO::rchar, leanux::process::ProcPidIO::read_bytes, leanux::process::ProcPidIO::syscr, leanux::process::ProcPidIO::syscw, leanux::process::ProcPidIO::wchar, and leanux::process::ProcPidIO::write_bytes.
getProcPidStat()
bool leanux::process::getProcPidStat (pid_t pid, ProcPidStat & stat)
Get the ProcPidStat for the pid.
Parameters
pid the process id to get the stats for.
stat the ProcPidStat struct in which to set the results.
Returns
false if the pid is not found.
Examples
example_process.cpp.
Definition at line 58 of file process.cpp.
References leanux::process::ProcPidStat::cmajflt, leanux::process::ProcPidStat::cminflt, leanux::process::ProcPidStat::comm, leanux::process::ProcPidStat::cstime, leanux::process::ProcPidStat::cutime, leanux::process::ProcPidStat::delayacct_blkio_ticks, leanux::system::getUserHz(), getWChan(), leanux::process::ProcPidStat::majflt, leanux::process::ProcPidStat::minflt, leanux::process::ProcPidStat::nice, leanux::process::ProcPidStat::num_threads, leanux::process::ProcPidStat::pgrp, leanux::process::ProcPidStat::pid, leanux::process::ProcPidStat::ppid, leanux::process::ProcPidStat::priority, leanux::process::ProcPidStat::processor, leanux::process::ProcPidStat::rss, leanux::process::ProcPidStat::rsslim, leanux::process::ProcPidStat::session, leanux::process::ProcPidStat::starttime, leanux::process::ProcPidStat::state, leanux::process::ProcPidStat::stime, leanux::process::ProcPidStat::tpgid, leanux::process::ProcPidStat::tty_nr, leanux::process::ProcPidStat::utime, leanux::process::ProcPidStat::vsize, and leanux::process::ProcPidStat::wchan.
Referenced by leanux::tools::lard::ensureSinglePid(), and getAllProcPidStat().
getProcUid()
bool leanux::process::getProcUid (pid_t pid, uid_t & uid)
get the effective uid of a running process.
Parameters
pid the pid to get the uid for.
uid is set to the uid of the pid if returning true.
Returns
true if pid was found and uid detrmined.
Definition at line 336 of file process.cpp.
Referenced by findProcByUid(), leanux::tools::lmon::RealtimeSampler::sampleXProcView(), and leanux::tools::lard::ProcSnap::storeSnap().
getWChan()
std::string leanux::process::getWChan (pid_t pid)
get the current kernel channel waited on by the process.
the value "0" means the process is not waiting.
Parameters
pid the process to return the wchan for.
Returns
the wchan for the pid, or an empty std::string if the pid does not exist.
Examples
example_process.cpp, and example_process2.cpp.
Definition at line 123 of file process.cpp.
References leanux::util::fileReadString().
Referenced by getProcPidStat().
valueState()
int leanux::process::valueState (char state)
order process states from 'good' to 'bad'.
Definition at line 283 of file process.cpp.