leanux: leanux::tools::lmon::Palette Class Reference
leanux::tools::lmon::Palette Class Reference
The Palette provides reasonable colors within terminal capabilities, hiding the details of such capabilities behind standardized calls.
#include <lmon_curses.hpp>
Public Member Functions
Palette ()
Constructor.
int getColorBlockedProc () const
get blocked process color.
int getColorBoldText () const
get bold text color.
int getColorIOWaitCPU () const
get iowait color.
int getColorIRQCPU () const
get irq color.
int getColorLine () const
get normal text color.
int getColorNiceCPU () const
get nice cpu color.
int getColorRunningProc () const
get running process color.
int getColorSoftIRQCPU () const
get softirq color.
int getColorSystemCPU () const
get system cpu color.
int getColorText () const
get normal text color.
int getColorUserCPU () const
get user cpu color.
void setup ()
setup the Palette.
Private Attributes
int idx_color_blocked_proc_
palette index entry for blocked processes.
int idx_color_bold_text_
palette index entry for bold text.
int idx_color_line_
palette index entry for horizontal and vertical lines.
int idx_color_running_proc_
palette index entry for running processes.
int idx_color_text_
palette index entry for normal text.
int idx_iowait_mode_cpu_
palette index entry for iowait mode CPU.
int idx_irq_mode_cpu_
palette index entry for irq mode CPU.
int idx_nice_mode_cpu_
palette index entry for nice mode CPU.
int idx_softirq_mode_cpu_
palette index entry for sortirq mode CPU.
int idx_system_mode_cpu_
palette index entry for system mode CPU.
int idx_user_mode_cpu_
palette index entry for user mode CPU.
Detailed Description
The Palette provides reasonable colors within terminal capabilities, hiding the details of such capabilities behind standardized calls.
Definition at line 642 of file lmon_curses.hpp.
Constructor & Destructor Documentation
Palette()
leanux::tools::lmon::Palette::Palette ()
Constructor.
Definition at line 80 of file lmon_curses.cpp.
Member Function Documentation
getColorBlockedProc()
int leanux::tools::lmon::Palette::getColorBlockedProc () const inline
get blocked process color.
Returns
blocked process color.
Definition at line 683 of file lmon_curses.hpp.
References idx_color_blocked_proc_.
Referenced by leanux::tools::lmon::Footer::Footer(), leanux::tools::lmon::View::View(), leanux::tools::lmon::IOView::xrefresh(), and leanux::tools::lmon::ProcessView::xrefresh().
getColorBoldText()
int leanux::tools::lmon::Palette::getColorBoldText () const inline
get bold text color.
Returns
normal text color.
Definition at line 665 of file lmon_curses.hpp.
References idx_color_bold_text_.
Referenced by leanux::tools::lmon::View::View().
getColorIOWaitCPU()
int leanux::tools::lmon::Palette::getColorIOWaitCPU () const inline
get iowait color.
Returns
iowait color.
Definition at line 707 of file lmon_curses.hpp.
References idx_iowait_mode_cpu_.
Referenced by leanux::tools::lmon::SysView::attrFromCPUChar().
getColorIRQCPU()
int leanux::tools::lmon::Palette::getColorIRQCPU () const inline
get irq color.
Returns
irq color.
Definition at line 713 of file lmon_curses.hpp.
References idx_irq_mode_cpu_.
Referenced by leanux::tools::lmon::SysView::attrFromCPUChar().
getColorLine()
int leanux::tools::lmon::Palette::getColorLine () const inline
get normal text color.
Returns
normal text color.
Definition at line 671 of file lmon_curses.hpp.
References idx_color_line_.
Referenced by leanux::tools::lmon::View::View().
getColorNiceCPU()
int leanux::tools::lmon::Palette::getColorNiceCPU () const inline
get nice cpu color.
Returns
nice cpu color.
Definition at line 701 of file lmon_curses.hpp.
References idx_nice_mode_cpu_.
Referenced by leanux::tools::lmon::SysView::attrFromCPUChar(), and leanux::tools::lmon::Footer::Footer().
getColorRunningProc()
int leanux::tools::lmon::Palette::getColorRunningProc () const inline
get running process color.
Returns
runinng process color.
Definition at line 677 of file lmon_curses.hpp.
References idx_color_running_proc_.
Referenced by leanux::tools::lmon::View::View(), and leanux::tools::lmon::ProcessView::xrefresh().
getColorSoftIRQCPU()
int leanux::tools::lmon::Palette::getColorSoftIRQCPU () const inline
get softirq color.
Returns
softirq color.
Definition at line 719 of file lmon_curses.hpp.
Referenced by leanux::tools::lmon::SysView::attrFromCPUChar().
getColorSystemCPU()
int leanux::tools::lmon::Palette::getColorSystemCPU () const inline
get system cpu color.
Returns
system cpu color.
Definition at line 689 of file lmon_curses.hpp.
References idx_system_mode_cpu_.
Referenced by leanux::tools::lmon::SysView::attrFromCPUChar(), and leanux::tools::lmon::Footer::Footer().
getColorText()
int leanux::tools::lmon::Palette::getColorText () const inline
get normal text color.
Returns
normal text color.
Definition at line 659 of file lmon_curses.hpp.
References idx_color_text_.
Referenced by leanux::tools::lmon::SysView::attrFromCPUChar(), and leanux::tools::lmon::View::View().
getColorUserCPU()
int leanux::tools::lmon::Palette::getColorUserCPU () const inline
get user cpu color.
Returns
user cpu color.
Definition at line 695 of file lmon_curses.hpp.
References idx_user_mode_cpu_.
Referenced by leanux::tools::lmon::SysView::attrFromCPUChar().
setup()
void leanux::tools::lmon::Palette::setup ()
setup the Palette.
Definition at line 83 of file lmon_curses.cpp.
References leanux::util::ConfigFile::RGB::blue, leanux::util::ConfigFile::getConfig(), leanux::util::ConfigFile::getRGBValue(), leanux::util::ConfigFile::RGB::green, idx_color_blocked_proc_, idx_color_bold_text_, idx_color_line_, idx_color_running_proc_, idx_color_text_, idx_iowait_mode_cpu_, idx_irq_mode_cpu_, idx_nice_mode_cpu_, idx_softirq_mode_cpu_, idx_system_mode_cpu_, idx_user_mode_cpu_, leanux::util::ConfigFile::RGB::red, and TRACE.
Referenced by leanux::tools::lmon::Screen::initTerminal().
Field Documentation
idx_color_blocked_proc_
int leanux::tools::lmon::Palette::idx_color_blocked_proc_ private
palette index entry for blocked processes.
Definition at line 730 of file lmon_curses.hpp.
Referenced by getColorBlockedProc(), and setup().
idx_color_bold_text_
int leanux::tools::lmon::Palette::idx_color_bold_text_ private
palette index entry for bold text.
Definition at line 724 of file lmon_curses.hpp.
Referenced by getColorBoldText(), and setup().
idx_color_line_
int leanux::tools::lmon::Palette::idx_color_line_ private
palette index entry for horizontal and vertical lines.
Definition at line 726 of file lmon_curses.hpp.
Referenced by getColorLine(), and setup().
idx_color_running_proc_
int leanux::tools::lmon::Palette::idx_color_running_proc_ private
palette index entry for running processes.
Definition at line 728 of file lmon_curses.hpp.
Referenced by getColorRunningProc(), and setup().
idx_color_text_
int leanux::tools::lmon::Palette::idx_color_text_ private
palette index entry for normal text.
Definition at line 719 of file lmon_curses.hpp.
Referenced by getColorText(), and setup().
idx_iowait_mode_cpu_
int leanux::tools::lmon::Palette::idx_iowait_mode_cpu_ private
palette index entry for iowait mode CPU.
Definition at line 738 of file lmon_curses.hpp.
Referenced by getColorIOWaitCPU(), and setup().
idx_irq_mode_cpu_
int leanux::tools::lmon::Palette::idx_irq_mode_cpu_ private
palette index entry for irq mode CPU.
Definition at line 740 of file lmon_curses.hpp.
Referenced by getColorIRQCPU(), and setup().
idx_nice_mode_cpu_
int leanux::tools::lmon::Palette::idx_nice_mode_cpu_ private
palette index entry for nice mode CPU.
Definition at line 736 of file lmon_curses.hpp.
Referenced by getColorNiceCPU(), and setup().
idx_softirq_mode_cpu_
int leanux::tools::lmon::Palette::idx_softirq_mode_cpu_ private
palette index entry for sortirq mode CPU.
Definition at line 742 of file lmon_curses.hpp.
Referenced by setup().
idx_system_mode_cpu_
int leanux::tools::lmon::Palette::idx_system_mode_cpu_ private
palette index entry for system mode CPU.
Definition at line 732 of file lmon_curses.hpp.
Referenced by getColorSystemCPU(), and setup().
idx_user_mode_cpu_
int leanux::tools::lmon::Palette::idx_user_mode_cpu_ private
palette index entry for user mode CPU.
Definition at line 734 of file lmon_curses.hpp.
Referenced by getColorUserCPU(), and setup().
The documentation for this class was generated from the following files:
tools/lmon/lmon_curses.hpp
tools/lmon/lmon_curses.cpp