leanux: leanux::tools::lmon Namespace Reference
leanux::tools::lmon Namespace Reference
Data Structures
class CPUBarDigit
Utility class for SysView::makeCPUBar.
class Footer
The lmon Footer is a View shown at the bottom.
class Header
The lmon Header is a View shown at the top.
class IOView
IO view.
class LardHistory
class NetView
View of top network devices.
class Palette
The Palette provides reasonable colors within terminal capabilities, hiding the details of such capabilities behind standardized calls.
class ProcessView
View of top processes.
class RealtimeSampler
Provides data by real time sampling.
class Screen
The curses screen.
struct Signal
struct SnapRange
class SysView
System view.
class Trigger
class TriggerBase
struct TriggerContext
class TriggerDirtyFilePages
If dirty file pages are over limit.
class TriggerSet
class View
A reactangular area on the ncurses Screen as a window of information.
struct XIORec
I/O statistics in a form suitable for XIOView.
struct XIOView
Data record for IOView display.
struct XNetView
Data record for NetView display.
struct XProcView
struct XSysView
Data record for SysView display.
Typedefs
typedef std::map< std::string, XIORec > IORecMap
typedef std::list< Signal > SignalList
Functions
int main (int argc, char *argv[])
std::string makeCPUBar (const cpu::CPUStat &stat, double maxvalue, int maxlines)
create a (vertical) CPU bar string from the CPUStat for terminal-based output.
bool operator< (const SnapRange &a, const SnapRange &b)
bool operator== (const SnapRange &a, const SnapRange &b)
void printHelp ()
void sig_handler (int sig)
handle signals such a CTRL-C.
bool verifyDatabase (persist::Database &db)
Variables
const unsigned int ALERT_HUGEPAGES_UNUSED = 1
Alert message id for significant amount of unused hugepages.
const unsigned int ALERT_MAJORFAULTS = 2
Alert message id for significant and sustained amount of major faults.
const unsigned int HLP_BROWSE_ARROW = 61
const unsigned int HLP_BROWSE_DAY = 63
const unsigned int HLP_BROWSE_HOMEND = 65
const unsigned int HLP_BROWSE_HOUR = 62
const unsigned int HLP_BROWSE_WEEK = 64
const unsigned int HLP_QUIT = 60
const unsigned int MAX_CPU_TRAIL =280
Maximum samples kept for CPU trail.
const unsigned int MSG_CPUMODEL = 5
const unsigned int MSG_DISTRO = 3
const unsigned int MSG_MACHINE = 4
const unsigned int MSG_STORAGE = 6
Screen * screen = 0
The global Screen.
Detailed Description
ncurses based realtime and historical performance viewer
Data Structure Documentation
leanux::tools::lmon::Signal
struct leanux::tools::lmon::Signal
Definition at line 48 of file trigger.hpp.
Data Fields
string message
leanux::tools::lmon::SnapRange
struct leanux::tools::lmon::SnapRange
Definition at line 66 of file xdata.hpp.
Data Fields
unsigned long snap_max
unsigned long snap_min
leanux::tools::lmon::TriggerContext
struct leanux::tools::lmon::TriggerContext
Definition at line 54 of file trigger.hpp.
Data Fields
const XIOView * ioview_
const XNetView * netview_
const XProcView * procview_
const XSysView * sysview_
leanux::tools::lmon::TriggerSet
class leanux::tools::lmon::TriggerSet
Definition at line 87 of file trigger.hpp.
leanux::tools::lmon::XIORec
struct leanux::tools::lmon::XIORec
I/O statistics in a form suitable for XIOView.
Definition at line 120 of file xdata.hpp.
Data Fields
double artm
double awtm
string device
double growths
double iodone_cnt
double ioerr_cnt
double iorequest_cnt
double qsz
double rbs
double rs
double svctm
double util
double wbs
double ws
leanux::tools::lmon::XIOView
struct leanux::tools::lmon::XIOView
Data record for IOView display.
Definition at line 142 of file xdata.hpp.
Data Fields
map< string, unsigned long > fsbytes1
map< string, unsigned long > fsbytes2
vector< string > iosorted
IORecMap iostats
vector< string > mountsorted
IORecMap mountstats
unsigned long sample_count number of samples taken
struct timeval t1 start of sample interval
struct timeval t2 end of sample interval
leanux::tools::lmon::XNetView
struct leanux::tools::lmon::XNetView
Data record for NetView display.
Definition at line 97 of file xdata.hpp.
Data Fields
NetStatDeviceVector delta net stat delta.
unsigned long sample_count number of samples taken
struct timeval t1 start of sample interval
struct timeval t2 end of sample interval
list< TCPKeyCounter > tcpclient TCP client connections.
list< TCPKeyCounter > tcpserver TCP server connections.
leanux::tools::lmon::XProcView
struct leanux::tools::lmon::XProcView
Definition at line 74 of file xdata.hpp.
Data Fields
ProcPidStatDeltaVector delta
bool disabled
map< pid_t, string > pidargs
map< pid_t, uid_t > piduids
unsigned long sample_count number of samples taken
struct timeval t1 start of sample interval
struct timeval t2 end of sample interval
leanux::tools::lmon::XSysView
struct leanux::tools::lmon::XSysView
Data record for SysView display.
Definition at line 165 of file xdata.hpp.
Data Fields
unsigned int blockq size of the block queue.
CPUStatsMap cpu_delta the per CPU, per cpumode delta, in seconds
double cpu_seconds the total number of cpu seconds
CPUTopology cpu_topo The CPUTopology.
CPUStat cpu_total per cpumode, total over all CPU's, in seconds
list< CPUStat > cpufuture
list< CPUStat > cpupast Future trail of CPU bars.
See also
makeCPUBar
list< string > cpurtpast Past trail of CPU bars (realtime mode).
See also
makeCPUBar
double ctxsws context switches per second.
double forks forks per second.
double fs_growths mounted filesystem growth rate bytes per second.
LoadAvg loadavg The CPU load averages (average run+block queue sizes)
double mem_allocs memory allocations per second.
unsigned long mem_anon unused memory in bytes.
unsigned long mem_commitas comitted address space (linux kernel estimate) in bytes.
unsigned long mem_dirty dirty memory in bytes.
unsigned long mem_file size of page cache for file data in bytes.
double mem_frees memory frees per second.
unsigned long mem_hpfree hugepages free in bytes.
unsigned long mem_hprsvd hugepages reserved in bytes.
unsigned long mem_hptotal hugepages total in bytes.
double mem_majflts major faults per second.
unsigned long mem_mapped mapped (memory mapped files) memory in bytes.
double mem_minflts minor faults per second.
unsigned long mem_mlock locked memory in bytes.
double mem_pageins pages paged in per second.
double mem_pageouts pages paged out per second.
unsigned long mem_pagetbls space used by page tables in bytes.
unsigned long mem_shmem shared memory in bytes.
unsigned long mem_slab slab size in bytes.
double mem_swapins pages swapped in per second.
double mem_swapouts pages swapped out per second.
unsigned long mem_swpsize swap size in bytes.
unsigned long mem_swpused swap used in bytes.
unsigned long mem_thpanon transparent hugepages anonymous in bytes.
unsigned long mem_total unused memory in bytes.
unsigned long mem_unused unused memory in bytes.
unsigned long pagesize_ the system page size
unsigned long res_filesmax max number of open files.
unsigned long res_filesopen number of open files.
unsigned long res_inodesfree number of free inodes.
unsigned long res_inodesopen number of open inodes.
unsigned long res_logins number of logins.
unsigned long res_processes number of processes.
unsigned long res_users number of distinct users.
unsigned int runq size of the run queue.
unsigned long sample_count
SnapRange snap_range
struct timeval t1 start of sample interval
struct timeval t2 end of sample interval
double time_slice average time slice duration.
Typedef Documentation
IORecMap
typedef std::map<std::string,XIORec> leanux::tools::lmon::IORecMap
Definition at line 137 of file xdata.hpp.
SignalList
typedef std::list<Signal> leanux::tools::lmon::SignalList
Definition at line 52 of file trigger.hpp.
Function Documentation
main()
int leanux::tools::lmon::main (int argc, char * argv[])
Examples
example_cpu.cpp, example_pci.cpp, example_process.cpp, example_process2.cpp, example_system.cpp, and example_usb.cpp.
Definition at line 105 of file lmon.cpp.
References leanux::util::ConfigFile::declareParameter(), leanux::util::fileReadAccess(), leanux::util::ConfigFile::getConfig(), leanux::Oops::getMessage(), leanux::util::getUserConfigDir(), leanux::init(), printHelp(), leanux::tools::lmon::Screen::runHistory(), leanux::tools::lmon::Screen::runRealtime(), screen, leanux::util::ConfigFile::setConfig(), leanux::util::Tracer::setTracer(), sig_handler(), leanux::tools::lmon::Screen::Stop(), TRACE, verifyDatabase(), and leanux::util::ConfigFile::write().
Referenced by main().
makeCPUBar()
std::string leanux::tools::lmon::makeCPUBar (const cpu::CPUStat & stat, double maxvalue, int maxlines)
create a (vertical) CPU bar string from the CPUStat for terminal-based output.
Create a character string representing a stacked CPU bar.
Parameters
stat the CPUStat statistics
maxvalue the maximum possible value
maxlines the maximum number of characters (lines) in the string
The bar will not be longer than maxlines. When the calue=maxvalue, the length of the bar equals maxlines.
Parameters
stat the source data
maxvalue the max value (max possible number of CPU seconds in stat)
maxlines the maximum number of lines/characters to incorporate.
Definition at line 100 of file xdata.cpp.
References leanux::cpu::getCPUUsageTotal(), leanux::cpu::CPUStat::iowait, leanux::cpu::CPUStat::irq, leanux::cpu::CPUStat::nice, leanux::cpu::CPUStat::softirq, leanux::cpu::CPUStat::system, and leanux::cpu::CPUStat::user.
Referenced by leanux::tools::lmon::RealtimeSampler::sampleXSysView(), and leanux::tools::lmon::SysView::xrefresh().
operator<()
bool leanux::tools::lmon::operator< (const SnapRange & a, const SnapRange & b) inline
Definition at line 72 of file xdata.hpp.
References leanux::tools::lmon::SnapRange::snap_max, and leanux::tools::lmon::SnapRange::snap_min.
operator==()
bool leanux::tools::lmon::operator== (const SnapRange & a, const SnapRange & b) inline
Definition at line 71 of file xdata.hpp.
References leanux::tools::lmon::SnapRange::snap_max, and leanux::tools::lmon::SnapRange::snap_min.
printHelp()
void leanux::tools::lmon::printHelp ()
Definition at line 71 of file lmon.cpp.
Referenced by main().
sig_handler()
void leanux::tools::lmon::sig_handler (int sig)
handle signals such a CTRL-C.
Definition at line 65 of file lmon.cpp.
References screen, and leanux::tools::lmon::Screen::Stop().
Referenced by main().
verifyDatabase()
bool leanux::tools::lmon::verifyDatabase (persist::Database & db)
Definition at line 83 of file lmon.cpp.
References leanux::persist::Query::getLong(), leanux::persist::Statement::prepare(), and leanux::persist::Query::step().
Referenced by main().
Variable Documentation
ALERT_HUGEPAGES_UNUSED
const unsigned int leanux::tools::lmon::ALERT_HUGEPAGES_UNUSED = 1
Alert message id for significant amount of unused hugepages.
Definition at line 65 of file lmon_curses.cpp.
ALERT_MAJORFAULTS
const unsigned int leanux::tools::lmon::ALERT_MAJORFAULTS = 2
Alert message id for significant and sustained amount of major faults.
Definition at line 68 of file lmon_curses.cpp.
HLP_BROWSE_ARROW
const unsigned int leanux::tools::lmon::HLP_BROWSE_ARROW = 61
Definition at line 74 of file lmon_curses.cpp.
Referenced by leanux::tools::lmon::Screen::runHistory(), and leanux::tools::lmon::Screen::runRealtime().
HLP_BROWSE_DAY
const unsigned int leanux::tools::lmon::HLP_BROWSE_DAY = 63
Definition at line 76 of file lmon_curses.cpp.
Referenced by leanux::tools::lmon::Screen::runHistory().
HLP_BROWSE_HOMEND
const unsigned int leanux::tools::lmon::HLP_BROWSE_HOMEND = 65
Definition at line 78 of file lmon_curses.cpp.
Referenced by leanux::tools::lmon::Screen::runHistory().
HLP_BROWSE_HOUR
const unsigned int leanux::tools::lmon::HLP_BROWSE_HOUR = 62
Definition at line 75 of file lmon_curses.cpp.
Referenced by leanux::tools::lmon::Screen::runHistory().
HLP_BROWSE_WEEK
const unsigned int leanux::tools::lmon::HLP_BROWSE_WEEK = 64
Definition at line 77 of file lmon_curses.cpp.
Referenced by leanux::tools::lmon::Screen::runHistory().
HLP_QUIT
const unsigned int leanux::tools::lmon::HLP_QUIT = 60
Definition at line 73 of file lmon_curses.cpp.
Referenced by leanux::tools::lmon::Screen::runHistory(), and leanux::tools::lmon::Screen::runRealtime().
MAX_CPU_TRAIL
const unsigned int leanux::tools::lmon::MAX_CPU_TRAIL =280
Maximum samples kept for CPU trail.
Definition at line 53 of file xdata.hpp.
Referenced by leanux::tools::lmon::RealtimeSampler::sampleXSysView().
MSG_CPUMODEL
const unsigned int leanux::tools::lmon::MSG_CPUMODEL = 5
Definition at line 71 of file lmon_curses.cpp.
Referenced by leanux::tools::lmon::Footer::Footer().
MSG_DISTRO
const unsigned int leanux::tools::lmon::MSG_DISTRO = 3
Definition at line 69 of file lmon_curses.cpp.
Referenced by leanux::tools::lmon::Footer::Footer().
MSG_MACHINE
const unsigned int leanux::tools::lmon::MSG_MACHINE = 4
Definition at line 70 of file lmon_curses.cpp.
Referenced by leanux::tools::lmon::Footer::Footer().
MSG_STORAGE
const unsigned int leanux::tools::lmon::MSG_STORAGE = 6
Definition at line 72 of file lmon_curses.cpp.
Referenced by leanux::tools::lmon::Footer::Footer().
screen
Screen* leanux::tools::lmon::screen = 0
The global Screen.
Definition at line 60 of file lmon.cpp.
Referenced by main(), sig_handler(), and leanux::tools::lmon::View::View().