leanux: leanux::persist::DML Class Reference
leanux::persist::DML Class Reference
Data Modification Language statements can take bind values.
#include <persist.hpp>
Public Member Functions
DML (const Database &db)
Constructor.
virtual ~DML ()
Destructor.
void bind (int position, const std::string &value)
Bind a string value to the bind at position.
void bind (int position, double value)
Bind a double value to the bind at position.
void bind (int position, int value)
Bind an int value to the bind at position.
void bind (int position, long value)
Bind a long value to the bind at position.
void close ()
A statement handle can be explicitly closed without deleting the Statement object itself.
void execute ()
Execute.
void prepare (const std::string &sql)
Prepare a SQL statement.
void reset ()
Reset a SQL statement for rexecute or even re-prepare.
Protected Attributes
sqlite3 * database_
database handle on which the stmt_ is created.
sqlite3_stmt * stmt_
statement handle.
Detailed Description
Data Modification Language statements can take bind values.
Note that calling reset leaves set bind values intact.
Definition at line 251 of file persist.hpp.
Constructor & Destructor Documentation
DML()
leanux::persist::DML::DML (const Database & db)
Constructor.
Definition at line 400 of file persist.cpp.
~DML()
virtual leanux::persist::DML::~DML () inline virtual
Destructor.
Definition at line 258 of file persist.hpp.
Member Function Documentation
bind() [1/4]
void leanux::persist::DML::bind (int position, const std::string & value)
Bind a string value to the bind at position.
Parameters
position the bind position in the SQL (start with 1)
value the value to bind.
Definition at line 431 of file persist.cpp.
References leanux::persist::Statement::database_, and leanux::persist::Statement::stmt_.
bind() [2/4]
void leanux::persist::DML::bind (int position, double value)
Bind a double value to the bind at position.
Parameters
position the bind position in the SQL (start with 1)
value the value to bind.
Definition at line 410 of file persist.cpp.
References leanux::persist::Statement::database_, and leanux::persist::Statement::stmt_.
Referenced by leanux::tools::lard::applyRetention(), leanux::tools::lrep::chartCmdAverage(), leanux::tools::lrep::chartCPUTimeLine(), leanux::tools::lrep::chartDiskAverage(), leanux::tools::lrep::chartDiskRSZHisto(), leanux::tools::lrep::chartDiskScvHisto(), leanux::tools::lrep::chartDiskTimeLine(), leanux::tools::lrep::chartDiskWSZHisto(), leanux::tools::lrep::chartKernelTimeLine(), leanux::tools::lrep::chartMountAverage(), leanux::tools::lrep::chartMountTimeLine(), leanux::tools::lrep::chartNetAverage(), leanux::tools::lrep::chartNicBWTimeLine(), leanux::tools::lrep::chartNICPacketTimeLine(), leanux::tools::lrep::chartPagingTimeLine(), leanux::tools::lrep::chartPerCPUAverage(), leanux::tools::lrep::chartSchedTimeLine(), leanux::tools::lrep::chartTCPClientAverage(), leanux::tools::lrep::chartTCPClientTimeLine(), leanux::tools::lrep::chartTCPServerAverage(), leanux::tools::lrep::chartTCPServerTimeLine(), leanux::tools::lrep::chartTotalCPUAverage(), leanux::tools::lrep::chartUserAverage(), leanux::tools::lrep::chartVMAverage(), leanux::tools::lrep::chartVMTimeLine(), leanux::tools::lrep::computeTotals(), leanux::tools::lrep::CPUHeatMap(), leanux::tools::lard::deleteSnapshots(), leanux::tools::lrep::DiskHeatMap(), leanux::tools::lard::ensureSinglePid(), leanux::tools::lmon::LardHistory::fetchXIOView(), leanux::tools::lmon::LardHistory::fetchXNetView(), leanux::tools::lmon::LardHistory::fetchXProcView(), leanux::tools::lmon::LardHistory::fetchXSysView(), leanux::tools::lmon::LardHistory::getCPUStatRange(), leanux::tools::lrep::htmlCmdCPUDetail(), leanux::tools::lrep::htmlCmdDetails(), leanux::tools::lrep::htmlCmdRSSDetail(), leanux::tools::lrep::htmlCmdUidDetail(), leanux::tools::lrep::htmlDiskDetail(), leanux::tools::lrep::htmlDiskDetails(), leanux::tools::lrep::load5HeatMap(), leanux::tools::lrep::main(), leanux::tools::lard::mainLoop(), leanux::tools::lrep::NetPktHeatMap(), leanux::tools::lard::TimeSnap::storeSnap(), leanux::tools::lard::IOSnap::storeSnap(), leanux::tools::lard::CPUSnap::storeSnap(), leanux::tools::lard::SchedSnap::storeSnap(), leanux::tools::lard::NetSnap::storeSnap(), leanux::tools::lard::VMSnap::storeSnap(), leanux::tools::lard::ProcSnap::storeSnap(), leanux::tools::lard::ResSnap::storeSnap(), leanux::tools::lard::MountSnap::storeSnap(), leanux::tools::lard::TCPEstaSnap::storeSnap(), and leanux::tools::lmon::LardHistory::updateRangeTime().
bind() [3/4]
void leanux::persist::DML::bind (int position, int value)
Bind an int value to the bind at position.
Parameters
position the bind position in the SQL (start with 1)
value the value to bind.
Definition at line 417 of file persist.cpp.
References leanux::persist::Statement::database_, and leanux::persist::Statement::stmt_.
bind() [4/4]
void leanux::persist::DML::bind (int position, long value)
Bind a long value to the bind at position.
Parameters
position the bind position in the SQL (start with 1)
value the value to bind.
Definition at line 424 of file persist.cpp.
References leanux::persist::Statement::database_, and leanux::persist::Statement::stmt_.
close()
void leanux::persist::Statement::close () inherited
A statement handle can be explicitly closed without deleting the Statement object itself.
This frees the resources in SQLite, . it's allowed to call prepare() again.
Definition at line 381 of file persist.cpp.
References leanux::persist::Statement::database_, and leanux::persist::Statement::stmt_.
Referenced by leanux::tools::lard::applyRetention(), leanux::persist::Database::begin(), leanux::persist::Database::beginExclusive(), leanux::persist::Database::beginImmediate(), leanux::persist::Database::commit(), leanux::tools::lard::deleteSnapshots(), leanux::tools::lard::ensureSinglePid(), leanux::persist::Database::getUserVersion(), leanux::tools::lard::initDB(), leanux::tools::lard::mainLoop(), leanux::persist::Statement::prepare(), leanux::persist::Database::release(), leanux::persist::Database::rollback(), leanux::persist::Database::savepoint(), leanux::persist::Database::setUserVersion(), leanux::tools::lard::shrinkDB(), and leanux::tools::lard::vacuumAnalyze().
execute()
void leanux::persist::DML::execute ()
Execute.
Definition at line 403 of file persist.cpp.
References leanux::persist::Statement::database_, and leanux::persist::Statement::stmt_.
Referenced by leanux::tools::lard::deleteSnapshots(), leanux::tools::lard::ensureSinglePid(), leanux::tools::lard::mainLoop(), leanux::tools::lard::TimeSnap::storeSnap(), leanux::tools::lard::IOSnap::storeSnap(), leanux::tools::lard::CPUSnap::storeSnap(), leanux::tools::lard::SchedSnap::storeSnap(), leanux::tools::lard::NetSnap::storeSnap(), leanux::tools::lard::VMSnap::storeSnap(), leanux::tools::lard::ProcSnap::storeSnap(), leanux::tools::lard::ResSnap::storeSnap(), leanux::tools::lard::MountSnap::storeSnap(), and leanux::tools::lard::TCPEstaSnap::storeSnap().
prepare()
void leanux::persist::Statement::prepare (const std::string & sql) inherited
Prepare a SQL statement.
Parameters
sql the SQL statement.
Definition at line 363 of file persist.cpp.
References leanux::persist::Statement::close(), leanux::persist::Statement::database_, and leanux::persist::Statement::stmt_.
Referenced by leanux::tools::lard::applyRetention(), leanux::persist::Database::begin(), leanux::persist::Database::beginExclusive(), leanux::persist::Database::beginImmediate(), leanux::tools::lrep::chartCmdAverage(), leanux::tools::lrep::chartCPUTimeLine(), leanux::tools::lrep::chartDiskAverage(), leanux::tools::lrep::chartDiskRSZHisto(), leanux::tools::lrep::chartDiskScvHisto(), leanux::tools::lrep::chartDiskTimeLine(), leanux::tools::lrep::chartDiskWSZHisto(), leanux::tools::lrep::chartKernelTimeLine(), leanux::tools::lrep::chartMountAverage(), leanux::tools::lrep::chartMountTimeLine(), leanux::tools::lrep::chartNetAverage(), leanux::tools::lrep::chartNicBWTimeLine(), leanux::tools::lrep::chartNICPacketTimeLine(), leanux::tools::lrep::chartPagingTimeLine(), leanux::tools::lrep::chartPerCPUAverage(), leanux::tools::lrep::chartSchedTimeLine(), leanux::tools::lrep::chartTCPClientAverage(), leanux::tools::lrep::chartTCPClientTimeLine(), leanux::tools::lrep::chartTCPServerAverage(), leanux::tools::lrep::chartTCPServerTimeLine(), leanux::tools::lrep::chartTotalCPUAverage(), leanux::tools::lrep::chartUserAverage(), leanux::tools::lrep::chartVMAverage(), leanux::tools::lrep::chartVMTimeLine(), leanux::persist::Database::commit(), leanux::tools::lrep::computeTotals(), leanux::tools::lrep::CPUHeatMap(), leanux::tools::lard::createTableCmd(), leanux::tools::lard::createTableCpustat(), leanux::tools::lard::createTableDisk(), leanux::tools::lard::createTableIostat(), leanux::tools::lard::createTableMountpoint(), leanux::tools::lard::createTableMountstat(), leanux::tools::lard::createTableNetstat(), leanux::tools::lard::createTableNic(), leanux::tools::lard::createTableProcstat(), leanux::tools::lard::createTableResstat(), leanux::tools::lard::createTableSchedstat(), leanux::tools::lard::createTableSnapshot(), leanux::tools::lard::createTableStatus(), leanux::tools::lard::createTableTcpclientstat(), leanux::tools::lard::createTableTcpkey(), leanux::tools::lard::createTableTcpserverstat(), leanux::tools::lard::createTableVmstat(), leanux::tools::lard::createTableWchan(), leanux::tools::lard::deleteSnapshots(), leanux::tools::lrep::DiskHeatMap(), leanux::tools::lard::ensureSinglePid(), leanux::tools::lmon::LardHistory::fetchXIOView(), leanux::tools::lmon::LardHistory::fetchXNetView(), leanux::tools::lmon::LardHistory::fetchXProcView(), leanux::tools::lmon::LardHistory::fetchXSysView(), leanux::tools::lmon::LardHistory::getCPUStatRange(), leanux::persist::Database::getUserVersion(), leanux::tools::lrep::htmlCmdCPUDetail(), leanux::tools::lrep::htmlCmdDetails(), leanux::tools::lrep::htmlCmdRSSDetail(), leanux::tools::lrep::htmlCmdUidDetail(), leanux::tools::lrep::htmlDiskDetail(), leanux::tools::lrep::htmlDiskDetails(), leanux::tools::lard::initDB(), leanux::tools::lrep::load5HeatMap(), leanux::tools::lrep::main(), leanux::tools::lard::mainLoop(), leanux::tools::lrep::NetPktHeatMap(), leanux::persist::Database::release(), leanux::persist::Database::rollback(), leanux::persist::Database::savepoint(), leanux::persist::Database::setUserVersion(), leanux::tools::lard::shrinkDB(), leanux::tools::lard::TimeSnap::storeSnap(), leanux::tools::lard::IOSnap::storeSnap(), leanux::tools::lard::CPUSnap::storeSnap(), leanux::tools::lard::SchedSnap::storeSnap(), leanux::tools::lard::NetSnap::storeSnap(), leanux::tools::lard::VMSnap::storeSnap(), leanux::tools::lard::ProcSnap::storeSnap(), leanux::tools::lard::ResSnap::storeSnap(), leanux::tools::lard::MountSnap::storeSnap(), leanux::tools::lard::TCPEstaSnap::storeSnap(), leanux::tools::lmon::LardHistory::updateMinMax(), leanux::tools::lmon::LardHistory::updateRangeTime(), leanux::tools::lard::vacuumAnalyze(), and leanux::tools::lmon::verifyDatabase().
reset()
void leanux::persist::Statement::reset () inherited
Reset a SQL statement for rexecute or even re-prepare.
Definition at line 374 of file persist.cpp.
References leanux::persist::Statement::database_, and leanux::persist::Statement::stmt_.
Referenced by leanux::tools::lrep::computeTotals(), leanux::tools::lard::createTableCpustat(), leanux::tools::lard::createTableIostat(), leanux::tools::lard::createTableMountstat(), leanux::tools::lard::createTableNetstat(), leanux::tools::lard::createTableProcstat(), leanux::tools::lard::createTableResstat(), leanux::tools::lard::createTableSchedstat(), leanux::tools::lard::createTableSnapshot(), leanux::tools::lard::createTableWchan(), leanux::tools::lard::deleteSnapshots(), leanux::tools::lard::ensureSinglePid(), leanux::tools::lmon::LardHistory::fetchXProcView(), leanux::tools::lrep::main(), leanux::tools::lard::ProcSnap::storeSnap(), leanux::tools::lard::MountSnap::storeSnap(), leanux::tools::lard::TCPEstaSnap::storeSnap(), and leanux::tools::lard::vacuumAnalyze().
Field Documentation
database_
sqlite3* leanux::persist::Statement::database_ protected inherited
database handle on which the stmt_ is created.
Definition at line 217 of file persist.hpp.
Referenced by bind(), leanux::persist::Statement::close(), leanux::persist::DDL::execute(), execute(), leanux::persist::Statement::prepare(), leanux::persist::Statement::reset(), leanux::persist::Statement::Statement(), and leanux::persist::Query::step().
stmt_
sqlite3_stmt* leanux::persist::Statement::stmt_ protected inherited
statement handle.
Definition at line 214 of file persist.hpp.
Referenced by bind(), leanux::persist::Statement::close(), leanux::persist::DDL::execute(), execute(), leanux::persist::DDL::execute_r(), leanux::persist::Query::getColumnCount(), leanux::persist::Query::getDouble(), leanux::persist::Query::getInt(), leanux::persist::Query::getLong(), leanux::persist::Query::getText(), leanux::persist::Query::isNull(), leanux::persist::Statement::prepare(), leanux::persist::Statement::reset(), leanux::persist::Statement::Statement(), leanux::persist::Query::step(), and leanux::persist::Statement::~Statement().
The documentation for this class was generated from the following files:
lib/persist.hpp
lib/persist.cpp