leanux: leanux::block::MajorMinor Class Reference
leanux::block::MajorMinor Class Reference
Datatype for major:minor pairs.
#include <block.hpp>
Public Member Functions
MajorMinor ()
Default constructor.
MajorMinor (const std::string &s)
Construct from string.
MajorMinor (dev_t dev)
Construct from Linux dev_t.
MajorMinor (unsigned long maj, unsigned long min)
Construct from major and minor values.
void getAliases (std::list< std::string > &aliases) const
get a list of device aliases, returned as full paths.
std::string getATAPort () const
Get the ATA port for the block MajorMinor.
std::string getCacheMode () const
get the SCSI disk caching mode (write back/write through).
DeviceClass getClass () const
Get the DeviceClass for a MajorMinor.
std::string getClassStr () const
Get a descriptive string for the device type of the MajorMinor.
std::string getDescription () const
Get a pretty-print description for the device.
std::string getDeviceFile () const
get the devicefile for this MajorMinor.
dev_t getDevT () const
return the MajorMinor dev_t.
std::string getDiskId () const
Retrieve a string identifying a disk on a best-efffort basis.
std::string getDMName () const
return the device dm name (or an empty string if not a dm device)
std::string getDMTargetTypes () const
return the device dm target type (or an empty string if not a d device)
std::string getDMUUID () const
return the device dm uuid (or an empty string if not a dm device)
std::string getFSType () const
Get the filesystem type of the block device.
std::string getFSUsage () const
Get the usage type of the block device.
void getHolders (std::list< std::string > &holders) const
Get a list of devices holding (using) the device m.
std::string getIOScheduler () const
get the IO scheduler (elevator) configured for the device.
std::string getKernelModule () const
get the kernel module (driver) used for the block device, such as 'scsi' or 'virtio'.
bool getLVMInfo (std::string &vgname, std::string &lvname) const
return VG and LV name for a LVM device.
std::string getLVMPV2VG () const
return the VG name the PV belongs to, or empty if the device is not a LVM PV.
std::string getLVName () const
Get the LV name the block device belongs to, or empty string if the device is not a LVM PV.
long getMajor () const
Get the major.
unsigned long getMaxHWIOSize () const
get the maximum IO size the hardware device reports to support.
unsigned long getMaxIOSize () const
get the maximum IO size configured to the device.
std::string getMDArrayState () const
Get the MD array state, valid for MetaDisk block devices.
unsigned long getMDChunkSize () const
Get the MD chunck size, valid for MetaDisk block devices.
unsigned long getMDDevices () const
Get the number of members in the MetaDisk or zero if not a MetaDisk.
std::string getMDLevel () const
Get the device MetaDisk RAID level or empty if the device is not an MetaDisk.
std::string getMDMetaDataVersion () const
Get the MD metadata version, valid for MetaDisk block devices.
std::string getMDName () const
Get the device MetaDisk name or empty if the device is not an MetaDisk.
void getMDRaidDisks (std::vector< MajorMinor > &disks) const
Get the raid disks participating in the MD array specified my MajorMinor.
std::string getMDRaidDiskStates () const
Get a string representing raid disk states as seen in /proc/mdstat.
unsigned long getMinIOSize () const
get the minimum IO size the device supports.
long getMinor () const
Get the minor.
std::string getModel () const
Get the model for the device.
bool getMountInfo (MountInfo &info) const
get MountInfo on devices with a mounted filesystem.
std::string getName () const
get the device name for this MajorMinor.
void getPartitions (std::list< std::string > &partitions) const
Get a list of partition devices in the disk,.
unsigned long getReadAhead () const
get the read-ahead size for the device
std::string getRevision () const
firmware revision of the device
bool getRotational () const
Chech if a disk is mechanical or solid state.
std::string getRotationalStr () const
Get a descriptive string of the rotational nature of the disk,.
unsigned long getRPM () const
Get the rotation speed of a device.
std::string getSCSIHCTL () const
get the host:channel:target:lun addess for the device.
unsigned long getSCSIIODone () const
Get SCSI iodone_cnt (number of SCSI IO completions)
unsigned long getSCSIIOError () const
Get SCSI ioerr_cnt (number of SCSI IO errors)
unsigned long getSCSIIORequest () const
Get SCSI iorequest_cnt (number of SCSI IO requests)
unsigned long getSectorSize () const
get the device sector size.
std::string getSerial () const
Get the serial number for the device.
unsigned long getSize () const
Return the size (capacity) of the device in bytes.
void getSlaves (std::list< std::string > &slaves) const
Get a list of devices slave to the device m.
bool getStats (DeviceStats &stats) const
get performance statistics for the block device specified by MajorMinor.
std::string getSysPath () const
return the full device path as it appears under /sys/devices/block
std::string getUDevPath () const
Get the udev path for the device.
std::string getVGName () const
Get the VG name the block device belongs to, or empty string if the device is not a LVM PV.
std::string getWWN () const
Some block devices do not have a WWN, so there is no guarentee a WWN exists.
bool isMetaDisk () const
determine if this MajorMinor represents a MetaDisk (software raid).
bool isPartition () const
bool isValid () const
Test MajorMinor validity.
bool isWholeDisk () const
Check if a disk is a whole disk (and not a partition).
bool operator!= (const MajorMinor &m) const
Test inequality.
bool operator< (const MajorMinor &m) const
compare MajorMinor objects.
MajorMinor & operator= (const std::string &s)
Assign a string.
bool operator== (const MajorMinor &m) const
Test equality.
Static Public Member Functions
static MajorMinor deriveWholeDisk (const MajorMinor &partition)
Derive the MajorMinor of the whole disk holding a partition.
static std::string getDeviceFileByMajorMinor (const MajorMinor &m)
Get the DeviceFile for the MajorMinor, such as '/dev/sda'.
static MajorMinor getMajorMinorByDeviceFile (const std::string &devicefile)
static MajorMinor getMajorMinorByName (const std::string &devicename)
Get the MajorMinor for the device name.
static std::string getNameByMajorMinor (const MajorMinor &m)
Get the DeviceName for the MajorMinor.
static bool isBCacheDisk (const MajorMinor &m)
determine if the MajorMinor represents a bcache disk.
static bool isIDEDisk (int major)
determine if the major represents an IDE disk.
static bool isMetaDisk (int major)
determine if the MajorMinor represents a MetaDisk (software raid).
static bool isMMCDisk (const MajorMinor &m)
determine if the MajorMinor represents an MMC disk.
static bool isNVMeDisk (const MajorMinor &m)
determine if the MajorMinor represents a NVMe disk.
static bool isSCSIDisk (int major)
determine if the major represents a SCSI disk.
static bool isVirtIODisk (const MajorMinor &m)
determine if the MajorMinor represents a virtio disk.
Static Public Attributes
static const MajorMinor invalid = MajorMinor(0, 0)
Invalid MajorMinor.
Static Private Member Functions
static void buildCache ()
(re)build the cached mapping between device names and MajorMinor numbers.
Private Attributes
dev_t dev_
The corresponding Linux dev_t.
Static Private Attributes
static struct timeval cacheage_
time of last rebuild.
static std::map< std::string, MajorMinor > file2mm_
cache of devicefile to MajorMinor mapping.
static std::map< MajorMinor, std::string > mm2file_
cache of MajorMinor to devicefile mapping.
static std::map< MajorMinor, std::string > mm2name_
cache of MajorMinor to device name mapping.
static std::map< std::string, MajorMinor > name2mm_
cache of device name to MajorMinor mapping.
Detailed Description
Datatype for major:minor pairs.
See also
invalid.
Examples
example_pci.cpp.
Definition at line 133 of file block.hpp.
Constructor & Destructor Documentation
MajorMinor() [1/4]
leanux::block::MajorMinor::MajorMinor (unsigned long maj, unsigned long min) inline
Construct from major and minor values.
Parameters
maj the major number.
min the minor number.
Definition at line 141 of file block.hpp.
References dev_.
MajorMinor() [2/4]
leanux::block::MajorMinor::MajorMinor (dev_t dev) inline
Construct from Linux dev_t.
Parameters
dev the Linux dev_t.
Definition at line 149 of file block.hpp.
References dev_.
MajorMinor() [3/4]
leanux::block::MajorMinor::MajorMinor () inline
Default constructor.
Definition at line 156 of file block.hpp.
References dev_.
Referenced by buildCache(), deriveWholeDisk(), getMDRaidDisks(), and isPartition().
MajorMinor() [4/4]
leanux::block::MajorMinor::MajorMinor (const std::string & s) inline
Construct from string.
Parameters
s string as in '8:0'
Definition at line 164 of file block.hpp.
Member Function Documentation
buildCache()
void leanux::block::MajorMinor::buildCache () static private
(re)build the cached mapping between device names and MajorMinor numbers.
Definition at line 171 of file block.cpp.
References file2mm_, MajorMinor(), mm2file_, mm2name_, name2mm_, and leanux::util::realPath().
Referenced by getDeviceFileByMajorMinor(), getMajorMinorByDeviceFile(), getMajorMinorByName(), and getNameByMajorMinor().
deriveWholeDisk()
MajorMinor leanux::block::MajorMinor::deriveWholeDisk (const MajorMinor & partition) static
Derive the MajorMinor of the whole disk holding a partition.
If the parameter partiton is not a partition, given MajorMinor is returned.
Parameters
partition the MajorMinor of the partition.
Returns
the MajorMinor of the wholedisk.
Definition at line 321 of file block.cpp.
References dev_, getMajorMinorByName(), getNameByMajorMinor(), isBCacheDisk(), isIDEDisk(), isMMCDisk(), isNVMeDisk(), isSCSIDisk(), isVirtIODisk(), and MajorMinor().
Referenced by leanux::tools::lblk::detailDisk(), getHolders(), getIOScheduler(), getReadAhead(), getRotational(), getSectorSize(), getSlaves(), getSysPath(), and leanux::tools::lblk::printSlaveTree().
getAliases()
void leanux::block::MajorMinor::getAliases (std::list< std::string > & aliases) const
get a list of device aliases, returned as full paths.
Parameters
aliases list of device aliases.
Definition at line 832 of file block.cpp.
References getDevT(), and getUDevPath().
Referenced by leanux::tools::lblk::detailLVM(), leanux::tools::lblk::detailMetaDisk(), leanux::sysdevice::BlockDevice::getPropertyValueList(), leanux::sysdevice::BlockPartition::getPropertyValueList(), leanux::sysdevice::NVMeDevice::getPropertyValueList(), leanux::sysdevice::NVMePartition::getPropertyValueList(), leanux::sysdevice::MapperDevice::getPropertyValueList(), leanux::sysdevice::LoopbackDevice::getPropertyValueList(), leanux::sysdevice::RamDiskDevice::getPropertyValueList(), and leanux::sysdevice::MDDevice::getPropertyValueList().
getATAPort()
std::string leanux::block::MajorMinor::getATAPort () const
Get the ATA port for the block MajorMinor.
Returns
the ATA port or empty if the block device is not ATA connected.
Definition at line 889 of file block.cpp.
References getSysPath().
getCacheMode()
std::string leanux::block::MajorMinor::getCacheMode () const
get the SCSI disk caching mode (write back/write through).
Returns
the SCSI disk caching mode or an empty string if not found.
Definition at line 856 of file block.cpp.
References leanux::util::fileReadString(), getNameByMajorMinor(), and getSCSIHCTL().
getClass()
DeviceClass leanux::block::MajorMinor::getClass () const
Get the DeviceClass for a MajorMinor.
Definition at line 385 of file block.cpp.
References leanux::block::BCacheDisk, leanux::block::BCacheDiskPartition, leanux::block::FloppyDisk, getDMUUID(), getLVName(), getMajor(), leanux::block::IDEDisk, leanux::block::IDEDiskPartition, isBCacheDisk(), isIDEDisk(), isMMCDisk(), isNVMeDisk(), isPartition(), isSCSIDisk(), isVirtIODisk(), leanux::block::Loopback, leanux::block::LVM, leanux::block::MetaDisk, leanux::block::MMCDisk, leanux::block::MMCDiskPartition, leanux::block::MultiPath, leanux::block::NVMeDisk, leanux::block::NVMeDiskPartition, leanux::block::RAMDisk, leanux::block::SCSICD, leanux::block::SCSIDisk, leanux::block::SCSIDiskPartition, leanux::block::Unknown, leanux::block::VirtioDisk, and leanux::block::VirtioDiskPartition.
Referenced by getClassStr(), getDescription(), getDiskId(), and leanux::tools::lblk::runOptions().
getClassStr()
std::string leanux::block::MajorMinor::getClassStr () const
Get a descriptive string for the device type of the MajorMinor.
Examples
example_pci.cpp.
Definition at line 418 of file block.cpp.
References leanux::block::BCacheDisk, leanux::block::BCacheDiskPartition, leanux::block::FloppyDisk, getClass(), leanux::block::IDEDisk, leanux::block::IDEDiskPartition, leanux::block::Loopback, leanux::block::LVM, leanux::block::MetaDisk, leanux::block::MMCDisk, leanux::block::MMCDiskPartition, leanux::block::MultiPath, leanux::block::NVMeDisk, leanux::block::NVMeDiskPartition, leanux::block::RAMDisk, leanux::block::SCSICD, leanux::block::SCSIDisk, leanux::block::SCSIDiskPartition, leanux::block::Unknown, leanux::block::VirtioDisk, and leanux::block::VirtioDiskPartition.
Referenced by leanux::tools::lblk::detailDeviceMapper(), leanux::tools::lblk::detailGenericBlockDevice(), leanux::tools::lblk::detailLVM(), and leanux::tools::lblk::detailMetaDisk().
getDescription()
std::string leanux::block::MajorMinor::getDescription () const
Get a pretty-print description for the device.
Get a loose description of what the device mm is.
Definition at line 264 of file block.cpp.
References leanux::block::MountInfo::fstype, getClass(), getDMName(), getFSType(), getLVMPV2VG(), getMDDevices(), getMDLevel(), getMountInfo(), getSCSIHCTL(), leanux::block::LVM, leanux::block::MetaDisk, and leanux::block::MountInfo::mountpoint.
Referenced by leanux::tools::lblk::detailMetaDisk().
getDeviceFile()
std::string leanux::block::MajorMinor::getDeviceFile () const inline
get the devicefile for this MajorMinor.
Returns
the device file.
Definition at line 373 of file block.hpp.
Referenced by leanux::tools::lblk::detailLVM().
getDeviceFileByMajorMinor()
std::string leanux::block::MajorMinor::getDeviceFileByMajorMinor (const MajorMinor & m) static
Get the DeviceFile for the MajorMinor, such as '/dev/sda'.
See also
getNameByMajorMinor
Parameters
m the device MajorMinor.
Returns
the name of the device,
Definition at line 247 of file block.cpp.
References buildCache(), and mm2file_.
getDevT()
dev_t leanux::block::MajorMinor::getDevT () const inline
return the MajorMinor dev_t.
Returns
the MajorMinor dev_t.
Definition at line 391 of file block.hpp.
References dev_.
Referenced by getAliases(), and leanux::block::operator<<().
getDiskId()
std::string leanux::block::MajorMinor::getDiskId () const
Retrieve a string identifying a disk on a best-efffort basis.
If the disk has a WWN, that is returned, else if the disk has a serial number, that is returned, else the device name is returned, in absence of required truth. virtio and vmware disks can lack a WWN and a serial number, so these disk types are impossible to identify (without tagging their contents).
Returns
a best-effort id for the disk.
Definition at line 1082 of file block.cpp.
References leanux::block::DeviceMapper, getClass(), getDMUUID(), getMDName(), getNameByMajorMinor(), getSerial(), getWWN(), leanux::block::LVM, and leanux::block::MetaDisk.
Referenced by leanux::tools::lblk::detailLVM().
getDMName()
std::string leanux::block::MajorMinor::getDMName () const
return the device dm name (or an empty string if not a dm device)
Returns
the device dm name or an empty string.
Definition at line 553 of file block.cpp.
References leanux::util::fileReadString(), and getNameByMajorMinor().
Referenced by leanux::tools::lblk::detailLVM(), and getDescription().
getDMTargetTypes()
std::string leanux::block::MajorMinor::getDMTargetTypes () const
return the device dm target type (or an empty string if not a d device)
Returns
the device dm target type or an empty string.
Definition at line 573 of file block.cpp.
References getUDevPath().
getDMUUID()
std::string leanux::block::MajorMinor::getDMUUID () const
return the device dm uuid (or an empty string if not a dm device)
Returns
the device dm name or an empty string.
Definition at line 563 of file block.cpp.
References leanux::util::fileReadString(), and getNameByMajorMinor().
Referenced by getClass(), getDiskId(), and leanux::tools::lsys::getLeafColStr().
getFSType()
std::string leanux::block::MajorMinor::getFSType () const
Get the filesystem type of the block device.
Returns
the block device filesystem.
Definition at line 640 of file block.cpp.
References getUDevPath().
Referenced by getDescription().
getFSUsage()
std::string leanux::block::MajorMinor::getFSUsage () const
Get the usage type of the block device.
Returns
the block device usage type.
Definition at line 656 of file block.cpp.
References getUDevPath().
getHolders()
void leanux::block::MajorMinor::getHolders (std::list< std::string > & holders) const
Get a list of devices holding (using) the device m.
Parameters
holders the devices holding m.
Definition at line 1167 of file block.cpp.
References deriveWholeDisk(), getNameByMajorMinor(), and isPartition().
Referenced by getLVMPV2VG().
getIOScheduler()
std::string leanux::block::MajorMinor::getIOScheduler () const
get the IO scheduler (elevator) configured for the device.
Returns
the IO scheduler configured.
Definition at line 761 of file block.cpp.
References deriveWholeDisk(), leanux::util::fileReadAccess(), leanux::util::fileReadString(), getNameByMajorMinor(), and isPartition().
Referenced by leanux::tools::lblk::detailLVM(), and leanux::tools::lsys::getLeafColStr().
getKernelModule()
std::string leanux::block::MajorMinor::getKernelModule () const
get the kernel module (driver) used for the block device, such as 'scsi' or 'virtio'.
Returns
the kernel module.
Definition at line 607 of file block.cpp.
References leanux::util::fileReadString(), and getNameByMajorMinor().
getLVMInfo()
bool leanux::block::MajorMinor::getLVMInfo (std::string & vgname, std::string & lvname) const
return VG and LV name for a LVM device.
Parameters
vgname will be set to VG name if function returns true.
lvname will be set to LV name if function returns true.
Returns
false if either E:DM_VG_NAME or E:DM_LV_NAME is not found in udev data fro the device.
Definition at line 701 of file block.cpp.
References getUDevPath().
getLVMPV2VG()
std::string leanux::block::MajorMinor::getLVMPV2VG () const
return the VG name the PV belongs to, or empty if the device is not a LVM PV.
Returns
the VG name to which m is a physical volume.
Definition at line 723 of file block.cpp.
References getHolders(), getMajorMinorByName(), getVGName(), and isValid().
Referenced by getDescription().
getLVName()
std::string leanux::block::MajorMinor::getLVName () const
Get the LV name the block device belongs to, or empty string if the device is not a LVM PV.
Returns
the LVM LV name.
Definition at line 686 of file block.cpp.
References getUDevPath().
Referenced by leanux::tools::lblk::detailLVM(), and getClass().
getMajor()
long leanux::block::MajorMinor::getMajor () const inline
Get the major.
Returns
the major.
Definition at line 197 of file block.hpp.
References dev_.
Referenced by getClass(), leanux::block::init(), and leanux::tools::lblk::runOptions().
getMajorMinorByDeviceFile()
MajorMinor leanux::block::MajorMinor::getMajorMinorByDeviceFile (const std::string & devicefile) static
Definition at line 219 of file block.cpp.
References buildCache(), file2mm_, and invalid.
getMajorMinorByName()
MajorMinor leanux::block::MajorMinor::getMajorMinorByName (const std::string & devicename) static
Get the MajorMinor for the device name.
Parameters
devicename the device name to find.
Returns
the MajorMinor of the device, or MajorMinor::invalid when the devicename is not a block device.
Definition at line 205 of file block.cpp.
References buildCache(), invalid, and name2mm_.
Referenced by leanux::sysdevice::BlockPartition::accept(), deriveWholeDisk(), getLVMPV2VG(), leanux::tools::lblk::parseDeviceArg(), leanux::tools::lblk::printHolderTree(), and leanux::tools::lblk::printSlaveTree().
getMaxHWIOSize()
unsigned long leanux::block::MajorMinor::getMaxHWIOSize () const
get the maximum IO size the hardware device reports to support.
Returns
the maximum hardware IO size in bytes.
Definition at line 867 of file block.cpp.
References leanux::util::fileReadUL(), and getNameByMajorMinor().
Referenced by leanux::tools::lblk::detailLVM().
getMaxIOSize()
unsigned long leanux::block::MajorMinor::getMaxIOSize () const
get the maximum IO size configured to the device.
Returns
the maximum configured IO size in bytes.
Definition at line 872 of file block.cpp.
References leanux::util::fileReadUL(), and getNameByMajorMinor().
Referenced by leanux::tools::lblk::detailLVM().
getMDArrayState()
std::string leanux::block::MajorMinor::getMDArrayState () const
Get the MD array state, valid for MetaDisk block devices.
Returns
the Array state or empty.
Definition at line 783 of file block.cpp.
References leanux::util::fileReadString(), and getNameByMajorMinor().
Referenced by leanux::tools::lblk::detailMetaDisk().
getMDChunkSize()
unsigned long leanux::block::MajorMinor::getMDChunkSize () const
Get the MD chunck size, valid for MetaDisk block devices.
Returns
the chunk size or zero.
Definition at line 757 of file block.cpp.
References leanux::util::fileReadUL(), and getNameByMajorMinor().
Referenced by leanux::tools::lblk::detailMetaDisk().
getMDDevices()
unsigned long leanux::block::MajorMinor::getMDDevices () const
Get the number of members in the MetaDisk or zero if not a MetaDisk.
Returns
the number of members in the MetaDisk.
Definition at line 828 of file block.cpp.
References leanux::util::fileReadUL(), and getNameByMajorMinor().
Referenced by leanux::tools::lblk::detailMetaDisk(), and getDescription().
getMDLevel()
std::string leanux::block::MajorMinor::getMDLevel () const
Get the device MetaDisk RAID level or empty if the device is not an MetaDisk.
Returns
the MetaDisk RAID level.
Definition at line 738 of file block.cpp.
References leanux::util::fileReadString(), and getNameByMajorMinor().
Referenced by leanux::tools::lblk::detailMetaDisk(), and getDescription().
getMDMetaDataVersion()
std::string leanux::block::MajorMinor::getMDMetaDataVersion () const
Get the MD metadata version, valid for MetaDisk block devices.
Returns
the metadata version or empty.
Definition at line 779 of file block.cpp.
References leanux::util::fileReadString(), and getNameByMajorMinor().
Referenced by leanux::tools::lblk::detailMetaDisk().
getMDName()
std::string leanux::block::MajorMinor::getMDName () const
Get the device MetaDisk name or empty if the device is not an MetaDisk.
Returns
the MetaDisk name.
Definition at line 742 of file block.cpp.
References getUDevPath().
Referenced by leanux::tools::lblk::detailMetaDisk(), and getDiskId().
getMDRaidDisks()
void leanux::block::MajorMinor::getMDRaidDisks (std::vector< MajorMinor > & disks) const
Get the raid disks participating in the MD array specified my MajorMinor.
Parameters
disks vector of MajorMinor for eachtof the disks (block devices) participating in the array. The vector index matches the index of the MajorMinor in the array.
Definition at line 787 of file block.cpp.
References leanux::util::fileReadString(), getNameByMajorMinor(), and MajorMinor().
Referenced by leanux::tools::lblk::detailMetaDisk(), and getMDRaidDiskStates().
getMDRaidDiskStates()
std::string leanux::block::MajorMinor::getMDRaidDiskStates () const
Get a string representing raid disk states as seen in /proc/mdstat.
Returns
the MDRaidDiskStates string.
Definition at line 805 of file block.cpp.
References leanux::util::fileReadString(), getMDRaidDisks(), and getNameByMajorMinor().
Referenced by leanux::tools::lblk::detailMetaDisk().
getMinIOSize()
unsigned long leanux::block::MajorMinor::getMinIOSize () const
get the minimum IO size the device supports.
Returns
the minimum IO size in bytes.
Definition at line 877 of file block.cpp.
References leanux::util::fileReadUL(), and getNameByMajorMinor().
Referenced by leanux::tools::lblk::detailLVM().
getMinor()
long leanux::block::MajorMinor::getMinor () const inline
Get the minor.
Returns
the minor.
Definition at line 203 of file block.hpp.
References dev_.
getModel()
std::string leanux::block::MajorMinor::getModel () const
Get the model for the device.
Returns
the device model or empty if unavailable.
Examples
example_pci.cpp.
Definition at line 588 of file block.cpp.
References leanux::util::fileReadAccess(), leanux::util::fileReadString(), getNameByMajorMinor(), and getUDevPath().
Referenced by leanux::sysdevice::BlockDevice::getDescription(), leanux::sysdevice::BlockDevice::getDisplayName(), and leanux::tools::lsys::getLeafColStr().
getMountInfo()
bool leanux::block::MajorMinor::getMountInfo (MountInfo & info) const
get MountInfo on devices with a mounted filesystem.
Parameters
info the MountInfo to fill.
Returns
false if the device (or it's aliases) does not appear in /proc/mounts.
Definition at line 938 of file block.cpp.
References leanux::block::enumMounts().
Referenced by getDescription().
getName()
std::string leanux::block::MajorMinor::getName () const inline
get the device name for this MajorMinor.
Returns
the device name.
Definition at line 367 of file block.hpp.
References getNameByMajorMinor().
Referenced by leanux::tools::lblk::detailDeviceMapper(), leanux::tools::lblk::detailGenericBlockDevice(), leanux::tools::lblk::detailLVM(), leanux::tools::lblk::detailMetaDisk(), leanux::block::enumMounts(), leanux::sysdevice::BlockDevice::getDisplayName(), leanux::sysdevice::BlockPartition::getDisplayName(), getSysPath(), leanux::tools::lrep::htmlDiskHolderTree(), leanux::tools::lrep::htmlDiskHolderTreeLine(), leanux::tools::lblk::printHolderTree(), and leanux::tools::lblk::printSlaveTree().
getNameByMajorMinor()
std::string leanux::block::MajorMinor::getNameByMajorMinor (const MajorMinor & m) static
Get the DeviceName for the MajorMinor.
Note that this DeviceName is the name as it appears in /proc/diskstats and /sys/class/block (or genreally, sysfs). This name may differ from the name as it appears under /dev, as an udev rule may have renamed the devicefile. So 'sdc' may be represented by '/dev/oracleasm/disk1', which is the 'DeviceFile', not the 'DeviceName'.
Parameters
m the device MajorMinor.
Returns
the name of the device,
Definition at line 233 of file block.cpp.
References buildCache(), and mm2name_.
Referenced by deriveWholeDisk(), getCacheMode(), leanux::tools::lmon::IOView::getDeviceName(), getDiskId(), getDMName(), getDMUUID(), getHolders(), getIOScheduler(), getKernelModule(), getMaxHWIOSize(), getMaxIOSize(), getMDArrayState(), getMDChunkSize(), getMDDevices(), getMDLevel(), getMDMetaDataVersion(), getMDRaidDisks(), getMDRaidDiskStates(), getMinIOSize(), getModel(), getName(), getPartitions(), getReadAhead(), getRevision(), getRotational(), getSCSIHCTL(), getSCSIIODone(), getSCSIIOError(), getSCSIIORequest(), getSectorSize(), getSerial(), getSize(), getSlaves(), getUDevPath(), getWWN(), isBCacheDisk(), isMMCDisk(), isNVMeDisk(), isPartition(), isVirtIODisk(), leanux::tools::lblk::listFile(), leanux::block::modeFromMajorMinor(), leanux::tools::lblk::printHolderTree(), and leanux::tools::lblk::printSlaveTree().
getPartitions()
void leanux::block::MajorMinor::getPartitions (std::list< std::string > & partitions) const
Get a list of partition devices in the disk,.
Parameters
partitions list of device names filled.
Definition at line 920 of file block.cpp.
References getNameByMajorMinor().
getReadAhead()
unsigned long leanux::block::MajorMinor::getReadAhead () const
get the read-ahead size for the device
Returns
the read-ahead size in bytes.
Definition at line 882 of file block.cpp.
References deriveWholeDisk(), leanux::util::fileReadUL(), getNameByMajorMinor(), and isPartition().
Referenced by leanux::tools::lblk::detailLVM().
getRevision()
std::string leanux::block::MajorMinor::getRevision () const
firmware revision of the device
Examples
example_pci.cpp.
Definition at line 539 of file block.cpp.
References leanux::util::fileReadString(), and getNameByMajorMinor().
getRotational()
bool leanux::block::MajorMinor::getRotational () const
Chech if a disk is mechanical or solid state.
Returns
treu when the device is rotational.
Examples
example_pci.cpp.
Definition at line 512 of file block.cpp.
References deriveWholeDisk(), leanux::util::fileReadString(), getNameByMajorMinor(), and isPartition().
Referenced by getRotationalStr().
getRotationalStr()
std::string leanux::block::MajorMinor::getRotationalStr () const
Get a descriptive string of the rotational nature of the disk,.
Returns
strings like 'SSD' or '7200RPM spindle'.
Definition at line 525 of file block.cpp.
References getRotational(), and getRPM().
getRPM()
unsigned long leanux::block::MajorMinor::getRPM () const
Get the rotation speed of a device.
Returns
the rotational speed if found, zero therwise. SSD's also report 0,
See also
getRotational.
Examples
example_pci.cpp.
Definition at line 625 of file block.cpp.
References getUDevPath().
Referenced by leanux::tools::lblk::detailDisk(), and getRotationalStr().
getSCSIHCTL()
std::string leanux::block::MajorMinor::getSCSIHCTL () const
get the host:channel:target:lun addess for the device.
Returns
the HCTL or an empty string if not found.
Definition at line 851 of file block.cpp.
References leanux::util::findDir(), and getNameByMajorMinor().
Referenced by getCacheMode(), and getDescription().
getSCSIIODone()
unsigned long leanux::block::MajorMinor::getSCSIIODone () const
Get SCSI iodone_cnt (number of SCSI IO completions)
Returns
iodone_cnt
Definition at line 291 of file block.cpp.
References leanux::util::fileReadHexString(), and getNameByMajorMinor().
Referenced by getStats(), and leanux::block::getStats().
getSCSIIOError()
unsigned long leanux::block::MajorMinor::getSCSIIOError () const
Get SCSI ioerr_cnt (number of SCSI IO errors)
Returns
ioerr_cnt
Definition at line 311 of file block.cpp.
References leanux::util::fileReadHexString(), and getNameByMajorMinor().
Referenced by getStats(), and leanux::block::getStats().
getSCSIIORequest()
unsigned long leanux::block::MajorMinor::getSCSIIORequest () const
Get SCSI iorequest_cnt (number of SCSI IO requests)
Returns
iorequest_cnt
Definition at line 301 of file block.cpp.
References leanux::util::fileReadHexString(), and getNameByMajorMinor().
Referenced by getStats(), and leanux::block::getStats().
getSectorSize()
unsigned long leanux::block::MajorMinor::getSectorSize () const
get the device sector size.
yields correct result for partitions as it returns the sector size of the device holding the partition.
Returns
the device sector size in bytes.
Definition at line 534 of file block.cpp.
References deriveWholeDisk(), leanux::util::fileReadUL(), and getNameByMajorMinor().
Referenced by leanux::tools::lblk::detailLVM(), leanux::tools::lsys::getLeafColStr(), and leanux::tools::lmon::IOView::getSectorSize().
getSerial()
std::string leanux::block::MajorMinor::getSerial () const
Get the serial number for the device.
Examples
example_pci.cpp.
Definition at line 476 of file block.cpp.
References leanux::util::fileReadAccess(), leanux::util::fileReadString(), getNameByMajorMinor(), and getUDevPath().
Referenced by getDiskId().
getSize()
unsigned long leanux::block::MajorMinor::getSize () const
Return the size (capacity) of the device in bytes.
Returns
the device capacity in bytes.
Examples
example_pci.cpp.
Definition at line 549 of file block.cpp.
References leanux::util::fileReadUL(), and getNameByMajorMinor().
Referenced by leanux::tools::lblk::detailLVM(), leanux::tools::lblk::detailMetaDisk(), and leanux::tools::lsys::getLeafColStr().
getSlaves()
void leanux::block::MajorMinor::getSlaves (std::list< std::string > & slaves) const
Get a list of devices slave to the device m.
Parameters
slaves providing m.
Definition at line 1193 of file block.cpp.
References deriveWholeDisk(), getNameByMajorMinor(), and isPartition().
getStats()
bool leanux::block::MajorMinor::getStats (DeviceStats & stats) const
get performance statistics for the block device specified by MajorMinor.
note that all numbers are totals since boot.
Parameters
stats the statistics to populate.
Returns
false if the MajorMinor is not found.
Examples
example_pci.cpp.
Definition at line 1219 of file block.cpp.
References getSCSIIODone(), getSCSIIOError(), getSCSIIORequest(), getSysPath(), leanux::block::DeviceStats::io_in_progress, leanux::block::DeviceStats::io_ms, leanux::block::DeviceStats::io_weighted_ms, leanux::block::DeviceStats::iodone_cnt, leanux::block::DeviceStats::ioerr_cnt, leanux::block::DeviceStats::iorequest_cnt, leanux::block::DeviceStats::read_ms, leanux::block::DeviceStats::read_sectors, leanux::block::DeviceStats::reads, leanux::block::DeviceStats::reads_merged, leanux::block::DeviceStats::write_ms, leanux::block::DeviceStats::write_sectors, leanux::block::DeviceStats::writes, and leanux::block::DeviceStats::writes_merged.
Referenced by leanux::tools::labbix::getIOms(), leanux::tools::labbix::getIOs(), leanux::tools::lsys::getLeafColStr(), leanux::tools::labbix::getReadms(), leanux::tools::labbix::getReads(), leanux::tools::labbix::getReadSectors(), leanux::tools::labbix::getWritems(), leanux::tools::labbix::getWrites(), and leanux::tools::labbix::getWriteSectors().
getSysPath()
std::string leanux::block::MajorMinor::getSysPath () const
return the full device path as it appears under /sys/devices/block
Definition at line 462 of file block.cpp.
References deriveWholeDisk(), getName(), isPartition(), and leanux::util::realPath().
Referenced by leanux::tools::lblk::detailDisk(), leanux::tools::lblk::detailLVM(), leanux::tools::lblk::detailMetaDisk(), getATAPort(), and getStats().
getUDevPath()
std::string leanux::block::MajorMinor::getUDevPath () const
Get the udev path for the device.
gentoo, ubuntu /run/udev/data/b{major}:{minor}. suse, redhat /dev/.udev/db/block:{devicename}. suse 11.3 /dev/.udev/db/b{major}:{minor}.
Returns
the udev path as described or an empty string if not found
Examples
example_pci.cpp.
Definition at line 496 of file block.cpp.
References getNameByMajorMinor(), leanux::block::udev_mode, leanux::block::udev_path, leanux::block::umBlockMM, leanux::block::umBlockName, and leanux::block::umBMM.
Referenced by getAliases(), getDMTargetTypes(), getFSType(), getFSUsage(), getLVMInfo(), getLVName(), getMDName(), getModel(), getRPM(), getSerial(), getVGName(), and getWWN().
getVGName()
std::string leanux::block::MajorMinor::getVGName () const
Get the VG name the block device belongs to, or empty string if the device is not a LVM PV.
Returns
the LVM VG name.
Definition at line 671 of file block.cpp.
References getUDevPath().
Referenced by leanux::tools::lblk::detailLVM(), and getLVMPV2VG().
getWWN()
std::string leanux::block::MajorMinor::getWWN () const
Some block devices do not have a WWN, so there is no guarentee a WWN exists.
Returns
the WWN of the disk or empty if no WWN assigned to the disk
Examples
example_pci.cpp.
Definition at line 901 of file block.cpp.
References leanux::util::fileReadString(), getNameByMajorMinor(), getUDevPath(), and isNVMeDisk().
Referenced by getDiskId(), and leanux::tools::lsys::getLeafColStr().
isBCacheDisk()
bool leanux::block::MajorMinor::isBCacheDisk (const MajorMinor & m) static
determine if the MajorMinor represents a bcache disk.
Parameters
m the device MajorMinor.
Returns
true when the MajorMinor represents a bcache disk.
Definition at line 378 of file block.cpp.
References getNameByMajorMinor().
Referenced by deriveWholeDisk(), getClass(), isPartition(), and leanux::tools::lblk::runOptions().
isIDEDisk()
static bool leanux::block::MajorMinor::isIDEDisk (int major) inline static
determine if the major represents an IDE disk.
Parameters
major the device major.
Returns
true when the major represents an IDE disk.
Definition at line 229 of file block.hpp.
Referenced by deriveWholeDisk(), getClass(), isPartition(), isWholeDisk(), and leanux::tools::lblk::runOptions().
isMetaDisk() [1/2]
bool leanux::block::MajorMinor::isMetaDisk () const inline
determine if this MajorMinor represents a MetaDisk (software raid).
Returns
true when the MajorMinor represents a MetaDisk.
Definition at line 274 of file block.hpp.
References dev_.
Referenced by leanux::tools::lblk::runOptions().
isMetaDisk() [2/2]
static bool leanux::block::MajorMinor::isMetaDisk (int major) inline static
determine if the MajorMinor represents a MetaDisk (software raid).
Parameters
major the device MajorMinor.
Returns
true when the MajorMinor represents a MetaDisk.
Definition at line 266 of file block.hpp.
isMMCDisk()
bool leanux::block::MajorMinor::isMMCDisk (const MajorMinor & m) static
determine if the MajorMinor represents an MMC disk.
Parameters
m the device MajorMinor.
Returns
true when the MajorMinor represents an MMC disk.
Definition at line 371 of file block.cpp.
References getNameByMajorMinor().
Referenced by deriveWholeDisk(), getClass(), isPartition(), isWholeDisk(), and leanux::tools::lblk::runOptions().
isNVMeDisk()
bool leanux::block::MajorMinor::isNVMeDisk (const MajorMinor & m) static
determine if the MajorMinor represents a NVMe disk.
Parameters
m the device MajorMinor.
Returns
true when the MajorMinor represents a NVMe disk.
Definition at line 363 of file block.cpp.
References getNameByMajorMinor().
Referenced by deriveWholeDisk(), getClass(), getWWN(), isPartition(), isWholeDisk(), and leanux::tools::lblk::runOptions().
isPartition()
bool leanux::block::MajorMinor::isPartition () const inline
Returns
true if the block device is a disk partition.
Definition at line 294 of file block.hpp.
References dev_, getNameByMajorMinor(), isBCacheDisk(), isIDEDisk(), isMMCDisk(), isNVMeDisk(), isSCSIDisk(), isVirtIODisk(), and MajorMinor().
Referenced by leanux::sysdevice::BlockPartition::accept(), getClass(), getHolders(), getIOScheduler(), getReadAhead(), getRotational(), getSlaves(), getSysPath(), and isWholeDisk().
isSCSIDisk()
static bool leanux::block::MajorMinor::isSCSIDisk (int major) inline static
determine if the major represents a SCSI disk.
Parameters
major the device major.
Returns
true when the major represents a SCSI disk.
Definition at line 219 of file block.hpp.
Referenced by deriveWholeDisk(), getClass(), isPartition(), isWholeDisk(), and leanux::tools::lblk::runOptions().
isValid()
bool leanux::block::MajorMinor::isValid () const inline
Test MajorMinor validity.
See also
invalid.
Returns
true when this MajorMinor is invalid.
Definition at line 385 of file block.hpp.
References invalid.
Referenced by leanux::block::enumMounts(), leanux::sysdevice::iSCSIDevice::getDescription(), getLVMPV2VG(), leanux::block::init(), leanux::tools::lblk::listFile(), leanux::tools::lblk::parseDeviceArg(), and leanux::tools::lblk::runOptions().
isVirtIODisk()
bool leanux::block::MajorMinor::isVirtIODisk (const MajorMinor & m) static
determine if the MajorMinor represents a virtio disk.
Parameters
m the device MajorMinor.
Returns
true when the MajorMinor represents a virtio disk.
Definition at line 358 of file block.cpp.
References getNameByMajorMinor().
Referenced by deriveWholeDisk(), getClass(), isPartition(), isWholeDisk(), and leanux::tools::lblk::runOptions().
isWholeDisk()
bool leanux::block::MajorMinor::isWholeDisk () const inline
Check if a disk is a whole disk (and not a partition).
Returns
true if the MajorMinor represents a whole IDE or SCSI disk.
Definition at line 282 of file block.hpp.
References dev_, isIDEDisk(), isMMCDisk(), isNVMeDisk(), isPartition(), isSCSIDisk(), and isVirtIODisk().
operator!=()
bool leanux::block::MajorMinor::operator!= (const MajorMinor & m) const inline
Test inequality.
Parameters
m MajorMinor to compare to.
Returns
true if *this != m.
Definition at line 189 of file block.hpp.
References dev_.
operator<()
bool leanux::block::MajorMinor::operator< (const MajorMinor & m) const inline
compare MajorMinor objects.
Parameters
m the MajorMinor to compoare this to.
Returns
true of this < m.
Definition at line 210 of file block.hpp.
References dev_.
operator=()
MajorMinor & leanux::block::MajorMinor::operator= (const std::string & s)
Assign a string.
Parameters
s string as in '8:0'.
Returns
reference to this.
Definition at line 147 of file block.cpp.
References dev_.
operator==()
bool leanux::block::MajorMinor::operator== (const MajorMinor & m) const inline
Test equality.
Parameters
m MajorMinor to compare to.
Returns
true if *this == m.
Definition at line 180 of file block.hpp.
References dev_.
Field Documentation
cacheage_
struct timeval leanux::block::MajorMinor::cacheage_ static private
time of last rebuild.
Definition at line 719 of file block.hpp.
dev_
dev_t leanux::block::MajorMinor::dev_ private
The corresponding Linux dev_t.
Definition at line 716 of file block.hpp.
Referenced by deriveWholeDisk(), getDevT(), getMajor(), getMinor(), isMetaDisk(), isPartition(), isWholeDisk(), MajorMinor(), operator!=(), operator<(), operator=(), and operator==().
file2mm_
std::map< std::string, MajorMinor > leanux::block::MajorMinor::file2mm_ static private
cache of devicefile to MajorMinor mapping.
Definition at line 728 of file block.hpp.
Referenced by buildCache(), and getMajorMinorByDeviceFile().
invalid
const MajorMinor leanux::block::MajorMinor::invalid = MajorMinor(0, 0) static
Invalid MajorMinor.
Definition at line 373 of file block.hpp.
Referenced by leanux::sysdevice::BlockPartition::accept(), leanux::block::enumMounts(), leanux::tools::labbix::findByZabbix(), leanux::block::getFileMajorMinor(), leanux::tools::labbix::getIOms(), leanux::tools::labbix::getIOs(), leanux::sysdevice::BlockDevice::getMajorMinor(), getMajorMinorByDeviceFile(), getMajorMinorByName(), leanux::tools::labbix::getReadms(), leanux::tools::labbix::getReads(), leanux::tools::labbix::getReadSectors(), leanux::tools::labbix::getWritems(), leanux::tools::labbix::getWrites(), leanux::tools::labbix::getWriteSectors(), isValid(), and leanux::tools::lblk::parseDeviceArg().
mm2file_
std::map< MajorMinor, std::string > leanux::block::MajorMinor::mm2file_ static private
cache of MajorMinor to devicefile mapping.
Definition at line 731 of file block.hpp.
Referenced by buildCache(), and getDeviceFileByMajorMinor().
mm2name_
std::map< MajorMinor, std::string > leanux::block::MajorMinor::mm2name_ static private
cache of MajorMinor to device name mapping.
Definition at line 725 of file block.hpp.
Referenced by buildCache(), and getNameByMajorMinor().
name2mm_
std::map< std::string, MajorMinor > leanux::block::MajorMinor::name2mm_ static private
cache of device name to MajorMinor mapping.
Definition at line 722 of file block.hpp.
Referenced by buildCache(), and getMajorMinorByName().
The documentation for this class was generated from the following files:
lib/block.hpp
lib/block.cpp