#!/bin/bash
#
# lard      @LARD_DESCR@
# Copyright @LEANUX_MAINTAINER_NAME@
# Contact   @LEANUX_MAINTAINER_EMAIL@
# Bugs      @LEANUX_BUG_URL@
#
### BEGIN INIT INFO
# Provides:          lard
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:     3 4 5
# Default-Stop:
# Short-Description: @LARD_DESCR@
# Description:       @LEANUX_SHORT_DESC@
### END INIT INFO

# Source function library.
. /lib/lsb/init-functions

PROG=lard
PROGRAM=/usr/bin/lard
PIDFILE=/var/run/lard.pid
DB_DIR=@LARD_SYSDB_PATH@
DB_FILE=@LARD_SYSDB_FILE@
CONF_FILE=@LARD_SYSCONF_FILE@

start() {
  log_daemon_msg "Starting ${PROG}" "${PROG}"
  mkdir -p ${DB_DIR}
  touch ${DB_FILE}
  chown -R @LARD_USER@:@LARD_USER@ ${DB_DIR}
  chmod 770 ${DB_DIR}
  chmod 660 ${DB_FILE}
  start_daemon -p ${PIDFILE} ${PROGRAM} -c ${CONF_FILE} -f ${DB_FILE}
  log_end_msg $?
}

stop() {
  log_daemon_msg "Stopping ${PROG}" "${PROG}"
  killproc -p ${PIDFILE} ${PROGRAM}
  log_end_msg $?
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status_of_proc -p ${PIDFILE} ${PROGRAM} ${PROG} && exit 0 || exit $?
    ;;
  force-reload|restart)
    stop
    start
    ;;
  *)
    echo "Usage: ${PROG} {start|stop|restart}"
    exit 1
    ;;
esac
exit $?
