leanux: leanux::util::ConfigFile Class Reference
leanux::util::ConfigFile Class Reference
A configuration file of name=value pairs.
#include <configfile.hpp>
Data Structures
struct Parameter
A name-value pair as configuration parameter.
struct RGB
RGB color.
Public Member Functions
void cleanup ()
cleanup objects in configfiles_;
int getIntValue (const std::string &name) const
return the configuration parameter as an int.
RGB getRGBValue (const std::string &name) const
return the configuration parameter as a RGB struct.
std::list< std::string > getStringListValue (const std::string &name) const
return the configuration parameter as an int.
std::string getValue (const std::string &name) const
return the configuration parameter as a string.
void read ()
read and interpret the configuration file.
void setValue (const std::string name, const RGB &value)
Set the configuration parameter to a RGB value.
void setValue (const std::string name, const std::list< std::string > value)
Set the configuration parameter to a stringlist value.
void setValue (const std::string name, const std::string &value)
Set the configuration parameter to a string value.
void setValue (const std::string name, int value)
Set the configuration parameter to an int value.
void write (bool defaults=false)
write out the configuration file, including runtime modifications.
Static Public Member Functions
static void declareParameter (const std::string &name, const std::string &value, const std::string &description, const std::string &comment="")
declare the configuration paramater and set a hardcoded default.
static ConfigFile * getConfig ()
Get the ConfigurationFile object for the appname, or construct one if it does not exist.
static void releaseConfig ()
Release (delete) the configFile.
static ConfigFile * setConfig (const std::string &appname, const std::string &filename)
set the application name and config file name.
Private Member Functions
ConfigFile (const std::string &appname, const std::string &filename)
Constructor, should not be called directly, use setConfig and getConfig to create the ConfigFile.
~ConfigFile ()
Destructor, should not be called directly.
Private Attributes
std::string appname_
name of application owning the ConfigFile
std::string filename_
The filename of the ConfigFile.
std::map< std::string, Parameter > values_
Current values.
Static Private Attributes
static std::map< std::string, std::string > comments_
Configuration parameter comments.
static ConfigFile * config_ = 0
The singleton ConfigFile.
static std::map< std::string, Parameter > defaults_
Configuration parameter defaults.
static std::map< std::string, std::string > descriptions_
Configuration parameter description.
Detailed Description
A configuration file of name=value pairs.
File format:
empty lines or lines with first non-whitespace character='#' are ignored.
name=value<eol> note that any whitespace in front of value is ignored.
Definition at line 56 of file configfile.hpp.
Data Structure Documentation
leanux::util::ConfigFile::RGB
struct leanux::util::ConfigFile::RGB
RGB color.
Definition at line 76 of file configfile.hpp.
Data Fields
unsigned short blue blue value.
unsigned short green green value.
unsigned short red red value.
Constructor & Destructor Documentation
ConfigFile()
leanux::util::ConfigFile::ConfigFile (const std::string & appname, const std::string & filename) private
Constructor, should not be called directly, use setConfig and getConfig to create the ConfigFile.
See also
getConfig.
Definition at line 53 of file configfile.cpp.
References appname_, filename_, and read().
Referenced by setConfig().
~ConfigFile()
leanux::util::ConfigFile::~ConfigFile () inline private
Destructor, should not be called directly.
See also
releaseConfig
Definition at line 197 of file configfile.hpp.
Member Function Documentation
cleanup()
void leanux::util::ConfigFile::cleanup ()
cleanup objects in configfiles_;
declareParameter()
void leanux::util::ConfigFile::declareParameter (const std::string & name, const std::string & value, const std::string & description, const std::string & comment = "") static
declare the configuration paramater and set a hardcoded default.
Parameters
name the parameter name
value the parameter default value
description the parameter description
comment parameter comment
Definition at line 259 of file configfile.cpp.
References comments_, defaults_, descriptions_, leanux::util::ConfigFile::Parameter::name_, and leanux::util::ConfigFile::Parameter::value_.
Referenced by leanux::tools::lmon::main(), and leanux::tools::lard::main().
getConfig()
ConfigFile * leanux::util::ConfigFile::getConfig () static
Get the ConfigurationFile object for the appname, or construct one if it does not exist.
setConfig(const std::string &appname, const std::string &filename) must be called first.
Returns
pointer to the ConfigFile, or 0 if setConfig was not called.
Definition at line 268 of file configfile.cpp.
References config_.
Referenced by leanux::tools::lard::applyRetention(), leanux::tools::lard::ensureSinglePid(), leanux::tools::lmon::IOView::getMinHeight(), leanux::tools::lmon::NetView::getMinHeight(), leanux::tools::lmon::IOView::getOptimalHeight(), leanux::tools::lard::initDB(), leanux::tools::lard::interrupt_handler(), leanux::tools::lmon::main(), leanux::tools::lard::main(), leanux::tools::lard::mainLoop(), leanux::tools::lmon::Screen::Screen(), leanux::tools::lmon::Palette::setup(), leanux::tools::lard::shrinkDB(), leanux::tools::lard::IOSnap::storeSnap(), leanux::tools::lard::ProcSnap::storeSnap(), leanux::tools::lard::MountSnap::storeSnap(), leanux::tools::lard::updateSchema(), leanux::tools::lard::wait_log_handler(), leanux::tools::lmon::IOView::xrefresh(), and leanux::tools::lmon::Screen::~Screen().
getIntValue()
int leanux::util::ConfigFile::getIntValue (const std::string & name) const
return the configuration parameter as an int.
Parameters
name the configuration parameter name.
Returns
the configuration parameter value.
Definition at line 221 of file configfile.cpp.
References getValue().
Referenced by leanux::tools::lmon::IOView::getMinHeight(), leanux::tools::lmon::NetView::getMinHeight(), leanux::tools::lard::mainLoop(), leanux::tools::lmon::Screen::Screen(), leanux::tools::lard::shrinkDB(), leanux::tools::lard::ProcSnap::storeSnap(), and leanux::tools::lmon::IOView::xrefresh().
getRGBValue()
ConfigFile::RGB leanux::util::ConfigFile::getRGBValue (const std::string & name) const
return the configuration parameter as a RGB struct.
Parameters
name the configuration parameter name.
Returns
the configuration parameter value.
Definition at line 172 of file configfile.cpp.
References leanux::util::ConfigFile::RGB::blue, getValue(), leanux::util::ConfigFile::RGB::green, and leanux::util::ConfigFile::RGB::red.
Referenced by leanux::tools::lmon::Palette::setup().
getStringListValue()
std::list< std::string > leanux::util::ConfigFile::getStringListValue (const std::string & name) const
return the configuration parameter as an int.
Parameters
name the configuration parameter name.
Returns
the configuration parameter value.
Definition at line 162 of file configfile.cpp.
References getValue().
Referenced by leanux::tools::lard::ProcSnap::storeSnap().
getValue()
std::string leanux::util::ConfigFile::getValue (const std::string & name) const
return the configuration parameter as a string.
Parameters
name the configuration parameter name.
Returns
the configuration parameter value.
Definition at line 155 of file configfile.cpp.
References defaults_, and values_.
Referenced by leanux::tools::lard::applyRetention(), getIntValue(), getRGBValue(), getStringListValue(), and leanux::tools::lard::initDB().
read()
void leanux::util::ConfigFile::read ()
read and interpret the configuration file.
Definition at line 59 of file configfile.cpp.
References defaults_, filename_, and values_.
Referenced by ConfigFile(), and leanux::tools::lmon::Screen::~Screen().
releaseConfig()
static void leanux::util::ConfigFile::releaseConfig () inline static
Release (delete) the configFile.
Definition at line 183 of file configfile.hpp.
References config_.
Referenced by leanux::tools::lard::main().
setConfig()
ConfigFile * leanux::util::ConfigFile::setConfig (const std::string & appname, const std::string & filename) static
set the application name and config file name.
Definition at line 272 of file configfile.cpp.
References config_, and ConfigFile().
Referenced by leanux::tools::lmon::main(), and leanux::tools::lard::main().
setValue() [1/4]
void leanux::util::ConfigFile::setValue (const std::string name, const RGB & value)
Set the configuration parameter to a RGB value.
Parameters
name the configuration parameter name.
value the RGB value to set.
Definition at line 240 of file configfile.cpp.
References leanux::util::ConfigFile::RGB::blue, defaults_, leanux::util::ConfigFile::RGB::green, leanux::util::ConfigFile::RGB::red, and values_.
setValue() [2/4]
void leanux::util::ConfigFile::setValue (const std::string name, const std::list< std::string > value)
Set the configuration parameter to a stringlist value.
Parameters
name the configuration parameter name.
value the stringlist value to set.
Definition at line 248 of file configfile.cpp.
References defaults_, and values_.
setValue() [3/4]
void leanux::util::ConfigFile::setValue (const std::string name, const std::string & value)
Set the configuration parameter to a string value.
Parameters
name the configuration parameter name.
value the string value to set.
Definition at line 234 of file configfile.cpp.
References defaults_, and values_.
setValue() [4/4]
void leanux::util::ConfigFile::setValue (const std::string name, int value)
Set the configuration parameter to an int value.
Parameters
name the configuration parameter name.
value the integer value to set.
Definition at line 226 of file configfile.cpp.
References defaults_, and values_.
Referenced by leanux::tools::lmon::Screen::~Screen().
write()
void leanux::util::ConfigFile::write (bool defaults = false)
write out the configuration file, including runtime modifications.
Parameters
defaults if set, overwrite with default values
Definition at line 115 of file configfile.cpp.
References appname_, comments_, defaults_, descriptions_, filename_, leanux::util::tokenize(), and values_.
Referenced by leanux::tools::lmon::main(), leanux::tools::lard::main(), and leanux::tools::lmon::Screen::~Screen().
Field Documentation
appname_
std::string leanux::util::ConfigFile::appname_ private
name of application owning the ConfigFile
Definition at line 197 of file configfile.hpp.
Referenced by ConfigFile(), and write().
comments_
std::map< std::string, std::string > leanux::util::ConfigFile::comments_ static private
Configuration parameter comments.
Definition at line 222 of file configfile.hpp.
Referenced by declareParameter(), and write().
config_
ConfigFile * leanux::util::ConfigFile::config_ = 0 static private
The singleton ConfigFile.
Definition at line 232 of file configfile.hpp.
Referenced by getConfig(), releaseConfig(), and setConfig().
defaults_
std::map< std::string, ConfigFile::Parameter > leanux::util::ConfigFile::defaults_ static private
Configuration parameter defaults.
Definition at line 227 of file configfile.hpp.
Referenced by declareParameter(), getValue(), read(), setValue(), and write().
descriptions_
std::map< std::string, std::string > leanux::util::ConfigFile::descriptions_ static private
Configuration parameter description.
Definition at line 217 of file configfile.hpp.
Referenced by declareParameter(), and write().
filename_
std::string leanux::util::ConfigFile::filename_ private
The filename of the ConfigFile.
Definition at line 207 of file configfile.hpp.
Referenced by ConfigFile(), read(), and write().
values_
std::map<std::string,Parameter> leanux::util::ConfigFile::values_ private
Current values.
Definition at line 212 of file configfile.hpp.
Referenced by getValue(), read(), setValue(), and write().
The documentation for this class was generated from the following files:
lib/configfile.hpp
lib/configfile.cpp