leanux: leanux::util::RegExp Class Reference
leanux::util::RegExp Class Reference
POSIX regular expression wrapper.
#include <util.hpp>
Public Member Functions
RegExp ()
~RegExp ()
bool match (const std::string &str) const
void set (const std::string &expr)
Private Attributes
std::string expr_
regex_t regex_
Detailed Description
POSIX regular expression wrapper.
Definition at line 313 of file util.hpp.
Constructor & Destructor Documentation
RegExp()
leanux::util::RegExp::RegExp () inline
Definition at line 315 of file util.hpp.
References expr_, and regex_.
~RegExp()
leanux::util::RegExp::~RegExp () inline
Definition at line 316 of file util.hpp.
References regex_.
Member Function Documentation
match()
bool leanux::util::RegExp::match (const std::string & str) const inline
Definition at line 324 of file util.hpp.
References regex_.
Referenced by leanux::sysdevice::NetDevice::accept(), leanux::sysdevice::VirtualNetDevice::accept(), leanux::sysdevice::SASPort::accept(), leanux::sysdevice::SASEndDevice::accept(), leanux::sysdevice::SCSIDevice::accept(), leanux::sysdevice::SCSIHost::accept(), leanux::sysdevice::SCSIRPort::accept(), leanux::sysdevice::SCSIVPort::accept(), leanux::sysdevice::iSCSIDevice::accept(), leanux::sysdevice::MMCDevice::accept(), leanux::sysdevice::NVMeDevice::accept(), leanux::sysdevice::NVMePartition::accept(), leanux::sysdevice::BCacheDevice::accept(), leanux::sysdevice::VirtioBlockDevice::accept(), leanux::sysdevice::VirtioNetDevice::accept(), leanux::sysdevice::MapperDevice::accept(), leanux::sysdevice::LoopbackDevice::accept(), leanux::sysdevice::RamDiskDevice::accept(), leanux::sysdevice::MDDevice::accept(), leanux::sysdevice::PCIDevice::accept(), leanux::sysdevice::USBDevice::accept(), leanux::sysdevice::USBInterface::accept(), leanux::sysdevice::USBBus::accept(), and leanux::tools::lsys::listDevices().
set()
void leanux::util::RegExp::set (const std::string & expr)
Definition at line 426 of file util.cpp.
References expr_, and regex_.
Referenced by leanux::sysdevice::NetDevice::accept(), leanux::sysdevice::VirtualNetDevice::accept(), leanux::sysdevice::SASPort::accept(), leanux::sysdevice::SASEndDevice::accept(), leanux::sysdevice::SCSIDevice::accept(), leanux::sysdevice::SCSIHost::accept(), leanux::sysdevice::SCSIRPort::accept(), leanux::sysdevice::SCSIVPort::accept(), leanux::sysdevice::iSCSIDevice::accept(), leanux::sysdevice::MMCDevice::accept(), leanux::sysdevice::NVMeDevice::accept(), leanux::sysdevice::NVMePartition::accept(), leanux::sysdevice::BCacheDevice::accept(), leanux::sysdevice::VirtioBlockDevice::accept(), leanux::sysdevice::VirtioNetDevice::accept(), leanux::sysdevice::MapperDevice::accept(), leanux::sysdevice::LoopbackDevice::accept(), leanux::sysdevice::RamDiskDevice::accept(), leanux::sysdevice::MDDevice::accept(), leanux::sysdevice::PCIDevice::accept(), leanux::sysdevice::USBDevice::accept(), leanux::sysdevice::USBInterface::accept(), leanux::sysdevice::USBBus::accept(), and leanux::tools::lsys::listDevices().
Field Documentation
expr_
std::string leanux::util::RegExp::expr_ private
Definition at line 321 of file util.hpp.
Referenced by RegExp(), and set().
regex_
regex_t leanux::util::RegExp::regex_ private
Definition at line 320 of file util.hpp.
Referenced by match(), RegExp(), set(), and ~RegExp().
The documentation for this class was generated from the following files:
lib/util.hpp
lib/util.cpp