leanux: leanux::tools::lard::VMSnap Class Reference
leanux::tools::lard::VMSnap Class Reference
#include <lar_snap.hpp>
Public Member Functions
VMSnap ()
virtual ~VMSnap ()
virtual void startSnap ()
virtual void stopSnap ()
virtual long storeSnap (const persist::Database &db, long snapid, double seconds)
Protected Attributes
vmem::VMStat stat1_
vmem::VMStat stat2_
Detailed Description
Definition at line 143 of file lar_snap.hpp.
Constructor & Destructor Documentation
VMSnap()
leanux::tools::lard::VMSnap::VMSnap () inline
Definition at line 145 of file lar_snap.hpp.
~VMSnap()
virtual leanux::tools::lard::VMSnap::~VMSnap () inline virtual
Definition at line 146 of file lar_snap.hpp.
Member Function Documentation
startSnap()
void leanux::tools::lard::VMSnap::startSnap () virtual
Implements leanux::tools::lard::Snapshot.
Definition at line 328 of file lar_snap.cpp.
References leanux::vmem::getVMStat(), and stat1_.
Referenced by leanux::tools::lard::mainLoop().
stopSnap()
void leanux::tools::lard::VMSnap::stopSnap () virtual
Implements leanux::tools::lard::Snapshot.
Definition at line 332 of file lar_snap.cpp.
References leanux::vmem::getVMStat(), and stat2_.
Referenced by leanux::tools::lard::mainLoop().
storeSnap()
long leanux::tools::lard::VMSnap::storeSnap (const persist::Database & db, long snapid, double seconds) virtual
Implements leanux::tools::lard::Snapshot.
Definition at line 336 of file lar_snap.cpp.
References leanux::persist::DML::bind(), leanux::vmem::VMStat::committed_as, leanux::persist::DML::execute(), leanux::system::getPageSize(), leanux::vmem::getSwapInfo(), leanux::vmem::VMStat::hugepages_free, leanux::vmem::VMStat::hugepages_reserved, leanux::vmem::VMStat::hugepages_total, leanux::vmem::VMStat::hugepagesize, leanux::vmem::VMStat::mem_total, leanux::vmem::VMStat::nr_anon_pages, leanux::vmem::VMStat::nr_anon_transparent_hugepages, leanux::vmem::VMStat::nr_dirty, leanux::vmem::VMStat::nr_file_pages, leanux::vmem::VMStat::nr_free_pages, leanux::vmem::VMStat::nr_mapped, leanux::vmem::VMStat::nr_mlock, leanux::vmem::VMStat::nr_page_table_pages, leanux::vmem::VMStat::nr_shmem, leanux::vmem::VMStat::nr_slab_reclaimable, leanux::vmem::VMStat::nr_slab_unreclaimable, leanux::vmem::VMStat::pgalloc_dma, leanux::vmem::VMStat::pgalloc_dma32, leanux::vmem::VMStat::pgalloc_movable, leanux::vmem::VMStat::pgalloc_normal, leanux::vmem::VMStat::pgfault, leanux::vmem::VMStat::pgfree, leanux::vmem::VMStat::pgmajfault, leanux::vmem::VMStat::pgpgin, leanux::vmem::VMStat::pgpgout, leanux::persist::Statement::prepare(), leanux::vmem::VMStat::pswpin, leanux::vmem::VMStat::pswpout, stat1_, and stat2_.
Referenced by leanux::tools::lard::mainLoop().
Field Documentation
stat1_
vmem::VMStat leanux::tools::lard::VMSnap::stat1_ protected
Definition at line 152 of file lar_snap.hpp.
Referenced by startSnap(), and storeSnap().
stat2_
vmem::VMStat leanux::tools::lard::VMSnap::stat2_ protected
Definition at line 153 of file lar_snap.hpp.
Referenced by stopSnap(), and storeSnap().
The documentation for this class was generated from the following files:
tools/lard/lar_snap.hpp
tools/lard/lar_snap.cpp