leanux: leanux::tools::lard::SchedSnap Class Reference
leanux::tools::lard::SchedSnap Class Reference
#include <lar_snap.hpp>
Public Member Functions
SchedSnap ()
virtual ~SchedSnap ()
virtual void startSnap ()
virtual void stopSnap ()
virtual long storeSnap (const persist::Database &db, long snapid, double seconds)
Protected Attributes
cpu::LoadAvg load1_
cpu::LoadAvg load2_
cpu::SchedInfo sched1_
cpu::SchedInfo sched2_
Detailed Description
Definition at line 114 of file lar_snap.hpp.
Constructor & Destructor Documentation
SchedSnap()
leanux::tools::lard::SchedSnap::SchedSnap () inline
Definition at line 116 of file lar_snap.hpp.
~SchedSnap()
virtual leanux::tools::lard::SchedSnap::~SchedSnap () inline virtual
Definition at line 117 of file lar_snap.hpp.
Member Function Documentation
startSnap()
void leanux::tools::lard::SchedSnap::startSnap () virtual
Implements leanux::tools::lard::Snapshot.
Definition at line 228 of file lar_snap.cpp.
References leanux::cpu::getLoadAvg(), leanux::cpu::getSchedInfo(), load1_, and sched1_.
Referenced by leanux::tools::lard::mainLoop().
stopSnap()
void leanux::tools::lard::SchedSnap::stopSnap () virtual
Implements leanux::tools::lard::Snapshot.
Definition at line 233 of file lar_snap.cpp.
References leanux::cpu::getLoadAvg(), leanux::cpu::getSchedInfo(), load2_, and sched2_.
Referenced by leanux::tools::lard::mainLoop().
storeSnap()
long leanux::tools::lard::SchedSnap::storeSnap (const persist::Database & db, long snapid, double seconds) virtual
Implements leanux::tools::lard::Snapshot.
Definition at line 238 of file lar_snap.cpp.
References leanux::cpu::LoadAvg::avg10_, leanux::cpu::LoadAvg::avg15_, leanux::cpu::LoadAvg::avg5_, leanux::persist::DML::bind(), leanux::cpu::SchedInfo::blocked, leanux::cpu::SchedInfo::ctxt, leanux::persist::DML::execute(), load2_, leanux::persist::Statement::prepare(), leanux::cpu::SchedInfo::processes, leanux::cpu::SchedInfo::running, sched1_, and sched2_.
Referenced by leanux::tools::lard::mainLoop().
Field Documentation
load1_
cpu::LoadAvg leanux::tools::lard::SchedSnap::load1_ protected
Definition at line 125 of file lar_snap.hpp.
Referenced by startSnap().
load2_
cpu::LoadAvg leanux::tools::lard::SchedSnap::load2_ protected
Definition at line 126 of file lar_snap.hpp.
Referenced by stopSnap(), and storeSnap().
sched1_
cpu::SchedInfo leanux::tools::lard::SchedSnap::sched1_ protected
Definition at line 123 of file lar_snap.hpp.
Referenced by startSnap(), and storeSnap().
sched2_
cpu::SchedInfo leanux::tools::lard::SchedSnap::sched2_ protected
Definition at line 124 of file lar_snap.hpp.
Referenced by stopSnap(), and storeSnap().
The documentation for this class was generated from the following files:
tools/lard/lar_snap.hpp
tools/lard/lar_snap.cpp