leanux: leanux::tools::lard::TimeSnap Class Reference
leanux::tools::lard::TimeSnap Class Reference
#include <lar_snap.hpp>
Public Member Functions
TimeSnap ()
virtual ~TimeSnap ()
long getSeconds () const
virtual void startSnap ()
virtual void stopSnap ()
virtual long storeSnap (const persist::Database &db, long snapid, double seconds)
Protected Attributes
time_t istart_
time_t istop_
Detailed Description
Definition at line 72 of file lar_snap.hpp.
Constructor & Destructor Documentation
TimeSnap()
leanux::tools::lard::TimeSnap::TimeSnap () inline
Definition at line 74 of file lar_snap.hpp.
References istart_, and istop_.
~TimeSnap()
virtual leanux::tools::lard::TimeSnap::~TimeSnap () inline virtual
Definition at line 75 of file lar_snap.hpp.
Member Function Documentation
getSeconds()
long leanux::tools::lard::TimeSnap::getSeconds () const inline
Definition at line 80 of file lar_snap.hpp.
Referenced by leanux::tools::lard::mainLoop().
startSnap()
virtual void leanux::tools::lard::TimeSnap::startSnap () inline virtual
Implements leanux::tools::lard::Snapshot.
Definition at line 76 of file lar_snap.hpp.
References istart_.
Referenced by leanux::tools::lard::mainLoop().
stopSnap()
virtual void leanux::tools::lard::TimeSnap::stopSnap () inline virtual
Implements leanux::tools::lard::Snapshot.
Definition at line 77 of file lar_snap.hpp.
References istop_.
Referenced by leanux::tools::lard::mainLoop().
storeSnap()
long leanux::tools::lard::TimeSnap::storeSnap (const persist::Database & db, long snapid, double seconds) virtual
Implements leanux::tools::lard::Snapshot.
Definition at line 92 of file lar_snap.cpp.
References leanux::persist::DML::bind(), leanux::persist::DML::execute(), istart_, istop_, leanux::persist::Database::lastInsertRowid(), and leanux::persist::Statement::prepare().
Referenced by leanux::tools::lard::mainLoop().
Field Documentation
istart_
time_t leanux::tools::lard::TimeSnap::istart_ protected
Definition at line 80 of file lar_snap.hpp.
Referenced by startSnap(), storeSnap(), and TimeSnap().
istop_
time_t leanux::tools::lard::TimeSnap::istop_ protected
Definition at line 83 of file lar_snap.hpp.
Referenced by stopSnap(), storeSnap(), and TimeSnap().
The documentation for this class was generated from the following files:
tools/lard/lar_snap.hpp
tools/lard/lar_snap.cpp