leanux: leanux::block Namespace Reference
leanux::block Namespace Reference
block device API.
Data Structures
struct DeviceStats
Device stats from /proc/diskstats.
class MajorMinor
Datatype for major:minor pairs.
struct MountInfo
Mounted filesystem configuration.
class StatsSorter
sorter for DeviceStatsMap delta.
Typedefs
typedef std::map< MajorMinor, DeviceStats > DeviceStatsMap
map of MajorMinor to DeviceStats.
typedef std::vector< MajorMinor > MajorMinorVector
vector of MajorMinor
Enumerations
enum DeviceClass {
Unknown, RAMDisk, FloppyDisk, IDEDisk,
IDEDiskPartition, Loopback, SCSIDisk, SCSIDiskPartition,
MetaDisk, SCSICD, DeviceMapper, LVM,
MultiPath, VirtioDisk, VirtioDiskPartition, NVMeDisk,
NVMeDiskPartition, MMCDisk, MMCDiskPartition, BCacheDisk,
BCacheDiskPartition
}
Enumeration to discern device types.
enum udevMode { umBlockMM, umBlockName, umBMM }
Three naming conventions for udev block device entries.
Functions
void deltaDeviceStats (const DeviceStatsMap &snap1, const DeviceStatsMap &snap2, DeviceStatsMap &delta, MajorMinorVector &vec)
create a delta of two DeviceStatsMaps.
void enumDevices (std::list< MajorMinor > &devices)
get a list of all block devices
void enumDevices (std::list< MajorMinor > &devices, DeviceClass t)
get a list of block devices of the specified DeviceClass
void enumLVMPVS (std::list< MajorMinor > &devices)
get a list of LVM physical volumes
void enumMounts (std::map< MajorMinor, MountInfo > &mounts)
Get a map of MajorMinor to MountInfo from /proc/mounts.
void enumMounts (std::map< MajorMinor, MountInfo > &mounts, std::map< std::string, MajorMinor > &cache)
Variant of enumMounts that accepts a cache of previously detected mappings between device special file names and MajorMinor.
void enumWholeDisks (std::list< MajorMinor > &devices)
get a list of whole disks (exclude partitions).
std::string getATADeviceName (const std::string &device)
get the ata device name from a device path
std::string getATALinkSpeed (const std::string &ata_port, const std::string &ata_link)
Get the ATA port link speed.
std::string getATAPortLink (const std::string &port)
Get the ATA port link.
std::string getATAPortName (const std::string &device)
return the ata port name from the device path
unsigned long getAttachedStorageSize ()
total attached storage.
unsigned long getAttachedWholeDisks ()
Get the number of attached whole disks.
MajorMinor getFileMajorMinor (const std::string &devicefile)
get the MajorMinor for a device file or aliases to it, resolves the devicefile with realpath.
unsigned long getMountUsedBytes ()
Used bytes over all mounted filesystems.
unsigned long getMountUsedBytes (const std::string &mount)
Bytes used on the filesystem.
void getStats (DeviceStatsMap &statsmap)
get block device statistics into a DeviceStatsMap.
void init ()
Initialize the block API.
udevMode modeFromMajorMinor (const MajorMinor &m, const std::string &udev_path)
Detect the udevMode from the given MajorMinor and udev_path.
int operator< (const DeviceStats &s1, const DeviceStats &s2)
less-than operator for DeviceStats type, used for sorting.
std::ostream & operator<< (std::ostream &s, const MajorMinor &m)
Write MajorMinor to stream as a string, eg {8,0} is written as '8:0'.
int operator== (const DeviceStats &s1, const DeviceStats &s2)
test DeviceStats equality.
Variables
udevMode udev_mode = umBlockMM
The detected udevMode.
std::string udev_path = ""
base directory for runtime udev information.
Detailed Description
block device API.
Block devices are represented by instances of the MajorMinor class, of which the member functions retrieve per-block device statistics. Block devices present on the system are enumerated into lists of MajorMinor objects with one of the enum* functions, such as enumWholeDisks(std::list< MajorMinor > &devices).
Data Structure Documentation
leanux::block::DeviceStats
struct leanux::block::DeviceStats
Device stats from /proc/diskstats.
See also
iostats.txt in the Linux kernel docs.
Examples
example_pci.cpp.
Definition at line 112 of file block.hpp.
Data Fields
unsigned long io_in_progress number of io's in progress (or pending and queued)
unsigned long io_ms number of milliseconds spent doing IO
unsigned long io_weighted_ms not sure.
unsigned long iodone_cnt number of SCSI IO's completed
unsigned long ioerr_cnt number of SCSI IO errors
unsigned long iorequest_cnt number of SCSI IO's requested
unsigned long read_ms number of milliseconds spent reading
unsigned long read_sectors number of sectors read
unsigned long reads number of read operations
unsigned long reads_merged number of read operations merged with other read operations
unsigned long write_ms number of milliseconds spent writing
unsigned long write_sectors number of sectors written
unsigned long writes number of write operations
unsigned long writes_merged number of writes merged with other write operations
leanux::block::MountInfo
struct leanux::block::MountInfo
Mounted filesystem configuration.
Definition at line 70 of file block.hpp.
Data Fields
string attrs The mount attributes.
string device The name of the device containing the filesystem.
string fstype The type of filesystem.
string mountpoint The mountpoint of the filesystem.
Typedef Documentation
DeviceStatsMap
typedef std::map<MajorMinor,DeviceStats> leanux::block::DeviceStatsMap
map of MajorMinor to DeviceStats.
Definition at line 878 of file block.hpp.
MajorMinorVector
typedef std::vector<MajorMinor> leanux::block::MajorMinorVector
vector of MajorMinor
Definition at line 881 of file block.hpp.
Enumeration Type Documentation
DeviceClass
enum leanux::block::DeviceClass
Enumeration to discern device types.
Enumerator
Unknown
RAMDisk
FloppyDisk
IDEDisk
IDEDiskPartition
Loopback
SCSIDisk
SCSIDiskPartition
MetaDisk
SCSICD
DeviceMapper
LVM
MultiPath
VirtioDisk
VirtioDiskPartition
NVMeDisk
NVMeDiskPartition
MMCDisk
MMCDiskPartition
BCacheDisk
BCacheDiskPartition
Definition at line 84 of file block.hpp.
udevMode
enum leanux::block::udevMode
Three naming conventions for udev block device entries.
See also
init
Enumerator
umBlockMM
block8:0
umBlockName
block:sda
umBMM
b8:0
Definition at line 81 of file block.cpp.
Function Documentation
deltaDeviceStats()
void leanux::block::deltaDeviceStats (const DeviceStatsMap & snap1, const DeviceStatsMap & snap2, DeviceStatsMap & delta, MajorMinorVector & vec)
create a delta of two DeviceStatsMaps.
Only MajorMinor objects present in both snapshots are returned in delta.
Parameters
snap1 first (earlier) DeviceStatsMap.
snap2 second (later) DeviceStatsMap.
delta DeviceStatsMap receiving the delta.
vec out unsorted vector of MajorMinor entries in the delta map
See also
StatsSorter
Definition at line 1271 of file block.cpp.
Referenced by leanux::tools::lmon::RealtimeSampler::sampleXIOView(), leanux::tools::lard::IOSnap::storeSnap(), and leanux::tools::lard::MountSnap::storeSnap().
enumDevices() [1/2]
void leanux::block::enumDevices (std::list< MajorMinor > & devices)
get a list of all block devices
Parameters
devices the device list to fill
Definition at line 1092 of file block.cpp.
Referenced by enumLVMPVS(), leanux::tools::lrep::htmlSystemDetails(), leanux::tools::lblk::listAllDevices(), and leanux::tools::lblk::listAllMetaDisks().
enumDevices() [2/2]
void leanux::block::enumDevices (std::list< MajorMinor > & devices, DeviceClass t)
get a list of block devices of the specified DeviceClass
Parameters
devices the list to fill
t list only these type of block devices
Definition at line 1105 of file block.cpp.
enumLVMPVS()
void leanux::block::enumLVMPVS (std::list< MajorMinor > & devices)
get a list of LVM physical volumes
Parameters
devices list of LVM physical volumes
Definition at line 1118 of file block.cpp.
References enumDevices().
Referenced by leanux::tools::lblk::listLVM().
enumMounts() [1/2]
void leanux::block::enumMounts (std::map< MajorMinor, MountInfo > & mounts)
Get a map of MajorMinor to MountInfo from /proc/mounts.
Parameters
mounts receives the map.
Definition at line 1032 of file block.cpp.
References leanux::block::MountInfo::attrs, leanux::block::MountInfo::device, leanux::block::MountInfo::fstype, getFileMajorMinor(), leanux::block::MajorMinor::getName(), leanux::block::MajorMinor::isValid(), and leanux::block::MountInfo::mountpoint.
Referenced by leanux::block::MajorMinor::getMountInfo(), leanux::tools::lmon::IOView::getOptimalHeight(), leanux::tools::lmon::RealtimeSampler::sampleXIOView(), leanux::tools::lard::MountSnap::stopSnap(), and leanux::tools::lard::MountSnap::storeSnap().
enumMounts() [2/2]
void leanux::block::enumMounts (std::map< MajorMinor, MountInfo > & mounts, std::map< std::string, MajorMinor > & cache)
Variant of enumMounts that accepts a cache of previously detected mappings between device special file names and MajorMinor.
This cache will be updated when entries are absent, so the first call may specify an empty cache, causing subsequent calls to hit and avoid a relatively costly lookup.
Parameters
mounts receives the map.
cache read through on cache miss, add to cache.
Definition at line 1056 of file block.cpp.
References leanux::block::MountInfo::attrs, leanux::block::MountInfo::device, leanux::block::MountInfo::fstype, getFileMajorMinor(), leanux::block::MajorMinor::getName(), leanux::block::MajorMinor::invalid, leanux::block::MajorMinor::isValid(), and leanux::block::MountInfo::mountpoint.
enumWholeDisks()
void leanux::block::enumWholeDisks (std::list< MajorMinor > & devices)
get a list of whole disks (exclude partitions).
Parameters
devices list of whole disk MajorMinors.
See also
MajorMinor::isWholeDisk
Definition at line 1129 of file block.cpp.
Referenced by leanux::tools::labbix::discovery(), leanux::tools::labbix::findByZabbix(), leanux::tools::lmon::Footer::Footer(), getAttachedStorageSize(), getAttachedWholeDisks(), leanux::tools::lrep::htmlDiskDetails(), leanux::tools::lrep::htmlSystemDetails(), init(), and leanux::tools::lblk::listAllDisks().
getATADeviceName()
std::string leanux::block::getATADeviceName (const std::string & device)
get the ata device name from a device path
Examples
example_pci.cpp.
Definition at line 963 of file block.cpp.
getATALinkSpeed()
std::string leanux::block::getATALinkSpeed (const std::string & ata_port, const std::string & ata_link)
Get the ATA port link speed.
Parameters
ata_port the ATA port as in 'ata1'.
ata_link the ATA port link as in 'link1'.
Returns
the ATA port link speed.
Definition at line 956 of file block.cpp.
References leanux::util::fileReadString().
Referenced by leanux::sysdevice::ATAPort::getDescription(), leanux::tools::lsys::getLeafColStr(), and leanux::sysdevice::ATAPort::getPropertyValueList().
getATAPortLink()
std::string leanux::block::getATAPortLink (const std::string & port)
Get the ATA port link.
Parameters
port the ATA port as in 'ata1'.
Returns
the ATA port link.
Definition at line 949 of file block.cpp.
References leanux::util::findDir().
Referenced by leanux::sysdevice::ATAPort::getDescription(), leanux::tools::lsys::getLeafColStr(), and leanux::sysdevice::ATAPort::getPropertyValueList().
getATAPortName()
std::string leanux::block::getATAPortName (const std::string & device)
return the ata port name from the device path
Definition at line 1015 of file block.cpp.
Referenced by leanux::sysdevice::ATAPort::getPropertyValueList().
getAttachedStorageSize()
unsigned long leanux::block::getAttachedStorageSize ()
total attached storage.
identical WWN's (multipath, software raid) are counted only once.
Returns
the attached storage size in bytes.
Definition at line 1142 of file block.cpp.
References enumWholeDisks().
Referenced by leanux::tools::lmon::Footer::Footer(), and leanux::tools::lrep::htmlSystemDetails().
getAttachedWholeDisks()
unsigned long leanux::block::getAttachedWholeDisks ()
Get the number of attached whole disks.
Returns
the number of attached whole disks.
Definition at line 1161 of file block.cpp.
References enumWholeDisks().
Referenced by leanux::tools::lmon::IOView::getOptimalHeight().
getFileMajorMinor()
MajorMinor leanux::block::getFileMajorMinor (const std::string & devicefile)
get the MajorMinor for a device file or aliases to it, resolves the devicefile with realpath.
Parameters
devicefile the device special file or an alias (link) to it.
Returns
the MajorMinor or MajorMinor::invalid
Definition at line 1024 of file block.cpp.
References leanux::block::MajorMinor::invalid, and leanux::util::realPath().
Referenced by enumMounts(), leanux::tools::lmon::RealtimeSampler::sampleXIOView(), and leanux::tools::lard::MountSnap::storeSnap().
getMountUsedBytes() [1/2]
unsigned long leanux::block::getMountUsedBytes ()
Used bytes over all mounted filesystems.
Returns
the number of bytes used.
Definition at line 1316 of file block.cpp.
References leanux::block::MountInfo::attrs, leanux::block::MountInfo::device, leanux::block::MountInfo::fstype, and leanux::block::MountInfo::mountpoint.
Referenced by leanux::tools::lmon::RealtimeSampler::sampleXIOView(), leanux::tools::lmon::RealtimeSampler::sampleXSysView(), and leanux::tools::lard::MountSnap::stopSnap().
getMountUsedBytes() [2/2]
unsigned long leanux::block::getMountUsedBytes (const std::string & mount)
Bytes used on the filesystem.
btrfs breaks the stat (2) call, by reporting an invalid major:minor pair, and hence btrfs breaks this function.
Parameters
mount the filesystem mountpoint (or any file on the filesystem).
Returns
the number of bytes used. always returns zero on btrfs.
Definition at line 1341 of file block.cpp.
getStats()
void leanux::block::getStats (DeviceStatsMap & statsmap)
get block device statistics into a DeviceStatsMap.
Parameters
statsmap the DeviceStatsMap to fill
Definition at line 1240 of file block.cpp.
References leanux::block::MajorMinor::getSCSIIODone(), leanux::block::MajorMinor::getSCSIIOError(), leanux::block::MajorMinor::getSCSIIORequest(), leanux::block::DeviceStats::io_in_progress, leanux::block::DeviceStats::io_ms, leanux::block::DeviceStats::io_weighted_ms, leanux::block::DeviceStats::iodone_cnt, leanux::block::DeviceStats::ioerr_cnt, leanux::block::DeviceStats::iorequest_cnt, leanux::block::DeviceStats::read_ms, leanux::block::DeviceStats::read_sectors, leanux::block::DeviceStats::reads, leanux::block::DeviceStats::reads_merged, leanux::block::DeviceStats::write_ms, leanux::block::DeviceStats::write_sectors, leanux::block::DeviceStats::writes, and leanux::block::DeviceStats::writes_merged.
Referenced by leanux::tools::lmon::RealtimeSampler::sampleXIOView(), leanux::tools::lard::IOSnap::startSnap(), leanux::tools::lard::MountSnap::startSnap(), leanux::tools::lard::IOSnap::stopSnap(), and leanux::tools::lard::MountSnap::stopSnap().
init()
void leanux::block::init ()
Initialize the block API.
This is implicitly called by leanux::init.
See also
leanux::init.
Examples
example_pci.cpp.
Definition at line 118 of file block.cpp.
References leanux::util::directoryExists(), enumWholeDisks(), leanux::block::MajorMinor::getMajor(), leanux::block::MajorMinor::isValid(), modeFromMajorMinor(), udev_mode, and udev_path.
Referenced by leanux::init().
modeFromMajorMinor()
udevMode leanux::block::modeFromMajorMinor (const MajorMinor & m, const std::string & udev_path)
Detect the udevMode from the given MajorMinor and udev_path.
Definition at line 97 of file block.cpp.
References leanux::util::fileReadAccess(), leanux::block::MajorMinor::getNameByMajorMinor(), udev_path, umBlockMM, umBlockName, and umBMM.
Referenced by init().
operator<()
int leanux::block::operator< (const DeviceStats & s1, const DeviceStats & s2) inline
less-than operator for DeviceStats type, used for sorting.
DeviceStats with more IO activity are <.
See also
int StatsSorter::operator()(MajorMinor m1, MajorMinor m2)
Parameters
s1 DeviceStats 1
s2 DeviceStats 2
Returns
1 if s1 < s2, 0 otherwise.
Definition at line 854 of file block.hpp.
References leanux::block::DeviceStats::io_ms, leanux::block::DeviceStats::reads, and leanux::block::DeviceStats::writes.
operator<<()
std::ostream& leanux::block::operator<< (std::ostream & s, const MajorMinor & m) inline
Write MajorMinor to stream as a string, eg {8,0} is written as '8:0'.
Definition at line 738 of file block.hpp.
References leanux::block::MajorMinor::getDevT().
operator==()
int leanux::block::operator== (const DeviceStats & s1, const DeviceStats & s2) inline
test DeviceStats equality.
Parameters
s1 first DeviceStats
s2 second DeviceStats
Returns
1 if the two DeviceStats are equal, 0 if not.
Definition at line 865 of file block.hpp.
References leanux::block::DeviceStats::io_ms, leanux::block::DeviceStats::read_ms, leanux::block::DeviceStats::read_sectors, leanux::block::DeviceStats::reads, leanux::block::DeviceStats::reads_merged, leanux::block::DeviceStats::write_ms, leanux::block::DeviceStats::write_sectors, leanux::block::DeviceStats::writes, and leanux::block::DeviceStats::writes_merged.
Variable Documentation
udev_mode
udevMode leanux::block::udev_mode = umBlockMM
The detected udevMode.
See also
init.
Definition at line 92 of file block.cpp.
Referenced by leanux::block::MajorMinor::getUDevPath(), and init().
udev_path
std::string leanux::block::udev_path = ""
base directory for runtime udev information.
See also
init
Definition at line 75 of file block.cpp.
Referenced by leanux::block::MajorMinor::getUDevPath(), init(), and modeFromMajorMinor().