leanux: leanux::tools::lard::CPUSnap Class Reference
leanux::tools::lard::CPUSnap Class Reference
#include <lar_snap.hpp>
Public Member Functions
CPUSnap ()
virtual ~CPUSnap ()
virtual void startSnap ()
virtual void stopSnap ()
virtual long storeSnap (const persist::Database &db, long snapid, double seconds)
Protected Attributes
cpu::CPUStatsMap stat1_
cpu::CPUStatsMap stat2_
Detailed Description
Definition at line 100 of file lar_snap.hpp.
Constructor & Destructor Documentation
CPUSnap()
leanux::tools::lard::CPUSnap::CPUSnap () inline
Definition at line 102 of file lar_snap.hpp.
~CPUSnap()
virtual leanux::tools::lard::CPUSnap::~CPUSnap () inline virtual
Definition at line 103 of file lar_snap.hpp.
Member Function Documentation
startSnap()
void leanux::tools::lard::CPUSnap::startSnap () virtual
Implements leanux::tools::lard::Snapshot.
Definition at line 185 of file lar_snap.cpp.
References leanux::cpu::getCPUStats(), and stat1_.
Referenced by leanux::tools::lard::mainLoop().
stopSnap()
void leanux::tools::lard::CPUSnap::stopSnap () virtual
Implements leanux::tools::lard::Snapshot.
Definition at line 189 of file lar_snap.cpp.
References leanux::cpu::getCPUStats(), and stat2_.
Referenced by leanux::tools::lard::mainLoop().
storeSnap()
long leanux::tools::lard::CPUSnap::storeSnap (const persist::Database & db, long snapid, double seconds) virtual
Implements leanux::tools::lard::Snapshot.
Definition at line 193 of file lar_snap.cpp.
References leanux::persist::DML::bind(), leanux::persist::DML::execute(), leanux::cpu::getCPUCoreId(), leanux::cpu::getCPUPhysicalId(), leanux::persist::Statement::prepare(), stat1_, and stat2_.
Referenced by leanux::tools::lard::mainLoop().
Field Documentation
stat1_
cpu::CPUStatsMap leanux::tools::lard::CPUSnap::stat1_ protected
Definition at line 109 of file lar_snap.hpp.
Referenced by startSnap(), and storeSnap().
stat2_
cpu::CPUStatsMap leanux::tools::lard::CPUSnap::stat2_ protected
Definition at line 110 of file lar_snap.hpp.
Referenced by stopSnap(), and storeSnap().
The documentation for this class was generated from the following files:
tools/lard/lar_snap.hpp
tools/lard/lar_snap.cpp