leanux: leanux::sysdevice::LoopbackDevice Class Reference
leanux::sysdevice::LoopbackDevice Class Reference
Say yes to loopback devices.
#include <device.hpp>
Public Types
enum SysDeviceType {
sdtAbstract, sdtATAPort, sdtBCacheDevice, sdtBlock,
sdtiSCSIDevice, sdtMapperDevice, sdtMetaDisk, sdtMMCDevice,
sdtNetDevice, sdtNVMeDevice, sdtNVMePartition, sdtBlockPartition,
sdtPCIBus, sdtPCIDevice, sdtSASPort, sdtSASEndDevice,
sdtSCSIDevice, sdtSCSIHost, sdtSCSIRPort, sdtSCSIVPort,
sdtUSBBus, sdtUSBInterface, sdtUSBDevice, sdtVirtioBlockDevice,
sdtVirtioNetDevice, sdtVirtualNetDevice, sdtLoopbackDevice, sdtRAMDiskDevice,
sdtVirtualRoot, sdtVirtualBlockRoot, sdtVirtualNetRoot, sdtUnknown
}
SysDevice type.
Public Member Functions
LoopbackDevice ()
LoopbackDevice (const LoopbackDevice &src)
virtual bool accept (SysDevicePath &path)
Return true if the SysDevice recognizes itself in the trailing part of path.
virtual std::string getClass () const
Get the device class for this device.
virtual std::string getDescription () const
Get a human readable description of this SysDevice.
virtual std::string getDisplayName () const
virtual std::string getDriver () const
Get the driver for this device.
SysDevicePath getLeaf () const
block::MajorMinor getMajorMinor () const
virtual std::string getModel () const
SysDevicePath getPath () const
Get the path for the SysDevice.
virtual void getPropertyValueList (PropertyValueList &pv) const
virtual SysDeviceType getType () const
Get the SysDeviceType.
virtual std::string getVendor () const
virtual bool matchSysDeviceType (SysDeviceType t) const
test if this SysDevice is of type t.
Static Public Member Functions
static std::string getTypeStr (SysDeviceType)
Get a string representation for the SysDeviceType.
static void tokenize (const SysDevicePath &path, std::list< std::string > &tokens)
Transform a SysDevicePath into a list of tokens in reverse order.
static bool validatePath (const SysDevicePath &path)
Test SysDevicePath validity; path must exist (be readable) and located under /sys/devices.
Protected Attributes
std::string leaf_
The leaf of the path_ for this SysDevice.
SysDevicePath path_
The path for this device.
SysDeviceType sysdevicetype_
The SysDevice SysDeviceType.
Detailed Description
Say yes to loopback devices.
Definition at line 557 of file device.hpp.
Member Enumeration Documentation
SysDeviceType
enum leanux::sysdevice::SysDevice::SysDeviceType inherited
SysDevice type.
Enumerator
sdtAbstract
sdtATAPort
ATA/SATA port.
sdtBCacheDevice
bcache block device
sdtBlock
generic block device
sdtiSCSIDevice
iSCSI device
sdtMapperDevice
device mapper block device
sdtMetaDisk
MetaDisk.
sdtMMCDevice
MMC disk.
sdtNetDevice
network device
sdtNVMeDevice
NVMe disk.
sdtNVMePartition
NVMe partition.
sdtBlockPartition
generic block partition
sdtPCIBus
PCI bus.
sdtPCIDevice
PCI device.
sdtSASPort
SAS port.
sdtSASEndDevice
SAS end device.
sdtSCSIDevice
SCSI device.
sdtSCSIHost
SCSI host.
sdtSCSIRPort
SCSI rport.
sdtSCSIVPort
SCSI rport.
sdtUSBBus
USB bus.
sdtUSBInterface
USB interface (USB device operation mode)
sdtUSBDevice
USB device.
sdtVirtioBlockDevice
virtio block device
sdtVirtioNetDevice
virtio network device
sdtVirtualNetDevice
virtual network device
sdtLoopbackDevice
loopback block device
sdtRAMDiskDevice
ram disk block device
sdtVirtualRoot
root for virtual devices
sdtVirtualBlockRoot
root for virtual block devices
sdtVirtualNetRoot
root for virtual net devices
sdtUnknown
unknown device
Definition at line 107 of file device.hpp.
Constructor & Destructor Documentation
LoopbackDevice() [1/2]
leanux::sysdevice::LoopbackDevice::LoopbackDevice () inline
Definition at line 559 of file device.hpp.
References leanux::sysdevice::SysDevice::sdtLoopbackDevice, and leanux::sysdevice::SysDevice::sysdevicetype_.
LoopbackDevice() [2/2]
leanux::sysdevice::LoopbackDevice::LoopbackDevice (const LoopbackDevice & src) inline
Definition at line 560 of file device.hpp.
Member Function Documentation
accept()
bool leanux::sysdevice::LoopbackDevice::accept (SysDevicePath & path) virtual
Return true if the SysDevice recognizes itself in the trailing part of path.
If so, the path is stripped so that it ends with the parent device, which may be empty for top level devices. Should be implemented by descendent classes.
Parameters
path the SysDevicePath to accept.
Returns
true when the SysDevice descendent accepts the path as valid.
Reimplemented from leanux::sysdevice::SysDevice.
Definition at line 654 of file device.cpp.
References leanux::sysdevice::SysDevice::leaf_, leanux::util::RegExp::match(), leanux::sysdevice::SysDevice::path_, leanux::util::RegExp::set(), and leanux::sysdevice::SysDevice::tokenize().
Referenced by leanux::sysdevice::leafDetect().
getClass()
virtual std::string leanux::sysdevice::SysDevice::getClass () const inline virtual inherited
Get the device class for this device.
Returns
the device class, or an empty string if undetermined.
Reimplemented in leanux::sysdevice::USBBus, leanux::sysdevice::USBInterface, leanux::sysdevice::USBDevice, leanux::sysdevice::PCIDevice, leanux::sysdevice::UnknownSysDevice, and leanux::sysdevice::BusDevice.
Definition at line 218 of file device.hpp.
Referenced by leanux::sysdevice::SysDevice::getPropertyValueList().
getDescription()
std::string leanux::sysdevice::BlockDevice::getDescription () const virtual inherited
Get a human readable description of this SysDevice.
Reimplemented from leanux::sysdevice::SysDevice.
Reimplemented in leanux::sysdevice::iSCSIDevice, and leanux::sysdevice::SCSIDevice.
Definition at line 150 of file device.cpp.
References leanux::sysdevice::BlockDevice::getMajorMinor(), and leanux::block::MajorMinor::getModel().
Referenced by leanux::sysdevice::SCSIDevice::getDescription().
getDisplayName()
std::string leanux::sysdevice::BlockDevice::getDisplayName () const virtual inherited
Reimplemented from leanux::sysdevice::SysDevice.
Reimplemented in leanux::sysdevice::BlockPartition.
Definition at line 141 of file device.cpp.
References leanux::sysdevice::BlockDevice::getMajorMinor(), leanux::sysdevice::SysDevice::getModel(), leanux::block::MajorMinor::getModel(), and leanux::block::MajorMinor::getName().
getDriver()
std::string leanux::sysdevice::BlockDevice::getDriver () const virtual inherited
Get the driver for this device.
Returns
the driver, or an empty string if no driver associated.
Reimplemented from leanux::sysdevice::SysDevice.
Reimplemented in leanux::sysdevice::NVMePartition, and leanux::sysdevice::BlockPartition.
Definition at line 2031 of file device.cpp.
References leanux::util::directoryExists(), leanux::sysdevice::SysDevice::path_, and leanux::util::realPath().
getLeaf()
SysDevicePath leanux::sysdevice::SysDevice::getLeaf () const inline inherited
Definition at line 182 of file device.hpp.
References leanux::sysdevice::SysDevice::leaf_.
getMajorMinor()
block::MajorMinor leanux::sysdevice::BlockDevice::getMajorMinor () const inherited
Definition at line 88 of file device.cpp.
References leanux::util::fileReadAccess(), leanux::util::fileReadString(), leanux::block::MajorMinor::invalid, and leanux::sysdevice::SysDevice::path_.
Referenced by leanux::sysdevice::BlockDevice::getDescription(), leanux::sysdevice::iSCSIDevice::getDescription(), leanux::sysdevice::BlockDevice::getDisplayName(), leanux::sysdevice::BlockPartition::getDisplayName(), leanux::tools::lsys::getLeafColStr(), leanux::sysdevice::BlockDevice::getPropertyValueList(), leanux::sysdevice::BlockPartition::getPropertyValueList(), leanux::sysdevice::NVMeDevice::getPropertyValueList(), leanux::sysdevice::NVMePartition::getPropertyValueList(), leanux::sysdevice::MapperDevice::getPropertyValueList(), getPropertyValueList(), leanux::sysdevice::RamDiskDevice::getPropertyValueList(), and leanux::sysdevice::MDDevice::getPropertyValueList().
getModel()
virtual std::string leanux::sysdevice::SysDevice::getModel () const inline virtual inherited
Definition at line 220 of file device.hpp.
Referenced by leanux::sysdevice::BlockDevice::getDisplayName(), leanux::sysdevice::BlockDevice::getPropertyValueList(), and leanux::sysdevice::NVMeDevice::getPropertyValueList().
getPath()
SysDevicePath leanux::sysdevice::SysDevice::getPath () const inline inherited
Get the path for the SysDevice.
Returns
the SysDevice path.
Definition at line 180 of file device.hpp.
References leanux::sysdevice::SysDevice::path_.
Referenced by leanux::tools::lsys::getLeafColStr(), and leanux::tools::lsys::listDevices().
getPropertyValueList()
void leanux::sysdevice::LoopbackDevice::getPropertyValueList (PropertyValueList & pv) const virtual
Reimplemented from leanux::sysdevice::BlockDevice.
Definition at line 697 of file device.cpp.
References leanux::util::ByteStr(), leanux::block::MajorMinor::getAliases(), leanux::sysdevice::BlockDevice::getMajorMinor(), and leanux::sysdevice::SysDevice::getPropertyValueList().
getType()
virtual SysDeviceType leanux::sysdevice::SysDevice::getType () const inline virtual inherited
Get the SysDeviceType.
See also
SysDeviceType.
Returns
the SysDevice type.
Definition at line 188 of file device.hpp.
References leanux::sysdevice::SysDevice::sysdevicetype_.
Referenced by leanux::tools::lsys::listDevices(), and leanux::sysdevice::treeDetect().
getTypeStr()
std::string leanux::sysdevice::SysDevice::getTypeStr (SysDeviceType dt) static inherited
Get a string representation for the SysDeviceType.
Returns
string representation of the SysDeviceType.
Definition at line 1983 of file device.cpp.
References leanux::sysdevice::SysDevice::sdtATAPort, leanux::sysdevice::SysDevice::sdtBCacheDevice, leanux::sysdevice::SysDevice::sdtBlock, leanux::sysdevice::SysDevice::sdtBlockPartition, leanux::sysdevice::SysDevice::sdtiSCSIDevice, leanux::sysdevice::SysDevice::sdtLoopbackDevice, leanux::sysdevice::SysDevice::sdtMapperDevice, leanux::sysdevice::SysDevice::sdtMetaDisk, leanux::sysdevice::SysDevice::sdtMMCDevice, leanux::sysdevice::SysDevice::sdtNetDevice, leanux::sysdevice::SysDevice::sdtNVMeDevice, leanux::sysdevice::SysDevice::sdtNVMePartition, leanux::sysdevice::SysDevice::sdtPCIBus, leanux::sysdevice::SysDevice::sdtPCIDevice, leanux::sysdevice::SysDevice::sdtRAMDiskDevice, leanux::sysdevice::SysDevice::sdtSASEndDevice, leanux::sysdevice::SysDevice::sdtSASPort, leanux::sysdevice::SysDevice::sdtSCSIDevice, leanux::sysdevice::SysDevice::sdtSCSIHost, leanux::sysdevice::SysDevice::sdtSCSIRPort, leanux::sysdevice::SysDevice::sdtSCSIVPort, leanux::sysdevice::SysDevice::sdtUnknown, leanux::sysdevice::SysDevice::sdtUSBBus, leanux::sysdevice::SysDevice::sdtUSBDevice, leanux::sysdevice::SysDevice::sdtUSBInterface, leanux::sysdevice::SysDevice::sdtVirtioBlockDevice, leanux::sysdevice::SysDevice::sdtVirtioNetDevice, leanux::sysdevice::SysDevice::sdtVirtualBlockRoot, leanux::sysdevice::SysDevice::sdtVirtualNetDevice, leanux::sysdevice::SysDevice::sdtVirtualNetRoot, and leanux::sysdevice::SysDevice::sdtVirtualRoot.
Referenced by leanux::tools::lblk::detailDisk(), leanux::sysdevice::SysDevice::getPropertyValueList(), leanux::tools::lrep::htmlDiskDetails(), leanux::tools::lsys::listDevices(), and leanux::tools::lsys::sysfsTree().
getVendor()
virtual std::string leanux::sysdevice::SysDevice::getVendor () const inline virtual inherited
Definition at line 222 of file device.hpp.
matchSysDeviceType()
virtual bool leanux::sysdevice::LoopbackDevice::matchSysDeviceType (SysDeviceType t) const inline virtual
test if this SysDevice is of type t.
Parameters
t the SysDeviceType to test.
Returns
true if this has SysDeviceType t.
Reimplemented from leanux::sysdevice::SysDevice.
Definition at line 562 of file device.hpp.
References leanux::sysdevice::SysDevice::sdtLoopbackDevice, and leanux::sysdevice::SysDevice::sysdevicetype_.
tokenize()
void leanux::sysdevice::SysDevice::tokenize (const SysDevicePath & path, std::list< std::string > & tokens) static inherited
Transform a SysDevicePath into a list of tokens in reverse order.
Definition at line 60 of file device.cpp.
References leanux::util::tokenize().
Referenced by leanux::sysdevice::BlockPartition::accept(), leanux::sysdevice::NetDevice::accept(), leanux::sysdevice::VirtualNetDevice::accept(), leanux::sysdevice::SASPort::accept(), leanux::sysdevice::SASEndDevice::accept(), leanux::sysdevice::SCSIDevice::accept(), leanux::sysdevice::SCSIHost::accept(), leanux::sysdevice::SCSIRPort::accept(), leanux::sysdevice::SCSIVPort::accept(), leanux::sysdevice::iSCSIDevice::accept(), leanux::sysdevice::MMCDevice::accept(), leanux::sysdevice::NVMeDevice::accept(), leanux::sysdevice::NVMePartition::accept(), leanux::sysdevice::BCacheDevice::accept(), leanux::sysdevice::ATAPort::accept(), leanux::sysdevice::VirtioBlockDevice::accept(), leanux::sysdevice::VirtioNetDevice::accept(), leanux::sysdevice::MapperDevice::accept(), accept(), leanux::sysdevice::RamDiskDevice::accept(), leanux::sysdevice::MDDevice::accept(), leanux::sysdevice::PCIDevice::accept(), leanux::sysdevice::USBDevice::accept(), leanux::sysdevice::USBInterface::accept(), and leanux::sysdevice::USBBus::accept().
validatePath()
bool leanux::sysdevice::SysDevice::validatePath (const SysDevicePath & path) static inherited
Test SysDevicePath validity; path must exist (be readable) and located under /sys/devices.
Both conditions are not enough to classify it as a SysDevice, but each SysDevice does have a path that returns true here.
Definition at line 67 of file device.cpp.
References leanux::util::directoryExists(), leanux::util::fileReadAccess(), and leanux::sysdevice::sysdevice_root.
Referenced by leanux::sysdevice::leafDetect(), and leanux::sysdevice::treeDetect().
Field Documentation
leaf_
std::string leanux::sysdevice::SysDevice::leaf_ protected inherited
The leaf of the path_ for this SysDevice.
Definition at line 244 of file device.hpp.
Referenced by leanux::sysdevice::BlockPartition::accept(), leanux::sysdevice::NetDevice::accept(), leanux::sysdevice::VirtualRoot::accept(), leanux::sysdevice::VirtualBlockRoot::accept(), leanux::sysdevice::VirtualNetRoot::accept(), leanux::sysdevice::VirtualNetDevice::accept(), leanux::sysdevice::SASPort::accept(), leanux::sysdevice::SASEndDevice::accept(), leanux::sysdevice::SCSIDevice::accept(), leanux::sysdevice::SCSIHost::accept(), leanux::sysdevice::SCSIRPort::accept(), leanux::sysdevice::SCSIVPort::accept(), leanux::sysdevice::iSCSIDevice::accept(), leanux::sysdevice::MMCDevice::accept(), leanux::sysdevice::NVMeDevice::accept(), leanux::sysdevice::NVMePartition::accept(), leanux::sysdevice::BCacheDevice::accept(), leanux::sysdevice::ATAPort::accept(), leanux::sysdevice::VirtioBlockDevice::accept(), leanux::sysdevice::VirtioNetDevice::accept(), leanux::sysdevice::MapperDevice::accept(), accept(), leanux::sysdevice::RamDiskDevice::accept(), leanux::sysdevice::MDDevice::accept(), leanux::sysdevice::PCIDevice::accept(), leanux::sysdevice::PCIBus::accept(), leanux::sysdevice::USBDevice::accept(), leanux::sysdevice::USBInterface::accept(), leanux::sysdevice::USBBus::accept(), leanux::sysdevice::SysDevice::getDisplayName(), leanux::sysdevice::SysDevice::getLeaf(), and leanux::sysdevice::SysDevice::SysDevice().
path_
SysDevicePath leanux::sysdevice::SysDevice::path_ protected inherited
The path for this device.
Definition at line 239 of file device.hpp.
Referenced by leanux::sysdevice::BlockPartition::accept(), leanux::sysdevice::NetDevice::accept(), leanux::sysdevice::VirtualRoot::accept(), leanux::sysdevice::VirtualBlockRoot::accept(), leanux::sysdevice::VirtualNetRoot::accept(), leanux::sysdevice::VirtualNetDevice::accept(), leanux::sysdevice::UnknownSysDevice::accept(), leanux::sysdevice::SASPort::accept(), leanux::sysdevice::SASEndDevice::accept(), leanux::sysdevice::SCSIDevice::accept(), leanux::sysdevice::SCSIHost::accept(), leanux::sysdevice::SCSIRPort::accept(), leanux::sysdevice::SCSIVPort::accept(), leanux::sysdevice::iSCSIDevice::accept(), leanux::sysdevice::MMCDevice::accept(), leanux::sysdevice::NVMeDevice::accept(), leanux::sysdevice::NVMePartition::accept(), leanux::sysdevice::BCacheDevice::accept(), leanux::sysdevice::ATAPort::accept(), leanux::sysdevice::VirtioBlockDevice::accept(), leanux::sysdevice::VirtioNetDevice::accept(), leanux::sysdevice::MapperDevice::accept(), accept(), leanux::sysdevice::RamDiskDevice::accept(), leanux::sysdevice::MDDevice::accept(), leanux::sysdevice::PCIDevice::accept(), leanux::sysdevice::PCIBus::accept(), leanux::sysdevice::USBDevice::accept(), leanux::sysdevice::USBInterface::accept(), leanux::sysdevice::USBBus::accept(), leanux::sysdevice::PCIDevice::getClass(), leanux::sysdevice::USBDevice::getClass(), leanux::sysdevice::USBInterface::getClass(), leanux::sysdevice::USBBus::getClass(), leanux::sysdevice::PCIDevice::getDescription(), leanux::sysdevice::PCIBus::getDescription(), leanux::sysdevice::USBDevice::getDescription(), leanux::sysdevice::USBBus::getDescription(), leanux::sysdevice::PCIDevice::getDisplayName(), leanux::sysdevice::PCIBus::getDisplayName(), leanux::sysdevice::USBDevice::getDisplayName(), leanux::sysdevice::USBBus::getDisplayName(), leanux::sysdevice::SysDevice::getDriver(), leanux::sysdevice::BlockDevice::getDriver(), leanux::sysdevice::BlockDevice::getMajorMinor(), leanux::sysdevice::SysDevice::getPath(), leanux::sysdevice::SysDevice::getPropertyValueList(), leanux::sysdevice::NetDevice::getPropertyValueList(), leanux::sysdevice::ATAPort::getPropertyValueList(), leanux::sysdevice::PCIDevice::getPropertyValueList(), leanux::sysdevice::PCIBus::getPropertyValueList(), leanux::sysdevice::USBDevice::getPropertyValueList(), leanux::sysdevice::USBBus::getPropertyValueList(), leanux::sysdevice::iSCSIDevice::getTargetAddress(), leanux::sysdevice::iSCSIDevice::getTargetIQN(), leanux::sysdevice::iSCSIDevice::getTargetPort(), and leanux::sysdevice::SysDevice::SysDevice().
sysdevicetype_
SysDeviceType leanux::sysdevice::SysDevice::sysdevicetype_ protected inherited
The SysDevice SysDeviceType.
Definition at line 249 of file device.hpp.
Referenced by leanux::sysdevice::ATAPort::ATAPort(), leanux::sysdevice::BCacheDevice::BCacheDevice(), leanux::sysdevice::BlockPartition::BlockPartition(), leanux::sysdevice::SysDevice::getPropertyValueList(), leanux::sysdevice::SysDevice::getType(), leanux::sysdevice::iSCSIDevice::iSCSIDevice(), LoopbackDevice(), leanux::sysdevice::MapperDevice::MapperDevice(), leanux::sysdevice::SysDevice::matchSysDeviceType(), leanux::sysdevice::BlockPartition::matchSysDeviceType(), leanux::sysdevice::VirtualRoot::matchSysDeviceType(), leanux::sysdevice::VirtualBlockRoot::matchSysDeviceType(), leanux::sysdevice::VirtualNetRoot::matchSysDeviceType(), leanux::sysdevice::VirtualNetDevice::matchSysDeviceType(), leanux::sysdevice::SCSIDevice::matchSysDeviceType(), leanux::sysdevice::MMCDevice::matchSysDeviceType(), leanux::sysdevice::NVMeDevice::matchSysDeviceType(), leanux::sysdevice::NVMePartition::matchSysDeviceType(), leanux::sysdevice::BCacheDevice::matchSysDeviceType(), leanux::sysdevice::VirtioBlockDevice::matchSysDeviceType(), leanux::sysdevice::VirtioNetDevice::matchSysDeviceType(), leanux::sysdevice::MapperDevice::matchSysDeviceType(), matchSysDeviceType(), leanux::sysdevice::RamDiskDevice::matchSysDeviceType(), leanux::sysdevice::MDDevice::matchSysDeviceType(), leanux::sysdevice::MDDevice::MDDevice(), leanux::sysdevice::MMCDevice::MMCDevice(), leanux::sysdevice::NetDevice::NetDevice(), leanux::sysdevice::NVMeDevice::NVMeDevice(), leanux::sysdevice::NVMePartition::NVMePartition(), leanux::sysdevice::PCIBus::PCIBus(), leanux::sysdevice::PCIDevice::PCIDevice(), leanux::sysdevice::RamDiskDevice::RamDiskDevice(), leanux::sysdevice::SASEndDevice::SASEndDevice(), leanux::sysdevice::SASPort::SASPort(), leanux::sysdevice::SCSIDevice::SCSIDevice(), leanux::sysdevice::SCSIHost::SCSIHost(), leanux::sysdevice::SCSIRPort::SCSIRPort(), leanux::sysdevice::SCSIVPort::SCSIVPort(), leanux::sysdevice::SysDevice::SysDevice(), leanux::sysdevice::UnknownSysDevice::UnknownSysDevice(), leanux::sysdevice::USBBus::USBBus(), leanux::sysdevice::USBDevice::USBDevice(), leanux::sysdevice::USBInterface::USBInterface(), leanux::sysdevice::VirtioBlockDevice::VirtioBlockDevice(), leanux::sysdevice::VirtioNetDevice::VirtioNetDevice(), leanux::sysdevice::VirtualBlockRoot::VirtualBlockRoot(), leanux::sysdevice::VirtualNetDevice::VirtualNetDevice(), leanux::sysdevice::VirtualNetRoot::VirtualNetRoot(), and leanux::sysdevice::VirtualRoot::VirtualRoot().
The documentation for this class was generated from the following files:
lib/device.hpp
lib/device.cpp