leanux: leanux::tools::lard::NetSnap Class Reference
leanux::tools::lard::NetSnap Class Reference
#include <lar_snap.hpp>
Public Member Functions
NetSnap ()
virtual ~NetSnap ()
virtual void startSnap ()
virtual void stopSnap ()
virtual long storeSnap (const persist::Database &db, long snapid, double seconds)
Protected Attributes
net::NetStatDeviceMap stat1_
net::NetStatDeviceMap stat2_
Detailed Description
Definition at line 130 of file lar_snap.hpp.
Constructor & Destructor Documentation
NetSnap()
leanux::tools::lard::NetSnap::NetSnap () inline
Definition at line 132 of file lar_snap.hpp.
~NetSnap()
virtual leanux::tools::lard::NetSnap::~NetSnap () inline virtual
Definition at line 133 of file lar_snap.hpp.
Member Function Documentation
startSnap()
void leanux::tools::lard::NetSnap::startSnap () virtual
Implements leanux::tools::lard::Snapshot.
Definition at line 263 of file lar_snap.cpp.
References leanux::net::getNetStat(), and stat1_.
Referenced by leanux::tools::lard::mainLoop().
stopSnap()
void leanux::tools::lard::NetSnap::stopSnap () virtual
Implements leanux::tools::lard::Snapshot.
Definition at line 267 of file lar_snap.cpp.
References leanux::net::getNetStat(), and stat2_.
Referenced by leanux::tools::lard::mainLoop().
storeSnap()
long leanux::tools::lard::NetSnap::storeSnap (const persist::Database & db, long snapid, double seconds) virtual
Implements leanux::tools::lard::Snapshot.
Definition at line 271 of file lar_snap.cpp.
References leanux::persist::DML::bind(), leanux::persist::DML::execute(), leanux::net::getDeviceMACAddress(), leanux::persist::Query::getLong(), leanux::net::getSysPath(), leanux::persist::Database::lastInsertRowid(), leanux::persist::Statement::prepare(), stat1_, stat2_, and leanux::persist::Query::step().
Referenced by leanux::tools::lard::mainLoop().
Field Documentation
stat1_
net::NetStatDeviceMap leanux::tools::lard::NetSnap::stat1_ protected
Definition at line 139 of file lar_snap.hpp.
Referenced by startSnap(), and storeSnap().
stat2_
net::NetStatDeviceMap leanux::tools::lard::NetSnap::stat2_ protected
Definition at line 140 of file lar_snap.hpp.
Referenced by stopSnap(), and storeSnap().
The documentation for this class was generated from the following files:
tools/lard/lar_snap.hpp
tools/lard/lar_snap.cpp