leanux: leanux::tools::lmon::NetView Class Reference
leanux::tools::lmon::NetView Class Reference
View of top network devices.
#include <lmon_curses.hpp>
Public Member Functions
NetView (int width, int height, int x, int y, Screen *screen)
Construct a NetView.
virtual ~NetView ()
Destructor.
virtual void doSample ()
Take a NetView sample.
int getHeight () const
virtual void resize (int width, int height, int x, int y)
Resize the View.
virtual void xrefresh (const XNetView &)
Refresh/redraw the ProcessView.
Static Public Member Functions
static int getMinHeight ()
Get the minimal height for the NetView.
static int getOptimalHeight ()
provide the optimal height for the NetView,
Protected Member Functions
void box (int x1, int y1, int x2, int y2)
Draw a box.
void charOut (int x, int y, int attrs, const chtype ch)
Write character ch at x,y with display attrs.
void doubleOut (int x, int y, int attrs, double value)
Write double at x,y with display attrs.
void doubleOutPct (int x, int y, int attrs, double value)
Write double as a percentage x,y with display attrs.
void hLine (int x1, int x2, int y, int attrs, chtype token=ACS_HLINE)
Draw a horizontal line.
void textOut (int x, int y, int attrs, const std::string &text)
Write text at x,y with display attrs.
void textOut (int x, int y, int attrs, int i)
Write integer as std::string at x,y with display attrs.
void textOutMoveXRA (int &x, int y, int w, int attrs, const std::string &text)
Draw text right-adjusted and progress x with w+1.
void textOutMoveXRA (int &x, int y, int w, int attrs, int i)
Draw an integer right-adjusted and progress x with w+1.
void textOutRA (int x, int y, int w, int attrs, const std::string &text)
Draw text right-adjusted.
void textOutRA (int x, int y, int w, int attrs, int i)
Draw integer right-adjusted.
void vLine (int y1, int y2, int x, int attrs, chtype token=ACS_VLINE)
Draw a vertical line.
Protected Attributes
int absx_
The absolute x (column) position of left-top.
int absy_
The absolute y (line) position of left-top.
int attr_alert_text_
attributes for drawing alert text.
int attr_bold_text_
attributes for drawing bold text.
int attr_line_
attributes for drawing lines.
int attr_normal_text_
attributes for drawing normal text.
int attr_plot_element_
attributes for (default) plotting characters.
int height_
The height (lines) of the View.
unsigned long sample_count_
total number of samples taken.
Screen * screen_
The Screen.
int width_
The width (columns) of the View.
WINDOW * window_
The ncurses window.
Detailed Description
View of top network devices.
Definition at line 599 of file lmon_curses.hpp.
Constructor & Destructor Documentation
NetView()
leanux::tools::lmon::NetView::NetView (int width, int height, int x, int y, Screen * screen)
Construct a NetView.
Parameters
width the width.
height the height.
x the top-left x.
y the top-left y.
screen the Screen to sit on.
Definition at line 1372 of file lmon_curses.cpp.
~NetView()
leanux::tools::lmon::NetView::~NetView () virtual
Destructor.
Definition at line 1376 of file lmon_curses.cpp.
Member Function Documentation
box()
void leanux::tools::lmon::View::box (int x1, int y1, int x2, int y2) protected inherited
Draw a box.
Parameters
x1 top-left column.
y1 top-left line.
x2 right-bottom column.
y2 right-bottom line.
Definition at line 610 of file lmon_curses.cpp.
References leanux::tools::lmon::View::attr_line_, leanux::tools::lmon::View::hLine(), leanux::tools::lmon::View::vLine(), and leanux::tools::lmon::View::window_.
Referenced by leanux::tools::lmon::SysView::xrefresh().
charOut()
void leanux::tools::lmon::View::charOut (int x, int y, int attrs, const chtype ch) inline protected inherited
Write character ch at x,y with display attrs.
Parameters
x the x (column) position.
y the y (line) position.
attrs the ncurses display attributes to use.
ch the char to display.
Definition at line 876 of file lmon_curses.hpp.
References leanux::tools::lmon::View::window_.
Referenced by leanux::tools::lmon::SysView::xrefresh().
doSample()
void leanux::tools::lmon::NetView::doSample () virtual
Take a NetView sample.
Reimplemented from leanux::tools::lmon::View.
Definition at line 1379 of file lmon_curses.cpp.
doubleOut()
void leanux::tools::lmon::View::doubleOut (int x, int y, int attrs, double value) inline protected inherited
Write double at x,y with display attrs.
Parameters
x the x (column) position.
y the y (line) position.
attrs the ncurses display attributes to use.
value the double to display.
Definition at line 911 of file lmon_curses.hpp.
References leanux::tools::lmon::View::window_.
doubleOutPct()
void leanux::tools::lmon::View::doubleOutPct (int x, int y, int attrs, double value) inline protected inherited
Write double as a percentage x,y with display attrs.
Parameters
x the x (column) position.
y the y (line) position.
attrs the ncurses display attributes to use.
value the double to display.
Definition at line 918 of file lmon_curses.hpp.
References leanux::tools::lmon::View::window_.
Referenced by leanux::tools::lmon::SysView::xrefresh().
getHeight()
int leanux::tools::lmon::View::getHeight () const inline inherited
Definition at line 100 of file lmon_curses.hpp.
References leanux::tools::lmon::View::height_.
Referenced by leanux::tools::lmon::Screen::runRealtime().
getMinHeight()
int leanux::tools::lmon::NetView::getMinHeight () static
Get the minimal height for the NetView.
Returns
the minimal height in lines.
Definition at line 1382 of file lmon_curses.cpp.
References leanux::util::ConfigFile::getConfig(), and leanux::util::ConfigFile::getIntValue().
Referenced by getOptimalHeight(), and leanux::tools::lmon::Screen::screenResize().
getOptimalHeight()
int leanux::tools::lmon::NetView::getOptimalHeight () static
provide the optimal height for the NetView,
Returns
the optimal height in lines.
Definition at line 1366 of file lmon_curses.cpp.
References getMinHeight(), and leanux::net::getNetStat().
Referenced by leanux::tools::lmon::Screen::screenResize().
hLine()
void leanux::tools::lmon::View::hLine (int x1, int x2, int y, int attrs, chtype token = ACS_HLINE) inline protected inherited
Draw a horizontal line.
Parameters
x1 line left.
x2 line right.
y line.
attrs draw attributes.
token token to use.
Definition at line 925 of file lmon_curses.hpp.
References leanux::tools::lmon::View::window_.
Referenced by leanux::tools::lmon::View::box(), leanux::tools::lmon::Footer::xrefresh(), leanux::tools::lmon::SysView::xrefresh(), leanux::tools::lmon::IOView::xrefresh(), leanux::tools::lmon::ProcessView::xrefresh(), and xrefresh().
resize()
void leanux::tools::lmon::View::resize (int width, int height, int x, int y) virtual inherited
Resize the View.
Reimplemented in leanux::tools::lmon::ProcessView.
Definition at line 596 of file lmon_curses.cpp.
References leanux::tools::lmon::View::absx_, leanux::tools::lmon::View::absy_, leanux::tools::lmon::View::height_, leanux::tools::lmon::View::width_, and leanux::tools::lmon::View::window_.
Referenced by leanux::tools::lmon::ProcessView::resize(), and leanux::tools::lmon::Screen::screenResize().
textOut() [1/2]
void leanux::tools::lmon::View::textOut (int x, int y, int attrs, const std::string & text) inline protected inherited
Write text at x,y with display attrs.
Parameters
x the x (column) position.
y the y (line) position.
attrs the ncurses display attributes to use.
text the text to display.
Definition at line 864 of file lmon_curses.hpp.
References leanux::tools::lmon::View::window_.
Referenced by leanux::tools::lmon::Header::xrefresh(), leanux::tools::lmon::Footer::xrefresh(), leanux::tools::lmon::SysView::xrefresh(), leanux::tools::lmon::IOView::xrefresh(), leanux::tools::lmon::ProcessView::xrefresh(), and xrefresh().
textOut() [2/2]
void leanux::tools::lmon::View::textOut (int x, int y, int attrs, int i) inline protected inherited
Write integer as std::string at x,y with display attrs.
Parameters
x the x (column) position.
y the y (line) position.
attrs the ncurses display attributes to use.
i the integer to display.
Definition at line 869 of file lmon_curses.hpp.
References leanux::tools::lmon::View::window_.
textOutMoveXRA() [1/2]
void leanux::tools::lmon::View::textOutMoveXRA (int & x, int y, int w, int attrs, const std::string & text) inline protected inherited
Draw text right-adjusted and progress x with w+1.
Parameters
x x position, set x=x+w+1 on finish.
y y position
w width of the displayed value.
attrs the ncurses display attributes to use.
text the text to display.
Definition at line 895 of file lmon_curses.hpp.
References leanux::tools::lmon::View::window_.
Referenced by leanux::tools::lmon::IOView::xrefresh(), leanux::tools::lmon::ProcessView::xrefresh(), and xrefresh().
textOutMoveXRA() [2/2]
void leanux::tools::lmon::View::textOutMoveXRA (int & x, int y, int w, int attrs, int i) inline protected inherited
Draw an integer right-adjusted and progress x with w+1.
Parameters
x x position, set x=x+w+1 on finish.
y y position
w width of the displayed value.
attrs the ncurses display attributes to use.
i the integer value to display.
Definition at line 903 of file lmon_curses.hpp.
References leanux::tools::lmon::View::window_.
textOutRA() [1/2]
void leanux::tools::lmon::View::textOutRA (int x, int y, int w, int attrs, const std::string & text) inline protected inherited
Draw text right-adjusted.
Parameters
x x position, set x=x+w+1 on finish.
y y position
w width of the displayed value.
attrs the ncurses display attributes to use.
text the text to display.
Definition at line 881 of file lmon_curses.hpp.
References leanux::tools::lmon::View::window_.
Referenced by leanux::tools::lmon::SysView::xrefresh().
textOutRA() [2/2]
void leanux::tools::lmon::View::textOutRA (int x, int y, int w, int attrs, int i) inline protected inherited
Draw integer right-adjusted.
Parameters
x x position, set x=x+w+1 on finish.
y y position
w width of the displayed value.
attrs the ncurses display attributes to use.
i the integer to display.
Definition at line 888 of file lmon_curses.hpp.
References leanux::tools::lmon::View::window_.
vLine()
void leanux::tools::lmon::View::vLine (int y1, int y2, int x, int attrs, chtype token = ACS_VLINE) inline protected inherited
Draw a vertical line.
Parameters
y1 line top.
y2 line bottom.
x column.
attrs draw attributes.
token token to use.
Definition at line 930 of file lmon_curses.hpp.
References leanux::tools::lmon::View::window_.
Referenced by leanux::tools::lmon::View::box(), leanux::tools::lmon::SysView::xrefresh(), leanux::tools::lmon::IOView::xrefresh(), and xrefresh().
xrefresh()
void leanux::tools::lmon::NetView::xrefresh (const XNetView & data) virtual
Refresh/redraw the ProcessView.
Definition at line 1386 of file lmon_curses.cpp.
References leanux::tools::lmon::View::attr_bold_text_, leanux::tools::lmon::View::attr_line_, leanux::tools::lmon::View::attr_normal_text_, leanux::util::ByteStr(), leanux::tools::lmon::XNetView::delta, leanux::system::getUserName(), leanux::tools::lmon::View::height_, leanux::tools::lmon::View::hLine(), leanux::util::NumStr(), leanux::tools::lmon::XNetView::sample_count, leanux::tools::lmon::XNetView::tcpclient, leanux::tools::lmon::XNetView::tcpserver, leanux::tools::lmon::View::textOut(), leanux::tools::lmon::View::textOutMoveXRA(), leanux::tools::lmon::View::vLine(), leanux::tools::lmon::View::width_, and leanux::tools::lmon::View::window_.
Field Documentation
absx_
int leanux::tools::lmon::View::absx_ protected inherited
The absolute x (column) position of left-top.
Definition at line 236 of file lmon_curses.hpp.
Referenced by leanux::tools::lmon::View::resize(), and leanux::tools::lmon::View::View().
absy_
int leanux::tools::lmon::View::absy_ protected inherited
The absolute y (line) position of left-top.
Definition at line 241 of file lmon_curses.hpp.
Referenced by leanux::tools::lmon::View::resize(), and leanux::tools::lmon::View::View().
attr_alert_text_
int leanux::tools::lmon::View::attr_alert_text_ protected inherited
attributes for drawing alert text.
Definition at line 276 of file lmon_curses.hpp.
Referenced by leanux::tools::lmon::View::View().
attr_bold_text_
int leanux::tools::lmon::View::attr_bold_text_ protected inherited
attributes for drawing bold text.
Definition at line 261 of file lmon_curses.hpp.
Referenced by leanux::tools::lmon::View::View(), leanux::tools::lmon::Header::xrefresh(), leanux::tools::lmon::SysView::xrefresh(), leanux::tools::lmon::IOView::xrefresh(), leanux::tools::lmon::ProcessView::xrefresh(), and xrefresh().
attr_line_
int leanux::tools::lmon::View::attr_line_ protected inherited
attributes for drawing lines.
Definition at line 266 of file lmon_curses.hpp.
Referenced by leanux::tools::lmon::View::box(), leanux::tools::lmon::View::View(), leanux::tools::lmon::Footer::xrefresh(), leanux::tools::lmon::SysView::xrefresh(), leanux::tools::lmon::IOView::xrefresh(), leanux::tools::lmon::ProcessView::xrefresh(), and xrefresh().
attr_normal_text_
int leanux::tools::lmon::View::attr_normal_text_ protected inherited
attributes for drawing normal text.
Definition at line 256 of file lmon_curses.hpp.
Referenced by leanux::tools::lmon::View::View(), leanux::tools::lmon::SysView::xrefresh(), leanux::tools::lmon::IOView::xrefresh(), leanux::tools::lmon::ProcessView::xrefresh(), and xrefresh().
attr_plot_element_
int leanux::tools::lmon::View::attr_plot_element_ protected inherited
attributes for (default) plotting characters.
Definition at line 271 of file lmon_curses.hpp.
Referenced by leanux::tools::lmon::View::View(), leanux::tools::lmon::Header::xrefresh(), and leanux::tools::lmon::SysView::xrefresh().
height_
int leanux::tools::lmon::View::height_ protected inherited
The height (lines) of the View.
Definition at line 226 of file lmon_curses.hpp.
Referenced by leanux::tools::lmon::View::getHeight(), leanux::tools::lmon::View::resize(), leanux::tools::lmon::View::View(), leanux::tools::lmon::SysView::xrefresh(), leanux::tools::lmon::IOView::xrefresh(), leanux::tools::lmon::ProcessView::xrefresh(), and xrefresh().
sample_count_
unsigned long leanux::tools::lmon::View::sample_count_ protected inherited
total number of samples taken.
Definition at line 281 of file lmon_curses.hpp.
Referenced by leanux::tools::lmon::View::View().
screen_
Screen* leanux::tools::lmon::View::screen_ protected inherited
The Screen.
Definition at line 251 of file lmon_curses.hpp.
Referenced by leanux::tools::lmon::SysView::attrFromCPUChar(), leanux::tools::lmon::Footer::Footer(), leanux::tools::lmon::View::View(), leanux::tools::lmon::IOView::xrefresh(), and leanux::tools::lmon::ProcessView::xrefresh().
width_
int leanux::tools::lmon::View::width_ protected inherited
The width (columns) of the View.
Definition at line 231 of file lmon_curses.hpp.
Referenced by leanux::tools::lmon::View::resize(), leanux::tools::lmon::View::View(), leanux::tools::lmon::Header::xrefresh(), leanux::tools::lmon::Footer::xrefresh(), leanux::tools::lmon::SysView::xrefresh(), leanux::tools::lmon::IOView::xrefresh(), leanux::tools::lmon::ProcessView::xrefresh(), and xrefresh().
window_
WINDOW* leanux::tools::lmon::View::window_ protected inherited
The ncurses window.
Definition at line 246 of file lmon_curses.hpp.
Referenced by leanux::tools::lmon::View::box(), leanux::tools::lmon::View::charOut(), leanux::tools::lmon::View::doubleOut(), leanux::tools::lmon::View::doubleOutPct(), leanux::tools::lmon::View::hLine(), leanux::tools::lmon::View::resize(), leanux::tools::lmon::View::textOut(), leanux::tools::lmon::View::textOutMoveXRA(), leanux::tools::lmon::View::textOutRA(), leanux::tools::lmon::View::View(), leanux::tools::lmon::View::vLine(), leanux::tools::lmon::Header::xrefresh(), leanux::tools::lmon::Footer::xrefresh(), leanux::tools::lmon::SysView::xrefresh(), leanux::tools::lmon::IOView::xrefresh(), leanux::tools::lmon::ProcessView::xrefresh(), xrefresh(), and leanux::tools::lmon::View::~View().
The documentation for this class was generated from the following files:
tools/lmon/lmon_curses.hpp
tools/lmon/lmon_curses.cpp