#!/bin/bash
#
# lard    @LARD_DESCR@
#
# chkconfig: 345 70 30
# description: @LARD_DESCR@
# processname: lard

# Source function library.
. /etc/init.d/functions

PROG=lard
PROGRAM=/usr/bin/lard
LOCKFILE=/var/lock/subsys/${PROG}
DB_DIR=/var/lib/lard
DB_FILE=${DB_DIR}/lard.db
CONF_FILE=/etc/lard/lard.conf

start() {
  echo -n "Starting ${PROG}: "
  mkdir -p ${DB_DIR}
  touch ${DB_FILE}
  chown -R leanux:leanux ${DB_DIR}
  chmod 770 ${DB_DIR}
  chmod 660 ${DB_FILE}
  daemon --check ${PROG} --user leanux ${PROGRAM} -c ${CONF_FILE} -f ${DB_FILE} &
  ERR=$?
  test $ERR -eq 0 && touch ${LOCKFILE}
  return $ERR
}

stop() {
  echo -n "Shutting down ${RPOG}: "
  killproc ${PROG}
  ERR=$?
  rm -f ${LOCKFILE}
  return $ERR
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status ${PROG}
    ;;
  restart)
    stop
    start
    ;;
  reload)
    stop
    start
    ;;
  condrestart)
    ;;
  *)
    echo "Usage: ${PROG} {start|stop|restart}"
    exit 1
    ;;
esac
exit $?
