#!/bin/bash
#
# lard    @LARD_DESCR@
#
# chkconfig: 345 70 30
# description: @LARD_DESCR@
# processname: lard

# Source function library.
. /etc/init.d/functions

PROG=lard
PROGRAM=/usr/bin/lard
LOCKFILE=/var/lock/subsys/${PROG}
DB_DIR=@LARD_SYSDB_PATH@
DB_FILE=@LARD_SYSDB_FILE@
CONF_FILE=@LARD_SYSCONF_FILE@

start() {
  echo -n "Starting ${PROG}: "
  mkdir -p ${DB_DIR}
  touch ${DB_FILE}
  chown -R @LARD_USER@:@LARD_USER@ ${DB_DIR}
  chmod 770 ${DB_DIR}
  chmod 660 ${DB_FILE}
  daemon --check ${PROG} --user @LARD_USER@ ${PROGRAM} -c ${CONF_FILE} -f ${DB_FILE} -d &
  ERR=$?
  test $ERR -eq 0 && touch ${LOCKFILE}
  return $ERR
}

stop() {
  echo -n "Shutting down ${PROG}: "
  killproc ${PROG}
  ERR=$?
  rm -f ${LOCKFILE}
  return $ERR
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status ${PROG}
    ;;
  restart)
    stop
    start
    ;;
  reload)
    stop
    start
    ;;
  condrestart)
    ;;
  *)
    echo "Usage: ${PROG} {start|stop|restart}"
    exit 1
    ;;
esac
exit $?
