leanux: leanux::tools::lard::ResSnap Class Reference
leanux::tools::lard::ResSnap Class Reference
#include <lar_snap.hpp>
Public Member Functions
ResSnap ()
virtual ~ResSnap ()
virtual void startSnap ()
virtual void stopSnap ()
virtual long storeSnap (const persist::Database &db, long snapid, double seconds)
Detailed Description
Definition at line 169 of file lar_snap.hpp.
Constructor & Destructor Documentation
ResSnap()
leanux::tools::lard::ResSnap::ResSnap () inline
Definition at line 171 of file lar_snap.hpp.
~ResSnap()
virtual leanux::tools::lard::ResSnap::~ResSnap () inline virtual
Definition at line 172 of file lar_snap.hpp.
Member Function Documentation
startSnap()
void leanux::tools::lard::ResSnap::startSnap () virtual
Implements leanux::tools::lard::Snapshot.
Definition at line 512 of file lar_snap.cpp.
Referenced by leanux::tools::lard::mainLoop().
stopSnap()
void leanux::tools::lard::ResSnap::stopSnap () virtual
Implements leanux::tools::lard::Snapshot.
Definition at line 515 of file lar_snap.cpp.
Referenced by leanux::tools::lard::mainLoop().
storeSnap()
long leanux::tools::lard::ResSnap::storeSnap (const persist::Database & db, long snapid, double seconds) virtual
Implements leanux::tools::lard::Snapshot.
Definition at line 518 of file lar_snap.cpp.
References leanux::persist::DML::bind(), leanux::persist::DML::execute(), leanux::system::getNumLogins(), leanux::system::getNumLoginUsers(), leanux::system::getNumProcesses(), leanux::system::getOpenFiles(), leanux::system::getOpenInodes(), and leanux::persist::Statement::prepare().
Referenced by leanux::tools::lard::mainLoop().
The documentation for this class was generated from the following files:
tools/lard/lar_snap.hpp
tools/lard/lar_snap.cpp