leanux: leanux Namespace Reference
leanux Namespace Reference
Linux performance and configuration API.
Namespaces
block
block device API.
cpu
CPU configuration and performance API.
net
network configuration and performance API.
pci
persist
Persistent SQL storage, uses the great sqlite3.
process
Process configuration and performance API.
sysdevice
system device API.
system
System / kernel detail API.
tools
usb
util
Utility classes and functions.
vmem
virtual memory API
Data Structures
class Oops
leanux exception class.
Functions
void init ()
Initialize leanux, run checks to verify leanux is compatible with the runtime environment.
std::ostream & operator<< (std::ostream &os, const Oops &oops)
Write an Oops to a stream.
Variables
const std::string kernel_required = "2.6.24"
The minimum kernel version required by leanux.
Detailed Description
Linux performance and configuration API.
Function Documentation
init()
void leanux::init ()
Initialize leanux, run checks to verify leanux is compatible with the runtime environment.
This must be the first call to make against leanux.
Exceptions
Oops if something is wrong.
Examples
example_cpu.cpp, example_process.cpp, example_process2.cpp, example_system.cpp, and example_usb.cpp.
Definition at line 66 of file system.cpp.
References leanux::util::directoryExists(), leanux::system::getKernelVersion(), leanux::net::init(), leanux::pci::init(), leanux::usb::init(), leanux::block::init(), and kernel_required.
Referenced by leanux::tools::lmon::main(), leanux::tools::labbix::main(), leanux::tools::lard::main(), leanux::tools::lsys::main(), leanux::tools::lblk::main(), and leanux::tools::lrep::main().
operator<<()
std::ostream& leanux::operator<< (std::ostream & os, const Oops & oops) inline
Write an Oops to a stream.
Parameters
os the stream to write to.
oops the Oops to write.
Returns
reference to the stream.
Definition at line 84 of file oops.hpp.
References leanux::Oops::getMessage().
Variable Documentation
kernel_required
const std::string leanux::kernel_required = "2.6.24"
The minimum kernel version required by leanux.
Definition at line 64 of file system.cpp.
Referenced by init().