leanux: leanux::system Namespace Reference
leanux::system Namespace Reference
System / kernel detail API.
Data Structures
struct Distribution
Distribution identifier.
Enumerations
enum ChassisType {
ChassisTypeOther =0x1, ChassisTypeUnknown =0x2, ChassisTypeDesktop =0x3, ChassisTypeLowProfileDesktop =0x4,
ChassisTypePizzaBox =0x5, ChassisTypeMiniTower =0x6, ChassisTypeTower =0x7, ChassisTypePortable =0x8,
ChassisTypeLaptop =0x9, ChassisTypeNotebook =0xa, ChassisTypeHandHeld =0xb, ChassisTypeDockingStation =0xc,
ChassisTypeAllInOne =0xd, ChassisTypeSubNotebook =0xe, ChassisTypeSpaceSaving =0xf, ChassisTypeLunchBox =0x10,
ChassisTypeMainServerChassis =0x11, ChassisTypeExpansionChassis =0x12, ChassisTypeSubChassis =0x13, ChassisTypeBusExpansionChassis =0x14,
ChassisTypePeripheralChassis =0x15, ChassisTypeRAIDChassis =0x16, ChassisTypeRackMountChassis =0x17, ChassisTypeSealedCasePC =0x18,
ChassisTypeMultiSystemChassis =0x19, ChassisTypeCompactPCI =0x1a, ChassisTypeAdvancedTCA =0x1b, ChassisTypeBlade =0x1c,
ChassisTypeBladeEnclosure =0x1d
}
Enumerate chassis types.
enum DistributionType {
Unkown, Gentoo, Debian, RedHat,
OpenSuSE, Ubuntu, Fedora, Mint,
Arch, CentOS
}
GNU/Linux distribution enumeration.
Functions
std::string getArchitecture ()
Get the system architecture.
std::string getBoardName ()
Get the name of the system board.
std::string getBoardVendor ()
Get the vendor of the system board.
std::string getBoardVersion ()
Get the version of the system board.
time_t getBootTime ()
Time in seconds since 1970-01-01 00:00:00 +0000 (UTC)
ChassisType getChassisType ()
Get the system chassis type.
std::string getChassisTypeString ()
Get the system chassis type as a std::string.
Distribution getDistribution ()
Detect the GNU/Linux distribution.
std::string getKernelVersion ()
Get the kernel version.
std::string getNodeName ()
The node name of the system.
unsigned int getNumLogins ()
The number of user logins as reported by who.
unsigned int getNumLoginUsers ()
The number of distinct users logged in.
void getNumProcesses (unsigned long *processes)
Get the number of processes on the system.
void getOpenFiles (unsigned long *used, unsigned long *max)
get the current and maximum number of open files.
void getOpenInodes (unsigned long *used, unsigned long *free)
get the used and free number of open inodes.
long getPageSize ()
Get the system page size.
double getUptime ()
Get the system uptime in seconds (with centisecond precision).
long getUserHz ()
Get the number of clock ticks per second.
std::string getUserName (uid_t uid)
Get username from a uid.
bool isBigEndian ()
Return true when the system is big endian.
std::string readLSBReleaseDistribDescription ()
Read the DISTRIB_DESCRIPTION from /etc/lsb-release.
std::string readLSBReleaseDistribId ()
Read the DISTRIB_ID from /etc/lsb-release.
std::string readOSReleaseDistribId ()
Read the ID from /etc/os-release.
std::string readOSReleaseName ()
Read the NAME from /etc/os-release.
std::string readOSReleasePrettyName ()
Read the PRETTY_NAME from /etc/os-release.
std::string readOSReleaseVersion ()
Read the VERSION from /etc/os-release.
Detailed Description
System / kernel detail API.
Data Structure Documentation
leanux::system::Distribution
struct leanux::system::Distribution
Distribution identifier.
Examples
example_system.cpp.
Definition at line 249 of file system.hpp.
Data Fields
string release The distribution release.
DistributionType type The distribution type.
Enumeration Type Documentation
ChassisType
enum leanux::system::ChassisType
Enumerate chassis types.
Enumerator
ChassisTypeOther
typically used for virtual machines.
ChassisTypeUnknown
ChassisTypeDesktop
Typical desktop PC.
ChassisTypeLowProfileDesktop
ChassisTypePizzaBox
ChassisTypeMiniTower
ChassisTypeTower
ChassisTypePortable
ChassisTypeLaptop
ChassisTypeNotebook
ChassisTypeHandHeld
ChassisTypeDockingStation
ChassisTypeAllInOne
ChassisTypeSubNotebook
ChassisTypeSpaceSaving
ChassisTypeLunchBox
ChassisTypeMainServerChassis
ChassisTypeExpansionChassis
ChassisTypeSubChassis
ChassisTypeBusExpansionChassis
ChassisTypePeripheralChassis
ChassisTypeRAIDChassis
ChassisTypeRackMountChassis
ChassisTypeSealedCasePC
ChassisTypeMultiSystemChassis
ChassisTypeCompactPCI
ChassisTypeAdvancedTCA
ChassisTypeBlade
ChassisTypeBladeEnclosure
Definition at line 121 of file system.hpp.
DistributionType
enum leanux::system::DistributionType
GNU/Linux distribution enumeration.
Enumerator
Unkown
distribution not recognized.
Gentoo
Gentoo.
Debian
Debian.
RedHat
RedHat.
OpenSuSE
SUSE.
Ubuntu
Ubuntu.
Fedora
Fedora.
Mint
Mint.
Arch
Arch.
CentOS
CentOS.
Definition at line 223 of file system.hpp.
Function Documentation
getArchitecture()
std::string leanux::system::getArchitecture ()
Get the system architecture.
Exceptions
Oops if call to uname fails.
Returns
the system architecture as in uname -m, for example x86_64.
Examples
example_system.cpp.
Definition at line 97 of file system.cpp.
Referenced by leanux::tools::lmon::Footer::Footer(), and leanux::tools::lrep::htmlSystemDetails().
getBoardName()
std::string leanux::system::getBoardName ()
Get the name of the system board.
Examples
example_system.cpp.
Definition at line 114 of file system.cpp.
References leanux::util::fileReadString().
Referenced by leanux::tools::lmon::Footer::Footer(), and leanux::tools::lrep::htmlSystemDetails().
getBoardVendor()
std::string leanux::system::getBoardVendor ()
Get the vendor of the system board.
Examples
example_system.cpp.
Definition at line 123 of file system.cpp.
References leanux::util::fileReadString().
Referenced by leanux::tools::lmon::Footer::Footer(), and leanux::tools::lrep::htmlSystemDetails().
getBoardVersion()
std::string leanux::system::getBoardVersion ()
Get the version of the system board.
Examples
example_system.cpp.
Definition at line 132 of file system.cpp.
References leanux::util::fileReadString().
Referenced by leanux::tools::lrep::htmlSystemDetails().
getBootTime()
time_t leanux::system::getBootTime ()
Time in seconds since 1970-01-01 00:00:00 +0000 (UTC)
Examples
example_process.cpp, and example_system.cpp.
Definition at line 173 of file system.cpp.
getChassisType()
ChassisType leanux::system::getChassisType ()
Get the system chassis type.
Definition at line 141 of file system.cpp.
References ChassisTypeUnknown, leanux::util::fileReadAccess(), and leanux::util::fileReadInt().
Referenced by getChassisTypeString().
getChassisTypeString()
std::string leanux::system::getChassisTypeString ()
Get the system chassis type as a std::string.
Examples
example_system.cpp.
Definition at line 148 of file system.cpp.
References ChassisTypeDesktop, ChassisTypeExpansionChassis, ChassisTypeHandHeld, ChassisTypeLaptop, ChassisTypeNotebook, ChassisTypeOther, ChassisTypePortable, ChassisTypeSealedCasePC, ChassisTypeUnknown, and getChassisType().
Referenced by leanux::tools::lmon::Footer::Footer(), and leanux::tools::lrep::htmlSystemDetails().
getDistribution()
Distribution leanux::system::getDistribution ()
Detect the GNU/Linux distribution.
Returns
the detected GNU/Linux distribution type, which may be Unkown.
Examples
example_system.cpp.
Definition at line 393 of file system.cpp.
References CentOS, Debian, leanux::util::fileReadAccess(), leanux::util::fileReadString(), Gentoo, OpenSuSE, readLSBReleaseDistribDescription(), readLSBReleaseDistribId(), readOSReleaseDistribId(), readOSReleaseName(), readOSReleaseVersion(), RedHat, leanux::system::Distribution::release, leanux::system::Distribution::type, Ubuntu, and Unkown.
Referenced by leanux::tools::lmon::Footer::Footer(), and leanux::tools::lrep::htmlSystemDetails().
getKernelVersion()
std::string leanux::system::getKernelVersion ()
Get the kernel version.
Exceptions
Oops if call to uname fails.
Returns
the kernel version.
Examples
example_system.cpp.
Definition at line 80 of file system.cpp.
Referenced by leanux::tools::lmon::Footer::Footer(), leanux::tools::lrep::htmlSystemDetails(), and leanux::init().
getNodeName()
std::string leanux::system::getNodeName ()
The node name of the system.
Not to be confused with a network hostname.
Exceptions
Oops if call to uname fails.
Returns
the system node name.
Examples
example_system.cpp.
Definition at line 90 of file system.cpp.
Referenced by leanux::tools::lmon::Header::Header(), leanux::tools::lrep::htmlSystemDetails(), and leanux::tools::lrep::main().
getNumLogins()
unsigned int leanux::system::getNumLogins ()
The number of user logins as reported by who.
Returns
the number of user logins.
Examples
example_system.cpp.
Definition at line 231 of file system.cpp.
Referenced by leanux::tools::lmon::RealtimeSampler::sampleXSysView(), and leanux::tools::lard::ResSnap::storeSnap().
getNumLoginUsers()
unsigned int leanux::system::getNumLoginUsers ()
The number of distinct users logged in.
Returns
the number of distinct users logged in.
Definition at line 244 of file system.cpp.
Referenced by leanux::tools::lmon::RealtimeSampler::sampleXSysView(), and leanux::tools::lard::ResSnap::storeSnap().
getNumProcesses()
void leanux::system::getNumProcesses (unsigned long * processes)
Get the number of processes on the system.
Examples
example_system.cpp.
Definition at line 219 of file system.cpp.
Referenced by leanux::tools::lmon::RealtimeSampler::sampleXProcView(), leanux::tools::lmon::RealtimeSampler::sampleXSysView(), and leanux::tools::lard::ResSnap::storeSnap().
getOpenFiles()
void leanux::system::getOpenFiles (unsigned long * used, unsigned long * max)
get the current and maximum number of open files.
Parameters
used receives the number of file handles currently allocated.
max receives the maximum number of file handles that can be allocated.
Examples
example_system.cpp.
Definition at line 196 of file system.cpp.
Referenced by leanux::tools::lmon::RealtimeSampler::sampleXSysView(), and leanux::tools::lard::ResSnap::storeSnap().
getOpenInodes()
void leanux::system::getOpenInodes (unsigned long * used, unsigned long * free)
get the used and free number of open inodes.
Definition at line 208 of file system.cpp.
Referenced by leanux::tools::lmon::RealtimeSampler::sampleXSysView(), and leanux::tools::lard::ResSnap::storeSnap().
getPageSize()
long leanux::system::getPageSize ()
Get the system page size.
Exceptions
Oops if call to sysconf fails.
Returns
the system page size.
Examples
example_process.cpp, and example_system.cpp.
Definition at line 104 of file system.cpp.
Referenced by leanux::tools::lrep::htmlCmdRSSDetail(), leanux::tools::lrep::htmlSystemDetails(), leanux::tools::lmon::RealtimeSampler::RealtimeSampler(), leanux::tools::lard::VMSnap::storeSnap(), and leanux::tools::lmon::ProcessView::xrefresh().
getUptime()
double leanux::system::getUptime ()
Get the system uptime in seconds (with centisecond precision).
Taken from /proc/uptime.
Returns
the system uptime in seconds.
Examples
example_cpu.cpp, and example_system.cpp.
Definition at line 166 of file system.cpp.
getUserHz()
long leanux::system::getUserHz ()
Get the number of clock ticks per second.
Used as unit of measure in /proc/stat (and others).
Returns
the number of clock ticks per second.
Examples
example_process.cpp, and example_system.cpp.
Definition at line 192 of file system.cpp.
Referenced by leanux::cpu::getCPUStats(), and leanux::process::getProcPidStat().
getUserName()
std::string leanux::system::getUserName (uid_t uid)
Get username from a uid.
Parameters
uid the uid for which to find the username.
Returns
the username for the uid, or an ampty std::string if not found.
Definition at line 185 of file system.cpp.
Referenced by leanux::tools::lrep::chartTCPClientTimeLine(), leanux::tools::lrep::chartTCPServerTimeLine(), leanux::tools::lrep::chartUserAverage(), leanux::tools::lrep::htmlCmdUidDetail(), leanux::net::operator<<(), leanux::tools::lmon::ProcessView::xrefresh(), and leanux::tools::lmon::NetView::xrefresh().
isBigEndian()
bool leanux::system::isBigEndian ()
Return true when the system is big endian.
Examples
example_system.cpp.
Definition at line 110 of file system.cpp.
readLSBReleaseDistribDescription()
std::string leanux::system::readLSBReleaseDistribDescription () private
Read the DISTRIB_DESCRIPTION from /etc/lsb-release.
Returns
the DISTRIB_DESCRIPTION or an empty std::string if not found.
Definition at line 376 of file system.cpp.
Referenced by getDistribution().
readLSBReleaseDistribId()
std::string leanux::system::readLSBReleaseDistribId () private
Read the DISTRIB_ID from /etc/lsb-release.
Returns
the DISTRIB_ID or an empty std::string if not found.
Definition at line 354 of file system.cpp.
Referenced by getDistribution().
readOSReleaseDistribId()
std::string leanux::system::readOSReleaseDistribId () private
Read the ID from /etc/os-release.
Returns
the ID or an empty std::string if not found.
Definition at line 262 of file system.cpp.
Referenced by getDistribution().
readOSReleaseName()
std::string leanux::system::readOSReleaseName () private
Read the NAME from /etc/os-release.
Returns
the NAME or an empty std::string if not found.
Definition at line 308 of file system.cpp.
Referenced by getDistribution().
readOSReleasePrettyName()
std::string leanux::system::readOSReleasePrettyName () private
Read the PRETTY_NAME from /etc/os-release.
Returns
the PRETTY_NAME or an empty std::string if not found.
Definition at line 285 of file system.cpp.
readOSReleaseVersion()
std::string leanux::system::readOSReleaseVersion () private
Read the VERSION from /etc/os-release.
Returns
the VERSION or an empty std::string if not found.
Definition at line 331 of file system.cpp.
Referenced by getDistribution().