leanux: leanux::tools::lard::MountSnap Class Reference
leanux::tools::lard::MountSnap Class Reference
#include <lar_snap.hpp>
Public Member Functions
MountSnap ()
virtual ~MountSnap ()
virtual void startSnap ()
virtual void stopSnap ()
virtual long storeSnap (const persist::Database &db, long snapid, double seconds)
Protected Attributes
std::map< std::string, unsigned long > fsbytes1_
std::map< std::string, unsigned long > fsbytes2_
block::DeviceStatsMap stat1_
block::DeviceStatsMap stat2_
Static Protected Attributes
static std::map< std::string, block::MajorMinor > devicefilecache_
Detailed Description
Definition at line 180 of file lar_snap.hpp.
Constructor & Destructor Documentation
MountSnap()
leanux::tools::lard::MountSnap::MountSnap () inline
Definition at line 182 of file lar_snap.hpp.
~MountSnap()
virtual leanux::tools::lard::MountSnap::~MountSnap () inline virtual
Definition at line 183 of file lar_snap.hpp.
Member Function Documentation
startSnap()
void leanux::tools::lard::MountSnap::startSnap () virtual
Implements leanux::tools::lard::Snapshot.
Definition at line 552 of file lar_snap.cpp.
References leanux::block::getStats(), and stat1_.
Referenced by leanux::tools::lard::mainLoop().
stopSnap()
void leanux::tools::lard::MountSnap::stopSnap () virtual
Implements leanux::tools::lard::Snapshot.
Definition at line 556 of file lar_snap.cpp.
References devicefilecache_, leanux::block::enumMounts(), fsbytes1_, fsbytes2_, leanux::block::getMountUsedBytes(), leanux::block::getStats(), and stat2_.
Referenced by leanux::tools::lard::mainLoop().
storeSnap()
long leanux::tools::lard::MountSnap::storeSnap (const persist::Database & db, long snapid, double seconds) virtual
Implements leanux::tools::lard::Snapshot.
Definition at line 568 of file lar_snap.cpp.
References leanux::persist::DML::bind(), leanux::block::deltaDeviceStats(), devicefilecache_, leanux::block::enumMounts(), leanux::persist::DML::execute(), fsbytes1_, fsbytes2_, leanux::util::ConfigFile::getConfig(), leanux::block::getFileMajorMinor(), leanux::persist::Query::getLong(), leanux::vmem::getSwapInfo(), leanux::persist::Database::lastInsertRowid(), leanux::persist::Statement::prepare(), leanux::persist::Statement::reset(), stat1_, stat2_, and leanux::persist::Query::step().
Referenced by leanux::tools::lard::mainLoop().
Field Documentation
devicefilecache_
std::map< std::string, block::MajorMinor > leanux::tools::lard::MountSnap::devicefilecache_ static protected
Definition at line 189 of file lar_snap.hpp.
Referenced by stopSnap(), and storeSnap().
fsbytes1_
std::map<std::string,unsigned long> leanux::tools::lard::MountSnap::fsbytes1_ protected
Definition at line 192 of file lar_snap.hpp.
Referenced by stopSnap(), and storeSnap().
fsbytes2_
std::map<std::string,unsigned long> leanux::tools::lard::MountSnap::fsbytes2_ protected
Definition at line 193 of file lar_snap.hpp.
Referenced by stopSnap(), and storeSnap().
stat1_
block::DeviceStatsMap leanux::tools::lard::MountSnap::stat1_ protected
Definition at line 190 of file lar_snap.hpp.
Referenced by startSnap(), and storeSnap().
stat2_
block::DeviceStatsMap leanux::tools::lard::MountSnap::stat2_ protected
Definition at line 191 of file lar_snap.hpp.
Referenced by stopSnap(), and storeSnap().
The documentation for this class was generated from the following files:
tools/lard/lar_snap.hpp
tools/lard/lar_snap.cpp