leanux: leanux::tools::lblk Namespace Reference
leanux::tools::lblk Namespace Reference
Data Structures
struct Options
Decoded options as specified on command line.
Functions
void detailDeviceMapper (const block::MajorMinor &mm, std::ostream &os)
Write device mapper details.
void detailDisk (const block::MajorMinor &mm, std::ostream &os)
Write disk details.
void detailGenericBlockDevice (const block::MajorMinor &mm, std::ostream &os)
Write generic block device details.
void detailLVM (const block::MajorMinor &mm, std::ostream &os)
Write LVM details.
void detailMetaDisk (const block::MajorMinor &mm, std::ostream &os)
Write MetaDisk details.
bool getOptions (int argc, char *argv[])
Transform command line arguments into options.
void listAllDevices (std::ostream &os)
Table listing all devices.
void listAllDisks (std::ostream &os)
Table listing all disks.
void listAllMetaDisks (std::ostream &os)
Table listing all MetaDisks.
void listFile (std::ostream &os, const std::string &file)
Table listing all storage needed for the filesystem containing file.
void listLVM (std::ostream &os)
Table listing LVM devices.
int main (int argc, char *argv[])
Entry point.
block::MajorMinor parseDeviceArg ()
do smart things with user input for device name so that we are not overly picky in user specified device names
void printHelp ()
Print command help.
void printHolderTree (const block::MajorMinor &mm, Tabular &tab, unsigned int level=0)
Write the tree of holders above and including mm, append to tab, starting with level.
void printSlaveTree (const block::MajorMinor &mm, Tabular &tab, unsigned int level=0)
Write the tree of slaves beneath and including mm, append to tab, starting with level.
void printVersion ()
void runOptions ()
Direct output run from options.
Variables
Options options
The user specified options.
Detailed Description
show block device configuration and performance
Data Structure Documentation
leanux::tools::lblk::Options
struct leanux::tools::lblk::Options
Decoded options as specified on command line.
Definition at line 74 of file lblk.cpp.
Data Fields
string device the specified device (empty if not specified)
bool opt_d -d : show only whole disks
bool opt_f -f : shows filesystem info
bool opt_h -h : show help
bool opt_l -l : shows LVM details
bool opt_m -d : show only MetaDisks
bool opt_t -t : shows tree
bool opt_v -v : show version
string opt_w -w substring : show only wwn's containing the substring
Function Documentation
detailDeviceMapper()
void leanux::tools::lblk::detailDeviceMapper (const block::MajorMinor & mm, std::ostream & os)
Write device mapper details.
Parameters
mm the device MajorMinor.
os the ostream to write to.
Definition at line 686 of file lblk.cpp.
References leanux::block::MajorMinor::getClassStr(), and leanux::block::MajorMinor::getName().
Referenced by runOptions().
detailDisk()
void leanux::tools::lblk::detailDisk (const block::MajorMinor & mm, std::ostream & os)
Write disk details.
Parameters
mm the device MajorMinor.
os the ostream to write to.
Definition at line 483 of file lblk.cpp.
References leanux::util::ByteStr(), leanux::block::MajorMinor::deriveWholeDisk(), leanux::sysdevice::destroy(), leanux::block::MajorMinor::getRPM(), leanux::block::MajorMinor::getSysPath(), leanux::sysdevice::SysDevice::getTypeStr(), leanux::block::DeviceStats::io_ms, leanux::util::NumStr(), leanux::block::DeviceStats::reads, leanux::util::TimeStrSec(), leanux::sysdevice::treeDetect(), and leanux::block::DeviceStats::writes.
Referenced by runOptions().
detailGenericBlockDevice()
void leanux::tools::lblk::detailGenericBlockDevice (const block::MajorMinor & mm, std::ostream & os)
Write generic block device details.
Parameters
mm the device MajorMinor.
os the ostream to write to.
Definition at line 674 of file lblk.cpp.
References leanux::block::MajorMinor::getClassStr(), and leanux::block::MajorMinor::getName().
Referenced by runOptions().
detailLVM()
void leanux::tools::lblk::detailLVM (const block::MajorMinor & mm, std::ostream & os)
Write LVM details.
Parameters
mm the device MajorMinor.
os the ostream to write to.
Definition at line 698 of file lblk.cpp.
References leanux::util::ByteStr(), leanux::block::MajorMinor::getAliases(), leanux::block::MajorMinor::getClassStr(), leanux::block::MajorMinor::getDeviceFile(), leanux::block::MajorMinor::getDiskId(), leanux::block::MajorMinor::getDMName(), leanux::block::MajorMinor::getIOScheduler(), leanux::block::MajorMinor::getLVName(), leanux::block::MajorMinor::getMaxHWIOSize(), leanux::block::MajorMinor::getMaxIOSize(), leanux::block::MajorMinor::getMinIOSize(), leanux::block::MajorMinor::getName(), leanux::block::MajorMinor::getReadAhead(), leanux::block::MajorMinor::getSectorSize(), leanux::block::MajorMinor::getSize(), leanux::block::MajorMinor::getSysPath(), and leanux::block::MajorMinor::getVGName().
Referenced by runOptions().
detailMetaDisk()
void leanux::tools::lblk::detailMetaDisk (const block::MajorMinor & mm, std::ostream & os)
Write MetaDisk details.
Parameters
mm the device MajorMinor.
os the ostream to write to.
Definition at line 638 of file lblk.cpp.
References leanux::util::ByteStr(), leanux::block::MajorMinor::getAliases(), leanux::block::MajorMinor::getClassStr(), leanux::block::MajorMinor::getDescription(), leanux::block::MajorMinor::getMDArrayState(), leanux::block::MajorMinor::getMDChunkSize(), leanux::block::MajorMinor::getMDDevices(), leanux::block::MajorMinor::getMDLevel(), leanux::block::MajorMinor::getMDMetaDataVersion(), leanux::block::MajorMinor::getMDName(), leanux::block::MajorMinor::getMDRaidDisks(), leanux::block::MajorMinor::getMDRaidDiskStates(), leanux::block::MajorMinor::getName(), leanux::block::MajorMinor::getSize(), and leanux::block::MajorMinor::getSysPath().
Referenced by runOptions().
getOptions()
bool leanux::tools::lblk::getOptions (int argc, char * argv[])
Transform command line arguments into options.
Parameters
argc as from main.
argv as from main.
Returns
false when the command line arguments could not be parsed.
Definition at line 133 of file lblk.cpp.
References leanux::tools::lblk::Options::device, leanux::tools::lblk::Options::opt_d, leanux::tools::lblk::Options::opt_f, leanux::tools::lblk::Options::opt_h, leanux::tools::lblk::Options::opt_l, leanux::tools::lblk::Options::opt_m, leanux::tools::lblk::Options::opt_t, leanux::tools::lblk::Options::opt_v, leanux::tools::lblk::Options::opt_w, and options.
Referenced by main().
listAllDevices()
void leanux::tools::lblk::listAllDevices (std::ostream & os)
Table listing all devices.
Parameters
os the ostream to write to.
Definition at line 349 of file lblk.cpp.
References leanux::util::ByteStr(), and leanux::block::enumDevices().
Referenced by runOptions().
listAllDisks()
void leanux::tools::lblk::listAllDisks (std::ostream & os)
Table listing all disks.
Parameters
os the ostream to write to.
Definition at line 374 of file lblk.cpp.
References leanux::util::ByteStr(), leanux::block::enumWholeDisks(), leanux::block::DeviceStats::io_ms, leanux::util::NumStr(), leanux::tools::lblk::Options::opt_w, options, leanux::block::DeviceStats::reads, leanux::util::TimeStrSec(), and leanux::block::DeviceStats::writes.
Referenced by runOptions().
listAllMetaDisks()
void leanux::tools::lblk::listAllMetaDisks (std::ostream & os)
Table listing all MetaDisks.
Parameters
os the ostream to write to.
Definition at line 430 of file lblk.cpp.
References leanux::util::ByteStr(), and leanux::block::enumDevices().
Referenced by runOptions().
listFile()
void leanux::tools::lblk::listFile (std::ostream & os, const std::string & file)
Table listing all storage needed for the filesystem containing file.
Parameters
os the ostream to write to.
file the file path.
Definition at line 332 of file lblk.cpp.
References leanux::block::MajorMinor::getNameByMajorMinor(), leanux::block::MajorMinor::isValid(), and printSlaveTree().
Referenced by runOptions().
listLVM()
void leanux::tools::lblk::listLVM (std::ostream & os)
Table listing LVM devices.
Parameters
os the ostream to write to.
Definition at line 307 of file lblk.cpp.
References leanux::block::enumLVMPVS(), printHolderTree(), and printSlaveTree().
Referenced by runOptions().
main()
int leanux::tools::lblk::main (int argc, char * argv[])
Entry point.
Parameters
argc number of command line arguments.
argv command line arguments.
Returns
0 on succes, 1 on Oops, 2 on other errors.
Definition at line 833 of file lblk.cpp.
References leanux::Oops::getMessage(), getOptions(), leanux::init(), printHelp(), and runOptions().
Referenced by main().
parseDeviceArg()
block::MajorMinor leanux::tools::lblk::parseDeviceArg ()
do smart things with user input for device name so that we are not overly picky in user specified device names
Definition at line 729 of file lblk.cpp.
References leanux::tools::lblk::Options::device, leanux::block::MajorMinor::getMajorMinorByName(), leanux::block::MajorMinor::invalid, leanux::block::MajorMinor::isValid(), options, and leanux::util::realPath().
Referenced by runOptions().
printHelp()
void leanux::tools::lblk::printHelp ()
Print command help.
Definition at line 98 of file lblk.cpp.
Referenced by main(), and runOptions().
printHolderTree()
void leanux::tools::lblk::printHolderTree (const block::MajorMinor & mm, Tabular & tab, unsigned int level = 0)
Write the tree of holders above and including mm, append to tab, starting with level.
Parameters
mm the device MajorMinor.
tab the Tabular to write to.
level start level (indent) for the tree.
Definition at line 197 of file lblk.cpp.
References leanux::util::ByteStr(), leanux::block::MajorMinor::getMajorMinorByName(), leanux::block::MajorMinor::getName(), leanux::block::MajorMinor::getNameByMajorMinor(), leanux::block::DeviceStats::io_ms, leanux::util::NumStr(), leanux::block::DeviceStats::reads, leanux::util::TimeStrSec(), and leanux::block::DeviceStats::writes.
Referenced by listLVM(), and runOptions().
printSlaveTree()
void leanux::tools::lblk::printSlaveTree (const block::MajorMinor & mm, Tabular & tab, unsigned int level = 0)
Write the tree of slaves beneath and including mm, append to tab, starting with level.
Parameters
mm the device MajorMinor.
tab the Tabular to write to.
level start level (indent) for the tree.
Definition at line 252 of file lblk.cpp.
References leanux::util::ByteStr(), leanux::block::MajorMinor::deriveWholeDisk(), leanux::block::MajorMinor::getMajorMinorByName(), leanux::block::MajorMinor::getName(), leanux::block::MajorMinor::getNameByMajorMinor(), leanux::block::DeviceStats::io_ms, leanux::util::NumStr(), leanux::block::DeviceStats::reads, leanux::util::TimeStrSec(), and leanux::block::DeviceStats::writes.
Referenced by listFile(), listLVM(), and runOptions().
printVersion()
void leanux::tools::lblk::printVersion ()
Definition at line 91 of file lblk.cpp.
Referenced by runOptions().
runOptions()
void leanux::tools::lblk::runOptions ()
Direct output run from options.
Definition at line 764 of file lblk.cpp.
References detailDeviceMapper(), detailDisk(), detailGenericBlockDevice(), detailLVM(), detailMetaDisk(), leanux::tools::lblk::Options::device, leanux::block::DeviceMapper, leanux::block::MajorMinor::getClass(), leanux::block::MajorMinor::getMajor(), leanux::block::MajorMinor::isBCacheDisk(), leanux::block::MajorMinor::isIDEDisk(), leanux::block::MajorMinor::isMetaDisk(), leanux::block::MajorMinor::isMMCDisk(), leanux::block::MajorMinor::isNVMeDisk(), leanux::block::MajorMinor::isSCSIDisk(), leanux::block::MajorMinor::isValid(), leanux::block::MajorMinor::isVirtIODisk(), listAllDevices(), listAllDisks(), listAllMetaDisks(), listFile(), listLVM(), leanux::block::LVM, leanux::tools::lblk::Options::opt_d, leanux::tools::lblk::Options::opt_f, leanux::tools::lblk::Options::opt_h, leanux::tools::lblk::Options::opt_l, leanux::tools::lblk::Options::opt_m, leanux::tools::lblk::Options::opt_t, leanux::tools::lblk::Options::opt_v, options, parseDeviceArg(), printHelp(), printHolderTree(), printSlaveTree(), and printVersion().
Referenced by main().
Variable Documentation
options
Options leanux::tools::lblk::options
The user specified options.
Definition at line 89 of file lblk.cpp.
Referenced by getOptions(), listAllDisks(), parseDeviceArg(), and runOptions().