leanux: leanux::tools::lrep Namespace Reference
leanux::tools::lrep Namespace Reference
Data Structures
struct IORec
struct NicBWRec
struct Options
Command line options type.
struct SnapRange
Snapshot range type.
struct SnapTotals
Snapshot totals type.
Typedefs
typedef map< int, double > HourValueMap
map of weekday (Mon=0) to a (map of hour to value)
typedef HourValueMap::const_iterator HourValueMapCI
typedef map< int, HourValueMap > WeekHourMap
typedef WeekHourMap::const_iterator WeekHourMapCI
Functions
string chartCmdAverage (const persist::Database &db, const string &domcmd)
void chartCPUTimeLine (const persist::Database &db, const string &dom)
list< string > chartDiskAverage (const persist::Database &db, const string &domutil, const string &domsvctm, const string &domrsws)
void chartDiskRSZHisto (const persist::Database &db, const string &dom, long diskid)
void chartDiskScvHisto (const persist::Database &db, const string &dom, long diskid, double bucket)
void chartDiskTimeLine (const persist::Database &db, const string &domutil, const string &dombwr, const string &dombww, const string &domiopsr, const string &domiopsw, const string &domartm, const string &domawtm, const string &domsvctm)
void chartDiskWSZHisto (const persist::Database &db, const string &dom, long diskid)
void chartKernelTimeLine (const persist::Database &db, const string &domprocs, const string &domusers, const string &domfiles, const string &dominodes)
list< string > chartMountAverage (const persist::Database &db, const string &domutil, const string &domsvctm, const string &domrsws, const string &domgrowth)
void chartMountTimeLine (const persist::Database &db, const string &domutil, const string &dombwr, const string &dombww, const string &domiopsr, const string &domiopsw, const string &domartm, const string &domawtm, const string &domsvctm, const string &domused)
list< string > chartNetAverage (const persist::Database &db, const string &dombw, const string &dompktsz)
void chartNicBWTimeLine (const persist::Database &db, const string &domrx, const string &domtx)
void chartNICPacketTimeLine (const persist::Database &db, const string &domrx, const string &domtx)
void chartPagingTimeLine (const persist::Database &db, const string &dommajflt, const string &dompagein, const string &dompageout)
string chartPerCPUAverage (const persist::Database &db, const string &domname)
void chartSchedTimeLine (const persist::Database &db, const string &domfork, const string &domctxsw, const string &domload5)
string chartTCPClientAverage (const persist::Database &db, const string &dom)
void chartTCPClientTimeLine (const persist::Database &db, const string &dom)
string chartTCPServerAverage (const persist::Database &db, const string &dom)
void chartTCPServerTimeLine (const persist::Database &db, const string &dom)
string chartTotalCPUAverage (const persist::Database &db, const string &domname)
setup the chart in jschart and return the html div element
string chartUserAverage (const persist::Database &db, const string &domcmd)
string chartVMAverage (const persist::Database &db, const string &domname)
void chartVMTimeLine (const persist::Database &db, const string &domram, const string &domswap)
void computeTotals (const persist::Database &db)
compute totals into snaptotals.
void CPUHeatMap (const persist::Database &db)
void DiskHeatMap (const persist::Database &db)
void htmlCmdCPUDetail (const string &cmdname, const persist::Database &db)
void htmlCmdDetails (const persist::Database &db)
void htmlCmdRSSDetail (const string &cmdname, const persist::Database &db)
void htmlCmdUidDetail (const string &cmdname, const persist::Database &db)
void htmlCSS (ofstream &doc)
void htmlDiskDetail (const persist::Database &db, long diskid)
void htmlDiskDetails (const persist::Database &db)
void htmlDiskHolderTree (const persist::Database &db, const block::MajorMinor &mm)
void htmlDiskHolderTreeLine (const persist::Database &db, const block::MajorMinor &mm, unsigned int level)
void htmlHeatMap (ostream &os, WeekHourMap &whmap, const string &title, const std::string &unit, double min, double max)
void htmlHeatMaps (const persist::Database &db)
void htmlReportAverages (const persist::Database &db)
void htmlSnapDetails (const persist::Database &db)
void htmlSystemDetails ()
generate system details html.
void htmlTimeLine (ostream &os, const string &id, const string &title)
void htmlTimeLines (const persist::Database &db)
void jsConst (ofstream &doc)
string jsIdFromString (const string &s)
deterministic transform of arbitray strings into valid javascript identifiers
void jsScript (ofstream &doc)
void load5HeatMap (const persist::Database &db)
int main (int argc, char *argv[])
void NetPktHeatMap (const persist::Database &db)
bool parseArgs (int argc, char *argv[])
void printHelp ()
void printVersion ()
string resolveCacheIP (const string &ip)
get from cache or DNS request on cache miss
Variables
const string body_background_color = "#F9F9F9"
const string body_font_size = "0.70em"
const string border_color = "#888888"
ofstream doc
The output stream (html file).
stringstream html
The buffered HTML doc.
stringstream jschart
The buffered charting javascript.
const long max_chart_pixels = 800
list< pair< string, string > > menu_cmds
cmd menu items
list< pair< string, string > > menu_disks
disk menu items
const double one_gib = 1024.0*1024.0*1024.0
Options options
Command line options.
map< string, string > resolvemap
map of ip's to resolved names to prevent repeated DNS requests
SnapRange snaprange
Snapshot range.
SnapTotals snaptotals
Snapshot totals.
const string th_background_color = "#DDDDDD"
const string timeline_background_color = "backgroundColor: '#E0E0E0'"
const string timeline_chart_height = "230px"
const string timeline_chartarea = "chartArea: {left:70, height:'70%', right:10}"
const string timeline_fontsize = "fontSize: 10"
const string timeline_legend = "legend: {position: 'top', maxLines: 3 }"
Detailed Description
generate HTML reports with javascript Google charts from a lard database
Data Structure Documentation
leanux::tools::lrep::IORec
struct leanux::tools::lrep::IORec
Definition at line 1827 of file lrep.cpp.
Data Fields
double artm
double awtm
double bwr
double bww
double iopsr
double iopsw
double svctm
double used
double util
leanux::tools::lrep::NicBWRec
struct leanux::tools::lrep::NicBWRec
Definition at line 2428 of file lrep.cpp.
Data Fields
double rx
double tx
leanux::tools::lrep::Options
struct leanux::tools::lrep::Options
Command line options type.
Definition at line 131 of file lrep.cpp.
Data Fields
time_t begin if nonzero, start of interval
time_t end if nonzero, end of interval
bool help if set, only display help
string htmlfile the html output file.
string lardfile the lard/sqlite database.
bool noresolv if set, do not attempt to resolv IP adresses
unsigned int trail if nonzero, the last trail in minutes
bool version if set, only display version
leanux::tools::lrep::SnapRange
struct leanux::tools::lrep::SnapRange
Snapshot range type.
Definition at line 88 of file lrep.cpp.
Data Fields
string local_time_max
string local_time_min
long snap_count
long snap_max
long snap_min
long snaps_in_db
time_t time_max
time_t time_min
long timeline_bucket
leanux::tools::lrep::SnapTotals
struct leanux::tools::lrep::SnapTotals
Snapshot totals type.
Definition at line 108 of file lrep.cpp.
Data Fields
double cmd_iotime_seconds
double cmd_systemcpu_seconds
double cmd_usercpu_seconds
double cpu_seconds
double io_seconds
double iowait_cpu_seconds
double irq_cpu_seconds
double nice_cpu_seconds
double softirq_cpu_seconds
double steal_cpu_seconds
double system_cpu_seconds
double user_cpu_seconds
Typedef Documentation
HourValueMap
typedef map<int,double> leanux::tools::lrep::HourValueMap
map of weekday (Mon=0) to a (map of hour to value)
Definition at line 2857 of file lrep.cpp.
HourValueMapCI
typedef HourValueMap::const_iterator leanux::tools::lrep::HourValueMapCI
Definition at line 2858 of file lrep.cpp.
WeekHourMap
typedef map< int,HourValueMap> leanux::tools::lrep::WeekHourMap
Definition at line 2859 of file lrep.cpp.
WeekHourMapCI
typedef WeekHourMap::const_iterator leanux::tools::lrep::WeekHourMapCI
Definition at line 2860 of file lrep.cpp.
Function Documentation
chartCmdAverage()
string leanux::tools::lrep::chartCmdAverage (const persist::Database & db, const string & domcmd)
Definition at line 926 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::tools::lrep::SnapTotals::cmd_iotime_seconds, leanux::tools::lrep::SnapTotals::cmd_systemcpu_seconds, leanux::tools::lrep::SnapTotals::cmd_usercpu_seconds, leanux::persist::Query::getDouble(), leanux::persist::Query::getText(), leanux::tools::lrep::SnapTotals::io_seconds, leanux::tools::lrep::SnapTotals::irq_cpu_seconds, jschart, leanux::tools::lrep::SnapTotals::nice_cpu_seconds, leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, snaptotals, leanux::tools::lrep::SnapTotals::softirq_cpu_seconds, leanux::persist::Query::step(), leanux::tools::lrep::SnapTotals::system_cpu_seconds, timeline_background_color, and leanux::tools::lrep::SnapTotals::user_cpu_seconds.
Referenced by htmlReportAverages().
chartCPUTimeLine()
void leanux::tools::lrep::chartCPUTimeLine (const persist::Database & db, const string & dom)
Definition at line 1449 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), jschart, leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::persist::Query::step(), timeline_background_color, leanux::tools::lrep::SnapRange::timeline_bucket, timeline_chartarea, timeline_fontsize, and timeline_legend.
Referenced by htmlTimeLines().
chartDiskAverage()
list<string> leanux::tools::lrep::chartDiskAverage (const persist::Database & db, const string & domutil, const string & domsvctm, const string & domrsws)
Definition at line 1308 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), leanux::persist::Query::getText(), jschart, leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::persist::Query::step(), and timeline_background_color.
Referenced by htmlReportAverages().
chartDiskRSZHisto()
void leanux::tools::lrep::chartDiskRSZHisto (const persist::Database & db, const string & dom, long diskid)
Definition at line 243 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), leanux::persist::Query::getInt(), jschart, leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::persist::Query::step(), and timeline_background_color.
Referenced by htmlDiskDetail().
chartDiskScvHisto()
void leanux::tools::lrep::chartDiskScvHisto (const persist::Database & db, const string & dom, long diskid, double bucket)
Definition at line 319 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), leanux::persist::Query::getInt(), jschart, leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::persist::Query::step(), and timeline_background_color.
Referenced by htmlDiskDetail().
chartDiskTimeLine()
void leanux::tools::lrep::chartDiskTimeLine (const persist::Database & db, const string & domutil, const string & dombwr, const string & dombww, const string & domiopsr, const string & domiopsw, const string & domartm, const string & domawtm, const string & domsvctm)
Definition at line 1829 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), leanux::persist::Query::getText(), jschart, leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::persist::Query::step(), timeline_background_color, leanux::tools::lrep::SnapRange::timeline_bucket, timeline_chartarea, timeline_fontsize, and timeline_legend.
Referenced by htmlTimeLines().
chartDiskWSZHisto()
void leanux::tools::lrep::chartDiskWSZHisto (const persist::Database & db, const string & dom, long diskid)
Definition at line 281 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), jschart, leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::persist::Query::step(), and timeline_background_color.
Referenced by htmlDiskDetail().
chartKernelTimeLine()
void leanux::tools::lrep::chartKernelTimeLine (const persist::Database & db, const string & domprocs, const string & domusers, const string & domfiles, const string & dominodes)
Definition at line 1656 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), jschart, leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::persist::Query::step(), timeline_background_color, leanux::tools::lrep::SnapRange::timeline_bucket, timeline_chartarea, and timeline_fontsize.
Referenced by htmlTimeLines().
chartMountAverage()
list<string> leanux::tools::lrep::chartMountAverage (const persist::Database & db, const string & domutil, const string & domsvctm, const string & domrsws, const string & domgrowth)
Definition at line 1184 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), leanux::persist::Query::getText(), jschart, leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::persist::Query::step(), and timeline_background_color.
Referenced by htmlReportAverages().
chartMountTimeLine()
void leanux::tools::lrep::chartMountTimeLine (const persist::Database & db, const string & domutil, const string & dombwr, const string & dombww, const string & domiopsr, const string & domiopsw, const string & domartm, const string & domawtm, const string & domsvctm, const string & domused)
Definition at line 2113 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), leanux::persist::Query::getText(), jschart, leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::persist::Query::step(), timeline_background_color, leanux::tools::lrep::SnapRange::timeline_bucket, timeline_chartarea, timeline_fontsize, and timeline_legend.
Referenced by htmlTimeLines().
chartNetAverage()
list<string> leanux::tools::lrep::chartNetAverage (const persist::Database & db, const string & dombw, const string & dompktsz)
Definition at line 982 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), leanux::persist::Query::getText(), jschart, leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::persist::Query::step(), and timeline_background_color.
Referenced by htmlReportAverages().
chartNicBWTimeLine()
void leanux::tools::lrep::chartNicBWTimeLine (const persist::Database & db, const string & domrx, const string & domtx)
Definition at line 2528 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), leanux::persist::Query::getText(), jschart, leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::persist::Query::step(), timeline_background_color, leanux::tools::lrep::SnapRange::timeline_bucket, timeline_chartarea, timeline_fontsize, and timeline_legend.
Referenced by htmlTimeLines().
chartNICPacketTimeLine()
void leanux::tools::lrep::chartNICPacketTimeLine (const persist::Database & db, const string & domrx, const string & domtx)
Definition at line 2433 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), leanux::persist::Query::getText(), jschart, leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::persist::Query::step(), timeline_background_color, leanux::tools::lrep::SnapRange::timeline_bucket, timeline_chartarea, timeline_fontsize, and timeline_legend.
Referenced by htmlTimeLines().
chartPagingTimeLine()
void leanux::tools::lrep::chartPagingTimeLine (const persist::Database & db, const string & dommajflt, const string & dompagein, const string & dompageout)
Definition at line 1491 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), jschart, leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::persist::Query::step(), timeline_background_color, leanux::tools::lrep::SnapRange::timeline_bucket, timeline_chartarea, and timeline_fontsize.
Referenced by htmlTimeLines().
chartPerCPUAverage()
string leanux::tools::lrep::chartPerCPUAverage (const persist::Database & db, const string & domname)
Definition at line 799 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), leanux::persist::Query::getInt(), jschart, leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::persist::Query::step(), and timeline_background_color.
Referenced by htmlReportAverages().
chartSchedTimeLine()
void leanux::tools::lrep::chartSchedTimeLine (const persist::Database & db, const string & domfork, const string & domctxsw, const string & domload5)
Definition at line 1573 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), jschart, leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::persist::Query::step(), timeline_background_color, leanux::tools::lrep::SnapRange::timeline_bucket, timeline_chartarea, and timeline_fontsize.
Referenced by htmlTimeLines().
chartTCPClientAverage()
string leanux::tools::lrep::chartTCPClientAverage (const persist::Database & db, const string & dom)
Definition at line 1121 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), leanux::persist::Query::getInt(), leanux::net::getServiceName(), leanux::persist::Query::getText(), jschart, leanux::tools::lrep::Options::noresolv, options, leanux::persist::Statement::prepare(), resolveCacheIP(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::persist::Query::step(), and timeline_background_color.
Referenced by htmlReportAverages().
chartTCPClientTimeLine()
void leanux::tools::lrep::chartTCPClientTimeLine (const persist::Database & db, const string & dom)
Definition at line 2690 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), leanux::persist::Query::getInt(), leanux::net::getServiceName(), leanux::persist::Query::getText(), leanux::system::getUserName(), jschart, leanux::tools::lrep::Options::noresolv, options, leanux::persist::Statement::prepare(), resolveCacheIP(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::persist::Query::step(), timeline_background_color, leanux::tools::lrep::SnapRange::timeline_bucket, timeline_chartarea, timeline_fontsize, and timeline_legend.
Referenced by htmlTimeLines().
chartTCPServerAverage()
string leanux::tools::lrep::chartTCPServerAverage (const persist::Database & db, const string & dom)
Definition at line 1058 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), leanux::persist::Query::getInt(), leanux::net::getServiceName(), leanux::persist::Query::getText(), jschart, leanux::tools::lrep::Options::noresolv, options, leanux::persist::Statement::prepare(), resolveCacheIP(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::persist::Query::step(), and timeline_background_color.
Referenced by htmlReportAverages().
chartTCPServerTimeLine()
void leanux::tools::lrep::chartTCPServerTimeLine (const persist::Database & db, const string & dom)
Definition at line 2619 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), leanux::persist::Query::getInt(), leanux::net::getServiceName(), leanux::system::getUserName(), jschart, leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::persist::Query::step(), timeline_background_color, leanux::tools::lrep::SnapRange::timeline_bucket, timeline_chartarea, timeline_fontsize, and timeline_legend.
Referenced by htmlTimeLines().
chartTotalCPUAverage()
string leanux::tools::lrep::chartTotalCPUAverage (const persist::Database & db, const string & domname)
setup the chart in jschart and return the html div element
Definition at line 753 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), jschart, leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::persist::Query::step(), and timeline_background_color.
Referenced by htmlReportAverages().
chartUserAverage()
string leanux::tools::lrep::chartUserAverage (const persist::Database & db, const string & domcmd)
Definition at line 880 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), leanux::persist::Query::getInt(), leanux::system::getUserName(), jschart, leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::persist::Query::step(), and timeline_background_color.
Referenced by htmlReportAverages().
chartVMAverage()
string leanux::tools::lrep::chartVMAverage (const persist::Database & db, const string & domname)
Definition at line 841 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), jschart, one_gib, leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::persist::Query::step(), and timeline_background_color.
Referenced by htmlReportAverages().
chartVMTimeLine()
void leanux::tools::lrep::chartVMTimeLine (const persist::Database & db, const string & domram, const string & domswap)
Definition at line 1762 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), jschart, one_gib, leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::persist::Query::step(), timeline_background_color, leanux::tools::lrep::SnapRange::timeline_bucket, timeline_chartarea, timeline_fontsize, and timeline_legend.
Referenced by htmlTimeLines().
computeTotals()
void leanux::tools::lrep::computeTotals (const persist::Database & db)
compute totals into snaptotals.
Definition at line 207 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::tools::lrep::SnapTotals::cmd_iotime_seconds, leanux::tools::lrep::SnapTotals::cmd_systemcpu_seconds, leanux::tools::lrep::SnapTotals::cmd_usercpu_seconds, leanux::tools::lrep::SnapTotals::cpu_seconds, leanux::persist::Query::getDouble(), leanux::tools::lrep::SnapTotals::io_seconds, leanux::tools::lrep::SnapTotals::iowait_cpu_seconds, leanux::tools::lrep::SnapTotals::irq_cpu_seconds, leanux::tools::lrep::SnapTotals::nice_cpu_seconds, leanux::persist::Statement::prepare(), leanux::persist::Statement::reset(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, snaptotals, leanux::tools::lrep::SnapTotals::softirq_cpu_seconds, leanux::tools::lrep::SnapTotals::steal_cpu_seconds, leanux::persist::Query::step(), leanux::tools::lrep::SnapTotals::system_cpu_seconds, and leanux::tools::lrep::SnapTotals::user_cpu_seconds.
Referenced by main().
CPUHeatMap()
void leanux::tools::lrep::CPUHeatMap (const persist::Database & db)
Definition at line 2902 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), leanux::persist::Query::getInt(), html, htmlHeatMap(), leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, and leanux::persist::Query::step().
Referenced by htmlHeatMaps().
DiskHeatMap()
void leanux::tools::lrep::DiskHeatMap (const persist::Database & db)
Definition at line 2920 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), leanux::persist::Query::getInt(), html, htmlHeatMap(), leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, and leanux::persist::Query::step().
Referenced by htmlHeatMaps().
htmlCmdCPUDetail()
void leanux::tools::lrep::htmlCmdCPUDetail (const string & cmdname, const persist::Database & db)
Definition at line 2987 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), html, htmlTimeLine(), jschart, jsIdFromString(), leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::persist::Query::step(), timeline_background_color, and leanux::tools::lrep::SnapRange::timeline_bucket.
Referenced by htmlCmdDetails().
htmlCmdDetails()
void leanux::tools::lrep::htmlCmdDetails (const persist::Database & db)
Definition at line 3110 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getText(), html, htmlCmdCPUDetail(), htmlCmdRSSDetail(), htmlCmdUidDetail(), menu_cmds, leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, and leanux::persist::Query::step().
Referenced by main().
htmlCmdRSSDetail()
void leanux::tools::lrep::htmlCmdRSSDetail (const string & cmdname, const persist::Database & db)
Definition at line 3041 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), leanux::system::getPageSize(), html, htmlTimeLine(), jschart, jsIdFromString(), leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::persist::Query::step(), timeline_background_color, and leanux::tools::lrep::SnapRange::timeline_bucket.
Referenced by htmlCmdDetails().
htmlCmdUidDetail()
void leanux::tools::lrep::htmlCmdUidDetail (const string & cmdname, const persist::Database & db)
Definition at line 3093 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), leanux::persist::Query::getInt(), leanux::system::getUserName(), html, leanux::util::NumStr(), leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, and leanux::persist::Query::step().
Referenced by htmlCmdDetails().
htmlCSS()
void leanux::tools::lrep::htmlCSS (ofstream & doc)
Definition at line 655 of file lrep.cpp.
References body_background_color, body_font_size, border_color, doc, and th_background_color.
Referenced by main().
htmlDiskDetail()
void leanux::tools::lrep::htmlDiskDetail (const persist::Database & db, long diskid)
Definition at line 404 of file lrep.cpp.
References leanux::persist::DML::bind(), chartDiskRSZHisto(), chartDiskScvHisto(), chartDiskWSZHisto(), leanux::persist::Query::getDouble(), html, leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, and leanux::persist::Query::step().
Referenced by htmlDiskDetails().
htmlDiskDetails()
void leanux::tools::lrep::htmlDiskDetails (const persist::Database & db)
Definition at line 436 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::util::ByteStr(), leanux::sysdevice::destroy(), leanux::block::enumWholeDisks(), leanux::persist::Query::getDouble(), leanux::persist::Query::getInt(), leanux::Oops::getMessage(), leanux::persist::Query::getText(), leanux::sysdevice::SysDevice::getTypeStr(), html, htmlDiskDetail(), htmlDiskHolderTree(), menu_disks, leanux::util::NumStr(), leanux::persist::Statement::prepare(), leanux::util::shortenString(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::persist::Query::step(), and leanux::sysdevice::treeDetect().
Referenced by main().
htmlDiskHolderTree()
void leanux::tools::lrep::htmlDiskHolderTree (const persist::Database & db, const block::MajorMinor & mm)
Definition at line 386 of file lrep.cpp.
References leanux::block::MajorMinor::getName(), html, and htmlDiskHolderTreeLine().
Referenced by htmlDiskDetails().
htmlDiskHolderTreeLine()
void leanux::tools::lrep::htmlDiskHolderTreeLine (const persist::Database & db, const block::MajorMinor & mm, unsigned int level)
Definition at line 359 of file lrep.cpp.
References leanux::util::ByteStr(), leanux::block::MajorMinor::getName(), and html.
Referenced by htmlDiskHolderTree().
htmlHeatMap()
void leanux::tools::lrep::htmlHeatMap (ostream & os, WeekHourMap & whmap, const string & title, const std::string & unit, double min, double max)
Definition at line 2862 of file lrep.cpp.
References leanux::util::NumStr().
Referenced by CPUHeatMap(), DiskHeatMap(), load5HeatMap(), and NetPktHeatMap().
htmlHeatMaps()
void leanux::tools::lrep::htmlHeatMaps (const persist::Database & db)
Definition at line 2974 of file lrep.cpp.
References CPUHeatMap(), DiskHeatMap(), html, load5HeatMap(), NetPktHeatMap(), snaprange, leanux::tools::lrep::SnapRange::time_max, and leanux::tools::lrep::SnapRange::time_min.
Referenced by main().
htmlReportAverages()
void leanux::tools::lrep::htmlReportAverages (const persist::Database & db)
Definition at line 1405 of file lrep.cpp.
References chartCmdAverage(), chartDiskAverage(), chartMountAverage(), chartNetAverage(), chartPerCPUAverage(), chartTCPClientAverage(), chartTCPServerAverage(), chartTotalCPUAverage(), chartUserAverage(), chartVMAverage(), and html.
Referenced by main().
htmlSnapDetails()
void leanux::tools::lrep::htmlSnapDetails (const persist::Database & db)
Definition at line 630 of file lrep.cpp.
References leanux::util::ByteStr(), html, leanux::tools::lrep::Options::lardfile, leanux::tools::lrep::SnapRange::local_time_max, leanux::tools::lrep::SnapRange::local_time_min, leanux::util::localStrISOTime(), options, leanux::tools::lrep::SnapRange::snap_count, leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::tools::lrep::SnapRange::snaps_in_db, leanux::tools::lrep::SnapRange::time_max, leanux::tools::lrep::SnapRange::time_min, leanux::tools::lrep::SnapRange::timeline_bucket, and leanux::util::TimeStrSec().
Referenced by main().
htmlSystemDetails()
void leanux::tools::lrep::htmlSystemDetails ()
generate system details html.
Definition at line 580 of file lrep.cpp.
References leanux::util::ByteStr(), leanux::cpu::CPUTopology::cores, leanux::block::enumDevices(), leanux::block::enumWholeDisks(), leanux::system::getArchitecture(), leanux::block::getAttachedStorageSize(), leanux::system::getBoardName(), leanux::system::getBoardVendor(), leanux::system::getBoardVersion(), leanux::system::getChassisTypeString(), leanux::cpu::getCPUInfo(), leanux::cpu::getCPUTopology(), leanux::net::getDeviceIP4Addresses(), leanux::system::getDistribution(), leanux::system::getKernelVersion(), leanux::system::getNodeName(), leanux::system::getPageSize(), leanux::vmem::getVMStat(), html, leanux::cpu::CPUTopology::logical, leanux::vmem::VMStat::mem_total, leanux::cpu::CPUInfo::model, leanux::tools::lrep::Options::noresolv, options, leanux::cpu::CPUTopology::physical, leanux::system::Distribution::release, and resolveCacheIP().
Referenced by main().
htmlTimeLine()
void leanux::tools::lrep::htmlTimeLine (ostream & os, const string & id, const string & title)
Definition at line 2761 of file lrep.cpp.
References max_chart_pixels, and timeline_chart_height.
Referenced by htmlCmdCPUDetail(), htmlCmdRSSDetail(), and htmlTimeLines().
htmlTimeLines()
void leanux::tools::lrep::htmlTimeLines (const persist::Database & db)
Definition at line 2768 of file lrep.cpp.
References chartCPUTimeLine(), chartDiskTimeLine(), chartKernelTimeLine(), chartMountTimeLine(), chartNicBWTimeLine(), chartNICPacketTimeLine(), chartPagingTimeLine(), chartSchedTimeLine(), chartTCPClientTimeLine(), chartTCPServerTimeLine(), chartVMTimeLine(), html, htmlTimeLine(), snaprange, leanux::tools::lrep::SnapRange::timeline_bucket, and leanux::util::TimeStrSec().
Referenced by main().
jsConst()
void leanux::tools::lrep::jsConst (ofstream & doc)
Definition at line 723 of file lrep.cpp.
References doc.
Referenced by main().
jsIdFromString()
string leanux::tools::lrep::jsIdFromString (const string & s)
deterministic transform of arbitray strings into valid javascript identifiers
Definition at line 170 of file lrep.cpp.
Referenced by htmlCmdCPUDetail(), and htmlCmdRSSDetail().
jsScript()
void leanux::tools::lrep::jsScript (ofstream & doc)
Definition at line 736 of file lrep.cpp.
References doc.
Referenced by main().
load5HeatMap()
void leanux::tools::lrep::load5HeatMap (const persist::Database & db)
Definition at line 2938 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), leanux::persist::Query::getInt(), html, htmlHeatMap(), leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, and leanux::persist::Query::step().
Referenced by htmlHeatMaps().
main()
int leanux::tools::lrep::main (int argc, char * argv[])
Definition at line 3214 of file lrep.cpp.
References leanux::tools::lrep::Options::begin, leanux::persist::DML::bind(), computeTotals(), doc, leanux::tools::lrep::Options::end, leanux::util::Stopwatch::getElapsedSeconds(), leanux::persist::Query::getInt(), leanux::Oops::getMessage(), leanux::system::getNodeName(), leanux::persist::Query::getText(), leanux::tools::lrep::Options::help, html, htmlCmdDetails(), htmlCSS(), htmlDiskDetails(), leanux::tools::lrep::Options::htmlfile, htmlHeatMaps(), htmlReportAverages(), htmlSnapDetails(), htmlSystemDetails(), htmlTimeLines(), leanux::init(), jschart, jsConst(), jsScript(), leanux::tools::lrep::Options::lardfile, leanux::tools::lrep::SnapRange::local_time_max, leanux::tools::lrep::SnapRange::local_time_min, max_chart_pixels, menu_cmds, menu_disks, options, parseArgs(), leanux::persist::Statement::prepare(), printHelp(), printVersion(), leanux::persist::Statement::reset(), leanux::tools::lrep::SnapRange::snap_count, leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, leanux::tools::lrep::SnapRange::snaps_in_db, leanux::util::Stopwatch::start(), leanux::persist::Query::step(), leanux::util::Stopwatch::stop(), leanux::tools::lrep::SnapRange::time_max, leanux::tools::lrep::SnapRange::time_min, leanux::tools::lrep::SnapRange::timeline_bucket, leanux::util::TimeStrSec(), leanux::tools::lrep::Options::trail, and leanux::tools::lrep::Options::version.
Referenced by main().
NetPktHeatMap()
void leanux::tools::lrep::NetPktHeatMap (const persist::Database & db)
Definition at line 2956 of file lrep.cpp.
References leanux::persist::DML::bind(), leanux::persist::Query::getDouble(), leanux::persist::Query::getInt(), html, htmlHeatMap(), leanux::persist::Statement::prepare(), leanux::tools::lrep::SnapRange::snap_max, leanux::tools::lrep::SnapRange::snap_min, snaprange, and leanux::persist::Query::step().
Referenced by htmlHeatMaps().
parseArgs()
bool leanux::tools::lrep::parseArgs (int argc, char * argv[])
Definition at line 3133 of file lrep.cpp.
References leanux::tools::lrep::Options::begin, leanux::tools::lrep::Options::end, leanux::tools::lrep::Options::help, leanux::tools::lrep::Options::htmlfile, leanux::tools::lrep::Options::lardfile, leanux::tools::lrep::Options::noresolv, options, leanux::tools::lrep::Options::trail, and leanux::tools::lrep::Options::version.
Referenced by main().
printHelp()
void leanux::tools::lrep::printHelp ()
Definition at line 3208 of file lrep.cpp.
Referenced by main().
printVersion()
void leanux::tools::lrep::printVersion ()
Definition at line 3204 of file lrep.cpp.
Referenced by main().
resolveCacheIP()
string leanux::tools::lrep::resolveCacheIP (const string & ip)
get from cache or DNS request on cache miss
Definition at line 184 of file lrep.cpp.
References leanux::net::resolveIP(), and resolvemap.
Referenced by chartTCPClientAverage(), chartTCPClientTimeLine(), chartTCPServerAverage(), and htmlSystemDetails().
Variable Documentation
body_background_color
const string leanux::tools::lrep::body_background_color = "#F9F9F9"
Definition at line 73 of file lrep.cpp.
Referenced by htmlCSS().
body_font_size
const string leanux::tools::lrep::body_font_size = "0.70em"
Definition at line 72 of file lrep.cpp.
Referenced by htmlCSS().
border_color
const string leanux::tools::lrep::border_color = "#888888"
Definition at line 74 of file lrep.cpp.
Referenced by htmlCSS().
doc
ofstream leanux::tools::lrep::doc
The output stream (html file).
Definition at line 150 of file lrep.cpp.
Referenced by htmlCSS(), jsConst(), jsScript(), and main().
html
stringstream leanux::tools::lrep::html
The buffered HTML doc.
Definition at line 155 of file lrep.cpp.
Referenced by CPUHeatMap(), DiskHeatMap(), htmlCmdCPUDetail(), htmlCmdDetails(), htmlCmdRSSDetail(), htmlCmdUidDetail(), htmlDiskDetail(), htmlDiskDetails(), htmlDiskHolderTree(), htmlDiskHolderTreeLine(), htmlHeatMaps(), htmlReportAverages(), htmlSnapDetails(), htmlSystemDetails(), htmlTimeLines(), load5HeatMap(), main(), and NetPktHeatMap().
jschart
stringstream leanux::tools::lrep::jschart
The buffered charting javascript.
Definition at line 160 of file lrep.cpp.
Referenced by chartCmdAverage(), chartCPUTimeLine(), chartDiskAverage(), chartDiskRSZHisto(), chartDiskScvHisto(), chartDiskTimeLine(), chartDiskWSZHisto(), chartKernelTimeLine(), chartMountAverage(), chartMountTimeLine(), chartNetAverage(), chartNicBWTimeLine(), chartNICPacketTimeLine(), chartPagingTimeLine(), chartPerCPUAverage(), chartSchedTimeLine(), chartTCPClientAverage(), chartTCPClientTimeLine(), chartTCPServerAverage(), chartTCPServerTimeLine(), chartTotalCPUAverage(), chartUserAverage(), chartVMAverage(), chartVMTimeLine(), htmlCmdCPUDetail(), htmlCmdRSSDetail(), and main().
max_chart_pixels
const long leanux::tools::lrep::max_chart_pixels = 800
Definition at line 81 of file lrep.cpp.
Referenced by htmlTimeLine(), and main().
menu_cmds
list<pair <string,string> > leanux::tools::lrep::menu_cmds
cmd menu items
Definition at line 202 of file lrep.cpp.
Referenced by htmlCmdDetails(), and main().
menu_disks
list<pair <string,string> > leanux::tools::lrep::menu_disks
disk menu items
Definition at line 197 of file lrep.cpp.
Referenced by htmlDiskDetails(), and main().
one_gib
const double leanux::tools::lrep::one_gib = 1024.0*1024.0*1024.0
Definition at line 83 of file lrep.cpp.
Referenced by chartVMAverage(), and chartVMTimeLine().
options
Options leanux::tools::lrep::options
Command line options.
Definition at line 145 of file lrep.cpp.
Referenced by chartTCPClientAverage(), chartTCPClientTimeLine(), chartTCPServerAverage(), htmlSnapDetails(), htmlSystemDetails(), main(), and parseArgs().
resolvemap
map<string,string> leanux::tools::lrep::resolvemap
map of ip's to resolved names to prevent repeated DNS requests
Definition at line 165 of file lrep.cpp.
Referenced by resolveCacheIP().
snaprange
SnapRange leanux::tools::lrep::snaprange
Snapshot range.
Definition at line 103 of file lrep.cpp.
Referenced by chartCmdAverage(), chartCPUTimeLine(), chartDiskAverage(), chartDiskRSZHisto(), chartDiskScvHisto(), chartDiskTimeLine(), chartDiskWSZHisto(), chartKernelTimeLine(), chartMountAverage(), chartMountTimeLine(), chartNetAverage(), chartNicBWTimeLine(), chartNICPacketTimeLine(), chartPagingTimeLine(), chartPerCPUAverage(), chartSchedTimeLine(), chartTCPClientAverage(), chartTCPClientTimeLine(), chartTCPServerAverage(), chartTCPServerTimeLine(), chartTotalCPUAverage(), chartUserAverage(), chartVMAverage(), chartVMTimeLine(), computeTotals(), CPUHeatMap(), DiskHeatMap(), htmlCmdCPUDetail(), htmlCmdDetails(), htmlCmdRSSDetail(), htmlCmdUidDetail(), htmlDiskDetail(), htmlDiskDetails(), htmlHeatMaps(), htmlSnapDetails(), htmlTimeLines(), load5HeatMap(), main(), and NetPktHeatMap().
snaptotals
SnapTotals leanux::tools::lrep::snaptotals
Snapshot totals.
Definition at line 126 of file lrep.cpp.
Referenced by chartCmdAverage(), and computeTotals().
th_background_color
const string leanux::tools::lrep::th_background_color = "#DDDDDD"
Definition at line 75 of file lrep.cpp.
Referenced by htmlCSS().
timeline_background_color
const string leanux::tools::lrep::timeline_background_color = "backgroundColor: '#E0E0E0'"
Definition at line 79 of file lrep.cpp.
Referenced by chartCmdAverage(), chartCPUTimeLine(), chartDiskAverage(), chartDiskRSZHisto(), chartDiskScvHisto(), chartDiskTimeLine(), chartDiskWSZHisto(), chartKernelTimeLine(), chartMountAverage(), chartMountTimeLine(), chartNetAverage(), chartNicBWTimeLine(), chartNICPacketTimeLine(), chartPagingTimeLine(), chartPerCPUAverage(), chartSchedTimeLine(), chartTCPClientAverage(), chartTCPClientTimeLine(), chartTCPServerAverage(), chartTCPServerTimeLine(), chartTotalCPUAverage(), chartUserAverage(), chartVMAverage(), chartVMTimeLine(), htmlCmdCPUDetail(), and htmlCmdRSSDetail().
timeline_chart_height
const string leanux::tools::lrep::timeline_chart_height = "230px"
Definition at line 76 of file lrep.cpp.
Referenced by htmlTimeLine().
timeline_chartarea
const string leanux::tools::lrep::timeline_chartarea = "chartArea: {left:70, height:'70%', right:10}"
Definition at line 77 of file lrep.cpp.
Referenced by chartCPUTimeLine(), chartDiskTimeLine(), chartKernelTimeLine(), chartMountTimeLine(), chartNicBWTimeLine(), chartNICPacketTimeLine(), chartPagingTimeLine(), chartSchedTimeLine(), chartTCPClientTimeLine(), chartTCPServerTimeLine(), and chartVMTimeLine().
timeline_fontsize
const string leanux::tools::lrep::timeline_fontsize = "fontSize: 10"
Definition at line 80 of file lrep.cpp.
Referenced by chartCPUTimeLine(), chartDiskTimeLine(), chartKernelTimeLine(), chartMountTimeLine(), chartNicBWTimeLine(), chartNICPacketTimeLine(), chartPagingTimeLine(), chartSchedTimeLine(), chartTCPClientTimeLine(), chartTCPServerTimeLine(), and chartVMTimeLine().
timeline_legend
const string leanux::tools::lrep::timeline_legend = "legend: {position: 'top', maxLines: 3 }"
Definition at line 78 of file lrep.cpp.
Referenced by chartCPUTimeLine(), chartDiskTimeLine(), chartMountTimeLine(), chartNicBWTimeLine(), chartNICPacketTimeLine(), chartTCPClientTimeLine(), chartTCPServerTimeLine(), and chartVMTimeLine().