leanux: leanux::Oops Class Reference
leanux::Oops Class Reference
leanux exception class.
#include <oops.hpp>
Public Member Functions
Oops (const char *file, int line, const std::string &msg)
construct Oops from source file name, line and with msg.
Oops (const char *file, int line, int err)
construct from source file name, line and system error.
const std::string & getMessage () const
Get the Oops message.
Static Protected Member Functions
static std::string stripSourceDir (const std::string &srcdir)
Protected Attributes
std::string msg_
The Oops message.
Detailed Description
leanux exception class.
Examples
example_cpu.cpp, example_pci.cpp, example_process.cpp, example_process2.cpp, example_system.cpp, and example_usb.cpp.
Definition at line 46 of file oops.hpp.
Constructor & Destructor Documentation
Oops() [1/2]
leanux::Oops::Oops (const char * file, int line, const std::string & msg)
construct Oops from source file name, line and with msg.
Parameters
file the source file throwing the Oops.
line the line on which the Oops is thrown.
msg the Oops message.
Definition at line 44 of file oops.cpp.
References msg_, and stripSourceDir().
Oops() [2/2]
leanux::Oops::Oops (const char * file, int line, int err)
construct from source file name, line and system error.
Parameters
file the source file throwing the Oops.
line the line on which the Oops is thrown.
err the errno converted to error std::string with strerror.
Definition at line 50 of file oops.cpp.
References msg_, and stripSourceDir().
Member Function Documentation
getMessage()
const std::string& leanux::Oops::getMessage () const inline
Get the Oops message.
Returns
the Oops message.
Definition at line 68 of file oops.hpp.
References msg_.
Referenced by leanux::tools::lard::ensureSinglePid(), leanux::tools::lrep::htmlDiskDetails(), leanux::tools::lmon::main(), leanux::tools::lard::main(), leanux::tools::lsys::main(), leanux::tools::lblk::main(), leanux::tools::lrep::main(), and leanux::operator<<().
stripSourceDir()
std::string leanux::Oops::stripSourceDir (const std::string & srcdir) static protected
Definition at line 56 of file oops.cpp.
Referenced by Oops().
Field Documentation
msg_
std::string leanux::Oops::msg_ protected
The Oops message.
Definition at line 75 of file oops.hpp.
Referenced by getMessage(), and Oops().
The documentation for this class was generated from the following files:
lib/oops.hpp
lib/oops.cpp