leanux: leanux::persist::Query Class Reference
leanux::persist::Query Class Reference
Queries can take bind values and return select lists.
#include <persist.hpp>
Public Member Functions
Query (const Database &db)
Constructor.
virtual ~Query ()
Destructor.
void bind (int position, const std::string &value)
Bind a string value to the bind at position.
void bind (int position, double value)
Bind a double value to the bind at position.
void bind (int position, int value)
Bind an int value to the bind at position.
void bind (int position, long value)
Bind a long value to the bind at position.
void close ()
A statement handle can be explicitly closed without deleting the Statement object itself.
void execute ()
Execute.
int getColumnCount () const
get the number of columns in the query result set.
double getDouble (int col) const
Get double value from select list.
int getInt (int col) const
Get int value from select list.
long getLong (int col) const
Get long value from select list.
std::string getText (int col) const
Get string value from select list.
bool isNull (int col) const
Test if the result is NULL.
void prepare (const std::string &sql)
Prepare a SQL statement.
void reset ()
Reset a SQL statement for rexecute or even re-prepare.
bool step ()
Step the result list, end of list returns false.
Protected Attributes
sqlite3 * database_
database handle on which the stmt_ is created.
sqlite3_stmt * stmt_
statement handle.
Detailed Description
Queries can take bind values and return select lists.
Definition at line 297 of file persist.hpp.
Constructor & Destructor Documentation
Query()
leanux::persist::Query::Query (const Database & db) inline
Constructor.
Definition at line 300 of file persist.hpp.
~Query()
virtual leanux::persist::Query::~Query () inline virtual
Destructor.
Definition at line 303 of file persist.hpp.
Member Function Documentation
bind() [1/4]
void leanux::persist::DML::bind (int position, const std::string & value) inherited
Bind a string value to the bind at position.
Parameters
position the bind position in the SQL (start with 1)
value the value to bind.
Definition at line 431 of file persist.cpp.
References leanux::persist::Statement::database_, and leanux::persist::Statement::stmt_.
bind() [2/4]
void leanux::persist::DML::bind (int position, double value) inherited
Bind a double value to the bind at position.
Parameters
position the bind position in the SQL (start with 1)
value the value to bind.
Definition at line 410 of file persist.cpp.
References leanux::persist::Statement::database_, and leanux::persist::Statement::stmt_.
Referenced by leanux::tools::lard::applyRetention(), leanux::tools::lrep::chartCmdAverage(), leanux::tools::lrep::chartCPUTimeLine(), leanux::tools::lrep::chartDiskAverage(), leanux::tools::lrep::chartDiskRSZHisto(), leanux::tools::lrep::chartDiskScvHisto(), leanux::tools::lrep::chartDiskTimeLine(), leanux::tools::lrep::chartDiskWSZHisto(), leanux::tools::lrep::chartKernelTimeLine(), leanux::tools::lrep::chartMountAverage(), leanux::tools::lrep::chartMountTimeLine(), leanux::tools::lrep::chartNetAverage(), leanux::tools::lrep::chartNicBWTimeLine(), leanux::tools::lrep::chartNICPacketTimeLine(), leanux::tools::lrep::chartPagingTimeLine(), leanux::tools::lrep::chartPerCPUAverage(), leanux::tools::lrep::chartSchedTimeLine(), leanux::tools::lrep::chartTCPClientAverage(), leanux::tools::lrep::chartTCPClientTimeLine(), leanux::tools::lrep::chartTCPServerAverage(), leanux::tools::lrep::chartTCPServerTimeLine(), leanux::tools::lrep::chartTotalCPUAverage(), leanux::tools::lrep::chartUserAverage(), leanux::tools::lrep::chartVMAverage(), leanux::tools::lrep::chartVMTimeLine(), leanux::tools::lrep::computeTotals(), leanux::tools::lrep::CPUHeatMap(), leanux::tools::lard::deleteSnapshots(), leanux::tools::lrep::DiskHeatMap(), leanux::tools::lard::ensureSinglePid(), leanux::tools::lmon::LardHistory::fetchXIOView(), leanux::tools::lmon::LardHistory::fetchXNetView(), leanux::tools::lmon::LardHistory::fetchXProcView(), leanux::tools::lmon::LardHistory::fetchXSysView(), leanux::tools::lmon::LardHistory::getCPUStatRange(), leanux::tools::lrep::htmlCmdCPUDetail(), leanux::tools::lrep::htmlCmdDetails(), leanux::tools::lrep::htmlCmdRSSDetail(), leanux::tools::lrep::htmlCmdUidDetail(), leanux::tools::lrep::htmlDiskDetail(), leanux::tools::lrep::htmlDiskDetails(), leanux::tools::lrep::load5HeatMap(), leanux::tools::lrep::main(), leanux::tools::lard::mainLoop(), leanux::tools::lrep::NetPktHeatMap(), leanux::tools::lard::TimeSnap::storeSnap(), leanux::tools::lard::IOSnap::storeSnap(), leanux::tools::lard::CPUSnap::storeSnap(), leanux::tools::lard::SchedSnap::storeSnap(), leanux::tools::lard::NetSnap::storeSnap(), leanux::tools::lard::VMSnap::storeSnap(), leanux::tools::lard::ProcSnap::storeSnap(), leanux::tools::lard::ResSnap::storeSnap(), leanux::tools::lard::MountSnap::storeSnap(), leanux::tools::lard::TCPEstaSnap::storeSnap(), and leanux::tools::lmon::LardHistory::updateRangeTime().
bind() [3/4]
void leanux::persist::DML::bind (int position, int value) inherited
Bind an int value to the bind at position.
Parameters
position the bind position in the SQL (start with 1)
value the value to bind.
Definition at line 417 of file persist.cpp.
References leanux::persist::Statement::database_, and leanux::persist::Statement::stmt_.
bind() [4/4]
void leanux::persist::DML::bind (int position, long value) inherited
Bind a long value to the bind at position.
Parameters
position the bind position in the SQL (start with 1)
value the value to bind.
Definition at line 424 of file persist.cpp.
References leanux::persist::Statement::database_, and leanux::persist::Statement::stmt_.
close()
void leanux::persist::Statement::close () inherited
A statement handle can be explicitly closed without deleting the Statement object itself.
This frees the resources in SQLite, . it's allowed to call prepare() again.
Definition at line 381 of file persist.cpp.
References leanux::persist::Statement::database_, and leanux::persist::Statement::stmt_.
Referenced by leanux::tools::lard::applyRetention(), leanux::persist::Database::begin(), leanux::persist::Database::beginExclusive(), leanux::persist::Database::beginImmediate(), leanux::persist::Database::commit(), leanux::tools::lard::deleteSnapshots(), leanux::tools::lard::ensureSinglePid(), leanux::persist::Database::getUserVersion(), leanux::tools::lard::initDB(), leanux::tools::lard::mainLoop(), leanux::persist::Statement::prepare(), leanux::persist::Database::release(), leanux::persist::Database::rollback(), leanux::persist::Database::savepoint(), leanux::persist::Database::setUserVersion(), leanux::tools::lard::shrinkDB(), and leanux::tools::lard::vacuumAnalyze().
execute()
void leanux::persist::DML::execute () inherited
Execute.
Definition at line 403 of file persist.cpp.
References leanux::persist::Statement::database_, and leanux::persist::Statement::stmt_.
Referenced by leanux::tools::lard::deleteSnapshots(), leanux::tools::lard::ensureSinglePid(), leanux::tools::lard::mainLoop(), leanux::tools::lard::TimeSnap::storeSnap(), leanux::tools::lard::IOSnap::storeSnap(), leanux::tools::lard::CPUSnap::storeSnap(), leanux::tools::lard::SchedSnap::storeSnap(), leanux::tools::lard::NetSnap::storeSnap(), leanux::tools::lard::VMSnap::storeSnap(), leanux::tools::lard::ProcSnap::storeSnap(), leanux::tools::lard::ResSnap::storeSnap(), leanux::tools::lard::MountSnap::storeSnap(), and leanux::tools::lard::TCPEstaSnap::storeSnap().
getColumnCount()
int leanux::persist::Query::getColumnCount () const
get the number of columns in the query result set.
Returns
the number of columns
Definition at line 469 of file persist.cpp.
References leanux::persist::Statement::stmt_.
getDouble()
double leanux::persist::Query::getDouble (int col) const
Get double value from select list.
Parameters
col the select list column (start with 0).
Returns
the select list value.
Definition at line 460 of file persist.cpp.
References leanux::persist::Statement::stmt_.
Referenced by leanux::tools::lrep::chartCmdAverage(), leanux::tools::lrep::chartCPUTimeLine(), leanux::tools::lrep::chartDiskAverage(), leanux::tools::lrep::chartDiskRSZHisto(), leanux::tools::lrep::chartDiskScvHisto(), leanux::tools::lrep::chartDiskTimeLine(), leanux::tools::lrep::chartDiskWSZHisto(), leanux::tools::lrep::chartKernelTimeLine(), leanux::tools::lrep::chartMountAverage(), leanux::tools::lrep::chartMountTimeLine(), leanux::tools::lrep::chartNetAverage(), leanux::tools::lrep::chartNicBWTimeLine(), leanux::tools::lrep::chartNICPacketTimeLine(), leanux::tools::lrep::chartPagingTimeLine(), leanux::tools::lrep::chartPerCPUAverage(), leanux::tools::lrep::chartSchedTimeLine(), leanux::tools::lrep::chartTCPClientAverage(), leanux::tools::lrep::chartTCPClientTimeLine(), leanux::tools::lrep::chartTCPServerAverage(), leanux::tools::lrep::chartTCPServerTimeLine(), leanux::tools::lrep::chartTotalCPUAverage(), leanux::tools::lrep::chartUserAverage(), leanux::tools::lrep::chartVMAverage(), leanux::tools::lrep::chartVMTimeLine(), leanux::tools::lrep::computeTotals(), leanux::tools::lrep::CPUHeatMap(), leanux::tools::lrep::DiskHeatMap(), leanux::tools::lmon::LardHistory::fetchXIOView(), leanux::tools::lmon::LardHistory::fetchXNetView(), leanux::tools::lmon::LardHistory::fetchXProcView(), leanux::tools::lmon::LardHistory::fetchXSysView(), leanux::tools::lmon::LardHistory::getCPUStatRange(), leanux::tools::lrep::htmlCmdCPUDetail(), leanux::tools::lrep::htmlCmdRSSDetail(), leanux::tools::lrep::htmlCmdUidDetail(), leanux::tools::lrep::htmlDiskDetail(), leanux::tools::lrep::htmlDiskDetails(), leanux::tools::lrep::load5HeatMap(), leanux::tools::lrep::NetPktHeatMap(), and leanux::tools::lmon::LardHistory::updateMinMax().
getInt()
int leanux::persist::Query::getInt (int col) const
Get int value from select list.
Parameters
col the select list column (start with 0).
Returns
the select list value.
Definition at line 452 of file persist.cpp.
References leanux::persist::Statement::stmt_.
Referenced by leanux::tools::lrep::chartDiskRSZHisto(), leanux::tools::lrep::chartDiskScvHisto(), leanux::tools::lrep::chartPerCPUAverage(), leanux::tools::lrep::chartTCPClientAverage(), leanux::tools::lrep::chartTCPClientTimeLine(), leanux::tools::lrep::chartTCPServerAverage(), leanux::tools::lrep::chartTCPServerTimeLine(), leanux::tools::lrep::chartUserAverage(), leanux::tools::lrep::CPUHeatMap(), leanux::tools::lrep::DiskHeatMap(), leanux::tools::lard::ensureSinglePid(), leanux::persist::Database::getUserVersion(), leanux::tools::lrep::htmlCmdUidDetail(), leanux::tools::lrep::htmlDiskDetails(), leanux::tools::lrep::load5HeatMap(), leanux::tools::lrep::main(), and leanux::tools::lrep::NetPktHeatMap().
getLong()
long leanux::persist::Query::getLong (int col) const
Get long value from select list.
Parameters
col the select list column (start with 0).
Returns
the select list value.
Definition at line 456 of file persist.cpp.
References leanux::persist::Statement::stmt_.
Referenced by leanux::tools::lard::applyRetention(), leanux::tools::lmon::LardHistory::fetchXNetView(), leanux::tools::lmon::LardHistory::fetchXProcView(), leanux::tools::lmon::LardHistory::fetchXSysView(), leanux::tools::lard::shrinkDB(), leanux::tools::lard::IOSnap::storeSnap(), leanux::tools::lard::NetSnap::storeSnap(), leanux::tools::lard::ProcSnap::storeSnap(), leanux::tools::lard::MountSnap::storeSnap(), leanux::tools::lard::TCPEstaSnap::storeSnap(), leanux::tools::lmon::LardHistory::updateMinMax(), leanux::tools::lmon::LardHistory::updateRangeTime(), and leanux::tools::lmon::verifyDatabase().
getText()
std::string leanux::persist::Query::getText (int col) const
Get string value from select list.
Parameters
col the select list column (start with 0).
Returns
the select list value.
Definition at line 464 of file persist.cpp.
References leanux::persist::Statement::stmt_.
Referenced by leanux::tools::lrep::chartCmdAverage(), leanux::tools::lrep::chartDiskAverage(), leanux::tools::lrep::chartDiskTimeLine(), leanux::tools::lrep::chartMountAverage(), leanux::tools::lrep::chartMountTimeLine(), leanux::tools::lrep::chartNetAverage(), leanux::tools::lrep::chartNicBWTimeLine(), leanux::tools::lrep::chartNICPacketTimeLine(), leanux::tools::lrep::chartTCPClientAverage(), leanux::tools::lrep::chartTCPClientTimeLine(), leanux::tools::lrep::chartTCPServerAverage(), leanux::tools::lmon::LardHistory::fetchXIOView(), leanux::tools::lmon::LardHistory::fetchXNetView(), leanux::tools::lmon::LardHistory::fetchXProcView(), leanux::tools::lrep::htmlCmdDetails(), leanux::tools::lrep::htmlDiskDetails(), and leanux::tools::lrep::main().
isNull()
bool leanux::persist::Query::isNull (int col) const
Test if the result is NULL.
Parameters
col the select list column (start with 0).
Returns
true if the col holds a NULL value
Definition at line 448 of file persist.cpp.
References leanux::persist::Statement::stmt_.
Referenced by leanux::tools::lmon::LardHistory::fetchXProcView(), and leanux::tools::lmon::LardHistory::getCPUStatRange().
prepare()
void leanux::persist::Statement::prepare (const std::string & sql) inherited
Prepare a SQL statement.
Parameters
sql the SQL statement.
Definition at line 363 of file persist.cpp.
References leanux::persist::Statement::close(), leanux::persist::Statement::database_, and leanux::persist::Statement::stmt_.
Referenced by leanux::tools::lard::applyRetention(), leanux::persist::Database::begin(), leanux::persist::Database::beginExclusive(), leanux::persist::Database::beginImmediate(), leanux::tools::lrep::chartCmdAverage(), leanux::tools::lrep::chartCPUTimeLine(), leanux::tools::lrep::chartDiskAverage(), leanux::tools::lrep::chartDiskRSZHisto(), leanux::tools::lrep::chartDiskScvHisto(), leanux::tools::lrep::chartDiskTimeLine(), leanux::tools::lrep::chartDiskWSZHisto(), leanux::tools::lrep::chartKernelTimeLine(), leanux::tools::lrep::chartMountAverage(), leanux::tools::lrep::chartMountTimeLine(), leanux::tools::lrep::chartNetAverage(), leanux::tools::lrep::chartNicBWTimeLine(), leanux::tools::lrep::chartNICPacketTimeLine(), leanux::tools::lrep::chartPagingTimeLine(), leanux::tools::lrep::chartPerCPUAverage(), leanux::tools::lrep::chartSchedTimeLine(), leanux::tools::lrep::chartTCPClientAverage(), leanux::tools::lrep::chartTCPClientTimeLine(), leanux::tools::lrep::chartTCPServerAverage(), leanux::tools::lrep::chartTCPServerTimeLine(), leanux::tools::lrep::chartTotalCPUAverage(), leanux::tools::lrep::chartUserAverage(), leanux::tools::lrep::chartVMAverage(), leanux::tools::lrep::chartVMTimeLine(), leanux::persist::Database::commit(), leanux::tools::lrep::computeTotals(), leanux::tools::lrep::CPUHeatMap(), leanux::tools::lard::createTableCmd(), leanux::tools::lard::createTableCpustat(), leanux::tools::lard::createTableDisk(), leanux::tools::lard::createTableIostat(), leanux::tools::lard::createTableMountpoint(), leanux::tools::lard::createTableMountstat(), leanux::tools::lard::createTableNetstat(), leanux::tools::lard::createTableNic(), leanux::tools::lard::createTableProcstat(), leanux::tools::lard::createTableResstat(), leanux::tools::lard::createTableSchedstat(), leanux::tools::lard::createTableSnapshot(), leanux::tools::lard::createTableStatus(), leanux::tools::lard::createTableTcpclientstat(), leanux::tools::lard::createTableTcpkey(), leanux::tools::lard::createTableTcpserverstat(), leanux::tools::lard::createTableVmstat(), leanux::tools::lard::createTableWchan(), leanux::tools::lard::deleteSnapshots(), leanux::tools::lrep::DiskHeatMap(), leanux::tools::lard::ensureSinglePid(), leanux::tools::lmon::LardHistory::fetchXIOView(), leanux::tools::lmon::LardHistory::fetchXNetView(), leanux::tools::lmon::LardHistory::fetchXProcView(), leanux::tools::lmon::LardHistory::fetchXSysView(), leanux::tools::lmon::LardHistory::getCPUStatRange(), leanux::persist::Database::getUserVersion(), leanux::tools::lrep::htmlCmdCPUDetail(), leanux::tools::lrep::htmlCmdDetails(), leanux::tools::lrep::htmlCmdRSSDetail(), leanux::tools::lrep::htmlCmdUidDetail(), leanux::tools::lrep::htmlDiskDetail(), leanux::tools::lrep::htmlDiskDetails(), leanux::tools::lard::initDB(), leanux::tools::lrep::load5HeatMap(), leanux::tools::lrep::main(), leanux::tools::lard::mainLoop(), leanux::tools::lrep::NetPktHeatMap(), leanux::persist::Database::release(), leanux::persist::Database::rollback(), leanux::persist::Database::savepoint(), leanux::persist::Database::setUserVersion(), leanux::tools::lard::shrinkDB(), leanux::tools::lard::TimeSnap::storeSnap(), leanux::tools::lard::IOSnap::storeSnap(), leanux::tools::lard::CPUSnap::storeSnap(), leanux::tools::lard::SchedSnap::storeSnap(), leanux::tools::lard::NetSnap::storeSnap(), leanux::tools::lard::VMSnap::storeSnap(), leanux::tools::lard::ProcSnap::storeSnap(), leanux::tools::lard::ResSnap::storeSnap(), leanux::tools::lard::MountSnap::storeSnap(), leanux::tools::lard::TCPEstaSnap::storeSnap(), leanux::tools::lmon::LardHistory::updateMinMax(), leanux::tools::lmon::LardHistory::updateRangeTime(), leanux::tools::lard::vacuumAnalyze(), and leanux::tools::lmon::verifyDatabase().
reset()
void leanux::persist::Statement::reset () inherited
Reset a SQL statement for rexecute or even re-prepare.
Definition at line 374 of file persist.cpp.
References leanux::persist::Statement::database_, and leanux::persist::Statement::stmt_.
Referenced by leanux::tools::lrep::computeTotals(), leanux::tools::lard::createTableCpustat(), leanux::tools::lard::createTableIostat(), leanux::tools::lard::createTableMountstat(), leanux::tools::lard::createTableNetstat(), leanux::tools::lard::createTableProcstat(), leanux::tools::lard::createTableResstat(), leanux::tools::lard::createTableSchedstat(), leanux::tools::lard::createTableSnapshot(), leanux::tools::lard::createTableWchan(), leanux::tools::lard::deleteSnapshots(), leanux::tools::lard::ensureSinglePid(), leanux::tools::lmon::LardHistory::fetchXProcView(), leanux::tools::lrep::main(), leanux::tools::lard::ProcSnap::storeSnap(), leanux::tools::lard::MountSnap::storeSnap(), leanux::tools::lard::TCPEstaSnap::storeSnap(), and leanux::tools::lard::vacuumAnalyze().
step()
bool leanux::persist::Query::step ()
Step the result list, end of list returns false.
Returns
true as long as there are more rows.
Definition at line 440 of file persist.cpp.
References leanux::persist::Statement::database_, and leanux::persist::Statement::stmt_.
Referenced by leanux::tools::lard::applyRetention(), leanux::tools::lrep::chartCmdAverage(), leanux::tools::lrep::chartCPUTimeLine(), leanux::tools::lrep::chartDiskAverage(), leanux::tools::lrep::chartDiskRSZHisto(), leanux::tools::lrep::chartDiskScvHisto(), leanux::tools::lrep::chartDiskTimeLine(), leanux::tools::lrep::chartDiskWSZHisto(), leanux::tools::lrep::chartKernelTimeLine(), leanux::tools::lrep::chartMountAverage(), leanux::tools::lrep::chartMountTimeLine(), leanux::tools::lrep::chartNetAverage(), leanux::tools::lrep::chartNicBWTimeLine(), leanux::tools::lrep::chartNICPacketTimeLine(), leanux::tools::lrep::chartPagingTimeLine(), leanux::tools::lrep::chartPerCPUAverage(), leanux::tools::lrep::chartSchedTimeLine(), leanux::tools::lrep::chartTCPClientAverage(), leanux::tools::lrep::chartTCPClientTimeLine(), leanux::tools::lrep::chartTCPServerAverage(), leanux::tools::lrep::chartTCPServerTimeLine(), leanux::tools::lrep::chartTotalCPUAverage(), leanux::tools::lrep::chartUserAverage(), leanux::tools::lrep::chartVMAverage(), leanux::tools::lrep::chartVMTimeLine(), leanux::tools::lrep::computeTotals(), leanux::tools::lrep::CPUHeatMap(), leanux::tools::lrep::DiskHeatMap(), leanux::tools::lard::ensureSinglePid(), leanux::tools::lmon::LardHistory::fetchXIOView(), leanux::tools::lmon::LardHistory::fetchXNetView(), leanux::tools::lmon::LardHistory::fetchXProcView(), leanux::tools::lmon::LardHistory::fetchXSysView(), leanux::tools::lmon::LardHistory::getCPUStatRange(), leanux::persist::Database::getUserVersion(), leanux::tools::lrep::htmlCmdCPUDetail(), leanux::tools::lrep::htmlCmdDetails(), leanux::tools::lrep::htmlCmdRSSDetail(), leanux::tools::lrep::htmlCmdUidDetail(), leanux::tools::lrep::htmlDiskDetail(), leanux::tools::lrep::htmlDiskDetails(), leanux::tools::lard::initDB(), leanux::tools::lrep::load5HeatMap(), leanux::tools::lrep::main(), leanux::tools::lard::mainLoop(), leanux::tools::lrep::NetPktHeatMap(), leanux::tools::lard::shrinkDB(), leanux::tools::lard::IOSnap::storeSnap(), leanux::tools::lard::NetSnap::storeSnap(), leanux::tools::lard::ProcSnap::storeSnap(), leanux::tools::lard::MountSnap::storeSnap(), leanux::tools::lard::TCPEstaSnap::storeSnap(), leanux::tools::lmon::LardHistory::updateMinMax(), leanux::tools::lmon::LardHistory::updateRangeTime(), and leanux::tools::lmon::verifyDatabase().
Field Documentation
database_
sqlite3* leanux::persist::Statement::database_ protected inherited
database handle on which the stmt_ is created.
Definition at line 217 of file persist.hpp.
Referenced by leanux::persist::DML::bind(), leanux::persist::Statement::close(), leanux::persist::DDL::execute(), leanux::persist::DML::execute(), leanux::persist::Statement::prepare(), leanux::persist::Statement::reset(), leanux::persist::Statement::Statement(), and step().
stmt_
sqlite3_stmt* leanux::persist::Statement::stmt_ protected inherited
statement handle.
Definition at line 214 of file persist.hpp.
Referenced by leanux::persist::DML::bind(), leanux::persist::Statement::close(), leanux::persist::DDL::execute(), leanux::persist::DML::execute(), leanux::persist::DDL::execute_r(), getColumnCount(), getDouble(), getInt(), getLong(), getText(), isNull(), leanux::persist::Statement::prepare(), leanux::persist::Statement::reset(), leanux::persist::Statement::Statement(), step(), and leanux::persist::Statement::~Statement().
The documentation for this class was generated from the following files:
lib/persist.hpp
lib/persist.cpp