leanux: leanux::tools::lard::IOSnap Class Reference
leanux::tools::lard::IOSnap Class Reference
#include <lar_snap.hpp>
Public Member Functions
IOSnap ()
virtual ~IOSnap ()
virtual void startSnap ()
virtual void stopSnap ()
virtual long storeSnap (const persist::Database &db, long snapid, double seconds)
Protected Attributes
block::DeviceStatsMap stat1_
block::DeviceStatsMap stat2_
Detailed Description
Definition at line 86 of file lar_snap.hpp.
Constructor & Destructor Documentation
IOSnap()
leanux::tools::lard::IOSnap::IOSnap () inline
Definition at line 88 of file lar_snap.hpp.
~IOSnap()
virtual leanux::tools::lard::IOSnap::~IOSnap () inline virtual
Definition at line 89 of file lar_snap.hpp.
Member Function Documentation
startSnap()
void leanux::tools::lard::IOSnap::startSnap () virtual
Implements leanux::tools::lard::Snapshot.
Definition at line 101 of file lar_snap.cpp.
References leanux::block::getStats(), and stat1_.
Referenced by leanux::tools::lard::mainLoop().
stopSnap()
void leanux::tools::lard::IOSnap::stopSnap () virtual
Implements leanux::tools::lard::Snapshot.
Definition at line 105 of file lar_snap.cpp.
References leanux::block::getStats(), and stat2_.
Referenced by leanux::tools::lard::mainLoop().
storeSnap()
long leanux::tools::lard::IOSnap::storeSnap (const persist::Database & db, long snapid, double seconds) virtual
Implements leanux::tools::lard::Snapshot.
Definition at line 109 of file lar_snap.cpp.
References leanux::persist::DML::bind(), leanux::block::deltaDeviceStats(), leanux::persist::DML::execute(), leanux::util::ConfigFile::getConfig(), leanux::persist::Query::getLong(), leanux::persist::Database::lastInsertRowid(), leanux::persist::Statement::prepare(), stat1_, stat2_, and leanux::persist::Query::step().
Referenced by leanux::tools::lard::mainLoop().
Field Documentation
stat1_
block::DeviceStatsMap leanux::tools::lard::IOSnap::stat1_ protected
Definition at line 96 of file lar_snap.hpp.
Referenced by startSnap(), and storeSnap().
stat2_
block::DeviceStatsMap leanux::tools::lard::IOSnap::stat2_ protected
Definition at line 97 of file lar_snap.hpp.
Referenced by stopSnap(), and storeSnap().
The documentation for this class was generated from the following files:
tools/lard/lar_snap.hpp
tools/lard/lar_snap.cpp