leanux: leanux::vmem Namespace Reference
leanux::vmem Namespace Reference
virtual memory API
Data Structures
struct SwapInfo
Information on a swap container.
struct VMStat
information from /proc/vmstat.
Functions
ssize_t getDirtyBackgroundBytes ()
get /proc/sys/vm/dirty_background_bytes
ssize_t getDirtyBackgroundRatio ()
get /proc/sys/vm/dirty_background_ratio
ssize_t getDirtyBytes ()
get /proc/sys/vm/dirty_bytes
double getDirtyPressure (ssize_t ram, ssize_t dirtied)
ssize_t getDirtyRatio ()
get /proc/sys/vm/dirty_ratio
void getSwapInfo (std::list< SwapInfo > &swaps)
Get a std::list of SwapInfo swap spaces.
void getVMStat (VMStat &stat)
get virtual memory statistics.
Detailed Description
virtual memory API
Data Structure Documentation
leanux::vmem::SwapInfo
struct leanux::vmem::SwapInfo
Information on a swap container.
Definition at line 167 of file vmem.hpp.
Data Fields
string devicefile the device file used as swap.
string devicetype the device type used as swap.
int priority the swap priority.
unsigned long size the size of the device in bytes.
unsigned long used the number of used bytes.
leanux::vmem::VMStat
struct leanux::vmem::VMStat
information from /proc/vmstat.
Definition at line 50 of file vmem.hpp.
Data Fields
unsigned long committed_as committed address space bytes
unsigned long hugepages_free total number of (fixed) hugepages unused
unsigned long hugepages_reserved total number of (fixed) hugepages unused but reserved
unsigned long hugepages_total total number of (fixed) hugepages
unsigned long hugepagesize hugepagesize
unsigned long mem_total total memory bytes
unsigned long nr_active_anon number of active anonymous pages.
unsigned long nr_active_file number of active file pages.
unsigned long nr_anon_pages number of anonymous pages
unsigned long nr_anon_transparent_hugepages number of anonymous transparent pages
unsigned long nr_dirty number of dirty file pages
unsigned long nr_file_pages number of file pages
unsigned long nr_free_pages number of pages not used for anything.
unsigned long nr_inactive_anon number of inactive anonymous pages.
unsigned long nr_inactive_file number of inactive file pages.
unsigned long nr_kernel_stack number of kernel pages
unsigned long nr_mapped number of mapped pages
unsigned long nr_mlock number of mlocked pages
unsigned long nr_page_table_pages number of paging table pages
unsigned long nr_shmem number of shared memory pages
unsigned long nr_slab_reclaimable number of reclaimable pages from the slab
unsigned long nr_slab_unreclaimable number of unreclaimable pages from the slab
unsigned long nr_unevictable number of unevictable pages
unsigned long nr_writeback number of dirty file pages written out now
unsigned long pgalloc_dma number of dma pages
unsigned long pgalloc_dma32 number of dma 32 pages
unsigned long pgalloc_movable number of allocated moveable pages
unsigned long pgalloc_normal number of allocated normal pages
unsigned long pgfault number of minor page faults
unsigned long pgfree number of pages freed
unsigned long pgmajfault number of major page faults
unsigned long pgpgin number of pages paged in
unsigned long pgpgout number of pages paged out
unsigned long pswpin number of pages swapped in
unsigned long pswpout number of pages swapped out
Function Documentation
getDirtyBackgroundBytes()
ssize_t leanux::vmem::getDirtyBackgroundBytes ()
get /proc/sys/vm/dirty_background_bytes
Returns
/proc/sys/vm/dirty_background_bytes
Definition at line 169 of file vmem.cpp.
References leanux::util::fileReadUL().
getDirtyBackgroundRatio()
ssize_t leanux::vmem::getDirtyBackgroundRatio ()
get /proc/sys/vm/dirty_background_ratio
Returns
/proc/sys/vm/dirty_background_ratio
Definition at line 173 of file vmem.cpp.
References leanux::util::fileReadUL().
getDirtyBytes()
ssize_t leanux::vmem::getDirtyBytes ()
get /proc/sys/vm/dirty_bytes
Returns
/proc/sys/vm/dirty_bytes
Definition at line 161 of file vmem.cpp.
References leanux::util::fileReadUL().
Referenced by getDirtyPressure().
getDirtyPressure()
double leanux::vmem::getDirtyPressure (ssize_t ram, ssize_t dirtied)
Definition at line 177 of file vmem.cpp.
References getDirtyBytes(), and getDirtyRatio().
getDirtyRatio()
ssize_t leanux::vmem::getDirtyRatio ()
get /proc/sys/vm/dirty_ratio
Returns
/proc/sys/vm/dirty_ratio
Definition at line 165 of file vmem.cpp.
References leanux::util::fileReadUL().
Referenced by getDirtyPressure().
getSwapInfo()
void leanux::vmem::getSwapInfo (std::list< SwapInfo > & swaps)
Get a std::list of SwapInfo swap spaces.
Parameters
swaps the std::list to fill with the systems swaps.
Definition at line 143 of file vmem.cpp.
References leanux::vmem::SwapInfo::devicefile, leanux::vmem::SwapInfo::devicetype, leanux::vmem::SwapInfo::priority, leanux::vmem::SwapInfo::size, and leanux::vmem::SwapInfo::used.
Referenced by leanux::tools::lmon::IOView::getOptimalHeight(), leanux::tools::lmon::RealtimeSampler::sampleXIOView(), leanux::tools::lmon::RealtimeSampler::sampleXSysView(), leanux::tools::lard::VMSnap::storeSnap(), and leanux::tools::lard::MountSnap::storeSnap().
getVMStat()
void leanux::vmem::getVMStat (VMStat & stat)
get virtual memory statistics.
Parameters
stat the VMStat structure to fill.
Definition at line 52 of file vmem.cpp.
References leanux::vmem::VMStat::committed_as, leanux::vmem::VMStat::hugepages_free, leanux::vmem::VMStat::hugepages_reserved, leanux::vmem::VMStat::hugepages_total, leanux::vmem::VMStat::hugepagesize, leanux::vmem::VMStat::mem_total, leanux::vmem::VMStat::nr_active_anon, leanux::vmem::VMStat::nr_active_file, leanux::vmem::VMStat::nr_anon_pages, leanux::vmem::VMStat::nr_anon_transparent_hugepages, leanux::vmem::VMStat::nr_dirty, leanux::vmem::VMStat::nr_file_pages, leanux::vmem::VMStat::nr_free_pages, leanux::vmem::VMStat::nr_inactive_anon, leanux::vmem::VMStat::nr_inactive_file, leanux::vmem::VMStat::nr_kernel_stack, leanux::vmem::VMStat::nr_mapped, leanux::vmem::VMStat::nr_mlock, leanux::vmem::VMStat::nr_page_table_pages, leanux::vmem::VMStat::nr_shmem, leanux::vmem::VMStat::nr_slab_reclaimable, leanux::vmem::VMStat::nr_slab_unreclaimable, leanux::vmem::VMStat::nr_unevictable, leanux::vmem::VMStat::nr_writeback, leanux::vmem::VMStat::pgalloc_dma, leanux::vmem::VMStat::pgalloc_dma32, leanux::vmem::VMStat::pgalloc_movable, leanux::vmem::VMStat::pgalloc_normal, leanux::vmem::VMStat::pgfault, leanux::vmem::VMStat::pgfree, leanux::vmem::VMStat::pgmajfault, leanux::vmem::VMStat::pgpgin, leanux::vmem::VMStat::pgpgout, leanux::vmem::VMStat::pswpin, and leanux::vmem::VMStat::pswpout.
Referenced by leanux::tools::lrep::htmlSystemDetails(), leanux::tools::lmon::RealtimeSampler::sampleXSysView(), leanux::tools::lard::VMSnap::startSnap(), and leanux::tools::lard::VMSnap::stopSnap().